### ISSUE TITLE
Broken automatic color conversion

### ISSUE THREAD

**Issue by TigerHix** [FlailingFog/KK-Blender-Porter-Pack#100]
It seems like the automatic color conversion is broken for this model.

This is after step 15 (after clicking "Import KK Shader and Textures"). I think this looks yellowish so it's probably expected behavior up to this point.
![image](https://user-images.githubusercontent.com/3406505/150135014-c0f341f2-f004-420f-ad4f-bad3b06c4148.png)

This is after step 16 (after clicking "Convert and Apply Colors").
![image](https://user-images.githubusercontent.com/3406505/150135259-e7b40398-e410-46ed-b9c3-e59f146de107.png)

This is how it's supposed to look like:
![image](https://user-images.githubusercontent.com/3406505/150135359-ab4317c4-fa11-4791-804d-7d21a9efec24.png)

Tested on Blender 3.0 and KKBP 5.0.

Source card:
[src.zip](https://github.com/FlailingFog/KK-Blender-Porter-Pack/files/7897310/src.zip)

Exported PMX files:
https://drive.google.com/file/d/1SnBK6RD4ZSanbx0O52_TpFHjxTezBv3m/view?usp=sharing
(I checked the textures and they look correct to me).

I tried other LUT profiles (sunset, saturation based...) but none seemed to work.

Btw, this is phenomenal work and I'd really love to support you guys. Would you consider opening Patreon, for example?

**Comment by MediaMoots** [comment]
Does it work on blender 2.93?

**Comment by TigerHix** [comment]
> Does it work on blender 2.93?

Unfortunately not. Just tried using 2.93.7 and the result is the same as #1.

**Comment by MediaMoots** [comment]
Try this.

For the top, shorts, and shoes, set "manually set detail" color to 0.
For the Hair, don't separate it from the clothes object and you should be fine.

**Comment by TigerHix** [comment]
> Try this.
> 
> For the top, shorts, and shoes, set "manually set detail color" to 0 and do the same for "detail shine" on the shoes. For the Hair, don't separate it from the clothes object, and you should be fine.
> 
> Also, since KKBP requires a mesh object named hair to be present in the scene, try selecting a random mesh from the clothes object and duplicating it into a separate "Hair" object. You can then delete that object after it's done. ![image](https://user-images.githubusercontent.com/81146974/150670376-b86d2c00-6320-4da8-82df-bf2d22601504.png)

Thanks! That indeed fixed the incorrect colors of the clothes.

However, there are still a few issues. See the following KKBP render of the face:

![image](https://user-images.githubusercontent.com/3406505/150675689-97cafa86-c125-4956-878b-0c7b97241f86.png)

Compared to in-game render:

![image](https://user-images.githubusercontent.com/3406505/150675915-ff14f1ee-714a-4893-a177-26ce479dd804.png)

* The hair seems weird - only the front hair's shading looks correct?
* There is a blue-ish tint on the skin. (even if I chose the `LUT Day` preset) Indeed, both body and face shader has this blue color in them: 
![image](https://user-images.githubusercontent.com/3406505/150676531-dbc947f7-f74f-4556-88fc-efc36776f8b1.png)
Could that be a color conversion mistake? I can set it manually to pink, for example, but I hope to preserve the "real" color that was used in Koikatsu.
* The eyebrow texture (below) is not showing. I checked the shader - it is definitely used but maybe some error in the color calculation messed things up:
![image](https://user-images.githubusercontent.com/3406505/150676415-06ef107b-56f4-4777-b046-c113b4082c12.png)
* The face overlay is not showing. It _seems_ setting "Use maintex instead?" to 1 for the face overlay shader fixes this issue, but I am not sure if this is the right way to do it.

Finally, the body has weird black strips over it:

![image](https://user-images.githubusercontent.com/3406505/150676801-e190cb1d-acad-44c9-b379-8b097a8f641b.png)

I have yet to find a shader parameter that caused this issue.

Thanks again for your help!

**Comment by TigerHix** [comment]
@MediaMoots Wondering if you had time to look into any of those items. Thanks! 😃

**Comment by MediaMoots** [comment]
For the blue tint, it seems that KK also has a blue tint:
![image](https://user-images.githubusercontent.com/81146974/190902668-b737e2e1-cf9d-46d9-a02a-9417c93ce06f.png)

So, I suggest tweaking the color in blender.


> Finally, the body has weird black strips over it:

This is caused by the outline:
![image](https://user-images.githubusercontent.com/81146974/190902470-a408d325-d52a-4701-80ac-2cf9215dc282.png)

Disable it and it will be fine.
Or you can change the alpha setting in the skin shader:
![image](https://user-images.githubusercontent.com/81146974/190902509-a51ca32e-ede3-46c4-9998-9614e96d7d1c.png)

Final Result:
![image](https://user-images.githubusercontent.com/81146974/190903022-984bb5a1-bd8e-4453-8560-98c4ff49652b.png)
