### ISSUE TITLE
Alpha mask is sometimes stored in the Main Texture slot.

### ISSUE THREAD

**Issue by dragonash2019** [FlailingFog/KK-Blender-Porter-Pack#101]
As we are all aware, a lot of the custom hair in Koikatsu is done by using "accessories" and adjusting their shape.
This particular model seems to have ALL Accessories for hair

I *think* the custom shapes are not being kept on export. (ignore the lack of shader adjustment)

The hair is completely different on this model in blender vs in Koikatsu
![image](https://user-images.githubusercontent.com/47508016/150404929-ed3f29f2-83a0-4992-9477-f9a63d5c6f2b.png)
![image](https://user-images.githubusercontent.com/47508016/150405113-225f96b7-69cf-4f85-8252-6ea8bf95fcae.png)

Anyone else notice  this?

Here is the card
[Karin.zip](https://github.com/FlailingFog/KK-Blender-Porter-Pack/files/7907848/Karin.zip)

**Comment by MediaMoots** [comment]
That is probably because the alpha masks are not set, Please do all the steps in the README especially the import textures/colors one.

**Comment by dragonash2019** [comment]
I'm not entirely sure that is correct. 
Here are the two example accessory models side by side. 

The left side (purple) is the original one along with the default adjustment values.
![image](https://user-images.githubusercontent.com/47508016/150538753-a310d4f8-72dc-4246-8234-475bab48857a.png)


The right side (brown) is the one on the model, which I moved off of it for a side by side comparison.
As you can see by the adjustment values, it's just a scaled version (reduced) from the original
![image](https://user-images.githubusercontent.com/47508016/150539183-1d815d53-d996-470e-8caa-c9dc6296c629.png)

**Comment by MediaMoots** [comment]
The creator of this card put the alpha mask in the main texture slot.
I'll work on exporting the textures automatically but for now please export those textures and add them to the alpha mask for the hair materials.
![image](https://user-images.githubusercontent.com/81146974/150665756-3d997625-c084-46db-b05c-57912ef320c4.png)
cf_m_hair_f_82_MainTex.png
![_Export_2022-01-23-13-04-04_cf_m_hair_f_82_MainTex](https://user-images.githubusercontent.com/81146974/150665799-69666e67-8cac-4e00-abd6-c47649cf64ca.png)
![image](https://user-images.githubusercontent.com/81146974/150665773-260b2a4f-23c7-4795-9a63-628868f4034a.png)

**Comment by dragonash2019** [comment]
I'll try when I have a moment, but I'm a bit confused. I'm not that educated in blender and barely know enough to get items into unity for vrc. How is the alpha mask related to scaling? I thought it was for transparency.

**Comment by dragonash2019** [comment]
edit:
Removed my other questions. Didn't realize you explained and showed an example in a new issue (104)
Thanks!
