### ISSUE TITLE
The Playlist of tutorials is dead

### ISSUE THREAD

**Issue by EmpressAmyy** [FlailingFog/KK-Blender-Porter-Pack#102]
Hi, I'm trying to use this, but as I'm new to blender and all that jazz I'm struggling a bit. The written tutorial is quite confusing to me, and I think I (and noobs like me) would greatly benefit from a video guide but the link to the playlist is dead. I did manage to find the playlist after looking on youtube, so maybe fixing the link would be beneficial

**Comment by FlailingFog** [comment]
Thanks, I forgot to update the link
