### ISSUE TITLE
Torso is gone?

### ISSUE THREAD

**Issue by EmpressAmyy** [FlailingFog/KK-Blender-Porter-Pack#103]
Hi, me again! Sorry if this is a stupid question, but is the torso supposed to vanish underneath the shirt? When I first import the model.pmx file the chest is fine, but after I import the shader and textures the chest is almost completely gone while the lower half of the body is all there. Is this intentional? And if so is there a way to make it not happen?
![image](https://user-images.githubusercontent.com/78116482/150658156-ca682eba-6b20-481c-95a9-9b6907b7b9f3.png)

**Comment by EmpressAmyy** [comment]
Alright, I just checked by hiding all the clothes before adding the textures and the body is there underneath, it just seems to go away after adding the textures 
![image](https://user-images.githubusercontent.com/78116482/150658565-e1ce6c3c-36be-4d12-9ddc-f2d894769256.png)

**Comment by EmpressAmyy** [comment]
Ok, one last test, I exported the model with no clothes on at all and when I apply the textures this happens 
![image](https://user-images.githubusercontent.com/78116482/150658941-def8cc50-b338-4dbb-8f16-93110141eeee.png)
(If there's anything else to show/send that would help let me know, again I'm not super knowledgeable when it comes to this stuff 😅)

**Comment by miyabi-95** [comment]
I'm no expert but this is probably due to an alpha mask from the clothing textures, which hides areas of the body to prevent the skin from clipping thru clothing.

The best fix I could think of would be to export a nude character model from Koikatsu.

**Comment by EmpressAmyy** [comment]
> I'm no expert 
_Instantly gives me the right answer_
> The best fix I could think of would be to export a nude character model from Koikatsu.
It worked perfectly! On my third test I, galaxy brain that I am, only used 
![image](https://user-images.githubusercontent.com/78116482/150661756-70b8250b-2ce2-4512-b8fd-1a422791379a.png)
that setting, rather than actively stripping my model. I guess it kept that alpha mask or whatever 😝

**Comment by Wacken** [comment]
which version of blender did you use. I got the same/similar problem(torso gone female, completely black male), but choosing naked option doesn't work in both cases.

**Comment by Uradamus** [comment]
There really should be a toggle for this, as it is needed for some outfits to keep bits from poking out, but for others it is either unnecessary or straight up breaks the model's appearance when the chosen outfit (or lack of one) reveals the masked off area.

The steps I take to deal with this are:
1. duplicate the mask in question
2. make the duplicate a single user
3. flood fill it with the background color of the image to clear the masked bit
4. then feed both into a MixRGB node that feeds into the base mask output
5. Finally I could now use the factor value on the MixRGB node to switch between the 2 versions of the mask with values of 0 or 1.

I saw that the importer is being reworked and there seems to even be some support for the pushup features which should hopefully eliminate the need for the mask, but unfortunately the latest snapshot of that branch fails during the import for me still, but will be looking forward to trying it out again once the refactor is complete.
