### ISSUE TITLE
Question concerning shadow

### ISSUE THREAD

**Issue by yuyuki** [FlailingFog/KK-Blender-Porter-Pack#108]
After importing, fixing and apply texture, I've no shadow on my model except when I customize the shadow in Blender.
Do you have something easier or it's the right way ?

Scene witout contact shadow enabled
![scene without contact shadows](https://user-images.githubusercontent.com/5981867/151971084-b8acbf4b-c42e-4536-b3ee-f21024ca8456.png)

Setting the contact shadows on my light
![custom](https://user-images.githubusercontent.com/5981867/151971094-d0464df5-ed6c-4c37-8950-0f550d9f1f98.png)

The result
![scene](https://user-images.githubusercontent.com/5981867/151971095-03aad718-6598-4e92-a081-191bd7a22172.png)

**Comment by FlailingFog** [comment]
Make sure the shadow mode is set to something other than "None" or you'll get no shadows from the body or clothes materials. I think the hair is the only one set to "opaque" by default.
![image](https://user-images.githubusercontent.com/65811931/152073266-1c570f4d-a02a-4e9c-aa94-84df879dc8ab.png)
