### ISSUE TITLE
run Apply as Rest Pose before converting transformed bones to shape keys

### ISSUE THREAD

**Issue by miyabi-95** [FlailingFog/KK-Blender-Porter-Pack#111]
this actually has more to do with CATS but deals with an affect of the KKBP. note that by default, your character's legs are positioned differently in the Rest Position than they are in the Pose Position. if you go into Pose Mode and convert a Transform (scaled, rotated, moved bones) to Shape Keys using CATS, your characters legs will rotate along with the Shape Keys. this is due to the Rest and Pose Position discrepancy. an easy fix for this is to enter Pose Mode, and in CATS select Apply as Rest Pose, prior to creating Shape Keys with their Pose to Shape Key feature.

this isn't really an issue, but definitely something that I recently overlooked, much to my own dismay lol

**Comment by FlailingFog** [comment]
I'm not really sure how much of an issue this is, I see the effect you're talking about but it isn't obvious until you kick the shapekey value up to 10, and even then it's a pretty minor difference

**Comment by miyabi-95** [comment]
oh that's fair, it was just bothering me a lot personally lol
