### ISSUE TITLE
some Mod items conflict with separatebody.py

### ISSUE THREAD

**Issue by miyabi-95** [FlailingFog/KK-Blender-Porter-Pack#114]
![Screenshot (1372)](https://user-images.githubusercontent.com/63174638/155484608-766997cd-b638-433a-8925-0fb7255e2654.png)
KKBP runs into a naming issue due to one of my materials, a bodysuit because by default it has .003 in the name.

thankfully this was a quick fix but i thought i'd report it anywho!

![Screenshot (1373)](https://user-images.githubusercontent.com/63174638/155484610-3eb6f76a-96e6-4d04-96de-66ae1fedc485.png)
![Screenshot (1374)](https://user-images.githubusercontent.com/63174638/155484611-ef80be05-fa7a-4058-b424-cb5f855cdff8.png)

**Comment by FlailingFog** [comment]
https://github.com/FlailingFog/KK-Blender-Porter-Pack/commit/489c4b27326416b66b2ebab452a2f0754ab603e1 should have fixed this
