### ISSUE TITLE
Support importing multiple animations without being overwritten 

### ISSUE THREAD

**Issue by ghost** [FlailingFog/KK-Blender-Porter-Pack#117]
Maybe I'm a bit stupid but I was able to import multiple animations from koikatsu as per part 4 of the guide but unable to toggle between any of them it's stuck on the newest one, I'm pretty sure I did something wrong here but I don't know what I did.

**Comment by FlailingFog** [comment]
Currently it just overwrites any animation data when you import a new one

**Comment by lurkingaround** [comment]
No problem, looking forward to it.

**Comment by LingHyun** [comment]
How to export animation, is there a tutorial？

**Comment by FlailingFog** [comment]
this was superseded by the animation library feature, which allows you to import multiple animations at a time
