### ISSUE TITLE
ISSUE: Accessories and Hair become part of the "Center" parent bone when exporting from Koikatsu

### ISSUE THREAD

**Issue by qwsrkiwi** [FlailingFog/KK-Blender-Porter-Pack#118]
When extracting my male character, some of his accessories and parts of his hair become part of the "Center" parent bone instead of being on their respective parent bones (wrist, arms, etc). They don't have their own bones in the hierarchy, rather they are just part of the parent bone itself.

It makes it frustrating when trying to convert it for VRChat as the accessories will float in place since they are not attached to any bones in the "Hips" hierarchy.

![1](https://user-images.githubusercontent.com/74026253/156527502-f9a32600-b4d5-4383-8cc3-0391f0b4f2bc.png)
![2](https://user-images.githubusercontent.com/74026253/156527823-dbf64915-aa3c-4fe0-b165-3ddc8a09e9fc.png)

**Comment by qwsrkiwi** [comment]
Correcting myself, the issue occurs when I select "Finalize PMX" in Blender, NOT when I export the model from Koikatsu.
Some of the hair and accessories become part of the "Center" parent bone instead of being in the "Hips" hierarchy.

**Comment by BugMonkey42335** [comment]
This seems to be happening to the MasterFootIK as well.

![MasterFootIK](https://user-images.githubusercontent.com/64150986/156672233-0cbdaabd-ec3e-4288-961a-a59da933b955.png)

**Comment by FlailingFog** [comment]
I see this happening before selecting Finalize PMX, so I don't think that's the cause. You can fix it by assigning the accessories to the head and arm vertex groups. The last thirty seconds of this video shows how to do that: https://www.youtube.com/watch?v=GtuVV2waX4M&list=PLhiuav2SCuvdEAbUzJxSqp61fNiPTFfwb&index=2

**Comment by MediaMoots** [comment]
PR #138
