### ISSUE TITLE
Troubles with Importing Optionss (Finalization)

### ISSUE THREAD

**Issue by Fractune** [FlailingFog/KK-Blender-Porter-Pack#119]
I've been doing this in a loop for 6 hours trying to find the issue but there's basically the plugin itself acting sus, my issue here is basically that whenever I attempt to import the raw version aka. just the .pmx, it works, however when I attempt to Import KK Shader & Textures, the chest becomes invisible & the clothes as well as accessories.

Issues https://cdn.fractune.dev/oni/9gezko.mp4 (Video)

How it was actually supposed to be,
![JustAnImage](https://cdn.fractune.dev/oni/t6ston.png)

**Comment by Fractune** [comment]
Another video that includes the clothes on, and the matter most of them become invisible, https://cdn.fractune.dev/oni/owa1ln.mp4 + https://cdn.fractune.dev/oni/x0rgpk.mp4

**Comment by BugMonkey42335** [comment]
If you look in the shader that controls the body's illuminated and shaded colors you should see a, "Toggle to fix clipping" node.
There is also a toggle in the outline material you will need to toggle if you want the outline.
![Toggle to fix clipping](https://user-images.githubusercontent.com/64150986/156664645-148f8062-b07b-4917-a36d-8eaceccb0874.png)

**Comment by Fractune** [comment]
Sorry to say this but I barely can see anything in that screenshot you sent, the quality is bad when I zoom in to read and find where that is..

> If you look in the shader that controls the body's illuminated and shaded colors you should see a, "Toggle to fix clipping" node. There is also a toggle in the outline material you will need to toggle if you want the outline. ![Toggle to fix clipping](https://user-images.githubusercontent.com/64150986/156664645-148f8062-b07b-4917-a36d-8eaceccb0874.png)

**Comment by Fractune** [comment]
**I will try that** but I forgot to say that I got plugin errors while I was doing this, with just a simple template (which I had to redo & separate a ton of times in under 6 hours because of an error that I didn't know whaat it revolved around) remaking the project fixed it (somehow) altho it was the same template as before

First
![First](https://cdn.fractune.dev/oni/26orqm.png)
Second, 
![Second](https://cdn.fractune.dev/oni/vltmbg.png)
Third,
```
Python: Traceback (most recent call last):
  File "C:\Users\yuuko\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\KK-Blender-Porter-Pack-master\importing\importeverything.py", line 794, in execute
    texture_error = get_and_load_textures(directory)
  File "C:\Users\yuuko\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\KK-Blender-Porter-Pack-master\importing\importeverything.py", line 484, in get_and_load_textures
    newNode = genMat.material.node_tree.nodes['Gentex'].node_tree.copy()
KeyError: 'bpy_prop_collection[key]: key "Gentex" not found'

location: <unknown location>:-1
```

the template (`.pmx`)
![Image](https://cdn.fractune.dev/oni/cgqgii.png)

**Comment by Fractune** [comment]
> Click on the Node Group called, "Body Shader" and press Tab, that will bring you inside the Node Group.

It took me a while to find out how to open node groups (Just had to click shading) anyways, I ain't got "body shader" but in it's place I got KK Shader

![Image](https://cdn.fractune.dev/oni/elhr1b.png)

**Comment by Fractune** [comment]
> Click on the Node Group called, "Body Shader" and press Tab, that will bring you inside the Node Group ...

Thank you 👀 does the same sequence apply to Clothes as well?

**Comment by Fractune** [comment]
I found the issue, it was because I separated everything from Clothes (Underwear, Socks, Sandals, etc) and Hair as described in the tutorial video ep. 1, which said that I am free to separate "anything" from Clothes section but doing that basically breaks the import of KK Shader & Textures

Proof,
![Image](https://cdn.fractune.dev/oni/0hmv0n.png)
