### ISSUE TITLE
Plugin refuses to export .pmx file

### ISSUE THREAD

**Issue by BTHP5** [FlailingFog/KK-Blender-Porter-Pack#120]
Hi, I've been trying to export my model for multiple days now, surprised nobody brought this up yet.
I'm using **KKBP 5.0.0, Koikatsu BetterRepack RX6, BepInEx 5.4.15.0**, Unsure what HF patch, but certain it's there somewhere (I downloaded a pack of mods with the base game)

When I load my character card, everything is fine. I press the Export for KKBP button, it exports all of the textures, the normalmaps, colourmaps, detailmaps, but **no .pmx file.** 

I've been trying to use the old PMX Exporter plugin with the textures from KKBP in blender, using the latest CATS and KKBP addon for all different versions of Blender, but **I'm constantly getting callback python errors.**

**I've tried removing clothes, accessories, nothing ever works. Is someone able to fix this?**

**Comment by FlailingFog** [comment]
The .pmx from the PMX Exporter won't work with 5.0, only 4.3 and lower.
Are you sure you have HF Patch v3.13 or higher? That version comes with an update to the modding API that the exporter needs to function.

**Comment by BTHP5** [comment]
I had used KKManager to update any mods I had, though I'm unsure which HF patch RX6 uses as it was pre-patched.

And by "the .pmx from the PMX Exporter", do you mean that the KKBP Blender addon 5.0 is incompatible with the .pmx from the older PMX Exporter? 

I'll download a torrent client to install a more recent patch just in case, thank you for the help by the way!

**Comment by FlailingFog** [comment]
It looks like that BR release uses KKAPI 1.13, you need 1.25 or higher. And yes, the PMX exporter won't give you the same files as the KKBP exporter, so I don't think anything on 5.0 would work for it

**Comment by BTHP5** [comment]
Hi again, after installing the latest HF patch, API and the Bepis plug-in update needed, and it still does not export a .pmx file sadly

**Comment by BTHP5** [comment]
Oops, it appears I didn't download the HF patch correctly, I'll update after it's downloaded

**Comment by BTHP5** [comment]
It worked, thank you so much!! I'll inform the masses
