### ISSUE TITLE
Foot IK not working.

### ISSUE THREAD

**Issue by BugMonkey42335** [FlailingFog/KK-Blender-Porter-Pack#121]
While testing this card I noticed that the Feet IK's aren't working.
Looking through the bone constraints, vertex groups, bones, and logs I don't see any obvious problem.

![Foot IK bug](https://user-images.githubusercontent.com/64150986/156833768-684b5338-c054-4703-967f-7faa6846ceba.png)
![Darkness (3)](https://user-images.githubusercontent.com/64150986/156833416-1cd8a114-4682-4465-a6e3-9f367600b05d.png)

**Comment by MoriMorinya** [comment]
Try enabling the second armature layer by shift left clicking on it, selecting the upper points of both knee bones in edit mode  using box select and move them forward a bit. 

![image](https://user-images.githubusercontent.com/101014618/156893795-f6df5bc2-80ec-4815-aebd-2bcb17644b38.png)
![image](https://user-images.githubusercontent.com/101014618/156893927-95a26788-96d4-4000-ae14-32b98b9e8d5e.png)
