### ISSUE TITLE
Bake Material templates bug

### ISSUE THREAD

**Issue by X3gold** [FlailingFog/KK-Blender-Porter-Pack#122]
With the KKBP V5.1.0 is with me a bug, if I want to make because 4 step. It gets stuck at template body normal map and does not make the others

**Comment by FlailingFog** [comment]
Does https://github.com/FlailingFog/KK-Blender-Porter-Pack/issues/126 work?

**Comment by X3gold** [comment]
Thank you, has worked wonderfully for me
