### ISSUE TITLE
<< ISSUE >> Importing Shaders causes Python Callback Error + Missing Spine

### ISSUE THREAD

**Issue by BTHP5** [FlailingFog/KK-Blender-Porter-Pack#124]
Hey there, I'm using blender 3.0, the latest version of CATS, and version 5.10 (Latest) of the KKBP plugin.
At step 2a, importing the shaders, I receive an error and it doesn't complete the process 
![image](https://user-images.githubusercontent.com/54001645/156932287-f9eaa04e-eeaa-41ce-b096-364d24928524.png)

The console provided this

Applying material templates and textures...
Info: Removed 211 slots
Warning:        material or template wasn't found: cf_m_sirome_00 / Template Eyewhites (sirome)
Warning:        material or template wasn't found: cm_m_body / Template Body
Warning: 1 x Draw window and swap: 166.7318 ms, average: 166.73180001 ms
Getting textures from: D:\Koikatsu.BetterRepack.RX6\Koikatsu.BetterRepack.RX6\Koikatsu.BetterRepack.RX6\Export_PMX\20220306014233_RoperElise\
File not found, skipping: cm_m_body_DetailMask.png
File not found, skipping: cm_m_body_LineMask.png
File not found, skipping: cf_m_body_overtex2.png
File not found, skipping: cm_m_body_overtex1.png
File not found, skipping: cm_m_body_overtex1.png
File not found, skipping: cf_m_face_00_Texture5.png
File not found, skipping: cf_m_hair_b_aurora_al_00 -298398.001_DetailMask.png
File not found, skipping: cf_m_hair_b_aurora_al_00 -298398.001_ColorMask.png
File not found, skipping: cf_m_hair_b_aurora_al_00 -298398.001_HairGloss.png
File not found, skipping: cf_m_hair_b_aurora_al_00 -298398.001_AlphaMask.png
File not found, skipping: cf_m_hair_b_aurora_al_00 -298398.002_DetailMask.png
File not found, skipping: cf_m_hair_b_aurora_al_00 -298398.002_ColorMask.png
File not found, skipping: cf_m_hair_b_aurora_al_00 -298398.002_HairGloss.png
File not found, skipping: cf_m_hair_b_aurora_al_00 -298398.002_AlphaMask.png
File not found, skipping: cf_m_hair_b_aurora_al_00 -298398.003_DetailMask.png
File not found, skipping: cf_m_hair_b_aurora_al_00 -298398.003_ColorMask.png
File not found, skipping: cf_m_hair_b_aurora_al_00 -298398.003_HairGloss.png
File not found, skipping: cf_m_hair_b_aurora_al_00 -298398.003_AlphaMask.png
File not found, skipping: cf_m_hair_b_aurora_al_00 -298398_AlphaMask.png
File not found, skipping: cf_m_hair_f_16_00 -298496_AlphaMask.png
File not found, skipping: cf_m_hair_s_05_00 -298586_AlphaMask.png
File not found, skipping: ribbon -316396_MainTex.png
File not found, skipping: ribbon -316396_ColorMask.png
File not found, skipping: ribbon -316396_DetailMask.png
File not found, skipping: ribbon -316396_NormalMap.png
File not found, skipping: ribbon -316396_AlphaMask.png
File not found, skipping: ribbon -316396_PatternMask1.png
File not found, skipping: ribbon -316396_PatternMask2.png
File not found, skipping: ribbon -316396_PatternMask3.png
File not found, skipping: cf_m_tooth -298088_MainTex.png
File not found, skipping: cf_m_tooth -298088_NormalMap.png
File not found, skipping: cf_m_tooth -298088_AlphaMask.png
File not found, skipping: cf_m_tooth -298088_PatternMask1.png
File not found, skipping: cf_m_tooth -298088_PatternMask2.png
File not found, skipping: cf_m_tooth -298088_PatternMask3.png
File not found, skipping: panties_lacey_mat -307408_AlphaMask.png
File not found, skipping: panties_lacey_mat -307408_PatternMask1.png
File not found, skipping: panties_lacey_mat -307408_PatternMask2.png
File not found, skipping: panties_lacey_mat -307408_PatternMask3.png
File not found, skipping: cf_m_body_L -309600_NormalMap.png
File not found, skipping: cf_m_body_L -309600_AlphaMask.png
File not found, skipping: cf_m_body_L -309600_PatternMask1.png
File not found, skipping: cf_m_body_L -309600_PatternMask2.png
File not found, skipping: cf_m_body_L -309600_PatternMask3.png
File not found, skipping: acs_m_headphone_01 -316508_MainTex.png
File not found, skipping: acs_m_headphone_01 -316508_AlphaMask.png
File not found, skipping: acs_m_headphone_01 -316508_PatternMask1.png
File not found, skipping: acs_m_headphone_01 -316508_PatternMask2.png
File not found, skipping: acs_m_headphone_01 -316508_PatternMask3.png
File not found, skipping: cmnitm1007_frame_CH_ITEM_SD008Z -316370_MainTex.png
File not found, skipping: cmnitm1007_frame_CH_ITEM_SD008Z -316370_ColorMask.png
File not found, skipping: cmnitm1007_frame_CH_ITEM_SD008Z -316370_DetailMask.png
File not found, skipping: cmnitm1007_frame_CH_ITEM_SD008Z -316370_NormalMap.png
File not found, skipping: cmnitm1007_frame_CH_ITEM_SD008Z -316370_AlphaMask.png
File not found, skipping: cmnitm1007_frame_CH_ITEM_SD008Z -316370_PatternMask1.png
File not found, skipping: cmnitm1007_frame_CH_ITEM_SD008Z -316370_PatternMask2.png
File not found, skipping: cmnitm1007_frame_CH_ITEM_SD008Z -316370_PatternMask3.png
File not found, skipping: cmnitm1007_renz_CH_ITEM_SD008R1S5Z.002 -316370_MainTex.png
File not found, skipping: cmnitm1007_renz_CH_ITEM_SD008R1S5Z.002 -316370_MainTex_CT.png
File not found, skipping: cmnitm1007_renz_CH_ITEM_SD008R1S5Z.002 -316370_ColorMask.png
File not found, skipping: cmnitm1007_renz_CH_ITEM_SD008R1S5Z.002 -316370_DetailMask.png
File not found, skipping: cmnitm1007_renz_CH_ITEM_SD008R1S5Z.002 -316370_NormalMap.png
File not found, skipping: cmnitm1007_renz_CH_ITEM_SD008R1S5Z.002 -316370_AlphaMask.png
File not found, skipping: cmnitm1007_renz_CH_ITEM_SD008R1S5Z.002 -316370_PatternMask1.png
File not found, skipping: cmnitm1007_renz_CH_ITEM_SD008R1S5Z.002 -316370_PatternMask2.png
File not found, skipping: cmnitm1007_renz_CH_ITEM_SD008R1S5Z.002 -316370_PatternMask3.png
File not found, skipping: acs_m_wristR_wbandR -316480_MainTex.png
File not found, skipping: acs_m_wristR_wbandR -316480_AlphaMask.png
File not found, skipping: acs_m_wristR_wbandR -316480_PatternMask1.png
File not found, skipping: acs_m_wristR_wbandR -316480_PatternMask2.png
File not found, skipping: acs_m_wristR_wbandR -316480_PatternMask3.png
File not found, skipping: SallyTail_mat -316454_MainTex.png
File not found, skipping: SallyTail_mat -316454_DetailMask.png
File not found, skipping: SallyTail_mat -316454_NormalMap.png
File not found, skipping: SallyTail_mat -316454_AlphaMask.png
File not found, skipping: SallyTail_mat -316454_PatternMask1.png
File not found, skipping: SallyTail_mat -316454_PatternMask2.png
File not found, skipping: SallyTail_mat -316454_PatternMask3.png
File not found, skipping: cf_m_top_tsyatu01_a -318840_AlphaMask.png
File not found, skipping: cf_m_top_tsyatu01_a -318840_PatternMask1.png
File not found, skipping: cf_m_top_tsyatu01_a -318840_PatternMask2.png
File not found, skipping: cf_m_top_tsyatu01_a -318840_PatternMask3.png
File not found, skipping: cf_m_bot_high-waist_skirt -302958_AlphaMask.png
File not found, skipping: cf_m_bot_high-waist_skirt -302958_PatternMask2.png
File not found, skipping: cf_m_bot_high-waist_skirt -302958_PatternMask3.png
File not found, skipping: cf_m_top_suspenders -302958_AlphaMask.png
File not found, skipping: cf_m_top_suspenders -302958_PatternMask2.png
File not found, skipping: cf_m_top_suspenders -302958_PatternMask3.png
File not found, skipping: cf_m_socks_xmas -311846_AlphaMask.png
File not found, skipping: cf_m_socks_xmas -311846_PatternMask2.png
File not found, skipping: cf_m_socks_xmas -311846_PatternMask3.png
File not found, skipping: cf_m_shoes_cheersboots -314092_AlphaMask.png
File not found, skipping: cf_m_shoes_cheersboots -314092_PatternMask1.png
File not found, skipping: cf_m_shoes_cheersboots -314092_PatternMask2.png
File not found, skipping: cf_m_shoes_cheersboots -314092_PatternMask3.png
Warning: 1 x Draw window and swap: 84.0578 ms, average: 84.05780001 ms
cf_m_hair_b_aurora_al_00 -298398.001 had no alphamask
cf_m_hair_b_aurora_al_00 -298398.002 had no alphamask
cf_m_hair_b_aurora_al_00 -298398.003 had no alphamask
cf_m_hair_b_aurora_al_00 -298398 had no alphamask
cf_m_hair_f_16_00 -298496 had no alphamask
cf_m_hair_s_05_00 -298586 had no alphamask
Warning: 1 x Draw window and swap: 201.6745 ms, average: 201.67449999 ms
Warning: 1 x Draw window and swap: 125.0726 ms, average: 125.07260000 ms
Warning: 1 x Draw window and swap: 105.6689 ms, average: 105.66890001 ms
Warning: 1 x Draw window and swap: 83.3929 ms, average: 83.39290001 ms
Warning: 1 x Draw window and swap: 83.3268 ms, average: 83.32680000 ms
Warning: 1 x Draw window and swap: 87.5484 ms, average: 87.54840001 ms
Warning: 1 x Draw window and swap: 101.6621 ms, average: 101.66210000 ms
Warning: 1 x Draw window and swap: 76.6733 ms, average: 76.67329998 ms
Warning: 1 x Draw window and swap: 77.4641 ms, average: 77.46410000 ms
Warning: 1 x Draw window and swap: 74.7124 ms, average: 74.71240000 ms
Warning: 1 x Draw window and swap: 80.6347 ms, average: 80.63469999 ms
Warning: 1 x Draw window and swap: 83.9976 ms, average: 83.99759998 ms
Warning: 1 x Draw window and swap: 71.9391 ms, average: 71.93910002 ms
Warning: 1 x Draw window and swap: 113.8635 ms, average: 113.86350001 ms
Warning: 1 x Draw window and swap: 99.1422 ms, average: 99.14220002 ms
Warning: 1 x Draw window and swap: 141.5825 ms, average: 141.58249999 ms
Warning: 1 x Draw window and swap: 121.4522 ms, average: 121.45220002 ms
Warning: 1 x Draw window and swap: 115.9244 ms, average: 115.92440002 ms
Warning: 1 x Draw window and swap: 110.3599 ms, average: 110.35989999 ms
Warning: 1 x Draw window and swap: 87.5223 ms, average: 87.52229999 ms
Python: Traceback (most recent call last):
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\KK-Blender-Porter-Pack-master\importing\importeverything.py", line 800, in execute
    if modify_armature and bpy.data.objects['Armature'].pose.bones["Spine"].custom_shape == None:
KeyError: 'bpy_prop_collection[key]: key "Spine" not found'

location: <unknown location>:-1

It looks like it's not finding the textures for some reason, I selected the correct folder which all the textures are in, as well as the Spine not being found. The function only gets so far and then gives me the error, then changing the bone names with the prefix "Widget"

**Comment by BTHP5** [comment]
Does...anyone know what's up with this or..

**Comment by MediaMoots** [comment]
Hi!

I think the KKAPI plugin is outdated


Try to install KKAPI v1.25 or higher or use BetterRepack RX11
`D:\Koikatsu.BetterRepack.RX6\Koikatsu.BetterRepack.RX6\Koikatsu.BetterRepack.RX6`

**Comment by BTHP5** [comment]
Heyo!! I have the latest KKAPI and it appears I need to open the .blend file for it to work, however, when it comes to preparing it for export, the plug-in gets stuck at “Using CATS to simplify bones…”

**Comment by BTHP5** [comment]
The fix: Actually using the .blend file provided
Why isn't this in the tutorial? Oh well :P
