### ISSUE TITLE
gl_FragColor error on Blender 3.1.0

### ISSUE THREAD

**Issue by finn7199** [FlailingFog/KK-Blender-Porter-Pack#125]
Hi, 
I get this error when I try to apply colors onto the shaders (step 2b).
I don't understand what it means by: _gl_FragColor is removed after version 420_

Blender Version 3.1.0
KKBP 5.1.0
CATS 0.19.0
HFPatch 3.14

```
ERROR (gpu.shader): pyGPUShader FragShader:
      |
   81 |         gl_FragColor = vec4(newColor.rgb, texRGBA.a);
      |
      | Error: C7616: global variable gl_FragColor is removed after version 420

Python: Traceback (most recent call last):
  File "C:\Users\shami\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\KK-Blender-Porter-Pack-master\importing\importcolors.py", line 727, in execute
    convert_main_textures(lut_light)
  File "C:\Users\shami\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\KK-Blender-Porter-Pack-master\importing\importcolors.py", line 479, in convert_main_textures
    image_to_KK(image, lut_light)
  File "C:\Users\shami\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\KK-Blender-Porter-Pack-master\importing\importcolors.py", line 90, in image_to_KK
    shader = gpu.types.GPUShader(vertex_default, current_code)
Exception: Shader Compile Error, see console for more details

location: <unknown location>:-1
```

**Comment by matchapuff** [comment]
I have the same problem.

**Comment by igugf** [comment]
Same Error

**Comment by TheLazyName** [comment]
Are you trying to export a male model?

**Comment by finn7199** [comment]
> Are you trying to export a male model?

It's a female model. I just tried exporting a male model and I get the same error on step 2b.

**Comment by WeepyWillow** [comment]
I am also running into this same error, everything prior to that flows just fine but I get to step 2b and its just a wall I've yet to be able to get working.

**Comment by MediaMoots** [comment]
Does it error on Blender 3.0?

**Comment by TheLazyName** [comment]
I did a test on Blender 3.0 and it seems to get passed that step. I'm assuming it's a 3.1 thing then.

**Comment by WeepyWillow** [comment]
I also just finished a 3.0 Test same results as LazyName it passed that step fine.

**Comment by TheLazyName** [comment]
Tested on 3.0 with a male model, it passed the step!

**Comment by finn7199** [comment]
I tested on Blender 3.0 and it is working fine. Thank you so much!
