### ISSUE TITLE
Error when baking textures

### ISSUE THREAD

**Issue by YellowInkling** [FlailingFog/KK-Blender-Porter-Pack#126]
Hi I'm trying to make a VRChat model from one of my Koikatsu Models but everytime I try to bake the models I get this error.
It happens when It tries to bake the Body Texture and I don't know how to resolve it.
![image](https://user-images.githubusercontent.com/74347915/158051377-c377c927-43f4-464b-9491-57499bdf412b.png)

**Comment by FlailingFog** [comment]
Sorry, that's my bad when I updated the template file.
It should work if you open the side bar and change this Rim node group's name from Rim.001 to Rim
![image](https://user-images.githubusercontent.com/65811931/158067684-34c972a4-fc68-46c8-a218-f0e5d6fe6031.png)

It screwed up on the hair too, so you'll probably have to change that to Rim as well.
