### ISSUE TITLE
Finalize PMX file, 'key "model" not found"

### ISSUE THREAD

**Issue by stearman10** [FlailingFog/KK-Blender-Porter-Pack#127]
Trying to import model from koikatsu to blender, using cats 0.19.0 and KKBP 5.1.1. when i click "a1) finalize PMX file" i get this error message. I am new to blender so im prone to think its something i forgot to install? i get the same error with models i made using mods present in Koikatsu HF patch 3.15 and models that are included in the base game. 
![error](https://user-images.githubusercontent.com/18451018/158103045-cee2cfdf-42fb-417c-9778-3a61650d1675.png)

**Comment by FlailingFog** [comment]
When you import the pmx file with cats it should generate a 'Model' text and a 'Model_e' text in the scripting tab at the top. This line is meant to delete those but it looks like they were already deleted by the time you pressed the button.
Just create two text files with those names in the scripting tab and it should work
![image](https://user-images.githubusercontent.com/65811931/158277978-2c2fe72a-319a-4583-86d0-503d135f0120.png)

**Comment by stearman10** [comment]
thank you for response, i got around it by commenting out the line that was the key error, but am getting another error. will make new post about it.
