### ISSUE TITLE
Sun not casting shadows on to model

### ISSUE THREAD

**Issue by ghost** [FlailingFog/KK-Blender-Porter-Pack#128]
Followed your guide on youtube and I ran in to a problem with the sun.

I enabled the shadowcast shading proxy and added a sun to my scene however I can't see any shadows being casted in the viewport, the sun doesn't give me that option but I can't see it in the render either.

![sun](https://user-images.githubusercontent.com/101545518/158115179-d58e5b6f-aa84-4dc0-87c3-219d02031ad3.png)
![shadowproxy](https://user-images.githubusercontent.com/101545518/158115197-48db54cb-2a19-4715-9b2f-000e660e7b8e.png)

I'm using blender 3.0 so maybe it works differently than with 2.8.

**Comment by FlailingFog** [comment]
You shouldn't need to enable shadow or the shading proxy for shadows to work.
Is your world color set to white? That would prevent any shadowing

**Comment by newtoblender** [comment]
Ah, I didn't know that.
I changed the world color to black but shadows don't seem to appear, am I using the sun wrong? It's still the same as above.

**Comment by FlailingFog** [comment]
I just realized you're not in rendered view, so the sun won't work at all
![image](https://user-images.githubusercontent.com/65811931/160025220-1233fd0b-001f-4047-b2d2-c9a8fdd2b6e1.png)

**Comment by newtoblender** [comment]
I tried but it doesn't feel like it's working. Here's the render of it, there doesn't seem to be any shadowing on the face. Am I just using the sun wrong?
![render](https://user-images.githubusercontent.com/101545518/160055501-92b76e77-2ea6-4f93-be22-ff136caedc67.png)
