### ISSUE TITLE
Nipples Color Fix for Eevee/Cycles and Weird materials for Cycles in the updated "KK Shader V5.0.blend" [SOLVED]

### ISSUE THREAD

**Issue by im-pain** [FlailingFog/KK-Blender-Porter-Pack#134]
Hi, some time ago you uploaded a cycles version of the KK Shader blend file, noticed that in the new update you dont included that(also if you replace the blend file in the actual version of the addon it will gave you errors when you try to set the shaders), so i tried to solve easily connecting the MainTex, Normal, Alpha to a Principied BSDF, and all nice, but the config for nipples need to change because they have no colors and masking, so copied the originals from the game and set them as inputs
![imagen](https://user-images.githubusercontent.com/87384441/159897905-38746486-0d6e-49ad-9511-c9db0f18d118.png)
![imagen](https://user-images.githubusercontent.com/87384441/159900377-3d258bdb-f1a4-4696-beda-62f012a8d681.png)

also i adjusted a little the nipple red detail masking for eevee to get the exact masking, i did all this comparing with the game reference so 99% accuracity 

so here is the updated KK Shader blend file, ready for both Eevee and Cycles with nipples solved 
[KK Shader V5.0.blend.zip](https://github.com/FlailingFog/KK-Blender-Porter-Pack/files/8340742/KK.Shader.V5.0.blend.zip)

**Comment by im-pain** [comment]
idk if i can post nsfw textures lmao

**Comment by FlailingFog** [comment]
I was going to add your file at some point
