### ISSUE TITLE
Export to PMX not working for a certain character

### ISSUE THREAD

**Issue by hdddestroyer** [FlailingFog/KK-Blender-Porter-Pack#136]
I wanted to export a character to PMX first but all it does is create hair texture and that's it..
Here's the link to required zipmods and character card: [Link](https://mega.nz/folder/f4VGxRqC#xGjSPgRY_g9j-ZQD63NLUg)

**Comment by sleepymanakete** [comment]
Have this issue too with yelan.
card: [link](https://www.pixiv.net/en/artworks/96540815)

**Comment by sleepymanakete** [comment]
From my testing, it seems to have something to do with the face type. I guess the exporter can only do type 1 faces at the moment. 
card and mods:
[card](https://cdn.discordapp.com/attachments/447115249997578241/958021486633967657/Koikatu_F_20220226211751665__.png) 
[mod](https://www.mediafire.com/file/rfprgezok6d1hip/%255BJM%255Dyelan.zipmod/file) 
[mod 2](https://www.mediafire.com/file/1db06ueogsdut8m/%255BSZY%255Dyelan_headmod.zipmod/file)

**Comment by MediaMoots** [comment]
> I wanted to export a character to PMX first but all it does is create hair texture and that's it.. Here's the link to required zipmods and character card: [Link](https://mega.nz/folder/f4VGxRqC#xGjSPgRY_g9j-ZQD63NLUg)

@hdddestroyer 
Which KK game are you using? Thanks!
