### ISSUE TITLE
Eye Textures Tiling and offset always need to be set manually in blender

### ISSUE THREAD

**Issue by TheMaskedMan00** [FlailingFog/KK-Blender-Porter-Pack#139]
![image](https://user-images.githubusercontent.com/46354545/160299951-bc70c10e-92e2-4b96-9495-5b3f68dc461d.png)
Blender before fixing it myself /\

![image](https://user-images.githubusercontent.com/46354545/160299976-0831ad14-ad24-424f-9539-53bab337f223.png)
Hitomi in material editor in game /\

![image](https://user-images.githubusercontent.com/46354545/160300091-94064337-58f4-4eab-aa90-c64c62ac6c6f.png)
We disconnect scale from eye maintex overlay 1 and overlay 2, then copy the corsponding values to each textures mapping /\\
![image](https://user-images.githubusercontent.com/46354545/160300118-d8cdaa10-b20a-4661-8796-922b37c03ebf.png)
These values /\

Is there some way to build this into the exporter and blender plugin, its quite annoying to have to do this every time, this model was not a good example, a more noticable example would be this \\/

![image](https://user-images.githubusercontent.com/46354545/160300277-d7b60482-3c86-4b6e-adda-5f79710a78ca.png)

**Comment by FlailingFog** [comment]
That's interesting, I didn't know that data was accessible. These could be set automatically on the blender side, but the exporter would have to extract these numbers into the json file to do this

**Comment by MediaMoots** [comment]
PR #138
