### ISSUE TITLE
(Question) Is there a way to assign the overlay to the textures within the nodes?

### ISSUE THREAD

**Issue by BTHP5** [FlailingFog/KK-Blender-Porter-Pack#145]
Hi there! When importing my model, and getting the colours converted, but the custom overlay that I'd had on the clothes is absent.

I've tried fiddling around with the nodes and textures, but I can't seem to find a definitive way to place it back on.
![image](https://user-images.githubusercontent.com/54001645/161428381-b59c0e9c-eaee-4040-a4c9-d8403596b03c.png)

Is there a specific area in the nodes in which I should place a texture file?
Thank you <3

**Comment by FlailingFog** [comment]
These three groups are pretty much one block that gives the final colors for the model, so if you want to add anything on top of that you can add it after the "Color out" line
![image](https://user-images.githubusercontent.com/65811931/161439565-06375ea8-61d0-4636-a3ec-8eec174c153d.png)

Or you can open up the third block and add your textures to the connections going into the Mix node inputs to have different looks for light and dark
