### ISSUE TITLE
Problem in applying the baked materials

### ISSUE THREAD

**Issue by Souka42** [FlailingFog/KK-Blender-Porter-Pack#146]
When i try to apply the baked materials, the clothes, accessories and hair all disappears, and the body seems to have now the texture of the clothes.
This is what remains of it:
![error2](https://user-images.githubusercontent.com/102937223/161467229-a325fa95-c2ef-489c-a69e-42f7a4e6b92d.JPG)
![error1](https://user-images.githubusercontent.com/102937223/161467234-ed526106-0ad1-4594-a69d-79a078951cd8.JPG)

**Comment by FiiNomNom** [comment]
i am also having this issue some insight as to the cause would be greatly appreciated

**Comment by FlailingFog** [comment]
I'm interested as to why this is happening because it looks like blender is opening the file correctly but can't find the file immediately after its opened. Does it happen on a specific card or is it all models? And are you on blender 2.93 or 3.0? Because those are the only two I've tested the apply button on.

**Comment by Souka42** [comment]
> I'm interested as to why this is happening because it looks like blender is opening the template face file correctly but can't find the file immediately after its opened. Does it happen on a specific card or is it all models? And are you on blender 2.93 or 3.0? Because those are the only two I've tested the apply button on.

I didnt tested it with different cards. My blender right now is version 3.1.0

**Comment by Dudeydude420** [comment]
I'm getting the same issue as well on the same lines on the script. My Blender is on 3.1.0

**Comment by FlailingFog** [comment]
I was able to reproduce this using blender 3.1. It looks like the images are being (incorrectly) recognized as UDIM images so blender changes the filename during import. The file can't be found because the file is being renamed. Try using blender 3.0 or 2.93 for now.

**Comment by Clownman18** [comment]
I have the exact same issue except I am using Blender 3.0. I tried to use 2.93 but I was unable to open my .blend file and as a result could not test it.

**Comment by FlailingFog** [comment]
#109
