### ISSUE TITLE
Pelvis not found

### ISSUE THREAD

**Issue by ggw001001** [FlailingFog/KK-Blender-Porter-Pack#148]
![3](https://user-images.githubusercontent.com/102470245/162443923-b0ded108-e08e-4959-9045-a54ead80defa.JPG)
![32](https://user-images.githubusercontent.com/102470245/162443946-9bd02467-7e85-4a19-a5fc-7fa9fabd6652.JPG)

This issue appears in the third step.

**Comment by FlailingFog** [comment]
Before you hit the button, is there a pelvis bone on layer 1 of the armature?

**Comment by ggw001001** [comment]
> Before you hit the button, is there a pelvis bone on layer 1 of the armature?

Yes, there is. But when I hit the button, it disappears.
![24](https://user-images.githubusercontent.com/102470245/162652995-20f82daf-a878-4c56-8f38-280c0f51ef8a.JPG)

![25](https://user-images.githubusercontent.com/102470245/162653013-c593ee9b-ff4e-4342-887f-c75af9a084b4.JPG)

**Comment by MediaMoots** [comment]
Does this still happen?
