### ISSUE TITLE
Unable to export pmx and .json

### ISSUE THREAD

**Issue by KotoriKoi** [FlailingFog/KK-Blender-Porter-Pack#150]
@FlailingFog 
This is an issue caused by a specific character card, the console reads:
[Info :Skin Overlay Mod] Reading legacy overlay data
[Message:AccStateSync (Debug Build)] Reminder: Slot06 is set as secondary
[Info : Console] System.IndexOutOfRangeException: Array index is out of range.
   at PmxBuilder.CreateMeshList() [0x00000] in <filename unknown>:0
   at PmxBuilder.BuildStart_OG () [0x00000] in <filename unknown>:0
I can't figure this out, so I'm here for help.

**Comment by MediaMoots** [comment]
Which Koikatsu game are you using?

Could you share the card please? Thanks!

**Comment by KotoriKoi** [comment]
@MediaMoots OK, the link is here: https://www.mediafire.com/file/s88g0073s4gz5zy/card.png/file
The Koikatsu game I use is the same as yours. Please note that this card reaches an astonishing 50m, please make sure your RAM/Virtual RAM is above 32G when exporting, otherwise it may cause exceptions. Please let me know if you know how to streamline this card.
Also, it was already possible to export it after turning off some layers in the in-game character crafting interface, but it caused new problems, as you can see:
![1](https://user-images.githubusercontent.com/91445888/164222402-b9beb510-b5f3-4599-9146-30ccfe84f3d3.png)
After performing step 3, some color abnormalities and missing face textures appear. This problem also occurs in some other cards.

**Comment by MediaMoots** [comment]
It used over 50GB ram to export... bruh...
lol

**Comment by MediaMoots** [comment]
PR #138
