### ISSUE TITLE
KKBP exporter uses only first word of KK material name as export material name

### ISSUE THREAD

**Issue by TigerHix** [FlailingFog/KK-Blender-Porter-Pack#151]
For instance, if there are two materials named `Wolf Ear` and `Wolf Fur`, they will be exported as `Wolf` and the texture files also have names prefixed with `Wolf`. Subsequently, the second exported texture overrides the first, and in the "Finalize PMX" process the materials will be merged (because they have the same name) even though they shouldn't be.

**Comment by MediaMoots** [comment]
Could you share the card please? Thanks!

**Comment by TigerHix** [comment]
@MediaMoots Sure! https://drive.google.com/file/d/1q6gcnTqEWsgzN8itUwFQ57XAJvNlspVn/view?usp=sharing

**Comment by MediaMoots** [comment]
thank you!

**Comment by MediaMoots** [comment]
PR #138
