### ISSUE TITLE
Error with importing textures

### ISSUE THREAD

**Issue by sleepymanakete** [FlailingFog/KK-Blender-Porter-Pack#152]
When I use this [card](https://media.discordapp.net/attachments/447115249997578241/909715995743113226/Koikatu_F_20210928054725402_Eula_Lawrence.png) I get this error even though I have the texture. It happens on step 2a
`Python: Traceback (most recent call last):
  File "C:\Users\UserName\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\KK-Blender-Porter-Pack-master\importing\importeverything.py", line 794, in execute
    texture_error = get_and_load_textures(directory)
  File "C:\Users\UserName\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\KK-Blender-Porter-Pack-master\importing\importeverything.py", line 367, in get_and_load_textures
    bpy.data.images[image.name].pack()
KeyError: 'bpy_prop_collection[key]: key "Avatar_Lady_Claymore_Eula_Tex_Hair_Diffuse -712790_ColorMask.png" not found'`

**Comment by ilcane87** [comment]
I confirmed the issue in a previous thread: https://github.com/FlailingFog/KK-Blender-Porter-Pack/issues/149

There are two peculiarities I noticed with this character:

- The addon doesn't recognize the hair by itself at the end of the 'Finalize PMX' step, so no faces are selected automatically;
- The naming conventions for the problematic hair texture are different from the usual, none of the other models I've tried have the character name or 'Tex_Hair_Diffuse' included in the texture file name.

No idea if any of that is related though, perhaps it's just that the hair is part of a mod I've never seen used before.

**Comment by MediaMoots** [comment]
![image](https://user-images.githubusercontent.com/81146974/164198043-6f3ab538-0208-4a21-b3a9-ae90e6f15809.png)

**Comment by sleepymanakete** [comment]
Thank you!!

**Comment by MediaMoots** [comment]
PR #138 

> Thank you!!

No problem! :)
