### ISSUE TITLE
Support for "bald" :P characters?

### ISSUE THREAD

**Issue by MediaMoots** [FlailingFog/KK-Blender-Porter-Pack#153]
There are some cards that don't use "Hair" and instead make them accessories
#152 https://media.discordapp.net/attachments/447115249997578241/909715995743113226/Koikatu_F_20210928054725402_Eula_Lawrence.png 

What would be the best way to deal with this?
Remove the "Does Hair obj exist" check? but that check is quite useful...

**Comment by FlailingFog** [comment]
I added a "check for hair" toggle to your PR branch to let bald characters go through the 2a step. It just creates a cube and makes it act as a temporary hair object.
![image](https://user-images.githubusercontent.com/65811931/164977888-bf78bc6f-f962-4a86-bbe9-03e0bca89674.png)

**Comment by MediaMoots** [comment]
Perfect, thanks!

**Comment by BeamingTerror** [comment]
Hello, can you please inform me where the "check for hair" toggle is located?

**Comment by FlailingFog** [comment]
It's automatically detected in the pull request branch, so I removed it
