### ISSUE TITLE
"Template General not found" error

### ISSUE THREAD

**Issue by agudgorl** [FlailingFog/KK-Blender-Porter-Pack#157]
I just recently started to import my character/fursona into the program. I immediately ran into issues regardng importing the textures. Here's the raw log from the console:

Applying material templates and textures...
Warning:        material or template wasn't found: cf_m_face_00 / Template Face
Warning:        material or template wasn't found: cf_m_mayuge_00 / Template Eyebrows (mayuge)
Warning:        material or template wasn't found: cf_m_noseline_00 / Template Nose
Warning:        material or template wasn't found: cf_m_eyeline_00_up / Template Eyeline up
Warning:        material or template wasn't found: cf_m_eyeline_down / Template Eyeline down
Warning:        material or template wasn't found: cf_m_sirome_00 / Template Eyewhites (sirome)
Warning:        material or template wasn't found: cf_m_sirome_00.001 / Template Eyewhites (sirome)
Warning:        material or template wasn't found: cf_m_hitomi_00 / Template Eye (hitomi)
Warning:        material or template wasn't found: cf_m_hitomi_00.001 / Template Eye (hitomi)
Warning:        material or template wasn't found: cf_m_body / Template Body
Warning:        material or template wasn't found: cm_m_body / Template Body
Warning:        material or template wasn't found: cf_m_tooth / Template Teeth (tooth)
Warning:        material or template wasn't found: cf_m_tang / Template General
Python: Traceback (most recent call last):
  File "C:\Users\[user]\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\KK-Blender-Porter-Pack-master\importing\importeverything.py", line 787, in execute

  File "C:\Users\[user]\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\KK-Blender-Porter-Pack-master\importing\importeverything.py", line 112, in get_templates_and_apply
    body.material_slots['Template General'].material = tongueTemplate
KeyError: 'bpy_prop_collection[key]: key "Template General" not found'

I don't know if this is an issue with the textures themselves, or if it's the way the textures were exported. Regardless, I'll provide the card for her.

https://cdn.discordapp.com/attachments/971488693808427068/974797559245729862/Koikatu_F_20220314173334912_Kyrie_agudboi.png

**Comment by FlailingFog** [comment]
Can you check if this updated exporter and plugin work? #138 

It's working for me on that version
![image](https://user-images.githubusercontent.com/65811931/168424960-bf3a4a57-9560-490b-847a-b064a5e39b86.png)

**Comment by agudgorl** [comment]
I think it might have something to do with my game, as I'm on CE 6.2. I don't know what version of the HF patch I have, though.
