### ISSUE TITLE
Pupils/Irises clipping while tracking the eyes.

### ISSUE THREAD

**Issue by BTHP5** [FlailingFog/KK-Blender-Porter-Pack#158]
Hey there, plugin works pretty well, but there's one thing I just cannot seem to fix. The eyes.

After using the plugin as followed to convert my model to VRM, the eye tracking usually would follow my eyes in real-time. However, I had to turn this feature off because the irises/pupils would just clip into the eye whites. After testing the eye movement, it seems that the eyes rotate too much, causing them to clip.

Is there a way to fix this within Blender? Perhaps I need to re-weight the "hitomi" material to something else?

Feedback is much appreciated!

**Comment by SmilingLarva** [comment]
you should look to this #51 
before export, in atlas, you should separate the eye material, then in unity, remove the eye bones from the unity, remove vrm look at bone applyer, then add vrm look at blendshape applyer, then go to the blendshapes, you could see lookUp, lookDown, click them, material, select check eye, and change their uv position.

**Comment by alternate4a1** [comment]
> you should look to this #51 before export, in atlas, you should separate the eye material, then in unity, remove the eye bones from the unity, remove vrm look at bone applyer, then add vrm look at blendshape applyer, then go to the blendshapes, you could see lookUp, lookDown, click them, material, select check eye, and change their uv position.

hello, im new to unity, still encounter the clipping problem even after applying the look at blendshape script and follow your instruction may i ask for more clear step by step because i might probably dont understand some.
