### ISSUE TITLE
Sometimes the Exporter does not give a .PMX file

### ISSUE THREAD

**Issue by LegionInstaller** [FlailingFog/KK-Blender-Porter-Pack#159]
Hello
I've been using this version of the Porter Pack
https://github.com/MediaMoots/KK-Blender-Shader-Pack/tree/pluginupdate
but sometimes the KKBP Exporter does not give a .pmx file , it also does not give a file when you change the Uniform type ,
It always has to be set to In School for it to give a pmx file

**Comment by LegionInstaller** [comment]
And sometimes it does not give any Pmx file , no matter if it is set to In School or not

**Comment by LegionInstaller** [comment]
And also sometimes this happens
![Bild_2022-05-23_001557513](https://user-images.githubusercontent.com/49412050/169718300-ef1f344c-c5af-4205-ad9a-8265f334bb23.png)

**Comment by MediaMoots** [comment]
Does this happen with a specific card or on all of them?

**Comment by LegionInstaller** [comment]
> 

It happens very random , as an example for one card I had to remove the custom Main Texture for it to be able to export the PMX file

**Comment by LegionInstaller** [comment]
This is the best example I have https://drive.google.com/file/d/1hLdZyVqBGmjNmScw_pX9S9GWp6cmVOOs/view?usp=sharing
has to be set to "Sleeping Over" , older variants of the Exporter , exported the PMX file

**Comment by MediaMoots** [comment]
Fixed in PR #138
