### ISSUE TITLE
Color fade in hair

### ISSUE THREAD

**Issue by FiiNomNom** [FlailingFog/KK-Blender-Porter-Pack#160]
When i import my koikatsu model and add shaders and convert i lose the two toned hair on my model and it all goes to one color i dont know what the issue is if anyone can help that would be greatly appreciated
![blonde pink(KKP)](https://user-images.githubusercontent.com/103234210/169716668-ff191c66-ac8f-4307-91b7-32c9ea8e117b.png)
![all blonde(blender)](https://user-images.githubusercontent.com/103234210/169716669-11fad0e1-b47b-484a-964e-47952bb8f002.png)

first is in koikatsu party second is after colors are converted in blender

**Comment by MediaMoots** [comment]
Could you share the card please?

**Comment by FiiNomNom** [comment]
> 
![Koikatu_F_20220521134209625_Chika Haruno](https://user-images.githubusercontent.com/103234210/170809622-ea346613-1abb-4552-a429-8dbe2596d086.png)

**Comment by FlailingFog** [comment]
For adjusting the colors, you might want to check the youtube videos I have on the landing page. There's a fade slider for the hair you have to enable in hair shader group
![image](https://user-images.githubusercontent.com/65811931/170888300-bd737756-4d1b-4015-9add-020cabb4b4ac.png)

**Comment by FiiNomNom** [comment]
thankies
