### ISSUE TITLE
Eye/Eyelashes texture Issue

### ISSUE THREAD

**Issue by sleepymanakete** [FlailingFog/KK-Blender-Porter-Pack#161]
Hi!
I was trying out the #138 pr to import models with all the outfit variations. When I import the textures, her eyes/eyelashes are just white.
![blender_ayE3Tevph8](https://user-images.githubusercontent.com/30272172/170338704-954571ca-542a-4bc3-b5d5-6d25c765fb12.jpg)

card
https://www.pixiv.net/en/artworks/98187947

**Comment by LegionInstaller** [comment]
Yeah you have to combine it with the Eyelash Up

**Comment by MediaMoots** [comment]
Yeah, that pr is not done, and that's the Kage material.

**Comment by MediaMoots** [comment]
To be clear, the update does not export all the outfits (In School, Going Home, Casual, etc), just the variations of the current outfit (Fully clothed, half naked, etc)

**Comment by sleepymanakete** [comment]
Yeah, I understand that. thank you

**Comment by MediaMoots** [comment]
Oh ok cool, :)
Also, Ya better hide, Loids gonna get your for lewding his waifu, haha jk

**Comment by sleepymanakete** [comment]
forgive me for my sins 🥺
