### ISSUE TITLE
Face Linemask not in shader pack

### ISSUE THREAD

**Issue by poisenbery** [FlailingFog/KK-Blender-Porter-Pack#164]
Body Template has a slot for linemask texture, but face does not.
Faceline masks seem to be common on older characters
Please update Face Template to include a parser for LineMask textures.

**Comment by FlailingFog** [comment]
Sure, this is in https://github.com/FlailingFog/KK-Blender-Porter-Pack/pull/138

**Comment by poisenbery** [comment]
awesome possum. I'll check PR's before submitting issues in the future.
