### ISSUE TITLE
Missing source code for KKBP_Exporter.dll

### ISSUE THREAD

**Issue by poisenbery** [FlailingFog/KK-Blender-Porter-Pack#165]
Source Code for the plugin is nowhere to be found in this repository.

**Comment by MediaMoots** [comment]
Thanks for the suggestion, I think as long as I can maintain the plugin, I won't be releasing the source code, however, eventually I won't be able to maintain the plugin anymore, when that time comes, I will release the code.
I am very sorry for the inconvenience.

Also, I added support for KKS :)
It's in PR #138 
Enjoy!

**Comment by poisenbery** [comment]
> I am very sorry for the inconvenience.

No inconvenience. I've been working on it myself.
I had a feeling this would have been your response, so I'm just going to fork your repo and post the source code myself.

**Comment by poisenbery** [comment]
https://github.com/poisenbery/KK-Pmx-Export--Redux
