### ISSUE TITLE
Not an Issue , 3 Optional Options

### ISSUE THREAD

**Issue by LegionInstaller** [FlailingFog/KK-Blender-Porter-Pack#167]
1. Manual Hair Selection Editing as sometimes a bit of the Hair get's selected as Clothes and sometimes Clothes get selected as Hair so a little bug
2. Disable Normal Texture Export on Baking [Toggleable] as the baking proocedure already takes ages 
3. Select if you wan't to bake only Light or Dark or Both [also takes twice as long if both are getting baked]

Would love to see those changes in the next Update

**Comment by FlailingFog** [comment]
> * Disable Normal Texture Export on Baking [Toggleable] as the baking proocedure already takes ages
> * Select if you wan't to bake only Light or Dark or Both [also takes twice as long if both are getting baked]

That makes sense. It's easy to make them all toggleable (and I know how stupidly long it takes lol), so I'll add it in.

> 1. Manual Hair Selection Editing as sometimes a bit of the Hair get's selected as Clothes and sometimes Clothes get selected as Hair so a little bug

Do you have any examples of this? The hair selection in #138 should be selecting everything that uses the hair shader. If some of the hair is selected as clothes, then it isn't really hair, it's just being used as hair.

**Comment by LegionInstaller** [comment]
This is most likely the best example I hav
![Unbenannt](https://user-images.githubusercontent.com/49412050/172240312-69c61511-99d1-4ac9-a5e4-a5b243987282.PNG)
![Unbenannt1](https://user-images.githubusercontent.com/49412050/172240320-00433957-e293-4db2-9f44-b8ce99ad0785.PNG)
e

**Comment by LegionInstaller** [comment]
> 
![KK_220769](https://user-images.githubusercontent.com/49412050/172948549-069af1e0-2923-48c9-8ae7-a27968de5dc9.png)

**Comment by FlailingFog** [comment]
Thanks. I think I got it to a point where it won't be an annoyance. I don't exactly know what's wrong with the ears either, but it works if you change the material template to this:
![image](https://user-images.githubusercontent.com/65811931/173152861-0d71ca44-f948-490a-ac88-bec775a8188a.png)

I'll make the manual selection of hair available as well

**Comment by LegionInstaller** [comment]
Very Nice
