### ISSUE TITLE
"Sugestion" Fix the export and import scales to something sane, instead of upscalling to then downscale.

### ISSUE THREAD

**Issue by johnbbob-la-petite** [FlailingFog/KK-Blender-Porter-Pack#168]
Change the importer scale from .08 to 1 and the exporter scale from 12 to 1. Also the exporter scale should have been 12.5 not 12.
1/.08 = 12.5.
![exporter](https://user-images.githubusercontent.com/106894237/172030982-9956e816-a5c6-482d-8a18-0d2fa434a1b4.jpg)
![importer](https://user-images.githubusercontent.com/106894237/172030983-c5ab68f1-b24a-46cd-a576-04939b454a5f.jpg)

Fix this. It is irritating me.
Thank you.

**Comment by MediaMoots** [comment]
PR #138
