### ISSUE TITLE
Convert and apply colors to shaders error

### ISSUE THREAD

**Issue by yukist92** [FlailingFog/KK-Blender-Porter-Pack#172]
hi! thanks for all your work!! :D , i have a problem with the 2b option not loading the colors 
![image](https://user-images.githubusercontent.com/107106538/172572264-671c8e82-5604-4ea0-b299-a32dc74a8bf7.png)

**Comment by yukist92** [comment]
Python: Traceback (most recent call last):
  File "C:\Users\GIGABYTE\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\KK-Blender-Porter-Pack-master\importing\importcolors.py", line 727, in execute
    convert_main_textures(lut_light)
  File "C:\Users\GIGABYTE\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\KK-Blender-Porter-Pack-master\importing\importcolors.py", line 479, in convert_main_textures
    image_to_KK(image, lut_light)
  File "C:\Users\GIGABYTE\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\KK-Blender-Porter-Pack-master\importing\importcolors.py", line 90, in image_to_KK
    shader = gpu.types.GPUShader(vertex_default, current_code)
Exception: Shader Compile Error, see console for more details

location: <unknown location>:-1

**Comment by MediaMoots** [comment]
Please try it with PR #138 
It's probably fixed there

**Comment by yukist92** [comment]
nothing :C , maybe is the version of blender, i have 3.2.0, i'll try with 3.1

**Comment by yukist92** [comment]
tried in 3.1. the same error :c 
![image](https://user-images.githubusercontent.com/107106538/172851623-425956a1-53d5-4763-9970-688b6b1de53f.png)

**Comment by FlailingFog** [comment]
You need to update the blender plugin with the one linked above. The new one looks like this
![image](https://user-images.githubusercontent.com/65811931/172938300-45bc4574-1b4a-4d5e-97b4-6f61c12c1869.png)

**Comment by FoxNisha** [comment]
I have the same problem, I got the newest version, but where's the convert and apply colors button?

**Comment by yukist92** [comment]
> You need to update the blender plugin with the one linked above. The new one looks like this ![image](https://user-images.githubusercontent.com/65811931/172938300-45bc4574-1b4a-4d5e-97b4-6f61c12c1869.png)

mmm where is the new one?, i can only see ver. 5.1.1

**Comment by FlailingFog** [comment]
I mean the blender plugin and exporter that mediamoots linked.
[KK-Blender-Shader-Pack-422d8b9b76070523f5ac2bb8d2d2aeb157d8c3fa.zip](https://github.com/FlailingFog/KK-Blender-Porter-Pack/files/8944800/KK-Blender-Shader-Pack-422d8b9b76070523f5ac2bb8d2d2aeb157d8c3fa.zip)

**Comment by MediaMoots** [comment]
Make sure to have the latest plugins and use Blender 3.3 on Windows, that should work.
