### ISSUE TITLE
Nipple shape is not output correctly.

### ISSUE THREAD

**Issue by waomodder** [FlailingFog/KK-Blender-Porter-Pack#173]
*operating environment
koikatsu ver5.6.2.37.180
kkapi ver v1.33
blender v3.1
kkbp pluginupdate [40f63f1](https://github.com/FlailingFog/KK-Blender-Porter-Pack/pull/138/commits/40f63f1d8e5b0be7dfa72a823448cb1b16229994)

*Error Description
The nipple shape and breast shape of the output model does not match the character on the koikatsu side.
This phenomenon was observed with the default character as well as with a character of my own creation.
I think the problem is probably on the koikatu plugin side.
However, KKBP V5.1.1 outputs the data normally.

**Comment by MediaMoots** [comment]
In what way?

**Comment by waomodder** [comment]
![KKBP_bug_nip](https://user-images.githubusercontent.com/67697932/172814740-64d2dc4d-1a90-4944-bf3d-934e42f6f399.jpg)

As you can see from the images, the nipples are clearly different in color and size.
The right image is compared with blender and the left with koikatu.
This phenomenon also occurs with female characters.

**Comment by waomodder** [comment]
We have confirmed that the import was successful with the latest version.[442f6f3](https://github.com/FlailingFog/KK-Blender-Porter-Pack/pull/138/commits/442f6f3661888ca39efd3a625b08f16e3c4132cc)
Thanks for the fix.
