### ISSUE TITLE
Uv issue (?)

### ISSUE THREAD

**Issue by sleepymanakete** [FlailingFog/KK-Blender-Porter-Pack#174]
Trying out plugin update [03a9b44](https://github.com/FlailingFog/KK-Blender-Porter-Pack/pull/138/commits/03a9b4401e57842cf8c33d63c4ab176c2c6de1aa) and I think the UVs for the eyes got messed up so Marin has a bunch of pupils now. xD
![image](https://user-images.githubusercontent.com/30272172/172675408-44c19174-cf7f-400b-af05-fc66db361e83.png)

**Comment by MediaMoots** [comment]
Thats just Marin doing some extreme demon cosplay...

**Comment by FlailingFog** [comment]
I edited the blend file so it doesn't roll over like that anymore
