### ISSUE TITLE
IK Bone Issues

### ISSUE THREAD

**Issue by ZeeZulu** [FlailingFog/KK-Blender-Porter-Pack#177]
![Screenshot 2022-06-12 004956](https://user-images.githubusercontent.com/107337739/173215487-6f4b1acd-e94f-4790-883e-feeae400da4f.jpg)
so after following all the procces for some reason the ik for feet is all wonky or fucked, im assuming it's the shoes or any part of clothes for the  lower part is causing this problem but wondering if there's a fix of sort

here's the card https://www.pixiv.net/en/artworks/98236917
the card itself is too large for me to post it directly here so forgive me

**Comment by FlailingFog** [comment]
Sorry for the late response, but can you try this? https://github.com/FlailingFog/KK-Blender-Porter-Pack/issues/98
