### ISSUE TITLE
Pink body and face textures

### ISSUE THREAD

**Issue by lSeyL** [FlailingFog/KK-Blender-Porter-Pack#180]
Hey i am having a problem with the body and face, the character looks normal before baking but the baking makes pink body/face
![image](https://user-images.githubusercontent.com/78406471/173955811-1aaf8f01-8750-4be8-9e6b-cc05dbaf2a22.png)

**Comment by lSeyL** [comment]
I don't understand why, this is what it looks like when its exported from Koikatsu
![image](https://user-images.githubusercontent.com/78406471/173955901-3177a464-560c-4be9-8ab1-81ecdfbe566b.png)
and this is after the bake
![image](https://user-images.githubusercontent.com/78406471/173955955-4ec6edb7-4bd1-4abd-a658-8987e6946065.png)

**Comment by lSeyL** [comment]
![image](https://user-images.githubusercontent.com/78406471/173957876-c8d1dd94-709e-4975-9b86-35c7e79f3c0c.png)
I want it to look like this for the start at least

But in the render preview it looks like this
![image](https://user-images.githubusercontent.com/78406471/173957974-864b350d-2f6d-41f6-b619-aa21acbd07e2.png)

**Comment by poisenbery** [comment]
In the face/body shaders, turn the overlay strength of unused slots to 0.

Cycles renders everything as the same color if those overlay strengths are kept at their default values.
It's strange because it doesn't show up in tex view at all, or eevee, so it's very easy to miss.

**Comment by lSeyL** [comment]
Yes i did it, thank you!
