### ISSUE TITLE
Symmetrical Blush mapping

### ISSUE THREAD

**Issue by poisenbery** [FlailingFog/KK-Blender-Porter-Pack#181]
Problem: The current method of applying the blush can lead to situations where asymmetrical results are produced.
Example Image:
![Screenshot (674)](https://user-images.githubusercontent.com/78466408/174012464-bbc1b827-9695-4f09-aa26-a7a3a1270f5c.png)

My solution: Split the UV coordinates in half in the X direction and mirror it on the other side. All changes will now be perfectly symmetrical. 
Example Image: 
![Screenshot (676)](https://user-images.githubusercontent.com/78466408/174013019-86425415-774e-4313-9a60-96c4d5b72ad2.png)

Node Setup: 
![Screenshot (677)](https://user-images.githubusercontent.com/78466408/174013150-332a9237-4f65-4178-ba45-0444e0ca6ec9.png)

General explanation of math: 
Split XYZ
Y values remain unaltered.
X values are split in half by first using a compare node [functions as a mask], and then multiplying that result by the original X component.
It is mirrored with a multiply/add node [-1,1]
It then undergoes pretty much the same transforms from the original method.
I had to add a vector math node with Maximum set to [.5,0,0] because scaling was causing the other half of the texture to become visible, causing a double blush effect.

I have not yet figured out the correct math for rotation yet.
Nor have I figured out the correct math for preventing shifting during scaling.
I'm lazy.

Here is the node group. Input UV map

[ReBlush.zip](https://github.com/FlailingFog/KK-Blender-Porter-Pack/files/8917107/ReBlush.zip)

**Comment by MediaMoots** [comment]
Could you share the card please? It might be an issue with the Exporter and UVs

**Comment by poisenbery** [comment]
> It might be an issue with the Exporter and UVs

There is no "issue" as these perform exactly as expected.

The blush is overlayed onto the face, and the "Set SB3U blush position" node group allows you to scale/shift/rotate.

The problem I am describing is because of the math involved with positioning the face texture in that node group does not account for symmetry

https://user-images.githubusercontent.com/78466408/174144042-4f6f6257-d5ce-4417-bd7c-e334bf1ca2c0.mp4

As you can see, the entire mask is shifted.

But with my method, since the X coordinates are mirrored, you cannot get asymmetrical results.

https://user-images.githubusercontent.com/78466408/174145085-5460e626-64ca-4e41-a358-e669d71fde1a.mp4



The currently used method DOES place the blush exactly where it appears in game, but you can't really adjust or fine tune it in any way. There's no method in the game for adjusting blush either so I thought it would be nice if there was some way to make adjustments while preserving symmetry.

**Comment by FlailingFog** [comment]
This makes sense to do, I can add it as an alternate option if you're cool with me stealing another node group from you. It'll work for almost all of the blush textures, but a few textures are asymmetrical so I wouldn't want to use it as a default. 
Also, are you supposed to be able to shift the blush in the Y direction at all? That slider doesn't seem to work.

**Comment by poisenbery** [comment]
> if you're cool with me stealing another node group from you


I actually openly encourage this.

**Comment by FlailingFog** [comment]
I added your node group to the blush positioning group on the face material
