### ISSUE TITLE
Material are not imported correctly

### ISSUE THREAD

**Issue by yoshiiakihi** [FlailingFog/KK-Blender-Porter-Pack#182]
*operating environment
koikatsu ver5.1.00
kkapi ver v1.33
blender v2.93
KK-Blender-Porter-Pack-5.1.1

*Error Description
![维多利加 德·布洛瓦](https://user-images.githubusercontent.com/61128946/174445820-bd32ffd1-bc8f-449c-9e5d-34638ca05670.png)
after i Renamed the separated hair object in the outliner to "Hair"，when i Click the Import KK Shader and textures button. Choose the folder that contains the .pmx file，the blender warming the material are not imported correctly。Only a few materials are read, including the face and some limbs。
![image](https://user-images.githubusercontent.com/61128946/174446023-42c299e9-4e88-4880-9629-c23c5152e401.png)

*error log：
Python: Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\KK-Blender-Porter-Pack-master\importing\importeverything.py", line 803, in execute
    texture_error = get_and_load_textures(directory)
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\KK-Blender-Porter-Pack-master\importing\importeverything.py", line 447, in get_and_load_textures
    imageLoad('Template Tongue', 'Gentex', 'MainNorm', 'cf_m_tang_NormalMap.png', True)
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\KK-Blender-Porter-Pack-master\importing\importeverything.py", line 383, in imageLoad
    currentObj.material_slots[mat].material.node_tree.nodes[group].node_tree.nodes[node].image.colorspace_settings.name = 'Raw'
TypeError: bpy_struct: item.attr = val: enum "Raw" not found in ('Linear', 'sRGB')

location: <unknown location>:-1

====    KKBP Log    ====
Modifying armature...

Fixing shapekeys...
Fixing eyewhite shapekeys...
Combining shapekeys...

Separating body, clothes and shadowcast, then removing duplicate materials...
Warning:        Material wasn't found when separating body materials: cf_m_tooth.001
Warning:        Material wasn't found when separating body materials: cf_m_face_00.001
Warning:        Material wasn't found when separating body materials: cm_m_body
Warning:        Material wasn't found when separating body materials: Standard
Warning:        Material wasn't found when separating body materials: Bonelyfans
Warning:        Material wasn't found when separating body materials: Bonelyfans.001
Moving duplicate material cf_m_hair_b_04_00 -1101828 in slot 1 to the original slot 0
Moving duplicate material cf_m_hair_b_04_00 -1101828 in slot 2 to the original slot 0

Categorizing bones into armature layers...

Adding bone drivers...
Reparenting bones and setting up IKs...
Setting up joint bones...
Creating eye controller and renaming bones...

Applying material templates and textures...
Warning:        material or template wasn't found: cf_m_sirome_00 / Template Eyewhites (sirome)
Warning:        material or template wasn't found: cm_m_body / Template Body
Getting textures from: D:\Hgame\Koikatu\Export_PMX\20220618192051_维多利加德布洛瓦\
File not found, skipping: cm_m_body_DetailMask.png
File not found, skipping: cm_m_body_LineMask.png
File not found, skipping: cf_m_body_overtex2.png
File not found, skipping: cm_m_body_overtex1.png
File not found, skipping: cm_m_body_overtex1.png
File not found, skipping: cf_m_face_00_Texture5.png

The problem is me or the plug-in？Can you help me?please！

**Comment by FlailingFog** [comment]
Can you try https://github.com/FlailingFog/KK-Blender-Porter-Pack/pull/138 and Blender 3.2?

It seems to work on those.
![image](https://user-images.githubusercontent.com/65811931/174452775-fff6d265-21be-4d7c-93f5-6b218a92a55c.png)

**Comment by yoshiiakihi** [comment]
tanks，i will try 。

**Comment by yoshiiakihi** [comment]
*operating environment
koikatsu ver5.1.00
kkapi ver v1.33
**blender v3.2**
KK-Blender-Porter-Pack-5.1.1 
**KKBP_Exporter.zip  1e0f284** （The version you marked #138）
![QQ截图20220620223415](https://user-images.githubusercontent.com/61128946/174626723-5b2cc315-4371-4c99-bf57-8601ddbac16e.png)

well，i tried。the same female card ，and this time it still didn't succeed。The  Old problems have disappeared, but new problems have emerged。From Blender's pre rendered view, most of the clothes become transparent, and the body of the character becomes gray black on the background.

**blender erro log：**
Python: Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\KK-Blender-Porter-Pack-master\importing\importeverything.py", line 796, in execute
    template_error = get_templates_and_apply(directory, useFakeUser)
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\KK-Blender-Porter-Pack-master\importing\importeverything.py", line 150, in get_templates_and_apply
    shadowcast = bpy.data.objects['Shadowcast']
KeyError: 'bpy_prop_collection[key]: key "Shadowcast" not found'

**====    KKBP Log    ====**
Modifying armature...

Fixing shapekeys...
Fixing eyewhite shapekeys...
Combining shapekeys...

Separating body, clothes and shadowcast, then removing duplicate materials...
Warning:        Material wasn't found when separating body materials: cf_m_tooth.001
Warning:        Material wasn't found when separating body materials: cf_m_face_00.001
Warning:        Material wasn't found when separating body materials: cm_m_body
Warning:        Material wasn't found when separating body materials: c_m_shadowcast
Warning:        Material wasn't found when separating body materials: Standard
Warning:        Material wasn't found when separating body materials: Bonelyfans
Warning:        Material wasn't found when separating body materials: Bonelyfans.001
Moving duplicate material cf_m_hair_b_14_00 -1894808 in slot 2 to the original slot 1
Moving duplicate material cf_m_hair_b_14_00 -1894808 in slot 3 to the original slot 1
Moving duplicate material cf_m_namida_00 in slot 10 to the original slot 9
Moving duplicate material cf_m_namida_00 in slot 11 to the original slot 9

Categorizing bones into armature layers...

Adding bone drivers...
Reparenting bones and setting up IKs...
Setting up joint bones...
Creating eye controller and renaming bones...

Applying material templates and textures...
Warning:        material or template wasn't found: cf_m_sirome_00 / Template Eyewhites (sirome)
Warning:        material or template wasn't found: cm_m_body / Template Body

**Comment by FlailingFog** [comment]
That was from a while ago. Can you try the attached exporter **and** blender plugin?

[KK-Blender-Shader-Pack-422d8b9b76070523f5ac2bb8d2d2aeb157d8c3fa.zip](https://github.com/FlailingFog/KK-Blender-Porter-Pack/files/8944796/KK-Blender-Shader-Pack-422d8b9b76070523f5ac2bb8d2d2aeb157d8c3fa.zip)

**Comment by yoshiiakihi** [comment]
ps（The KKBP_Exporter.dll file  i am sure i selected Correct option，the file in net3.5 folder，because i ues it in Koikatsu）
