### ISSUE TITLE
How can we make characters with several outfits?

### ISSUE THREAD

**Issue by LuluViBritannia012** [FlailingFog/KK-Blender-Porter-Pack#183]
Hey there! First of all, thank you so much for this. Koikatsu has an excellent anime character editor, so it's great to be able to export our creations to do something else than... whatever this game offers.
Right now I'm using it to make VRChat avatars. It works great, but there's one feature I'd love to use in this game: the ability to swap clothes in real time. We can get several outfits with the latest versions, there are several Youtube tutorials explaining how. But in all those tutorials, they start with a model that has different meshes: one for the body, then one per outfit. Then they just toggle one mesh or the other to swap between them.

Right now, this plugin merges all the meshes together. As a result, since we can't separate the clothes from the body, we can't give our exported characters multiple clothes! It's even more sad when you realize Koikatsu does have several outfits per character, lol.

So, here is my request : **could you find a way for this plugin to work without merging the meshes together?**
If we could keep the outfits split from the body, we could then give it as secondary outfits somehow.
For now I'm looking for workarounds. I know we can make the character half-naked, but I'm not sure about how to properly merge it with clothes after that...

**Comment by MediaMoots** [comment]
👀

**Comment by MediaMoots** [comment]
![image](https://user-images.githubusercontent.com/81146974/174532608-6e85563c-9544-456a-a605-bd6dc00a573b.png)

Still WIP

**Comment by MediaMoots** [comment]
@LuluViBritannia012 
https://github.com/FlailingFog/KK-Blender-Porter-Pack/pull/138#issuecomment-1160076353

**Comment by LuluViBritannia012** [comment]
Well that was fast x). I see that you updated the Exporter so that it extracts several outfits. So now we only have to wait for the add-on to be updated? Or is it possible to download the Exporter alone somewhere?

Thank you very much for your work!

**Comment by MediaMoots** [comment]
> So now we only have to wait for the add-on to be updated?

Pretty much, but I'm having some issues with bones, so we shall see.

**Comment by LuluViBritannia012** [comment]
I should have mentioned I'm a lazy b*tch ^^'. I'm making a workflow that would allow me to mass-produce VRChat avatars with dynamic clothing. Your plugin is perfect for that, as it's just a few clicks to import-export from KK to Unity (without counting the time needed for fixes of course). But it could be _even more_ perfect! If we could import a character with multiple outfits (which you guys are working on, so I know it's coming) _and_ export the characters without merging the meshes, this tool would become even more convenient.

But I'll try by manually splitting the meshes, like you said. I've also figured out another way... maybe. I'll try it. If that works, the workflow would still be fairly simple.

**Comment by TheMaskedMan00** [comment]
Personally I do not like the new update as it is EXTREMELY slow for my puny little laptop, exporting something from kk with the old plugin takes under 1-2 mins, but with the new one there is no option to export only one outfit and it takes over 20 mins. And in blender pressing prep for export takes over an hour.

**Comment by TheMaskedMan00** [comment]
I guess that’s just a problem with my computer though, I wish there was a way to still export only one outfit

**Comment by FlailingFog** [comment]
> _and_ export the characters without merging the meshes

The meshes are now kept separate in the PR branch. As long as the object is not hidden in the outliner, it'll be baked. I haven't added a license to the project so technically you can do whatever you want

>And in blender pressing prep for export takes over an hour.

This is how it was supposed to work in the V5 plugin but I accidentally commented the line out. It seems like it slowed down, but it's really the same thing. You can choose the "No changes (FAST)" option in the PR branch plugin to get the same behaviour from V5
