### ISSUE TITLE
Missing eye expressions ?

### ISSUE THREAD

**Issue by johnvo0918** [FlailingFog/KK-Blender-Porter-Pack#189]
I can't help but notice that these eyes template(?) do not get exported but i love those.
![image](https://user-images.githubusercontent.com/69092770/175803412-fd6becac-b1ba-4dac-8b51-c8b02e44ccb4.png)
I think those would make easy expressions other than just changing the face shape. it's more anime like and sometimes more expressive to fit a certain emotion.

**Comment by nizhuan-jjr** [comment]
Yep, current version of KKBP ignores those expressions, some of which are not static expressions. I'd like to request this feature as well.
There's a shapekey(KK Eyes_gageye) that is supposed to work with those expressions, but currently the plugin doesn't output all the resource in need.

**Comment by FlailingFog** [comment]
The expression textures and meshes are now exported and available if you use the model in blender. Check the PR branch plugins

**Comment by johnvo0918** [comment]
> The expression textures and meshes are now exported and available as shapekeys if you use the model in blender. Check the PR branch plugins

thanks ! hopefully V6 will be available soon!
