### ISSUE TITLE
How can I adjust the Scale X of DetailMask or NormalMap from ME in the Blender?

### ISSUE THREAD

**Issue by nizhuan-jjr** [FlailingFog/KK-Blender-Porter-Pack#190]
![1](https://user-images.githubusercontent.com/3255986/176609576-dfa8962a-7435-463a-919d-d5f7c1aa2faf.png)
Is it possible to address this type of adjustment in the Shader Editor? I can't find a specific relevant option.
![2](https://user-images.githubusercontent.com/3255986/176610540-e5df0e09-8b49-4dcc-8aaf-6c925f957fa0.png)
Currently, the NormalMap and DetailMask have resulted a different look from the game. I believe it's the ScaleX value not being adjusted in Blender, because the noise/texture brought by DM and NM is much larger than the game.
How am I supposed to address ScaleX value changes in Blender?

**Comment by FlailingFog** [comment]
The plugin should be doing it automatically, but if it doesn't do it you can set the scale x and scale y in the right sidebar:
![image](https://user-images.githubusercontent.com/65811931/176783914-7dad188a-0378-4752-b4f2-38002fd5f827.png)

**Comment by nizhuan-jjr** [comment]
The texture looks much better now. Thank you.
