### ISSUE TITLE
Eye highlight colors should have an option to treat separately.

### ISSUE THREAD

**Issue by nizhuan-jjr** [FlailingFog/KK-Blender-Porter-Pack#192]
The game has separate color settings for upper eye highlight and the lower one, but the shader in blender doesn't seem to treat them separately. 
![3](https://user-images.githubusercontent.com/3255986/176988147-1b4e54d3-68cc-456f-bdc4-790e389c8173.png)
![1](https://user-images.githubusercontent.com/3255986/176988172-3387f4a2-772a-4781-b9f9-7e0f511f356b.png)
The issue I encountered is that the upper eye highlight has a different color and alpha value from the lower one. 
![2](https://user-images.githubusercontent.com/3255986/176988475-be49d4f6-c5c9-4f35-bef6-6fef23952832.png)
The current eye highlight color setting always controls two parts of highlight, so in my case, I get stuck.
It would be better to add an option to tweak each eye highlight color separately.
![5](https://user-images.githubusercontent.com/3255986/176989228-1c6c92db-40d5-496a-8018-f65ddef6b048.png)
By the way, these nodes don't look helpful in my case.

**Comment by FlailingFog** [comment]
Was this option added recently? I don't remember seeing this.

I added another color input for the bottom color
![image](https://user-images.githubusercontent.com/65811931/177009473-c62b9ed1-6fcc-4cd1-806b-e7ff11be8c51.png)

**Comment by nizhuan-jjr** [comment]
I was using KKBP v5.1.1 released on March 6th, and didn't see that option.
I've tested the lastest version just now(using the master zip), and it shows an error at the Finalize Pmx file step, so I guess it's not usable at this stage?
![6](https://user-images.githubusercontent.com/3255986/177018336-b79e5c9a-21d7-409b-b56e-7c2689fe7dd1.png)
I've also checked my working blend file with the master version of KKBP installed, and the eye highlight color option still remain unchanged.

**Comment by FlailingFog** [comment]
Try the zip file link on the release page for the V6 beta instead, it should be there.

**Comment by nizhuan-jjr** [comment]
I installed and enabled V6 beta, disabled the V5.1.1 one, rebooted Blender, yet my current blend file is still using the shader nodes from v5.1.1.
So, how can I upgrade the shader nodes if I want to retain all my progress made in my current project?

**Comment by poisenbery** [comment]
> I installed and enabled V6 beta, disabled the V5.1.1 one, rebooted Blender, yet my current blend file is still using the shader nodes from v5.1.1.

Changing that file will not do anything to blend files you have already saved. The KK Shader blend file is only used during the import process for the material templates.


> So, how can I upgrade the shader nodes if I want to retain all my progress made in my current project?


1.) Re-import the model and use these new materials for your old model
2.) Append the updated shader node group to your new file
