### ISSUE TITLE
Are these bones even in use ?

### ISSUE THREAD

**Issue by johnvo0918** [FlailingFog/KK-Blender-Porter-Pack#193]
I found that there are multiple duplicated bones that seems to not move anything or does anything. It's located under hips > spine > chest.001
I found that those are in the same naming convention as dontneedlol and its childrens.

plus on the last layer I found that many of those bones don't even move anything
![image](https://user-images.githubusercontent.com/69092770/177010916-62e3e59e-de68-4fc3-a211-a36642c67eb2.png)

How do i know which bones are actually not needed ? Will V6 automatically delete all the unneeded bones ?

**Comment by FlailingFog** [comment]
Some duplicated bones might show up if the model uses accessories that have extra bones with names like "spine" or "chest", causing blender to add the .001 tag to them.

And everything on that armature layer can be merged together with the "To parents" button in CATS to remove the extra bones.
![image](https://user-images.githubusercontent.com/65811931/177017604-f7e75774-62c6-41b8-8db3-708a5b4f9ad1.png)
The plugin is supposed to do that automatically, but I accidentally commented the line out in the 5.1.1 release.

**Comment by johnvo0918** [comment]
thanks for the reply ! hopefully it's fixed in v6!

**Comment by Crimson-foxGITHUB** [comment]
@FlailingFog What line was commented out, and where?

**Comment by FlailingFog** [comment]
Line 82 in selectbones.py
https://github.com/FlailingFog/KK-Blender-Porter-Pack/commit/97cb44769c697cadf535b54738a90df19cc92a55
