### ISSUE TITLE
Having Trouble with Hair Nodes

### ISSUE THREAD

**Issue by Sei-eki** [FlailingFog/KK-Blender-Porter-Pack#195]
Hi, I saw someone else had posted the same issues regarding the card creator using invisible hair which makes the model look like it was imported wrong, but my issue is which node/value I need to change in order to fix the hair? I've tried messing with most of them however no luck.

![Screenshot (35)](https://user-images.githubusercontent.com/46458284/177213552-02b3b572-108b-4fa0-b83d-986f4a294adc.png)

**Comment by FlailingFog** [comment]
The hair alpha mask and maintex in that green group should be attached like this. The V6 beta already has this fix if you don't want to add those in yourself
![image](https://user-images.githubusercontent.com/65811931/178125010-b73b19e4-be09-4d3c-98ac-98cba59e6771.png)
