### ISSUE TITLE
Generates wrong atlas and destroys original textures

### ISSUE THREAD

**Issue by guoodddd** [FlailingFog/KK-Blender-Porter-Pack#197]
Hi, after I have graded the material, I click the save atlas button. Then the correct atlas was not generated, and the generated png file only had black and white images, and then the original texture of the model was lost and turned into a white model.
like this.
https://github.com/guoodddd/question/blob/main/no.png
https://github.com/guoodddd/question/blob/main/mater.png
This is the generated atlas
https://github.com/guoodddd/question/blob/main/Atlas_45991.png

**Comment by guoodddd** [comment]
This is caused by my operation problem. After baking, the fifth button of kkbp should be used to reconnect to the baked image, otherwise the texture combination component will not be able to find the corresponding texture file.

**Comment by g0g5** [comment]
I believe I've done the right operations including 5th operation but still got the same result....

**Comment by guoodddd** [comment]
I solved this a few weeks ago, but forgot to mention it on github. The main reason is that the material fusion plugin cannot find the corresponding map texture. The solution is to use cat to bake the baked texture and relink it to the model, so that the correct atlas can be generated.

**Comment by guoodddd** [comment]
> I believe I've done the right operations including 5th operation but still got the same result.... So, what exact version of Blender, CATS and KKBP are you using now?

After baking it with kkbp, remember to use kkbp's button to reapply the baked image to the model, and then you can use cat to generate the correct atlas.
