### ISSUE TITLE
the hair is an accessory,How to recognize baldness?

### ISSUE THREAD

**Issue by NioN80** [FlailingFog/KK-Blender-Porter-Pack#201]
koikatsu ver: RX13
kkapi ver v1.33
blender v3.0
KKBP: 5.1.1(master) 

In Koikatsu, the character's hair is made of accessories. 
But if you import it with a blender, you have to recognize it as bald, but it's recognized as hair.
So if I designate the shoes as hair and put on a shader or texture, it's the same color as the koikatsu.

**In conclusion, is there a way to designate hair as an accessory in KKBP or to recognize a character as bald without hair in KKBP?**

The image below is a character model of Koikatsu.
![image](https://user-images.githubusercontent.com/89737013/178124375-eebf9f32-6870-49e6-aac9-4bb22e8d2830.png)

The first image is when I separate it with your hair
![image](https://user-images.githubusercontent.com/89737013/178124451-28e3c22b-09cd-4418-ac08-fc1aca3ecc20.png)
The second image is when the shoes are separated by hair.
![image](https://user-images.githubusercontent.com/89737013/178124422-4718375d-4eb4-44ec-87f5-035a688e0434.png)

**Comment by poisenbery** [comment]
Can you share the card please? I'm curious about this.

**Comment by MediaMoots** [comment]
This might be fixed in the latest master, if not, could you share the card please?
