### ISSUE TITLE
Any idea why this happens?

### ISSUE THREAD

**Issue by LuluViBritannia012** [FlailingFog/KK-Blender-Porter-Pack#202]
![Capture](https://user-images.githubusercontent.com/107808037/178143452-3f0da722-c0f9-4e77-b76e-9e43e7f287b6.PNG)

So, I'm using the beta, v6.0. It worked fine, until I updated Koikatsu to Better Repack R14. I made a total cleanup of Blender: erased CATS and KKBP, deleted the Extrator, then downloaded those plugins and reinstalled them all.
But it didn't solve the issue. No matter what model I use, whenever I click "Bake materials", this happens. The model becomes invisible or weird-looking, the "fillerplane" stays, and the materials extracted look like cursed images, lol.

Are you guys able to go all the way with the beta? Or are you stuck at this step, which explains this bug? My theory is it's due to compatibility with R14, since that happened basically when I updated the game... but I can't be sure.

I'm using Blender 3.2. For now I think I'll take the old 2.93 with ver. 5.0, but I'm sad, this version 6.0 is awesome T_T. (Also, if the problem is indeed because of my game version, maybe reverting to the old version won't help...

**Comment by FlailingFog** [comment]
I haven't updated the baking features to support multiple outfits yet, so that's most likely what's going on

**Comment by LuluViBritannia012** [comment]
But it does this even with a single mesh, T_T. It's also not what was happening at first. I did tweak a few lines of code here and there, but I had managed to get a model in Unity.
Have you managed to export a model with this version, in any way? Or can you confirm that exporting is simply not possible for now with 6.0?

**Comment by FlailingFog** [comment]
I checked it works on the latest HF patch, which is probably similar to what the repack has. It also bakes and applies for me, but some things related to the UVs still need adjustments. The CATS button gives me an error when I try to export it, but I don't think its KKBP's fault.
