### ISSUE TITLE
Face Linemask not properly parsed

### ISSUE THREAD

**Issue by poisenbery** [FlailingFog/KK-Blender-Porter-Pack#203]
Face Linemask in the shader pack is set to combine the Red and Green channel, when it should be Red and Blue channels.
From game:
![Screenshot (758)](https://user-images.githubusercontent.com/78466408/178898381-bd2329b7-d92f-4495-8856-decb219cf25c.png)

How it "should" look in blender
![Screenshot (757)](https://user-images.githubusercontent.com/78466408/178898421-9c4185c0-fa87-43b8-8bcd-5effa42b0c94.png)

How it currently looks in blender
![Screenshot (756)](https://user-images.githubusercontent.com/78466408/178898457-04c7c3b0-1e3d-4c28-92a5-4d27c1282a21.png)

Lipstick overlay needs to have color blend mode changed to...something else to properly work. I noticed that it uses the mask as an alpha to overlay onto the face. I changed it to "multiply" and had better results, but I'm not really an expert at this stuff.

**Comment by poisenbery** [comment]
@FlailingFog any reason this hasn't been fixed yet?

It's just 1 node.

**Comment by FlailingFog** [comment]
I was going to instead learn how [this skin shader](https://github.com/xukmi/KKShadersPlus/blob/main/Shaders/Skin/KKPSkinFrag.cginc) does it (because it seems to use all three linemask channels) and copy whatever the shader does into the blend file, but I never became motivated to look through it. I made your red/blue channel change to the shader.

**Comment by FlailingFog** [comment]
I was originally going to replicate what [this skin shader](https://github.com/xukmi/KKShadersPlus/blob/main/Shaders/Skin/KKPSkinFrag.cginc) does because it seems to use all three channels, but I lost motivation to read through it. I made your red/blue channel change to the shader.

**Comment by poisenbery** [comment]
Thanks.



> I lost motivation

I'll try looking into it once I finish some of the other things I'm working on. Seems like a fun challenge
