### ISSUE TITLE
3 Major Import Issues

### ISSUE THREAD

**Issue by LegionInstaller** [FlailingFog/KK-Blender-Porter-Pack#204]
![Unbenannt](https://user-images.githubusercontent.com/49412050/179316528-c1e65dfc-fed9-4456-a096-5915ee13fb3f.PNG)
![Unbenannt2](https://user-images.githubusercontent.com/49412050/179316532-22eba66e-663f-4c71-8f2c-52ee7b7b33c1.PNG)
![Unbenannt3](https://user-images.githubusercontent.com/49412050/179316533-87cc0d28-e444-4b55-ab58-42e18dff38cf.PNG)
![Unbenannt4](https://user-images.githubusercontent.com/49412050/179316536-608e648d-dc87-49ab-be87-cc53129724a8.PNG)

I have literally no clue what is happening when Importing nor do I know where the clothes went , the eybrows shift somehow and the pupils get scaled down

card:https://drive.google.com/file/d/1TqmqcLtyaPEosUuUEEK_Ib_XpmH_XYiZ/view?usp=sharing

This card is actually from the Sunshine Version of the Game but I took my time to Copy every Value

From the Sunshine Exporter side and KK Exporter the card looks the same

**Comment by FlailingFog** [comment]
Nice find. You can change the defaults to get something similar:
* unhide the Top alt objects parented to the Outfit 00 object (these were incorrectly separated, I will fix this eventually)
* unhide and move the GFN empty down a bit
* set KK Eyes_default_cl shapekey to 0.28
* Turn off overlay intensities on the face material
* Lower blush intensity on face material
* Turn off "ignore colormask" and "use colored maintex" on the clothes objects
* Set eye's highlight up color to black
![image](https://user-images.githubusercontent.com/65811931/179322314-28f82822-00c8-447e-a9ca-dbad73d7f5d4.png)

**Comment by LegionInstaller** [comment]
Nice , what does the GFN empty do ?

**Comment by FlailingFog** [comment]
It's for cleaner face normals: https://github.com/FlailingFog/KK-Blender-Porter-Pack/pull/138#issuecomment-1182591527

**Comment by LegionInstaller** [comment]
All of my Issues have been Resolved
Thanks
