### ISSUE TITLE
Doesn't export all clothes from KKS

### ISSUE THREAD

**Issue by kdru** [FlailingFog/KK-Blender-Porter-Pack#206]
Doesn't export all clothes from KKS (Top half)
card link: https://crepe.moe/aQcH35nv

**Comment by MediaMoots** [comment]
Which version of KKBP Exporter?

**Comment by kdru** [comment]
beta 6.0, isn't it the only one which can export from KKS?

**Comment by MediaMoots** [comment]
Oh, Beta 6.0 is a little bit outdated now, but the newest version may not be stable yet, please try [96649d5](https://github.com/FlailingFog/KK-Blender-Porter-Pack/pull/138/commits/96649d5088de5a2ed4d2fc8c2dac48eca1b37c70) V3.76 and import it with CATS to double check if the top meshes are there.

**Comment by kdru** [comment]
Amazing! It worked! All meshes exported! Thank you so much for such quick response! <3
