### ISSUE TITLE
Possible undesired behavior of maintex and overlays??

### ISSUE THREAD

**Issue by poisenbery** [FlailingFog/KK-Blender-Porter-Pack#207]
When you have any type of overlay/underlay on the skin [blush, moles, images, etc] they are added on top of the maintex for face and body.

Here is the main face texture with no overlays:
![_Export_2022-07-15-00-25-03_cf_m_face_00_MainTex](https://user-images.githubusercontent.com/78466408/179896664-61ec1f51-bb47-4541-b366-bf079fd36570.png)

Here are some examples when over/underlays were present in game:
![_Export_2022-07-13-19-42-13_cf_m_face_00_MainTex](https://user-images.githubusercontent.com/78466408/179896765-3039b105-6313-46d7-95da-08c99c3893dc.png)
![_Export_2022-06-12-19-20-08_cf_m_face_00_MainTex](https://user-images.githubusercontent.com/78466408/179896776-191fe646-d410-402c-87df-c442d357087a.png)
![daisy (1)](https://user-images.githubusercontent.com/78466408/179896790-6f202aea-c433-4d4d-92be-1c8b38ec1bb1.png)
![_Export_2022-07-14-23-05-30_cf_m_face_00_MainTex](https://user-images.githubusercontent.com/78466408/179896801-feac7195-0bf5-465d-bcf4-a7bef80a59f7.png)

As you can see, things like the lip line and blush are applied to the maintex during export. This is basically asking to get neck seams.

I only bring it up because the shader pack has options for the overlays to be edited in blender. The only way you'd be able to really use those options are if the maintex was to be disabled.

It does the same thing with the body maintex as well. 

No Over/underlays:
![_Export_2022-07-15-00-24-28_cf_m_body_MainTex](https://user-images.githubusercontent.com/78466408/179897243-63b47fd3-43b8-40f0-b224-af1bc695d3e7.png)

With Over/under lay
![daisy (2)](https://user-images.githubusercontent.com/78466408/179897244-3072f49e-950c-4c57-bb9a-0de8a13d4dfc.png)

**Comment by MediaMoots** [comment]
If some outfits don't use the overlays, you can get the texture from there (The plugin exports skin textures for each outfit), but if the overlay has been set on every outfit, then for now, there's no way to remove them during the export.

**Comment by poisenbery** [comment]
Yeah I figured as much. Material editor also spits out the same textures.
