### ISSUE TITLE
Collection of cards [Dunne] import with eyes off-centered

### ISSUE THREAD

**Issue by poisenbery** [FlailingFog/KK-Blender-Porter-Pack#209]
All cards from the same author seem to have the same problem. Can be fixed by manually changing mapping on each character, but that's not fun. 

![Screenshot (777)](https://user-images.githubusercontent.com/78466408/180115292-f68626eb-3660-4a3d-bd0b-a0af26898bf8.png)
![Screenshot (778)](https://user-images.githubusercontent.com/78466408/180115294-a9fd7fbb-13d3-467e-8c67-2d9c169deeda.png)
![Screenshot (783)](https://user-images.githubusercontent.com/78466408/180115295-564a1607-ae07-4e45-bea9-3a9288fcdfa1.png)
![Screenshot (784)](https://user-images.githubusercontent.com/78466408/180115296-9f82263e-4621-497d-8c0a-2f243c50a4da.png)
![Screenshot (785)](https://user-images.githubusercontent.com/78466408/180115297-1b247a2d-8712-4b88-a281-3c781cbcaf66.png)
![Screenshot (786)](https://user-images.githubusercontent.com/78466408/180115299-330802be-2042-4fdc-81bd-0e2618458cb8.png)
![Screenshot (787)](https://user-images.githubusercontent.com/78466408/180115300-bc947178-ea54-48e2-b6d8-24ea457142a4.png)
![Screenshot (788)](https://user-images.githubusercontent.com/78466408/180115301-d2eab615-68f6-4a4a-8c0a-5095d730e202.png)

Some cards:
![KK_235846](https://user-images.githubusercontent.com/78466408/180115476-42b7217d-4a70-4724-b0a9-d5069a68c169.png)

![KK_237355](https://user-images.githubusercontent.com/78466408/180115527-e7e68ba2-49cd-4278-b2d3-beec11e9e48d.png)

For some reason, #139 doesn't seem to fix it =/

**Comment by poisenbery** [comment]
![Screenshot (792)](https://user-images.githubusercontent.com/78466408/180134020-94e67fb2-0d5f-4618-af35-71c5b59bd93e.png)
If I separate both eyes into individial materials, I can then apply the numbers from the game to the eye, and it seems to work.

**Comment by MediaMoots** [comment]
Makes sense, in KK the eyes have separate materials.

**Comment by TheMaskedMan00** [comment]
This is just something you have to manually do as getting these values from the game is a lot easier to do manually then it is to do with a mod. I’ve tried making a mod to print out all the material values to a text doc but it seems to either round the numbers or just not work at all
