### ISSUE TITLE
After baking and apply the baked templates, still unable to atlas materials.

### ISSUE THREAD

**Issue by g0g5** [FlailingFog/KK-Blender-Porter-Pack#210]
The card:
 https://drive.google.com/file/d/1mnIwN2tCI-B5kQnr2QVZunz6cx4Y6nnC/view?usp=sharing
The process of how it went wrong:
After baking and apply the baked templates, I go CATS->Optimization->Atlas, generate material list and perform atlas.
It results into destroy the original materials and either there's no atlas png generated or it generated the wrong material, the same situation as #197

**Comment by FlailingFog** [comment]
This card works for me using the plugin in the PR branch
