### ISSUE TITLE
Import Error with latest stuff

### ISSUE THREAD

**Issue by ZombieKillerGaming** [FlailingFog/KK-Blender-Porter-Pack#211]
I get an import error every time I click on the import pmx option. It happens when I finish selecting the pmx and pressing go. I have 3.2.1 for blender, the latest version of the exporter and the latest beta version in the pull requests tab. And yes this happens with every character. Please let me know if its because of KK Sunshine or no
![Screenshot (694)](https://user-images.githubusercontent.com/106704341/180595196-d81e0cfe-7c2a-49fb-85a8-abb5e66dcca5.png)

**Comment by ghost573** [comment]
Mind copying the error and pasting it here? It might be related to my error #208.

**Comment by ZombieKillerGaming** [comment]
I dunno how

**Comment by poisenbery** [comment]
> I dunno how


![Screenshot (817)](https://user-images.githubusercontent.com/78466408/180666025-c2c614c9-cab4-466b-9a64-165ce7eaa107.png)
![Screenshot (818)](https://user-images.githubusercontent.com/78466408/180666028-3ef2e197-ec57-4204-9c47-a9a0f938cb18.png)

**Comment by a1374186265** [comment]
same question,and all i got is just a bald naked body

**Comment by TheMaskedMan00** [comment]
You need to wait for ALL the outfits to export, them you go to the character folder with all the outfit folders and import the main one

**Comment by someMinecrafter** [comment]
> You need to wait for ALL the outfits to export, them you go to the character folder with all the outfit folders and import the main one

I thought it was an issue with the newest issue not exporting them due to some flags?

**Comment by ZombieKillerGaming** [comment]
I’m pretty sure I exported all the outfits, it wouldn’t open the directory
otherwise

**Comment by BDCG-2** [comment]
I'm running into the same issue.
Up-to-date steam version of Koikatsu Party
HF 3.17
Blender 3.0.1
KKBP 5.0 or 6beta

I obtain this after importing the .pmx with cats then using the finalize button on the KKBP panel
![B1](https://user-images.githubusercontent.com/111394836/184992421-6693610c-8bec-4332-a163-9cd2be417f64.png)

My money would be on the export malfunctionating, but I can't be sure.

**Comment by Crimson-foxGITHUB** [comment]
Yeah, this is absolutely a broken exporter with the beta. I got the exact same results on KK Party.

**Comment by MediaMoots** [comment]
Could you try the latest V6?

Thanks!

**Comment by BDCG-2** [comment]
> Could you try the latest V6?
> 
> Thanks!

I can confirm that it works for me with the V6 now.
I had to upgrade whatever version I had of blender (I think it was 3.0) to 3.3 though, the importer wouldn't work with the previous one.
