### ISSUE TITLE
Discord?

### ISSUE THREAD

**Issue by TheMaskedMan00** [FlailingFog/KK-Blender-Porter-Pack#214]
Hello, I’ve submitted issues in the past, but I have a number of small issues and questions that would take far too long to ask on here, and I was wondering if either of you had a discord where we can talk. As it would be a lot more convenient for me.

**Comment by FlailingFog** [comment]
I personally think it's easier to track issues on github, and don't use my discord account very much...

**Comment by poisenbery** [comment]
Once a discord server reaches a certain size, it needs moderation and protection from scam bots.

I'm pretty sure this plugin is being worked on by only 2 people.
There's no way that they have the time to set up and run a functional discord server AND work on this project at the same time.
