### ISSUE TITLE
Source code for the actual plugin?

### ISSUE THREAD

**Issue by TheMaskedMan00** [FlailingFog/KK-Blender-Porter-Pack#216]
Can we have the source code for the actual plugin, I wanna see if I can make my own changes.

suggestions also: make it optional to export all outfits, I wanna export only once cause I’m on a laptop.
Add ability to switch between the old baking and the new baking, the new baking takes way longer on my laptop.

re add compatibility for GME, I managed to get in contact with grey and he sent me the source code, so I started tinkering with it and eventually I might be able to get it working and maybe even get it working in kks.

**Comment by poisenbery** [comment]
https://github.com/FlailingFog/KK-Blender-Porter-Pack/issues/165#issuecomment-1146645433
