### ISSUE TITLE
Cards that have no rigged skirt make the blender plugin cause errors. 

### ISSUE THREAD

**Issue by TheMaskedMan00** [FlailingFog/KK-Blender-Porter-Pack#217]
I looked into the errors and it seems that bonedrivers.py will look for the skirt bones so it can add them to a separate armature layer, but if there are no skirt bones then it will just throw an error. I think the cause is these lines  
[https://github.com/FlailingFog/KK-Blender-Porter-Pack/blob/master/importing/bonedrivers.py#L679-L684](https://github.com/FlailingFog/KK-Blender-Porter-Pack/blob/master/importing/bonedrivers.py#L679-L684)

**Comment by FlailingFog** [comment]
I don't think it's used in anything else, so I'll add a try catch around those lines
