### ISSUE TITLE
Import button without AUTO Shaders for v6.0

### ISSUE THREAD

**Issue by im-pain** [FlailingFog/KK-Blender-Porter-Pack#221]
hi, i recently tried the new v6.0 update of the addon in blender and the way it works now with KKS is awesome but, in comparison with the v5 version it now do all process automatically,i mean:
**import the model
correct the bones
separate the body objects
and apply the shaders**
Im asking if there is a way to get separated step process, so for example i just can import the model and set all other stuff but not apply the shaders directly, so i can play with the model without using the shaders, i ask for this because i use a workflow where first i need to import the character for do some stuff without materials and later i apply the shader with also some modifications, i know i can delete the node connections on the material and leave it vanilla but i lost the way to get them back if i do that, thx for your time guys :), **incredible addon btw**

**Comment by LegionInstaller** [comment]
> hi, i recently tried the new v6.0 update of the addon in blender and the way it works now with KKS is awesome but, in comparison with the v5 version it now do all process automatically,i mean: **import the model correct the bones separate the body objects and apply the shaders** Im asking if there is a way to get separated step process, so for example i just can import the model and set all other stuff but not apply the shaders directly, so i can play with the model without using the shaders, i ask for this because i use a workflow where first i need to import the character for do some stuff without materials and later i apply the shader with also some modifications, i know i can delete the node connections on the material and leave it vanilla but i lost the way to get them back if i do that, thx for your time guys :), **incredible addon btw**

Set it to Pause to Categorize

**Comment by FlailingFog** [comment]
Yes, if you set it to pause the plugin won't apply the materials until you press the "Finish categorization" button
![image](https://user-images.githubusercontent.com/65811931/185660221-4ac6ded1-7d29-4928-821b-6f9e452bf814.png)

**Comment by im-pain** [comment]
thx for the reply, i was testing the options and sometimes they gave me some errors in 3.3(i think because isnt built for that version) but they worked correctly at the end, thx for the replies. ill close the issue
