### ISSUE TITLE
Can't Import Exported Models into Blender

### ISSUE THREAD

**Issue by MythicSylvia** [FlailingFog/KK-Blender-Porter-Pack#222]
Please include the card that causes the issue!
It can really help with the debug process.
![Koikatu_F_20220813131605542_Sylvia Argyle_Sylvia](https://user-images.githubusercontent.com/110353639/185489843-99b544ca-31ee-4fce-951c-fb928bd2f469.png)
I tried with a default model too, they don't import correctly in blender
![grafik](https://user-images.githubusercontent.com/110353639/185489909-78399aea-bbac-434a-bace-de8cb96b58bc.png)
Here is the Error Log attached. I tried both the 6.0 Beta and the newest Stable release, none can Import models correctly
I'm using Koikatsu Party

**Comment by johnvo0918** [comment]
it looks like you're using blender 3.2. I'm p sure that this plugin only works with 2.9 and under right now

**Comment by FlailingFog** [comment]
This is importing for me on blender 3.2.1 with the V6 beta
![image](https://user-images.githubusercontent.com/65811931/185805460-f99c8040-cb3d-4e8a-9524-ea2d77b018b7.png)

**Comment by MythicalSylvia** [comment]
How. i think something is wrong with my game then and something in the pmx builder phase is wrong. lemme send console of when trying to export to pmx from the game

**Comment by MythicalSylvia** [comment]
> it looks like you're using blender 3.2. I'm p sure that this plugin only works with 2.9 and under right now

I used the V6 Beta so it shouldn't have been the blender version

**Comment by MythicalSylvia** [comment]
[output_log.txt](https://github.com/FlailingFog/KK-Blender-Porter-Pack/files/9389752/output_log.txt)
here is my log after exporting

**Comment by MythicalSylvia** [comment]
what no why did it close

**Comment by MythicalSylvia** [comment]
[20220821203544_SylviaArgyle.zip](https://github.com/FlailingFog/KK-Blender-Porter-Pack/files/9389757/20220821203544_SylviaArgyle.zip)
Here is what it exported. maybe it'll help
it's always me taht gets these stupid issues no one else ever has '^^

**Comment by MythicalSylvia** [comment]
Okay i tried another version of koikatsu (yay, another 30GB). I got one step closer now! It still doesnt export correctly. is there a discord or anything for this? maybe others can help me too. or is github issues only way.

**Comment by MythicalSylvia** [comment]
Is there a discord or anything for this or is Github Issues only way?
Using a different version with BetterRepack and HF Patch got me further from the looks of it but its still whatever that is
![grafik](https://user-images.githubusercontent.com/110353639/185814662-93d50168-4536-4738-919e-8cbd4e9b0c3c.png)

**Comment by MythicalSylvia** [comment]
![Quiet 2](https://user-images.githubusercontent.com/110353639/185814685-d69d3102-b834-49d4-9f6d-57e7a6788d39.png)
Above Image was made with this card.

**Comment by MythicalSylvia** [comment]
Okay! i got further. much further. There are some minor things that are wrong. For example The Ears don't have their texture and the choker/collar doesnt
![grafik](https://user-images.githubusercontent.com/110353639/185817064-370d4781-726b-48d0-b4aa-6e0940cbc36d.png)
![grafik](https://user-images.githubusercontent.com/110353639/185817067-e2aff1c4-7ece-4ca4-ba5a-4156c15a4b69.png)


Okay so here are the things i found out:
My old version of Koikatsu was bugging the plugin. i got the BetterRepack now.
Using an already open and used Blender Project and not a new one where the plugin hasn't been used before causes some python errors i guess.
Other than that i don't think i did anything wrong. i'm just dumb

**Comment by MediaMoots** [comment]
Could you try the latest V6?

Thanks!
