### ISSUE TITLE
Hair texture missing after step 2b

### ISSUE THREAD

**Issue by Mici247** [FlailingFog/KK-Blender-Porter-Pack#223]
Using BetterRepack RX15
Blender: 3.0 (also tried: 2.91, 2.93.4 and 3.2.2)
Cats: 0.19.0
KKBP: 5.1.1 (also tried: 5.0.0 and 5.0.1)

Card with (hopefully) everything included:
https://mega.nz/file/9EpBzRJb#SUtaS7wKxYtby6QXc02k17-HxF2tx6CnE9JpFj8sjVY

Hair texture missing after step '2b)'.
No errors and everything else seems to be fine.
Am I doing something wrong? Please help me.
(Might be related to #201 ?)

![20220819-001](https://user-images.githubusercontent.com/56317021/185692912-31bf8ac8-8e20-485c-bba7-43c2480d24f8.png)
.

**Comment by MediaMoots** [comment]
Could you try the latest V6?

If that does not work, try using pause to categorize and make a copy of the hair and name it "Hair Outfit XX" (the XX being your outfit number)

After that select Finish Categorization, then you can delete the copy of the hair model.

Thanks!
