### ISSUE TITLE
Textures cant be loaded

### ISSUE THREAD

**Issue by Honochan2** [FlailingFog/KK-Blender-Porter-Pack#224]
### Loading CATS...
mmd_tools_local registed 131 classes
### Loaded CATS successfully!

ValueError: the return value must be None
File "C:\Users\Orihi\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\cats-blender-plugin-0-19-0\tools\settings.py", line 249, in update_settings
Checking for Cats update...
No update found.
====    KKBP Log    ====
Info: Imported MMD model from "C:\Users\Orihi\Downloads\[ScrewThisNoise]+Koikatsu+Sunshine+EX+BetterRepack+R6\Export_PMX\20220820082808_YaeSakura\model.pmx"
   - removed 774 faces
Info: Imported MMD model from "C:\Users\Orihi\Downloads\[ScrewThisNoise]+Koikatsu+Sunshine+EX+BetterRepack+R6\Export_PMX\20220820082808_YaeSakura\Outfit 01\model.pmx"

Finalizing PMX file...
Modifying armature...
Finished in 2.59s

Separating body, clothes, hair, hitboxes and shadowcast, then removing duplicate materials...
Moving duplicate material Bonelyfans in slot 20 to the original slot 1
Info: Removed 1 slots
Moving duplicate material cm_m_glove_shortyubinuki 3661 in slot 2 to the original slot 1
Moving duplicate material cf_m_hair_b_21 5431 in slot 7 to the original slot 6
Moving duplicate material cf_m_hair_b_21 5431 in slot 8 to the original slot 6
Moving duplicate material cf_m_hair_b_21 5431 in slot 9 to the original slot 6
Moving duplicate material cf_m_hair_b_21 5861 in slot 11 to the original slot 10
Moving duplicate material cf_m_hair_b_21 5861 in slot 12 to the original slot 10
Moving duplicate material cf_m_hair_b_21 5861 in slot 13 to the original slot 10
Moving duplicate material cf_m_hair_f_06_00 6231 in slot 15 to the original slot 14
Moving duplicate material cf_m_hair_f_06_00 6231 in slot 16 to the original slot 14
Moving duplicate material cf_m_hair_f_06_00 6231 in slot 17 to the original slot 14
Moving duplicate material cf_m_hair_f_06_00 6231 in slot 18 to the original slot 14
Moving duplicate material cf_m_hair_b_aurora_al_00 8521 in slot 28 to the original slot 27
Moving duplicate material cf_m_hair_b_aurora_al_00 8521 in slot 29 to the original slot 27
Moving duplicate material cf_m_hair_b_aurora_al_00 8521 in slot 30 to the original slot 27
Moving duplicate material Hero_Scarlet_Cos19GloryLeague_Body01_D(RGB) 13041 in slot 36 to the original slot 35
Moving duplicate material Hero_Scarlet_Cos19GloryLeague_Body01_D(RGB) 13041 in slot 37 to the original slot 35
Moving duplicate material Hero_Scarlet_Cos19GloryLeague_Body01_D(RGB) 13041 in slot 38 to the original slot 35
Moving duplicate material Hero_Scarlet_Cos19GloryLeague_Body01_D(RGB) 13041 in slot 39 to the original slot 35
Moving duplicate material aya_body 13511 in slot 50 to the original slot 49
Moving duplicate material acs_hairtie_02 5121 in slot 54 to the original slot 53
Moving duplicate material acs_hairtie_02 6041 in slot 58 to the original slot 57
Info: Removed 21 slots
Warning:        Material wasn't found when separating body materials: c_m_shadowcast
Warning:        Material wasn't found when separating body materials: Standard
Error: Nothing selected
Warning:        Material wasn't found when separating body materials: Bonelyfans.001
Info: Bonelyfans moved to Shadowcast Collection
Info: Objects moved to Hitbox Collection
Info: Removed 1463 vertice(s)
Info: Removed 42 slots
Finished in 4.39s

Categorizing bones into armature layers...
Finished in 4.18s

Adding bone drivers...
Reparenting bones and setting up IKs...
Warning: 1 x Draw window and swap: 40.8512 ms, average: 40.85120000 ms
Warning: 1 x Draw window and swap: 36.0036 ms, average: 36.00359999 ms
Setting up joint bones...
Warning: 1 x Draw window and swap: 38.9310 ms, average: 38.93100002 ms
Creating eye controller and renaming bones...
Warning: 1 x Draw window and swap: 36.9446 ms, average: 36.94460000 ms
Finished in 7.67s

Applying material templates and textures...
Warning:        material or template wasn't found: cm_m_body / KK Body
Warning:        material or template wasn't found: cf_m_tooth.001 / KK Fangs (tooth.001)
Warning: 1 x Draw window and swap: 728.7539 ms, average: 728.75389998 ms
Getting textures from: \Downloads\[ScrewThisNoise]+Koikatsu+Sunshine+EX+BetterRepack+R6\Export_PMX\20220820082808_YaeSakura\

Error:          Unknown python error occurred
Traceback (most recent call last):
  File "C:\Users\Orihi\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\KK-Blender-Shader-Pack-pluginupdate\importing\importeverything.py", line 1163, in execute
    texture_error = get_and_load_textures(directory)
  File "C:\Users\Orihi\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\KK-Blender-Shader-Pack-pluginupdate\importing\importeverything.py", line 436, in get_and_load_textures
    bpy.data.images[image.name].pack()
KeyError: 'bpy_prop_collection[key]: key "Hero_Scarlet_Cos19GloryLeague_Body02_Effect(Color) 13041_MT_CT.png" not found'
Error: Traceback (most recent call last):
  File "C:\Users\Orihi\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\KK-Blender-Shader-Pack-pluginupdate\importing\importeverything.py", line 1163, in execute
    texture_error = get_and_load_textures(directory)
  File "C:\Users\Orihi\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\KK-Blender-Shader-Pack-pluginupdate\importing\importeverything.py", line 436, in get_and_load_textures
    bpy.data.images[image.name].pack()
KeyError: 'bpy_prop_collection[key]: key "Hero_Scarlet_Cos19GloryLeague_Body02_Effect(Color) 13041_MT_CT.png" not found'
Python: Traceback (most recent call last):
  File "C:\Users\Orihi\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\KK-Blender-Shader-Pack-pluginupdate\importing\importbuttons.py", line 120, in execute
    bpy.ops.kkb.importeverything('INVOKE_DEFAULT'),
  File "C:\Program Files\Blender Foundation\Blender 3.1\3.1\scripts\modules\bpy\ops.py", line 130, in __call__
    ret = _op_call(self.idname_py(), C_dict, kw, C_exec, C_undo)
RuntimeError: Error: Traceback (most recent call last):
  File "C:\Users\Orihi\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\KK-Blender-Shader-Pack-pluginupdate\importing\importeverything.py", line 1163, in execute
    texture_error = get_and_load_textures(directory)
  File "C:\Users\Orihi\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\KK-Blender-Shader-Pack-pluginupdate\importing\importeverything.py", line 436, in get_and_load_textures
    bpy.data.images[image.name].pack()
KeyError: 'bpy_prop_collection[key]: key "Hero_Scarlet_Cos19GloryLeague_Body02_Effect(Color) 13041_MT_CT.png" not found'

location: <unknown location>:-1
GPUTexture: Blender Texture Not Loaded!

how do i fix this ?

**Comment by MediaMoots** [comment]
Could you try the latest V6?

Thanks!
