### ISSUE TITLE
Version 5.11 cant load Detailmask Textures 

### ISSUE THREAD

**Issue by Honochan2** [FlailingFog/KK-Blender-Porter-Pack#225]
<a href="https://gyazo.com/64dbb4baff8f626cbd7f8ec35b01ae62"><img src="https://i.gyazo.com/64dbb4baff8f626cbd7f8ec35b01ae62.png" alt="Image from Gyazo" width="252"/></a> 

Version 5.11 cant load Detailmask Textures 

Read prefs: C:\Users\Orihi\AppData\Roaming\Blender Foundation\Blender\3.0\config\userpref.blend
Loading Material Combiner..
Registered 18 Material Combiner classes.

### Loading CATS...
mmd_tools_local registed 131 classes
### Loaded CATS successfully!

ValueError: the return value must be None
File "C:\Users\Orihi\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\cats-blender-plugin-0-19-0\tools\settings.py", line 249, in update_settings
Checking for Cats update...
No update found.
   - removed 774 faces
Info: Imported MMD model from "C:\Users\Orihi\Downloads\[ScrewThisNoise]+Koikatsu+BetterRepack+RX15\Export_PMX\20220822090426_Scarlet\model.pmx"
Added:  Model_arm
====    KKBP Log    ====
Modifying armature...

Fixing shapekeys...
Warning: 1 x Draw window and swap: 28.0497 ms, average: 28.04970001 ms
Fixing eyewhite shapekeys...
Warning: 1 x Draw window and swap: 44.7054 ms, average: 44.70540000 ms
Combining shapekeys...
Warning: 1 x Draw window and swap: 28.2089 ms, average: 28.20890000 ms
Warning: 1 x Draw window and swap: 26.6013 ms, average: 26.60129999 ms
Warning: 1 x Draw window and swap: 6.5445 ms, average: 6.54450001 ms
Warning: 1 x Draw window and swap: 9.8144 ms, average: 9.81440001 ms
Warning: 1 x Draw window and swap: 16.5769 ms, average: 16.57690000 ms
Warning: 1 x Draw window and swap: 16.3617 ms, average: 16.36169999 ms
Warning: 1 x Draw window and swap: 17.4147 ms, average: 17.41469999 ms
Warning: 1 x Draw window and swap: 31.2139 ms, average: 31.21390000 ms
Warning: 1 x Draw window and swap: 24.4834 ms, average: 24.48340000 ms
Warning: 1 x Draw window and swap: 9.2947 ms, average: 9.29469999 ms
Warning: 1 x Draw window and swap: 14.8722 ms, average: 14.87220000 ms
Warning: 1 x Draw window and swap: 16.7542 ms, average: 16.75420001 ms
Warning: 1 x Draw window and swap: 16.5965 ms, average: 16.59649999 ms
Warning: 1 x Draw window and swap: 15.9519 ms, average: 15.95190000 ms
Warning: 1 x Draw window and swap: 16.7263 ms, average: 16.72630000 ms
Warning: 1 x Draw window and swap: 16.1535 ms, average: 16.15350001 ms
Warning: 1 x Draw window and swap: 16.5090 ms, average: 16.50899999 ms
Warning: 1 x Draw window and swap: 16.7584 ms, average: 16.75840000 ms
Warning: 1 x Draw window and swap: 15.9022 ms, average: 15.90220000 ms
Warning: 1 x Draw window and swap: 16.7731 ms, average: 16.77310000 ms
Warning: 1 x Draw window and swap: 15.9658 ms, average: 15.96579999 ms
Warning: 1 x Draw window and swap: 16.8587 ms, average: 16.85869999 ms
Warning: 1 x Draw window and swap: 16.5315 ms, average: 16.53150000 ms
Warning: 1 x Draw window and swap: 27.5947 ms, average: 27.59470000 ms
Warning: 1 x Draw window and swap: 28.8470 ms, average: 28.84700001 ms
Warning: 1 x Draw window and swap: 28.1706 ms, average: 28.17060000 ms
Warning: 1 x Draw window and swap: 26.0034 ms, average: 26.00339999 ms
Warning: 1 x Draw window and swap: 8.6786 ms, average: 8.67859999 ms
Warning: 1 x Draw window and swap: 6.8376 ms, average: 6.83760000 ms
Warning: 1 x Draw window and swap: 8.7785 ms, average: 8.77849999 ms
Warning: 1 x Draw window and swap: 16.7138 ms, average: 16.71380000 ms
Warning: 1 x Draw window and swap: 16.1852 ms, average: 16.18520000 ms
Warning: 1 x Draw window and swap: 16.7792 ms, average: 16.77920000 ms
Warning: 1 x Draw window and swap: 16.4871 ms, average: 16.48710000 ms
Warning: 1 x Draw window and swap: 15.6171 ms, average: 15.61710000 ms
Warning: 1 x Draw window and swap: 16.5533 ms, average: 16.55330000 ms
Warning: 1 x Draw window and swap: 16.1659 ms, average: 16.16590000 ms
Warning: 1 x Draw window and swap: 16.4208 ms, average: 16.42079999 ms
Warning: 1 x Draw window and swap: 16.3693 ms, average: 16.36930001 ms
Warning: 1 x Draw window and swap: 16.2301 ms, average: 16.23009999 ms
Warning: 1 x Draw window and swap: 16.7803 ms, average: 16.78030001 ms
Warning: 1 x Draw window and swap: 15.7883 ms, average: 15.78830001 ms
Warning: 1 x Draw window and swap: 16.7734 ms, average: 16.77340000 ms
Warning: 1 x Draw window and swap: 16.4417 ms, average: 16.44170001 ms

Separating body, clothes and shadowcast, then removing duplicate materials...
Warning: 1 x Draw window and swap: 26.5734 ms, average: 26.57340000 ms
Warning:        Material wasn't found when separating body materials: cf_m_tooth.001
Warning:        Material wasn't found when separating body materials: cf_m_face_00.001
Warning:        Material wasn't found when separating body materials: cm_m_body
Warning:        Material wasn't found when separating body materials: Standard
Info: Removed 154 slots
Info: Objects moved to Shadowcast Collection
Info: Removed 1464 vertice(s)
Moving duplicate material Hero_Scarlet_Cos19GloryLeague_Body01_D(RGB) -48830 in slot 25 to the original slot 24
Moving duplicate material Hero_Scarlet_Cos19GloryLeague_Body01_D(RGB) -48830 in slot 26 to the original slot 24
Moving duplicate material Hero_Scarlet_Cos19GloryLeague_Body01_D(RGB) -48830 in slot 27 to the original slot 24
Moving duplicate material Hero_Scarlet_Cos19GloryLeague_Body01_D(RGB) -48830 in slot 28 to the original slot 24
Moving duplicate material Hero_Scarlet_Cos19GloryLeague_Body01_D(RGB) -49162 in slot 31 to the original slot 30
Moving duplicate material Hero_Scarlet_Cos19GloryLeague_Body01_D(RGB) -49365 in slot 33 to the original slot 32
Info: Removed 6 slots

Categorizing bones into armature layers...
Warning: 1 x Draw window and swap: 29.7526 ms, average: 29.75260001 ms

Adding bone drivers...
Warning: 1 x Draw window and swap: 27.4173 ms, average: 27.41730001 ms
Reparenting bones and setting up IKs...
Warning: 1 x Draw window and swap: 29.2984 ms, average: 29.29840000 ms
Warning: 1 x Draw window and swap: 23.3856 ms, average: 23.38560000 ms
Setting up joint bones...
Warning: 1 x Draw window and swap: 23.6040 ms, average: 23.60400000 ms
Creating eye controller and renaming bones...
Warning: 1 x Draw window and swap: 23.4132 ms, average: 23.41320000 ms

Applying material templates and textures...
Info: Removed 30 slots
Warning:        material or template wasn't found: cf_m_sirome_00 / Template Eyewhites (sirome)
Warning:        material or template wasn't found: cm_m_body / Template Body
Warning: 1 x Draw window and swap: 282.8232 ms, average: 282.82320000 ms
Getting textures from: C:\Users\Orihi\Downloads\[ScrewThisNoise]+Koikatsu+BetterRepack+RX15\Export_PMX\20220822090426_Scarlet\
Python: Traceback (most recent call last):
  File "C:\Users\Orihi\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\KK-Blender-Porter-Pack-master\importing\importeverything.py", line 803, in execute
    texture_error = get_and_load_textures(directory)
  File "C:\Users\Orihi\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\KK-Blender-Porter-Pack-master\importing\importeverything.py", line 367, in get_and_load_textures
    bpy.data.images[image.name].pack()
KeyError: 'bpy_prop_collection[key]: key "Hero_Scarlet_Cos19GloryLeague_Body01_D(RGB) -488300_DetailMask.png" not found'

location: <unknown location>:-1
Python: Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.0\3.0\scripts\modules\bpy_types.py", line 798, in draw_ls
    def draw_ls(self, context):
KeyboardInterrupt

location: <unknown location>:-1

Koikatsu export console :================================================

BoneWeight[] PmxBuilder.ConvertBoneWeight(BoneWeight, Transform[])
[Info   :   Console] System.NullReferenceException: Object reference not set to an instance of an object

BoneWeight[] PmxBuilder.ConvertBoneWeight(BoneWeight, Transform[])
[Info   :   Console] System.NullReferenceException: Object reference not set to an instance of an object

BoneWeight[] PmxBuilder.ConvertBoneWeight(BoneWeight, Transform[])
[Info   :   Console] System.NullReferenceException: Object reference not set to an instance of an object

BoneWeight[] PmxBuilder.ConvertBoneWeight(BoneWeight, Transform[])
[Info   :   Console] System.NullReferenceException: Object reference not set to an instance of an object

BoneWeight[] PmxBuilder.ConvertBoneWeight(BoneWeight, Transform[])
[Info   :   Console] System.NullReferenceException: Object reference not set to an instance of an object

BoneWeight[] PmxBuilder.ConvertBoneWeight(BoneWeight, Transform[])
[Info   :   Console] System.NullReferenceException: Object reference not set to an instance of an object

BoneWeight[] PmxBuilder.ConvertBoneWeight(BoneWeight, Transform[])
[Info   :   Console] System.NullReferenceException: Object reference not set to an instance of an object

BoneWeight[] PmxBuilder.ConvertBoneWeight(BoneWeight, Transform[])
[Info   :   Console] System.NullReferenceException: Object reference not set to an instance of an object

BoneWeight[] PmxBuilder.ConvertBoneWeight(BoneWeight, Transform[])
[Info   :   Console] System.NullReferenceException: Object reference not set to an instance of an object

BoneWeight[] PmxBuilder.ConvertBoneWeight(BoneWeight, Transform[])

**Comment by MediaMoots** [comment]
Could you try the latest V6?

Thanks!
