### ISSUE TITLE
Exception: Shader Compile Error, see console for more details

### ISSUE THREAD

**Issue by woldfswift** [FlailingFog/KK-Blender-Porter-Pack#228]
KK-blender-Porter-pack version：5.11，blender version：3.2.2
when use 2b ,the terminal say ：
```
ERROR (gpu.shader): pyGPUShader FragShader:
      |
  112 |         gl_FragColor = vec4(newColor.rgb, texRGBA.a);
      |
      | Error: C7616: global variable gl_FragColor is removed after version 420

Traceback (most recent call last):
  File "C:\Users\username\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\KK-Blender-Porter-Pack-master\importing\importcolors.py", line 727, in execute
    convert_main_textures(lut_light)
  File "C:\Users\username\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\KK-Blender-Porter-Pack-master\importing\importcolors.py", line 479, in convert_main_textures
    image_to_KK(image, lut_light)
  File "C:\Users\username\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\KK-Blender-Porter-Pack-master\importing\importcolors.py", line 90, in image_to_KK
    shader = gpu.types.GPUShader(vertex_default, current_code)
Exception: Shader Compile Error, see console for more details
```
what should i do?

**Comment by widarr** [comment]
I'm getting the same error.
* HF Patch: v3.17
* KK-Blender-Porter-Pack: 5.1.1
* CATS Plugin: 0.19.0
OS: latest Arch Linux
Blender: 17:3.2.2-1

Reproduction: Just import the standard Chika Haruno model without any changes with the KKBP_Exporter plugin

Error message from the python console:

`====    KKBP Log    ====
Modifying armature...

Fixing shapekeys...
Fixing eyewhite shapekeys...
Combining shapekeys...

Separating body, clothes and shadowcast, then removing duplicate materials...
Warning:        Material wasn't found when separating body materials: cf_m_tooth.001
Warning:        Material wasn't found when separating body materials: cf_m_face_00.001
Warning:        Material wasn't found when separating body materials: cm_m_body
Warning:        Material wasn't found when separating body materials: Standard

Categorizing bones into armature layers...

Adding bone drivers...
Reparenting bones and setting up IKs...
Setting up joint bones...
Creating eye controller and renaming bones...

Applying material templates and textures...
Warning:        material or template wasn't found: cf_m_sirome_00 / Template Eyewhites (sirome)
Warning:        material or template wasn't found: cm_m_body / Template Body
Getting textures from: /mnt/veracrypt2/spiele/steam/steamapps/common/Koikatsu Party/Export_PMX/20220828144534_HarunoChika/
File not found, skipping: cm_m_body_DetailMask.png
File not found, skipping: cm_m_body_LineMask.png
File not found, skipping: cm_m_body_overtex1.png
File not found, skipping: cm_m_body_overtex1.png
File not found, skipping: cf_m_face_00_Texture5.png
File not found, skipping: cf_m_hair_f_14_00_i -35620_MainTex_CT.png
File not found, skipping: cf_m_hair_f_14_00_i -35620_AlphaMask.png
File not found, skipping: cf_m_hair_b_08_00 -35538_MainTex_CT.png
File not found, skipping: cf_m_hair_b_08_00 -35538_AlphaMask.png
File not found, skipping: cf_m_bot_skirt01 -46832_AlphaMask.png
File not found, skipping: cf_m_bot_skirt01 -46832_PatternMask2.png
File not found, skipping: cf_m_bot_skirt01 -46832_PatternMask3.png
File not found, skipping: cf_m_shorts_01 -53650_AlphaMask.png
File not found, skipping: cf_m_shorts_01 -53650_PatternMask1.png
File not found, skipping: cf_m_shorts_01 -53650_PatternMask2.png
File not found, skipping: cf_m_shorts_01 -53650_PatternMask3.png
File not found, skipping: cf_m_socks_high01 -55932_AlphaMask.png
File not found, skipping: cf_m_socks_high01 -55932_PatternMask1.png
File not found, skipping: cf_m_socks_high01 -55932_PatternMask2.png
File not found, skipping: cf_m_socks_high01 -55932_PatternMask3.png
File not found, skipping: cf_m_shoes_roafer01 -60428_AlphaMask.png
File not found, skipping: cf_m_shoes_roafer01 -60428_PatternMask1.png
File not found, skipping: cf_m_shoes_roafer01 -60428_PatternMask2.png
File not found, skipping: cf_m_shoes_roafer01 -60428_PatternMask3.png
File not found, skipping: cf_m_top_inner01 -343862_PatternMask1.png
File not found, skipping: cf_m_top_inner01 -343862_PatternMask2.png
File not found, skipping: cf_m_top_inner01 -343862_PatternMask3.png
File not found, skipping: cf_m_emblem -346062_MainTex.png
File not found, skipping: cf_m_emblem -346062_MainTex.png
File not found, skipping: cf_m_emblem -346062_ColorMask.png
File not found, skipping: cf_m_emblem -346062_DetailMask.png
File not found, skipping: cf_m_emblem -346062_NormalMap.png
File not found, skipping: cf_m_emblem -346062_AlphaMask.png
File not found, skipping: cf_m_emblem -346062_PatternMask1.png
File not found, skipping: cf_m_emblem -346062_PatternMask2.png
File not found, skipping: cf_m_emblem -346062_PatternMask3.png
File not found, skipping: cf_m_top_jacket06 -346062_AlphaMask.png
File not found, skipping: cf_m_top_jacket06 -346062_PatternMask1.png
File not found, skipping: cf_m_top_jacket06 -346062_PatternMask2.png
File not found, skipping: cf_m_top_jacket06 -346062_PatternMask3.png
File not found, skipping: cf_m_top_deco01 -348256_AlphaMask.png
File not found, skipping: cf_m_top_deco01 -348256_PatternMask1.png
File not found, skipping: cf_m_top_deco01 -348256_PatternMask2.png
File not found, skipping: cf_m_top_deco01 -348256_PatternMask3.png
File not found, skipping: cf_m_bra_01 -350516_PatternMask1.png
File not found, skipping: cf_m_bra_01 -350516_PatternMask2.png
File not found, skipping: cf_m_bra_01 -350516_PatternMask3.png
cf_m_hair_f_14_00_i -35620 had no alphamask or maintex
cf_m_hair_b_08_00 -35538 had no alphamask or maintex
Adding bone widgets...`

The error message:

`Python: Traceback (most recent call last):
  File "/home/vidar/.config/blender/3.2/scripts/addons/KK-Blender-Porter-Pack-master/importing/importcolors.py", line 727, in execute
    convert_main_textures(lut_light)
  File "/home/vidar/.config/blender/3.2/scripts/addons/KK-Blender-Porter-Pack-master/importing/importcolors.py", line 479, in convert_main_textures
    image_to_KK(image, lut_light)
  File "/home/vidar/.config/blender/3.2/scripts/addons/KK-Blender-Porter-Pack-master/importing/importcolors.py", line 90, in image_to_KK
    shader = gpu.types.GPUShader(vertex_default, current_code)
Exception: Shader Compile Error, see console for more details
`

**Comment by MediaMoots** [comment]
Try using blender 3.1 or 3.0, they work better for now.

**Comment by widarr** [comment]
Ok Thank You that worked. 
I used Blender 3.0.0, acquired from here: https://download.blender.org/release/Blender3.0/
