### ISSUE TITLE
studio item error

### ISSUE THREAD

**Issue by johnbbob-la-petite** [FlailingFog/KK-Blender-Porter-Pack#233]
![errpr](https://user-images.githubusercontent.com/106894237/187110133-b05b68f9-20ff-4293-a2ea-2486bf3260b9.jpg)

changing line 118 in importstudio.py to0o:
`
`base_name, filetype, dupe_number = node.image.name.rsplit('.',2)`
`
basically, just dump anything extra into base_name
should fix it.
and probably break something else. 

fbx if you would like to test.
[Horse.zip](https://github.com/FlailingFog/KK-Blender-Porter-Pack/files/9441117/Horse.zip)

**Comment by FlailingFog** [comment]
Thanks! I wound up using rpartition instead.
