### ISSUE TITLE
Convert to Cycles

### ISSUE THREAD

**Issue by poisenbery** [FlailingFog/KK-Blender-Porter-Pack#234]
Simple script that I use to prep models for cycles.
This is irreversible so proceed with caution.

So far, all this does is remove the outline modifier and deletes the kage faces and eyelinedown mesh [what do those even do btw???].

```
import bpy


#remove outline modifier
for o in bpy.context.view_layer.objects:
    for m in o.modifiers:
        if(m.name == "Outline Modifier"):
            o.modifiers.remove(m)
            

####fix the eyelash mesh overlap

# deselect everything and make body active object
active = bpy.context.view_layer.objects.active
for o in bpy.data.objects:
    if o.name == "Body":
        active = o
    else:
        o.select_set(0)
# define some stuff
ops = bpy.ops
obj = ops.object
mesh = ops.mesh
context = bpy.context
object = context.object
# edit mode and deselect everything
obj.mode_set(mode='EDIT')
mesh.select_all(action='DESELECT')
# delete eyeline down verts and kage faces
object.active_material_index = 6
obj.material_slot_select()
mesh.delete(type='VERT')
object.active_material_index = 5
obj.material_slot_select()
mesh.delete(type='ONLY_FACE')
mesh.select_all(action='DESELECT')

```

One more problem you might notice is that the eyebrows cast a shadow on the face. This can be fixed by using a light path node's "Is Shadow Ray" as the factor into a mix shader, with the 2nd shader being a transparency shader. This effectively causes the eyebrow mesh to cast an invisible shadow.
![Screenshot (7)](https://user-images.githubusercontent.com/78466408/187321795-aa9291d7-c0ff-49e2-a272-873afeb774a9.png)
![Screenshot (8)](https://user-images.githubusercontent.com/78466408/187321796-89da5b8a-7948-4332-99fe-d2b438ac2769.png)

I can possibly upload some pretty simple cycles materials, but it seems that the configuration of everything is largely subjective, since most of the toon shading techniques do not apply to PBR setups. [overlaying everything and slapping it on is not the correct approach for PBR Skin].

ONE OTHER PROBLEM That you may have is if you try to apply noise bump mapping to the skin. You'll notice that it is not correctly applied to the chest area. This is largely due to the fact that the game's normal maps seem to contain 0 height information at the nipples. This can be fixed by baking your own tangent space normal map, the old fashioned way, and use the Unity Tech Demo node group to combine it with your other normals [also courtesy of me lol]. [literally the only solution I could think of].

**Comment by poisenbery** [comment]
WIP

Subsurface mapping, can be applied to any character [correct me if im wrong]
![Screenshot (764)](https://user-images.githubusercontent.com/78466408/187322861-28e982e2-66f9-4988-b30b-945391db5d9b.png)

Subsurface happens to be the reason adding everything together and shoving it into a Principled BSDF ends up looking drastically worse than the toon shader
![Screenshot (661)](https://user-images.githubusercontent.com/78466408/187322955-2ee238f1-2737-4ecb-9547-4da97cb2db0d.png)

Sampleface.exe
![Screenshot (6)](https://user-images.githubusercontent.com/78466408/187322995-3befebba-f9bb-4896-b55a-c488c1b9f48c.png)


You can get pretty good results with the game textures [to my surprise actually].

**Comment by SP-Size** [comment]
Hey, quick question!

![grafik](https://user-images.githubusercontent.com/112580158/194623838-338e406f-2c5d-4e97-a931-8af5982e2012.png)

What specifically did you do to get her abs and muscle definition to look like that? Like, is that just the "skin type" or a normal map input as the displacement? 

Because I can't manage to get my koikatsu models' bodies to look as muscular as that with just the game assets and the KKBP

**Comment by poisenbery** [comment]
> What specifically did you do to get her abs and muscle definition to look like that? Like, is that just the "skin type" or a normal map input as the displacement?

It has to do with the body line mask. There's 2 normal maps: regular normal and Normal Map Detail [NMD from hereon]. The NMD is based on the line mask you choose for the body, so you don't have a line mask, you will not get muscle definition like this.


For SPECIFICS: https://blog.selfshadow.com/publications/blending-in-detail/

I sort of use a custom shader setup for this. I haven't posted it here yet because it's very WIP and makes irreversible changes to the groups.
![Screenshot (964)](https://user-images.githubusercontent.com/78466408/194688083-7d069a5a-e54f-425e-bdf9-688a0ba3c4f9.png)

The "PB Normals" group is literally the "Unity Tech Demo" from the post.

**Comment by poisenbery** [comment]
I have decided to upload the shader groups I have and the script to make it all work.
How to use: you can either replace the KK Shader V6.0.blend in the addon location, or drop this file in the directory of the character you are importing.

This does a few things, mainly based on personal preference. One of the MAJOR changes between this and the regular shader setup is how it handles eyes. It basically swaps around the role of hitomi shader and sirome shader. 
It also adds a new vertex group in order to handle the way eyes move/blink. The vertex group is called "Blink Eyes" and ensures that the new eye setup doesn't get squashed during blinking.

Most of the maps for the body and face are not connected to anything. They're so low resolution and have seam issues, so IMO they're unusable for this. Baking your own textures is a soft requirement because it will look like garbage if you only use the vanilla textures. 


How to use: You can either replace the KK shader blend file in the addon directory, or you can drop this file into the folder of the PMX you are trying to import. Once the character is successfully imported, SELECT THE BODY OBJECT and then run the "Convert Cycles.py" script


This basically sets everything up to be "Cycles ready" but this BY NO MEANS will make the characters suddenly photorealistic. You have to do the shading and textures yourself for that.
[KK Shader V6.0.blend.zip](https://github.com/FlailingFog/KK-Blender-Porter-Pack/files/9782713/KK.Shader.V6.0.blend.zip)

**Comment by poisenbery** [comment]
Random Walk subsurface scattering method causes darkening around lips.
I need to update the node group so that the skin uses Christensen-Burley.

This introduces a new issue where the transparent shadows from the nose, brows, and eyeline brighten the face under those areas. I have to update the script to separate those parts into separate objects, and then drive the shape keys from the face values.


I do not recommend using this currently.

**Comment by poisenbery** [comment]
@FlailingFog Random walk SSS cannot be used on these models. Mouth topology causes darkening that cannot be easily fixed. Suggest changing BSDF to "Christensen-Burley" method, and having separate Cycles groups for [very least] the face and the body, so that SSS can be used without affecting all objects. Here's no SSS compared to a small amount of Random Walk SSS. The mouth is darkened.
![Screenshot (993)](https://user-images.githubusercontent.com/78466408/197206076-188429c2-a148-4725-9138-9406567877da.png)
![Screenshot (992)](https://user-images.githubusercontent.com/78466408/197206085-eaef7e99-f364-4e44-8250-a8995cbf8ddb.png)


Also, for the cycles groups to work, the nose, eyeline, and eyebrows need to be separated into their own objects. The transparent shadows cause issues with Christensen-Burley SSS, but ONLY if it's part of the same mesh. When the Nose, Eyeline, and Eyebrows are separated into their own object, the issue goes away.
![Screenshot (994)](https://user-images.githubusercontent.com/78466408/197206726-50e77810-4cae-431c-bc9f-2f58c7870e89.png)
![Screenshot (995)](https://user-images.githubusercontent.com/78466408/197206730-1b1b8fa2-0a4f-47f5-ad12-ea9a04b22415.png)


That makes it all fine and dandy, but now the shape keys from the new, separated mesh have to be driven from the body mesh. At the very least, the eyeline shape keys need to be linked to each other so that you don't end up with stuff like this: 
![Screenshot (996)](https://user-images.githubusercontent.com/78466408/197207870-5e23bd84-624f-44f4-a220-de149f87e030.png)

**Comment by poisenbery** [comment]
[Documents.zip](https://github.com/FlailingFog/KK-Blender-Porter-Pack/files/9932772/Documents.zip)
Ok here are updated scripts:

Convert Cycles.py will make the necessary changes to prevent zbuffer issues with overlapping faces.

KK Shapekey Drivers.py REQUIRES EASYBPY by curtis holt [i was having problems setting up drivers with regular BPY]: https://github.com/curtisjamesholt/EasyBPY

This will create drivers for the nose/eyeline/eyebrow shapekeys, so that they are synced with the face.

I still have to update the shader nodes

**Comment by poisenbery** [comment]
I regret to announce that I have ceased all work on this project.

If anyone interested in pursuing this themselves and needs any help, I can be reached on discord poisenbery#1492

**Comment by LetterN** [comment]
modified `Convert Cycles.py` for 6.0 blend (from the "[latest](https://github.com/FlailingFog/KK-Blender-Porter-Pack/commit/657b29264254fc4e2dae6fb475325d66ab727bca)" commit)
```py
import bpy

# remove outline modifier
for o in bpy.data.objects:
    for m in o.modifiers:
        if(m.name == "Outline Modifier"):
            o.modifiers.remove(m)

# deselect everything and make body active object
active = bpy.context.view_layer.objects.active

for o in bpy.data.objects:
    if o.name == "Body":
        active = o
    else:
        o.select_set(False)

# define some stuff
ops = bpy.ops
obj = ops.object
mesh = ops.mesh
context = bpy.context
object = context.object

# edit mode and deselect everything
obj.mode_set(mode='EDIT')
mesh.select_all(action='DESELECT')

# delete eyeline down verts and kage faces 
object.active_material_index = 7 # old 6
obj.material_slot_select()
mesh.delete(type='VERT')
object.active_material_index = 12 # old 5 
obj.material_slot_select()
mesh.delete(type='ONLY_FACE')
mesh.select_all(action='DESELECT')

# select brows and eyeline and separate
#old values: 1 2 4
# eyeR
object.active_material_index = 2
obj.material_slot_select()
# eyeL
object.active_material_index = 3
obj.material_slot_select()
# KK Eyebrows (mayuge)
object.active_material_index = 5
obj.material_slot_select()

mesh.separate(type='SELECTED')
```
