### ISSUE TITLE
Colored maintex not properly saturated in Blender when saved

### ISSUE THREAD

**Issue by gitburned** [FlailingFog/KK-Blender-Porter-Pack#237]
Using KKBP 5.1.1 and Blender 3.0.0, I noticed when I import KK shaders then try to apply colors to the model, if I set ignore colormask, save project, then return to it, all the colors from the colored maintextures are muted, which is weird because when I first set the colors in the session, the maintex was perfectly saturated when I set ignore colormask with colored maintex, but it becomes desaturated when I save and close the session, then return to it.

As seen in Blender:
![Screenshot (105)](https://user-images.githubusercontent.com/94071450/187497055-5297b72c-ece8-4613-910c-6c05119fc25b.png)

How it's meant to look:
![KoikatsuParty-2022-08-30-13-06-17-Render](https://user-images.githubusercontent.com/94071450/187497544-cb97e844-71ee-4add-9bea-02d76f89d79a.jpg)

From when I first applied colors in the Blender session (notice the shader editor):
![Screenshot (106)](https://user-images.githubusercontent.com/94071450/187499604-3e763ff6-9e34-4787-8e92-9c5d54c4b0fa.png)

**Comment by Player4-AB** [comment]
I am having a similar issue. When I upload the model along with the clothes, it looks normal. As soon as I start editing clothing materials, and then switch to another preset, the saturation disappears.

**Comment by FlailingFog** [comment]
You have to use the "Save all images" button after importing or the saturation will be lost. You can also close out of blender entirely right after importing and it'll ask if you want to save the images.
