### ISSUE TITLE
KKBP failing on step 4, Bake Material Templates with AttrubyteError: 'NoneType' object has no attribute 'nodes'

### ISSUE THREAD

**Issue by TopazMarauder** [FlailingFog/KK-Blender-Porter-Pack#238]
I am unable to proceed beyond the 4th step of baking material templates,
Upon pressing the button, I am met with the following message inside the blender system console: 

`D:\Documents\Pes\aes\wvtmain\WIP\Anya\new\Textures\
Python: Traceback (most recent call last):
 File "C:\Users\OWNER\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\KK-Blender-Porter-Pack-master\exporting\bakematerials.py", line 382, in execute
    if setup_image_plane():
  File "C:\Users\OWNER\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\KK-Blender-Porter-Pack-master\exporting\bakematerials.py", line 75, in setup_image_plane
    bpy.data.worlds[0].node_tree.nodes['Background'].inputs[0].default_value = (0,0,0,1)
AttributeError: 'NoneType' object has no attribute 'nodes'

location: <unknown location>:-1 
`

This is on blender 2.93 using version 5.11
I have uninstalled blender and the addon and retried it using multiple different cards. 
card and full system console:
https://files.catbox.moe/044uwb.png
https://files.catbox.moe/4f5nzh.txt

**Comment by FlailingFog** [comment]
Can you check that your world shader node tree looks like the default? It looks like it was deleted or something from the error message.
![image](https://user-images.githubusercontent.com/65811931/188290084-9352ea50-66a5-41e0-967a-83c4e14e7ec4.png)

**Comment by TopazMarauder** [comment]
Yep, that was it. Thanks
