### ISSUE TITLE
KKS Fix Lipstick

### ISSUE THREAD

**Issue by poisenbery** [FlailingFog/KK-Blender-Porter-Pack#239]
Currently, the importer will look for textures that I have not seen exported:
From Importeverything.py:

```
    image_load('KK Face', 'Gentex', 'overlay1', 'cf_m_face_00_T5.png')
    image_load('KK Face', 'Gentex', 'overlay2', 'cf_m_face_00_T6.png')
    image_load('KK Face', 'Gentex', 'overlay3', 'cf_m_face_00_T7.png')
```

It will also put the lip line on the forehead.

I propose a change:

```
    image_load('KK Face', 'Gentex', 'overlay1', 'cf_m_face_00_ot1.png')
    image_load('KK Face', 'Gentex', 'overlay2', 'cf_m_face_00_ot2.png')
    image_load('KK Face', 'Gentex', 'overlay3', 'cf_m_face_00_T5.png')
```

This will ensure that the lipstick and the face flush blush textures are properly loaded.

To make sure that the lipstick colors are correctly loaded, in importcolors.py:

```
   shader_inputs['Overlay 1 multiplier'].default_value = face_colors[6]

```

To ensure correct mapping, change the Overlay 1 position node to look like this:
![Screenshot (13)](https://user-images.githubusercontent.com/78466408/188294118-68113a5f-bcdc-4445-ba07-f4e1e7a50591.png)

And Overlay 3 to look like this:
![Screenshot (15)](https://user-images.githubusercontent.com/78466408/188636418-27981659-3cbc-40ff-9ae9-fc56b829e5b8.png)

It will result in the character being imported with lipstick and lip line textures in the correct location, with the correct mapping, and correct colors.
![Screenshot (14)](https://user-images.githubusercontent.com/78466408/188294171-a9247763-5e14-4036-8ec6-c897ffc4a1ad.png)

[Mind the makeup. I used RGB to make sure I knew which value was which in the colors json.]

**Comment by BTHP5** [comment]
This would be really useful, I take commissions for turning koi models into VTuber models, and some of my clients have makeup on their models currently and I don't know how to make it show up :/

**Comment by FlailingFog** [comment]
I added dedicated slots for these textures

**Comment by poisenbery** [comment]
Love the changes! Thanks for everything
