### ISSUE TITLE
Foetal position export

### ISSUE THREAD

**Issue by AsunaKoB** [FlailingFog/KK-Blender-Porter-Pack#240]
Hi, I downloaded the v6 beta, I'm having an issue where all of the characters I export appear in the foetal position (H-pose 5) not T-pose so they wont work no matter what I do.

**Comment by LegionInstaller** [comment]
Tried setting the Manually into T-Pose ?

**Comment by AsunaKoB** [comment]
the pose? I dont even have that pose in my character creator

**Comment by LegionInstaller** [comment]
> the pose? I dont even have that pose in my character creator

Should be the last one in KK It's the last one , atleast for me it is

**Comment by AsunaKoB** [comment]
it is for regular KK, I'm talking about the Sunshine version. There is no T-pose. I have no problems using the older version for KK Party

**Comment by poisenbery** [comment]
> it is for regular KK, I'm talking about the Sunshine version. There is no T-pose. I have no problems using the older version for KK Party

what version of sunshine are you using?
i have the t pose in mine

**Comment by AsunaKoB** [comment]
I'm not sure, I'm using the better repack version (R1.2)

**Comment by MediaMoots** [comment]
Try using RX5 or newer.

**Comment by MediaMoots** [comment]
Did it work?
