### ISSUE TITLE
Does anyone knows which version actually works and with which version of blender is compatible?

### ISSUE THREAD

**Issue by bplordH** [FlailingFog/KK-Blender-Porter-Pack#241]
Tried all the latest releases with almost all hf patches and none of them work. I only manage to reach the point where i import the pmx file but when i get to import the textures everythings starts to break some times eyelashes do not appear other times the textures are too yellowish but most of the time when i try to click import shaders (second action) it always shows an error no matter which version i use.So if anyone knows which version of blender,hf patch,kkbp actually works please let me know

**Comment by Germain9000** [comment]
Blender 3.0.1
HF patch 3.17
V5.1.1
Note: that some card has issues like no eyelashes.

**Comment by poisenbery** [comment]
> Blender 3.0.0 specifically

May I ask where you are getting this information from?

I notice 0 differences between 3.0 and later versions, aside from the obvious fact that 3.3 is MUCH faster than 3.0


So, the change between 2.xx and 3.xx is rather significant: the change in the first number indicates something called "Incompatible API Changes" which basically means that things made for 2.xx are likely not to work in 3.xx. I'm pretty sure that a newer version of python was used in 3.xx but I am not entirely sure if it was done at 3.xx or prior. 


So, anything made to work in 3.xx SHOULD work perfectly fine in all subsequent releases, until blender 4.xx when there will be incompatible API changes once again.

**Comment by MediaMoots** [comment]
Blender 3.3 - Koikatsu RX14 - KKS R5 - Latest master
