### ISSUE TITLE
Export eye textures in the correct size + Support for heterochromia + Remove the Blue pixels when using maintex.

### ISSUE THREAD

**Issue by BTHP5** [FlailingFog/KK-Blender-Porter-Pack#242]
When importing the model into Blender, the eye size is never correct. You have to manually adjust it, which can be tedious when you're trying to export multiple of the same character.

Along with this, you can set one eye a different colour to the other eye in Koikatsu, but this isn't reflected in blender.

And, when selecting "Use maintex instead?" in the shader node, blue pixels begin to form everywhere. Image below:
![image](https://user-images.githubusercontent.com/54001645/188639169-7b37950f-2487-4394-ae0b-935ee733dcec.png)
I think it would be really useful if these things were fixed, along with the missing makeup problem.
Thank you for reading.

**Comment by MediaMoots** [comment]
> Along with this, you can set one eye a different colour to the other eye in Koikatsu, but this isn't reflected in blender.

This has been fixed in PR #138

**Comment by MediaMoots** [comment]
As for the eye size, it could be fixed if the plugin exports the Shape key values, so I'll look into that.

**Comment by MediaMoots** [comment]
> Is there also a way to look into lipstick and makeup exporting/showing up on the Use Maintex Instead slider?

What do you mean?

**Comment by BTHP5** [comment]
If a chacter I export has lipstick on in the makeup section of Koikatsu, it isn't exported into blender. Usually, if I have any overlays like body paint or moles, they will be visible after I go into the Shader node for the face and use the Use Maintex Instead slider, but lipstick doesn't seem to show up :(

**Comment by MediaMoots** [comment]
@BTHP5 I think @FlailingFog has fixed this in #239 and #138 , it all works now, just make sure to set lip intensity to 1.

**Comment by BTHP5** [comment]
@MediaMoots Was this fix recent or from a while ago, because when I opened the issue it was after I did set the lip intensity to 1 and it wasn't there ^^'. I'll try again today though, thank you!

**Comment by MediaMoots** [comment]
@BTHP5 
The fix was done yesterday, I think.
