### ISSUE TITLE
Eye lashes texture missing

### ISSUE THREAD

**Issue by Germain9000** [FlailingFog/KK-Blender-Porter-Pack#243]
Everything is fine expect for the eyelash texture and the red highlight.

![Koikatu_F_20191107045056666_Matoi Ryuko_Evaan](https://user-images.githubusercontent.com/112973330/188702152-8505f6fd-07aa-465a-ae52-4c618ae5b06a.png)

Pls help me

![Desktop Screenshot 2022 09 07 - 00 47 53 32](https://user-images.githubusercontent.com/112973330/188704552-33294802-c006-4c9c-9634-071e5dcd7a17.png)

**Comment by sleepymanakete** [comment]
Iirc, sometimes the addon doesn't do it so you'll need to manually add the eyelash kage texture (or something similar) yourself. been a while since i had this issue but that should be the fix!

**Comment by Germain9000** [comment]
> 

Problem: The eyelashes texture is blank
![cf_m_eyeline_kage_MainTex](https://user-images.githubusercontent.com/112973330/188791874-8738854b-9515-43c5-af32-0685695b5d5e.png)

**Comment by MediaMoots** [comment]
@Germain9000 
This card does not use an eyelash texture, somehow the eyelash is part of the face texture
![cf_m_face_tex_MT_00](https://user-images.githubusercontent.com/81146974/188831394-aae8a7cf-5a4f-4673-b349-c2997ae481ed.png)

**Comment by MediaMoots** [comment]
The dark texture seems to have an issue but if you set it to daylight there are eyelashes
![image](https://user-images.githubusercontent.com/81146974/188832049-d83e6d10-dd91-4aee-8ed4-1d560be034e6.png)
![image](https://user-images.githubusercontent.com/81146974/188832078-27c10299-22a5-4e1b-8df5-1147a1964f5d.png)

**Comment by MediaMoots** [comment]
the material for the red hair is:
![image](https://user-images.githubusercontent.com/81146974/188832593-eaa3d004-804f-4bf8-a6d1-9d7ab1e680c7.png)


So, keep that deselected when separating the hair object
![image](https://user-images.githubusercontent.com/81146974/188833058-7b173c40-e5da-4d0b-aceb-5e046d97c347.png)

Then in the shader set shine to 0:
![image](https://user-images.githubusercontent.com/81146974/188836742-523a0e6c-a961-413c-9d3a-949f3924f09f.png)

![image](https://user-images.githubusercontent.com/81146974/188836839-4ca450f0-cca6-423b-a167-75041738f589.png)

**Comment by Germain9000** [comment]
Oh Okay! Thanks!

**Comment by Germain9000** [comment]
Red Highlight works, but the eyelashes is still missing... Am i doing something wrong?

![Desktop Screenshot 2022 09 07 - 21 53 57 47](https://user-images.githubusercontent.com/112973330/188910069-0cb5f3f4-0661-44c0-8154-b66274f5547c.png)

**Comment by MediaMoots** [comment]
Maybe make sure the face texture has the eyelash overlays?

> @Germain9000 This card does not use an eyelash texture, somehow the eyelash is part of the face texture ![cf_m_face_tex_MT_00](https://user-images.githubusercontent.com/81146974/188831394-aae8a7cf-5a4f-4673-b349-c2997ae481ed.png)

That seems to be V5 of the plugin though, so there might be some issues there, you could try V6 in PR #138 but there might be breaking changes so it's best to start with a new blend file.

**Comment by Germain9000** [comment]
Okay, I'll try to use V6

**Comment by Germain9000** [comment]
> Maybe make sure the face texture has the eyelash overlays?
> 
> > @Germain9000 This card does not use an eyelash texture, somehow the eyelash is part of the face texture ![cf_m_face_tex_MT_00](https://user-images.githubusercontent.com/81146974/188831394-aae8a7cf-5a4f-4673-b349-c2997ae481ed.png)
> 
> That seems to be V5 of the plugin though, so there might be some issues there, you could try V6 in PR #138 but there might be breaking changes so it's best to start with a new blend file.

In the V6 version I can't seem to export a new model, Idk why I have HF patch 3.7.

**Comment by MediaMoots** [comment]
I think you need HF Patch 1.16 or above

**Comment by Germain9000** [comment]
> I think you need HF Patch 1.16 or above

I have HF patch 3.17

**Comment by Germain9000** [comment]
I mean the button to export is there, but it did nothing since I can still play the game.

![Desktop Screenshot 2022 09 07 - 23 31 21 20](https://user-images.githubusercontent.com/112973330/188931689-3ff9bfdb-e5c2-4aab-95ca-0376405bd0c9.png)

**Comment by MediaMoots** [comment]
Could you share the output log? Thanks!

**Comment by Germain9000** [comment]
> Try to untick Export Hit Meshes, if that doesn't work, then could you share the output log? Thanks!

Output log? Where can I access it?
I already tried unticking the Export Hit Meshes button, no luck
The game didn't freeze or anything, the game act like there is no button.

**Comment by MediaMoots** [comment]
@Germain9000 

It's in the folder with the .exe for the game, called `output_log.txt`

**Comment by Germain9000** [comment]
[output_log.txt](https://github.com/FlailingFog/KK-Blender-Porter-Pack/files/9546749/output_log.txt)

Oh yeah, forgot to mention, I use ScrewThisNoise's BetterRepack RX15

**Comment by MediaMoots** [comment]
Very weird, you are using the dll in net3.5 right?

**Comment by Germain9000** [comment]
> Very weird, you are using the dll in net3.5 right?

Yes

**Comment by MediaMoots** [comment]
Hmm, i am using RX14 and it works fine, maybe try installing the plugin again, or updating KKBP to the master branch

**Comment by Germain9000** [comment]
> 

Tried it, no luck here, is it because I installed other mods or something?

**Comment by Germain9000** [comment]
> Hmm, i am using RX14 and it works fine, maybe try installing the plugin again, or updating KKBP to the master branch

Alright, I've figured it out. Either it's Kplug or other mods that I've installed that's preventing the plugin to export the model. I've finally got the result that I wanted, Thanks!

![Desktop Screenshot 2022 09 19 - 00 21 36 19](https://user-images.githubusercontent.com/112973330/190920168-803685c2-b7f6-40d1-9da0-85089ebbc5d5.png)
