### ISSUE TITLE
Imported vertex groups are empty for some clothes

### ISSUE THREAD

**Issue by evshiron** [FlailingFog/KK-Blender-Porter-Pack#244]
Game: KKS BetterRepack R5
Blender: 3.2.1
Exporter: V6.0 20220907
Addon: V6.0 20220907
Card: 
![KoikatsuSun_F_20220912020550217_春野 千佳](https://user-images.githubusercontent.com/8800643/189543268-17deb20f-c9aa-4c8e-a124-236d4e0250f2.png)
Blender File: 
[untitled.zip](https://github.com/FlailingFog/KK-Blender-Porter-Pack/files/9543272/untitled.zip)
Mod File:
[[nashi]Babydoll.zip](https://github.com/FlailingFog/KK-Blender-Porter-Pack/files/9543281/nashi.Babydoll.zip)

Recently I have encountered some Rigify failures, because no vertices are found in imported vertex groups, and the armature is unable to control the meshes.

The exported file size looks normal though, so I suspect the cause is in the addon, but I can't figure it out.

**Comment by ilcane87** [comment]
Hi @evshiron, just to be sure, is this a problem you have with the Rigify armature only, or does it exist with the standard armature too?
If it's the former I could probably help, but unfortunately I don't have Koikatsu Sunshine installed, so I'd need you to post the output folder of the imported character from Koikatsu, to be able to test the whole conversion from the beginning.

**Comment by evshiron** [comment]
@ilcane87

Thanks for your reply. It's a problem with the standard armature.

I am attaching the output below, which is a 7z archive with zip extension to bypass GitHub's size & extension limitation.

[20220912020722_春野千佳.zip](https://github.com/FlailingFog/KK-Blender-Porter-Pack/files/9554265/20220912020722_.zip)

**Comment by ilcane87** [comment]
Thanks, but as you said the problem in on a higher level so I'm afraid I can't help with it, you'll have to wait for one of the plugin developers to address this.

**Comment by MediaMoots** [comment]
Just tested with Blender 3.3 - KKS R5 - latest #138 
![image](https://user-images.githubusercontent.com/81146974/190356486-52ad638e-c3ba-4837-860b-07efabcf3297.png)

Seems to work ok.
