### ISSUE TITLE
Boots aren't being exported.

### ISSUE THREAD

**Issue by BugMonkey42335** [FlailingFog/KK-Blender-Porter-Pack#250]
Megumin's boots aren't being exported.
I'm using blender 3.3 and the v6beta of the exporter.
![Koikatu_F_20220309170635271_紅魔族の めぐみん](https://user-images.githubusercontent.com/64150986/190674264-2a78e61e-7bd4-482f-af85-6a76953755ee.png)

**Comment by MediaMoots** [comment]
Should be fixed now!
