### ISSUE TITLE
Terrible Artifacts when using the new baking system

### ISSUE THREAD

**Issue by TheMaskedMan00** [FlailingFog/KK-Blender-Porter-Pack#251]
![image](https://user-images.githubusercontent.com/46354545/190878008-80276d97-248c-4d7b-ac0c-4680dbb332a3.png)
Artifacts are most visible here /\

They also appear in hair too.

card in question https://db.bepis.moe/koikatsu/view/236462

**Comment by nizhuan-jjr** [comment]
Is this an armor or what?

**Comment by MediaMoots** [comment]
Looks like the outline, try disabling the outline in the modifiers, it might help.

**Comment by FlailingFog** [comment]
It looks like the mesh is clipping into itself when being flattened down. It's also happening when just that particular material is separated and flattened down so I'm not sure how to fix this at the moment. 
![image](https://user-images.githubusercontent.com/65811931/192151197-18d52768-b0dc-4337-bfcf-42366852c8ba.png)

**Comment by FlailingFog** [comment]
I was able to fix this by changing how the baking works. It still clips into itself, but the artifacts shouldn't show anymore
![image](https://user-images.githubusercontent.com/65811931/194710047-d31647fc-bd06-4c76-8b3e-dee2e3ab1999.png)
