### ISSUE TITLE
Prep for export throwing error: bpy.ops.object.mode_set(mode="object")

### ISSUE THREAD

**Issue by Zorelnam** [FlailingFog/KK-Blender-Porter-Pack#254]
![Screenshot 2022-09-18 215549](https://user-images.githubusercontent.com/51460641/190937058-14b2f42b-c971-4a7a-b63b-98a77250c059.jpg)

Mind you, i am on the latest blender release, i believe it is 3.3 right now(?) so this might be the origin of the issue, please let me know any work arounds so i can export blender girls into koikatsu

**Comment by MediaMoots** [comment]
Could you share the card please? Thanks!

**Comment by Zorelnam** [comment]
it's not a card, its the model itself, any help is of course appreciated
[Sahori.zip](https://github.com/FlailingFog/KK-Blender-Porter-Pack/files/9595878/Sahori.zip)

**Comment by Dolliex** [comment]
Did you ever figure it out? I recently installed everything and it worked fine for 1 model, then a day and a half later I attempt a new model and I get flooded with that error no matter what I do, uninstall reinstall, use master zip etc. I tried again with the model that did work and it suddenly has the same errors now too. It's clearly the plugin and not the models being problematic but I can't seem to find out what it is specifically.

**Comment by Zorelnam** [comment]
no, i have no solution, i gave up after a while, i have a strong suspicion the issue is because i am not properly using a Koikatsu model and instead just literally ripped a model and mesh from somewhere else and attempted to use the plugin, i honestly have to keep testing to give you any answer
