### ISSUE TITLE
V6: Error when baking material templates

### ISSUE THREAD

**Issue by nizhuan-jjr** [FlailingFog/KK-Blender-Porter-Pack#256]
Traceback (most recent call last):
  File "C:\Users\pkopk\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\KK-Blender-Porter-Pack-V6-0-0\exporting\bakematerials.py", line 439, in execute
    camera = setup_camera()
  File "C:\Users\pkopk\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\KK-Blender-Porter-Pack-V6-0-0\exporting\bakematerials.py", line 64, in setup_camera
    bpy.data.worlds[0].node_tree.nodes['Background'].inputs[0].default_value = (0,0,0,1)
IndexError: bpy_prop_collection[index]: index 0 out of range, size 0

After clicking the Prep for target application, the objects are not merged into one(not sure if this is ok).
![0](https://user-images.githubusercontent.com/3255986/190976674-f72fdbe6-072b-4197-ad1e-3c6839906065.png)
Then I clicked Bake material templates and I only want light version, the error occurs.
![1](https://user-images.githubusercontent.com/3255986/190976677-68953bd6-bc1f-49dc-a5f1-e752858f68b0.png)
My scene has no world or background.
![2](https://user-images.githubusercontent.com/3255986/190978308-8dd17919-db29-4880-8d2e-9e87712ecd32.png)
Even though I setup a world for it, I still get this error.
![3](https://user-images.githubusercontent.com/3255986/190978476-4bb0cbd7-31da-4fb1-923d-bede252abee3.png)

**Comment by nizhuan-jjr** [comment]
It's not a matter of language, I believed. I changed to English and tried, it gave me the same error.

**Comment by FlailingFog** [comment]
Thanks, the language shouldn't matter now and it will create a new world if it doesn't find one
