### ISSUE TITLE
Bone weights issue (vertex groups duplication) when exporting from Koikatsu

### ISSUE THREAD

**Issue by fritty** [FlailingFog/KK-Blender-Porter-Pack#257]
When importing with Koikatsu armature, all the vertex groups get duplicated (duplicates have ".001" or simmilar after their names).
Actual weights get assigned only to duplicates, so none of them work on the objects until names are fixed.
Same with any characters.
Blender 3.3, Koikatsu Party, HF v3.17, KKBP V6.0.0

[KKBP Log](https://github.com/FlailingFog/KK-Blender-Porter-Pack/files/9600818/KKBP.Log)

**Comment by MediaMoots** [comment]
Card?

**Comment by fritty** [comment]
The cause might be leaving and re-entering the character creator. Not sure

**Comment by MediaMoots** [comment]
Should be fixed in the latest master branch, please try it out!
