### ISSUE TITLE
v6: Skirt bones placement is wrong

### ISSUE THREAD

**Issue by ilcane87** [FlailingFog/KK-Blender-Porter-Pack#258]
Here's a comparison image between KKBPP v5 (left), Koikatsu Studio (center), and KKBPP v6 (right):

![Scene](https://user-images.githubusercontent.com/34897042/191190839-f9124401-9e35-42c9-a44e-3905c5a4b068.png)

I ignored the final bone of the chain in Koikatsu since it has no weights on that skirt and isn't imported into Blender anyway.

I had also posted a picture of the weights positions for each bone yesterday, which shows v5 is more accurate: https://github.com/FlailingFog/KK-Blender-Porter-Pack/issues/78#issuecomment-1251316997

Here's the character card, just in case:
https://db.bepis.io/koikatsu/view/17005

**Comment by MediaMoots** [comment]
Could you try and import through this?
![image](https://user-images.githubusercontent.com/81146974/191226942-ca9c5971-7cdd-4205-9a4c-e898bca589d2.png)

And see if the weights are still broken? Thanks!

**Comment by ilcane87** [comment]
Here you go:
![Scene2](https://user-images.githubusercontent.com/34897042/191233878-30d4127b-5b3c-404a-9632-72dcaebe7c17.png)

It seems that the placement of the bone heads corresponds to v5 of the plugin.

Btw the weights are never broken, they're correct in all versions of the plugin, it's a bones placement issue.

**Comment by MediaMoots** [comment]
Ok thanks for testing, so the exporter exports correctly, but somewhere in the blender plugin the bones get moved it seems.
@FlailingFog Any ideas?

**Comment by ilcane87** [comment]
@FlailingFog 
I remembered checking old commits some time ago, and reading something about connecting the skirt bones to accomodate the Rigify conversion.
This is the commit in question:

https://github.com/FlailingFog/KK-Blender-Porter-Pack/commit/749a7d1b4bef244fc6fdcd814419443e5bb4af20

If it turns out that the problem is caused by Rigify-specific adjustments, I suggest you don't bother with it, everything concerning that should be relegated to its own scripts, it would be counterproductive to introduce error-prone code in the main plugin just for an extra feature.
You can leave the bones in their vertical state as they are exported, I'll take care to connect them during the conversion like I do for all other bone chains.

**Comment by FlailingFog** [comment]
The head of the bones were being moved by both the resize and connect functions in bonedrivers.py. I remember having the resize function in V5 though so I'm not sure why the placements are correct in that one. I removed the resize function, but I still want the skirt bones to look connected in the KKBP armature, so I redid the connection function to keep the bone heads in the correct location (they can be reset if needed by setting the bone's use_connect property to False then placing the tail directly above the head).

Comparing the redone one and the raw pmx import shows they match up nicely now:
![image](https://user-images.githubusercontent.com/65811931/191876271-fbc90c1c-fe67-48b1-8f95-9e92b0cf2ee6.png)

**Comment by ilcane87** [comment]
@FlailingFog 
Awesome, thanks a bunch.
I'm closing the issue with this.
