### ISSUE TITLE
Import KK animation (.fbx format)

### ISSUE THREAD

**Issue by Electrodynamo64** [FlailingFog/KK-Blender-Porter-Pack#259]
Does anyone know how to rip animations from the game, so they can be imported into blender using the option shown in the extras menu?
![2022-09-20](https://user-images.githubusercontent.com/114025767/191356509-7ee74b53-9bb3-4d32-970f-8183ee146279.png)

**Comment by FlailingFog** [comment]
This is how I've been exporting the animations: https://www.youtube.com/watch?v=XFt12n7ByBI&t=465s
I don't know if the import button still works though

**Comment by Electrodynamo64** [comment]
Thank you very much. I will try this method now.
