### ISSUE TITLE
Dark Shading on Materials with only Maintex have heavy contrasting.

### ISSUE THREAD

**Issue by BugMonkey42335** [FlailingFog/KK-Blender-Porter-Pack#26]
Not sure if this is a bug or an issue on my part, but attempting to use Materials in a dark enviroment that only have Maintex causes heavy pixel contrast.
![Light Shading](https://user-images.githubusercontent.com/64150986/128642973-b15e5217-302b-4864-a8ed-190995dc02a3.png)
![Dark Shading](https://user-images.githubusercontent.com/64150986/128642970-abb525fe-a636-40bc-93c8-73d24b95cd9f.png)

**Comment by FlailingFog** [comment]
@BugMonkey42335
The "Automatically generate a shadow color dark" node group inside of the "General overlays dark" node group seems to be causing this. This node group is for getting dark versions of a specific color and is used for clothes detail and hair detail when you don't want to set them. It works good enough for saturating and darkening solid colors on outfits and hair, but I guess it doesn't work out when applying it to certain maintex images

A "workaround" (if you can call it one) is plugging the maintex into the color mask base, tweaking the maintex to get a dark version yourself with hue contrast and rgb curve nodes, then enabling the color mask slider:
![image](https://user-images.githubusercontent.com/65811931/128789532-37f6580e-8e06-4429-91ed-397e528b65c1.png)

Though, unless you only have two or three materials to do this for, it's a pretty useless workaround.
I would need another way to saturate and darken images to actually fix this.

**Comment by FlailingFog** [comment]
The node group was replaced in V5, so this should be fixed when that releases
![image](https://user-images.githubusercontent.com/65811931/137048996-cb3370a7-20ab-449e-996d-c135dfeb0d2f.png)
![image](https://user-images.githubusercontent.com/65811931/137049038-fed66c87-8eb6-4d5c-b171-8c305e2bc7ae.png)
