### ISSUE TITLE
Can the 'Bake Materials Templates' do individual materials?

### ISSUE THREAD

**Issue by FrankVargas427** [FlailingFog/KK-Blender-Porter-Pack#260]
Due to my GPU being absolute shit, the baking of the materials outright causes a driver timeout (my issue, not the project's). 
Is there any way to run the baking one material at a time? Like only the body materials first, then one outfit, then the other and so on? Or maybe bake just one individual material?

**Comment by LegionInstaller** [comment]
It does it one by one

**Comment by nizhuan-jjr** [comment]
Baking only one selected material would be a nice feature to add.

**Comment by FrankVargas427** [comment]
I think I didn't explain my issue correctly or thoroughly, sorry for that!

My GPU cannot handle the continuous load that is baking every material in a batch. What I was asking for is a way to click the bake button and make it so that it only bakes ONE material. Then I can change the material to load and click it again for that ONE material to be baked, and so on, instead of a batch bake of all materials one after the other.

**Comment by FlailingFog** [comment]
Right now, it only does all materials at once. I can think of two workarounds:
* The bake materials button picks up where it left off. If the image already exists in the folder, it won't try to bake another one and it'll skip over it. You could let it run until you get a timeout, then run it again to continue the baking process until all the images are baked
* The script only bakes objects that are in a visible collection in the outliner. You should be able to go into edit mode and separate by material, then throw everything except a single material into a disabled collection. This should make the script bake only one material. Then when everything is baked you can combine all the separated materials back into one object.

**Comment by FrankVargas427** [comment]
Several crashes can attest that no, it does not pick up where it left. It still takes time (according to the console) to bake a texture, even if it already is in the folder where I am baking into.

However, the second point worked well for me and I could pinpoint the exact model that was causing the crash to happen. Thank you for the suggestion!

**Comment by FlailingFog** [comment]
Shoot, you're right it doesn't continue where it left off... I added that behaviour in but it only applied to a specific situation.

The master branch should now work as I said in the first point (if you encounter a timeout again)
