### ISSUE TITLE
Unable to bake materials properly due to error

### ISSUE THREAD

**Issue by infinitephantasm** [FlailingFog/KK-Blender-Porter-Pack#264]
```
Error:          Unknown python error occurred
Traceback (most recent call last):
  File "C:\Users\[redacted]\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\KK-Blender-Porter-Pack-master\exporting\bakematerials.py", line 464, in execute
    cleanup()
  File "C:\Users\[redacted]\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\KK-Blender-Porter-Pack-master\exporting\bakematerials.py", line 403, in cleanup
    fillerplane.select_set(True)
RuntimeError: Error: Object 'fillerplane.001' can't be selected because it is not in View Layer 'ViewLayer'!
```
this error appears every single time i try to bake materials on just about any exported card, resulting in the baking process just stopping in the middle of it without moving forwards (from what i can tell).

![image](https://user-images.githubusercontent.com/23409983/192137009-11efbfe5-4a18-4904-879f-de9594e2998f.png)

**Comment by FlailingFog** [comment]
I'm not sure what could cause that for all cards. Maybe try purging your orphan data in the scripting tab a few times before pressing the bake button?
![image](https://user-images.githubusercontent.com/65811931/192146761-2de56a03-3981-46c5-89c4-86326b11c5cd.png)

**Comment by infinitephantasm** [comment]
tried, didn't seem to work. for good measure i tested like 10 other cards of mine, some default, some not, and none of them got past this step, even after relaunching and doing the steps all over again. have no clue if my blender setup is just off somehow even after a fresh install, or if there's something wrong with how i'm exporting things

if it matters, i'm on koikatsu betterrepack RX15, i'm using single outfit export, and i've tried this on both the master branch and 6.0 release versions of the addon to no avail

**Comment by LegionInstaller** [comment]
Some Addons can cause that Issue I also had a baking problem until disabling specific addons

**Comment by infinitephantasm** [comment]
i basically just did a reinstall completely, reinstalled the required addons and now things are working. not exactly sure what i did, but it's working now i guess
