### ISSUE TITLE
Wrong Eye Openess (or maybe eye shape) from KKBP_Exporter

### ISSUE THREAD

**Issue by nizhuan-jjr** [FlailingFog/KK-Blender-Porter-Pack#265]
This is the eye in Blender, right after the import.
![0](https://user-images.githubusercontent.com/3255986/192146464-84a14a3e-a946-4b4d-9ad8-ef158f1a8377.png)
This is the default eye in game, with 100% eye openess.
![1](https://user-images.githubusercontent.com/3255986/192146466-7978488a-ae61-45cf-8eea-5404ffcf189e.png)
I guess it's mainly an issue on KKBP_Exporter, which doesn't set a correct eye openess value for its product.

**Comment by MediaMoots** [comment]
Please see this:
https://github.com/FlailingFog/KK-Blender-Porter-Pack/issues/166#issuecomment-1146759340

**Comment by nizhuan-jjr** [comment]
OK, I copied the KK Eyes_default_cl to a new shapekey and applied with value 0.2 to the basis. The eyes look fine now. Thank you for the solution.

**Comment by MediaMoots** [comment]
Nice, glad it helped!
