### ISSUE TITLE
V6.0: Incorrect/Broken Rigs When Exporting More Than Once

### ISSUE THREAD

**Issue by MoriMorinya** [FlailingFog/KK-Blender-Porter-Pack#266]
Exporting multiple characters in the same session with varying heights causes the rig to only adapt to the first exported model's height, only stops once you close the game entirely.

The bones update, but their position is incorrect and are instead using the previous character's height/position, it doesn't seem to matter what option I tick on the export, and it also happens if the bones (like the spine) have been moved using advanced bonemod

![image](https://user-images.githubusercontent.com/101014618/192270261-061ac4be-9fcd-42af-bab3-7a514d65c593.png)
![image](https://user-images.githubusercontent.com/101014618/192272605-968a2051-abf2-4685-b6d6-12836dec01cc.png)

This is probably the same issue/or could be related to #257 where exporting, exiting and re-entering the editor causes duplicate vertex groups on next export, I am not a coder or anything but it feels like the plugin forgets to update some data once it gets it the first time, causing issues like duplicated vertex groups and armatures updating the bones but with incorrect positions

**Comment by MediaMoots** [comment]
Thanks for the bug report, should be fixed now!
