### ISSUE TITLE
PMX rig with IK bone feature. SFW button not work

### ISSUE THREAD

**Issue by AsukaWhite** [FlailingFog/KK-Blender-Porter-Pack#268]
Thanks for the great tool.
Any plan of generating mmd style rig? Found kkpx_rig has ik,but pmx rig not. 
if mmd_style bone name and ik are generated, users can use mmd animation directly.
In v6.0 ,SFW button doesn't work. Be curious, how frequently people use it? mostly, it just wastes calculation time in render and makes tedious nodes.

**Comment by FlailingFog** [comment]
I've tried looking into an mmd rig / mmd export but have not figured it out.
The SFW button is for me. It only deletes things and is disabled by default. How does it affect performance?
