### ISSUE TITLE
Node Group not importing correctly? 

### ISSUE THREAD

**Issue by SP-Size** [FlailingFog/KK-Blender-Porter-Pack#270]
Hey all

I ran into an issue while trying to replicate this sort of cycles conversion https://github.com/FlailingFog/KK-Blender-Porter-Pack/issues/77. This worked for the 5.0 version of this converted, but I'd like the convenience of importing multiple outfits at once. :)

So I went into the KK Shader V6.0 file in my AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\KK-Blender-Porter-Pack-V6-0-0 folder, went into each material and added a node group to (hopefully!) make it possible to use the imported models in cycles without first having to bake the materials. I did it like so

![grafik](https://user-images.githubusercontent.com/112580158/192536197-db3f458b-3974-4375-ba52-465233c77a6d.png)

The node group is rather simple, only a few color inputs, a principled BSDF shader and a material output, just for convencience sake so that I don't have to go into every material of every model I port into Blender.

![grafik](https://user-images.githubusercontent.com/112580158/192536654-0758ee8e-e3c4-4537-a2ee-bdb0cc9d8a61.png)

But when I actually try to import a model, and it loads the shaders from the file mentioned above the node group gets converted to something completely different, and I don't understand why.

![grafik](https://user-images.githubusercontent.com/112580158/192535041-3d8a812c-d390-4289-b172-f6ea7caab3ab.png)

Any idea as to what might be causing this and how one can fix it?

**Comment by FlailingFog** [comment]
Try renaming your custom node group to something unique. From the first picture it looks like it's named "NodeGroup.###"
