### ISSUE TITLE
UnboundLocalError: local variable 'outlineStart' referenced before assignment

### ISSUE THREAD

**Issue by AsukaWhite** [FlailingFog/KK-Blender-Porter-Pack#271]
Card link: https://www.pixiv.net/artworks/101225204
Exported from KKS with v6, import into blender 3.0
issue:
"""
line 982, in add_outlines
    mod.material_offset = outlineStart
UnboundLocalError: local variable 'outlineStart' referenced before assignment
"""
is it better to use this on kk instead of kks?

**Comment by MediaMoots** [comment]
Try using the master branch instead of the V6 release, there was a fix for this made after V6 was released

**Comment by AsukaWhite** [comment]
This question is solved. but generated lots of "Outline_" materials for outfit.

**Comment by MediaMoots** [comment]
Well yeah, i think if you use Single outline then only one outline material will be made.

**Comment by AsukaWhite** [comment]
ok,did not realized that function.
Could you check the card ? 
I exported this chara but the head is obviously different from game, not as sharp as in game...

**Comment by MediaMoots** [comment]
Looks ok to me?
![image](https://user-images.githubusercontent.com/81146974/193506327-2ba758b8-9d10-43fb-8af7-855f64302002.png)
