### ISSUE TITLE
V6:Missplaced Bones on smaller characters

### ISSUE THREAD

**Issue by NotMomoK** [FlailingFog/KK-Blender-Porter-Pack#272]
I was trying to import one of my characters that is 140cm tall and the bones above the hip was out of the place, I tested on a overall height and that issue did not appears.
Other problem that I found is, if the character is using a Shader like Vanilla Plus or KKUST, the import will stop in middle of the importing.

Version tested was running on blender 3.1, the problem shows up in both rigify and KKBP armature

Here the card that give the problem https://mega.nz/folder/Qxt12ayb#XSDKqMzssUe60BkR4iy0-Q 
![unknown (2)](https://user-images.githubusercontent.com/114627673/192910733-a11cfd31-62fe-472a-9567-f1efe7adf72a.png)
![unknown (1)](https://user-images.githubusercontent.com/114627673/192910734-e61f186b-8f6b-4df5-aea6-b1fed0dd43a3.png)
![unknown](https://user-images.githubusercontent.com/114627673/192910742-bac990ae-879c-407c-9cf1-a909beabc231.png)

**Comment by MediaMoots** [comment]
Try using the master branch instead of the V6 release, there was a fix for this made after V6 was released

**Comment by NotMomoK** [comment]
i try again and i get the same result for KKBP armature and on rigify now i get this error
![image](https://user-images.githubusercontent.com/114627673/192914392-80efb4f6-e13f-4b92-b7aa-353de2db9281.png)

**Comment by MediaMoots** [comment]
Make sure to also update the KKBP Exporter plugin and export again:

Result:
![image](https://user-images.githubusercontent.com/81146974/192923291-a4b69bbd-d155-49de-bcd7-2bd54a349e7d.png)

**Comment by NotMomoK** [comment]
ooh i didn't know that part, yeah now is working just fine

**Comment by MediaMoots** [comment]
Nice!
