### ISSUE TITLE
There was a problem after adjusting the height

### ISSUE THREAD

**Issue by DWGIII** [FlailingFog/KK-Blender-Porter-Pack#273]
**Default height is fine**
![001](https://user-images.githubusercontent.com/93558630/193198885-4c48cf62-7306-4825-8cbf-23f1891d7264.png)

**Error after adjusting height**
![002](https://user-images.githubusercontent.com/93558630/193198898-6d6e78a7-09f6-4cb3-a516-b15b8bb1e77e.png)

Blender 3.3, Koikatsu Sunshine, HF v1.7, KKBP V6.0.0

**Comment by MediaMoots** [comment]
Please see #272

**Comment by DWGIII** [comment]
There is no problem with the hands, but the problem with the feet.
I am using the master branch, I just downloaded and installed it again, the problem is still not solved.

**Comment by MediaMoots** [comment]
Oh ok, so please see this then:
https://github.com/FlailingFog/KK-Blender-Porter-Pack/issues/177#issuecomment-1220785302

**Comment by DWGIII** [comment]
Great, solved! thank you
