### ISSUE TITLE
V6 Baking Issue: What I see is NOT what I get

### ISSUE THREAD

**Issue by nizhuan-jjr** [FlailingFog/KK-Blender-Porter-Pack#274]
Before I do the baking, this area looks like this.
![0](https://user-images.githubusercontent.com/3255986/193412322-7e083655-c3c0-488f-a436-6cde31504209.png)
After the baking, this area looks totally different(and worse).
![1](https://user-images.githubusercontent.com/3255986/193412326-05b52c5b-4ddb-44de-ad9c-6859f623e8f9.png)
I'm using the light atlas and have edited the body based on light version. The view looks fine, but the baking(of light version) can always have some issues on the armpit and side chest area. I've already turned off the outlines.

**Comment by FlailingFog** [comment]
It might be the rim. I noticed I get the same thing around the eyes on the face material.

**Comment by nizhuan-jjr** [comment]
What rim? I can't find anything related here.

**Comment by nizhuan-jjr** [comment]
I figure that if the dark part of the body shader nodes were tweaked to be the same as the light part(except for some alpha values of some colors), the baking result would look much like what I get in the view before the process.
However, I am still confused why the dark part is able to influence the light part in baking.

**Comment by miyabi-95** [comment]
think i may have a bad case of this issue myself. the parts that are pink should be white. looks like some weird polygonal glitching happens during the process?

![KK Face light](https://user-images.githubusercontent.com/63174638/214194853-da6568b4-eb04-495b-9231-2c9b8695c9b0.png)

**Comment by FlailingFog** [comment]
A "use old baker" checkbox  was added in one of the V6 updates. That will prevent corruption in the baked image like this.
