### ISSUE TITLE
How can I set the hair detail strength for hair materials individually?

### ISSUE THREAD

**Issue by nizhuan-jjr** [FlailingFog/KK-Blender-Porter-Pack#280]
![0](https://user-images.githubusercontent.com/3255986/193794671-bf219ad0-51a2-49d7-aa4d-ed28f2973a05.png)
There're some hair materials. Whenever I changed one of them, the other parts got changed as well.
![1](https://user-images.githubusercontent.com/3255986/193794675-25504a67-477d-4126-b31c-25f4f47926e4.png)
So how can I set values for each hair material individually? It looks like they are always linked in values.

**Comment by MoriMorinya** [comment]
![image](https://user-images.githubusercontent.com/101014618/194621226-466cdf6b-8eb6-47ad-a4fc-1cae4d6c00fe.png)
Press the number next to the hair node group for the hair you want to edit, this will make it a single user copy meaning any changes will apply to that material only.

**Comment by nizhuan-jjr** [comment]
Thank you, it works.
