### ISSUE TITLE
Stiletto issues.

### ISSUE THREAD

**Issue by Yariiko** [FlailingFog/KK-Blender-Porter-Pack#281]
A few models ago the the beta exporter managed to export the stiletto plugin settings for the heels I had equipped. I'm not sure how but that was pretty sick. 

Do you think it may be possible to add a check mark to the exporter in koikatsu to export the T pose with the heels settings?

Model worked fine on vtuber applications and VRChat. I haven't been able to replicate this using 5.11 or 6.00 not sure why.

**Comment by Yariiko** [comment]
Managed to replicate this using 5.11. Process was exporting a character with stiletto on, this first export DOES NOT export with the heels pose. Then just re-enable stiletto in Koikatsu and export again. This second export DOES show up in blender with the stiletto pose (on their toes). 

Tried doing this in 6.00, didn't work.

**Comment by MediaMoots** [comment]
Could you share a card that has stiletto?
Thanks!

**Comment by Yariiko** [comment]
Will do once I get home! will also post some screenshots to show you how it looks in blender. Just tested it today in vseeface and it works perfectly fine.

**Comment by Yariiko** [comment]
This card has stiletto on and this export was done with the 5.11 version, the feet and heels are in the stiletto pose in blender. Tried again exporting with the 6.00 but it didn't work. I feel 5.11 doesn't reset the T-pose if the chara is already in it but 6.00 does. 
[Jill.zip](https://github.com/FlailingFog/KK-Blender-Porter-Pack/files/9732943/Jill.zip)

**Comment by MediaMoots** [comment]
Thank you!

**Comment by MediaMoots** [comment]
Weird, the high heels don't work for me in KK

![image](https://user-images.githubusercontent.com/81146974/194567592-3a216d90-09da-448c-8299-95693f6ffd59.png)

Any ideas why?

I'm using BetterRepack RX14

**Comment by MediaMoots** [comment]
Got it working.

**Comment by Yariiko** [comment]
Yeah, remove the file "KK_AdvIKPlugin.dll" from the folder "plugins" located in "BepInEx" or all its settings in the plugin menu (you get to the plugin menu pressing F1)

**Comment by Yariiko** [comment]
> Got it working.

Heck yeah! sorry I answered as soon as I saw your comment xD

**Comment by MediaMoots** [comment]
Fixed :)

![image](https://user-images.githubusercontent.com/81146974/194578067-04572ffd-681c-43c4-a6c6-17c28341e8d7.png)

**Comment by Yariiko** [comment]
Oh nice! on 6.00?

**Comment by Yariiko** [comment]
I'll give it a look, thanks a lot!!

**Comment by Yariiko** [comment]
> Sorry, closed by mistake. Please try V3.94, it should work now, just make sure to set the stiletto settings first in KK's T-pose, if it doesn't update the feet, try setting the shoes to hidden then visible again (clothing states).

Tested it with a couple models and seems to work perfectly, thanks a loot!!!

**Comment by Yariiko** [comment]
Noticed an issue with the exporter.
SOME shoe mods do not need the toe roll on. Current exporter assumes toe roll to be on when stiletto is on. 
![image](https://user-images.githubusercontent.com/115004480/199617945-df32d0b9-8a7f-47d9-a0cf-579b9ec7fcf1.png)
Issue can be fixed just clicking the toe roll to off during the export process (after clicking "export", while the exporter is doing it's thing)
![image](https://user-images.githubusercontent.com/115004480/199618206-3c4c17bc-36e0-4aed-8b8a-dcde6c5535ce.png)

**Comment by MediaMoots** [comment]
The exporter doesn'tt change anything about the stiletto plugin, it only refreshes the clothing, so maybe the flags/preset needs to be saved first then it won't break.

![image](https://user-images.githubusercontent.com/81146974/208232859-855e1671-4fe8-40b2-80ae-273c0ccd689d.png)

**Comment by S00pergang** [comment]
Hey, I exported a character with Stiletto recently but the main body ignores it, meaning the entire outfit is shifted up

![Image](https://github.com/user-attachments/assets/f192609c-0f2b-48cf-a918-1c6d40e3333d)
