### ISSUE TITLE
No Texture after import.

### ISSUE THREAD

**Issue by Shylike** [FlailingFog/KK-Blender-Porter-Pack#282]
Hi. I'm currently using recent version (6.0.0) and mmd_tools
after importing the pmx model, it has no texture or all white

====    KKBP Log    ====
Info: Imported MMD model from "C:\Users\Windows10\Desktop\20221005165536_CarelessWhisper\model.pmx"
Info: Imported MMD model from "C:\Users\Windows10\Desktop\20221005165536_CarelessWhisper\Outfit 00\model.pmx"
Info: Imported MMD model from "C:\Users\Windows10\Desktop\20221005165536_CarelessWhisper\Outfit 01\model.pmx"
Info: Imported MMD model from "C:\Users\Windows10\Desktop\20221005165536_CarelessWhisper\Outfit 02\model.pmx"
Info: Imported MMD model from "C:\Users\Windows10\Desktop\20221005165536_CarelessWhisper\Outfit 03\model.pmx"
Info: Imported MMD model from "C:\Users\Windows10\Desktop\20221005165536_CarelessWhisper\Outfit 04\model.pmx"
Info: Imported MMD model from "C:\Users\Windows10\Desktop\20221005165536_CarelessWhisper\Outfit 05\model.pmx"
Info: Imported MMD model from "C:\Users\Windows10\Desktop\20221005165536_CarelessWhisper\Outfit 06\model.pmx"

Finalizing PMX file...
Modifying armature...
Finished in 3.66s

Translating and combining shapekeys...
Warning: 1 x Draw window and swap: 147.8298 ms, average: 147.82980000 ms
Warning: 1 x Draw window and swap: 34.3142 ms, average: 34.31420000 ms
Warning: 1 x Draw window and swap: 14.6350 ms, average: 14.63500000 ms
Warning: 1 x Draw window and swap: 19.6599 ms, average: 19.65990000 ms
Warning: 1 x Draw window and swap: 16.0553 ms, average: 16.05530000 ms
Warning: 1 x Draw window and swap: 39.3483 ms, average: 39.34830000 ms
Warning: 1 x Draw window and swap: 46.1368 ms, average: 46.13680000 ms
Warning: 1 x Draw window and swap: 18.7407 ms, average: 18.74070000 ms
Warning: 1 x Draw window and swap: 18.3160 ms, average: 18.31600000 ms
Warning: 1 x Draw window and swap: 14.9636 ms, average: 14.96360000 ms
Warning: 1 x Draw window and swap: 16.1590 ms, average: 16.15900000 ms
Warning: 1 x Draw window and swap: 23.3629 ms, average: 23.36290000 ms
Warning: 1 x Draw window and swap: 14.6823 ms, average: 14.68230000 ms
Warning: 1 x Draw window and swap: 14.4551 ms, average: 14.45510000 ms
Warning: 1 x Draw window and swap: 18.5328 ms, average: 18.53280000 ms
Warning: 1 x Draw window and swap: 14.9144 ms, average: 14.91440000 ms
Warning: 1 x Draw window and swap: 17.2430 ms, average: 17.24300000 ms
Warning: 1 x Draw window and swap: 15.0463 ms, average: 15.04630000 ms
Warning: 1 x Draw window and swap: 17.4350 ms, average: 17.43500000 ms
Warning: 1 x Draw window and swap: 14.6658 ms, average: 14.66580000 ms
Warning: 1 x Draw window and swap: 20.0314 ms, average: 20.03140000 ms
Warning: 1 x Draw window and swap: 13.2884 ms, average: 13.28840000 ms
Warning: 1 x Draw window and swap: 16.0525 ms, average: 16.05250000 ms
Warning: 1 x Draw window and swap: 16.8390 ms, average: 16.83900000 ms
Warning: 1 x Draw window and swap: 16.7538 ms, average: 16.75380000 ms
Warning: 1 x Draw window and swap: 35.5721 ms, average: 35.57210000 ms
Warning: 1 x Draw window and swap: 48.3455 ms, average: 48.34550000 ms
Warning: 1 x Draw window and swap: 44.4297 ms, average: 44.42970000 ms
Warning: 1 x Draw window and swap: 33.4968 ms, average: 33.49680000 ms
Warning: 1 x Draw window and swap: 19.1798 ms, average: 19.17980000 ms
Warning: 1 x Draw window and swap: 21.0523 ms, average: 21.05230000 ms
Warning: 1 x Draw window and swap: 18.1271 ms, average: 18.12710000 ms
Warning: 1 x Draw window and swap: 14.3320 ms, average: 14.33200000 ms
Warning: 1 x Draw window and swap: 16.6326 ms, average: 16.63260000 ms
Warning: 1 x Draw window and swap: 15.1687 ms, average: 15.16870000 ms
Warning: 1 x Draw window and swap: 16.4329 ms, average: 16.43290000 ms
Warning: 1 x Draw window and swap: 13.7934 ms, average: 13.79340000 ms
Warning: 1 x Draw window and swap: 17.2280 ms, average: 17.22800000 ms
Warning: 1 x Draw window and swap: 15.2359 ms, average: 15.23590000 ms
Warning: 1 x Draw window and swap: 19.5397 ms, average: 19.53970000 ms
Warning: 1 x Draw window and swap: 24.8219 ms, average: 24.82190000 ms
Warning: 1 x Draw window and swap: 13.8564 ms, average: 13.85640000 ms
Warning: 1 x Draw window and swap: 16.6420 ms, average: 16.64200000 ms
Warning: 1 x Draw window and swap: 13.6381 ms, average: 13.63810000 ms
Warning: 1 x Draw window and swap: 18.3760 ms, average: 18.37600000 ms
Warning: 1 x Draw window and swap: 14.1370 ms, average: 14.13700000 ms
Warning: 1 x Draw window and swap: 18.9998 ms, average: 18.99980000 ms
Warning: 1 x Draw window and swap: 13.7115 ms, average: 13.71150000 ms
Warning: 1 x Draw window and swap: 16.8631 ms, average: 16.86310000 ms
Finished in 2.66s

Separating body, clothes, hair, hitboxes and shadowcast, then removing duplicate materials...
Moving duplicate material cf_m_tooth in slot 5 to the original slot 0
Moving duplicate material Bonelyfans in slot 22 to the original slot 2
Moving duplicate material cf_m_namida_00 in slot 10 to the original slot 9
Moving duplicate material cf_m_namida_00 in slot 11 to the original slot 9
Moving duplicate material cf_m_sirome_00 in slot 13 to the original slot 12
Moving duplicate material cf_m_tang in slot 23 to the original slot 19
Info: Removed 6 slots
Warning:        Somehow found a false duplicate material but didn't merge: o_hit_armL_M.001
Warning:        Somehow found a false duplicate material but didn't merge: o_hit_armR_M.001
Warning:        Somehow found a false duplicate material but didn't merge: o_hit_footL_M.001
Warning:        Somehow found a false duplicate material but didn't merge: o_hit_footR_M.001
Warning:        Somehow found a false duplicate material but didn't merge: o_hit_handL_M.001
Warning:        Somehow found a false duplicate material but didn't merge: o_hit_handR_M.001
Warning:        Somehow found a false duplicate material but didn't merge: o_hit_hara_M.001
Warning:        Somehow found a false duplicate material but didn't merge: o_hit_haraB_M.001
Warning:        Somehow found a false duplicate material but didn't merge: o_hit_haraUnder_M.001
Warning:        Somehow found a false duplicate material but didn't merge: o_hit_kneeBL_M.001
Warning:        Somehow found a false duplicate material but didn't merge: o_hit_kneeBR_M.001
Warning:        Somehow found a false duplicate material but didn't merge: o_hit_kneeL_M.001
Warning:        Somehow found a false duplicate material but didn't merge: o_hit_kneeR_M.001
Warning:        Somehow found a false duplicate material but didn't merge: o_hit_kokan_M.001
Warning:        Somehow found a false duplicate material but didn't merge: o_hit_legBL_M.001
Warning:        Somehow found a false duplicate material but didn't merge: o_hit_legBR_M.001
Warning:        Somehow found a false duplicate material but didn't merge: o_hit_legL_M.001
Warning:        Somehow found a false duplicate material but didn't merge: o_hit_legR_M.001
Warning:        Somehow found a false duplicate material but didn't merge: o_hit_mune_M.001
Warning:        Somehow found a false duplicate material but didn't merge: o_hit_muneB_M.001
Warning:        Somehow found a false duplicate material but didn't merge: o_hit_siriL_M.001
Warning:        Somehow found a false duplicate material but didn't merge: o_hit_siriR_M.001
Warning:        Somehow found a false duplicate material but didn't merge: cf_O_face_atari_M.001
Warning:        Material wasn't found when separating materials: cf_m_ahoge04 3581
Warning:        Material wasn't found when separating materials: cf_m_ahoge04 3641
Warning:        Material wasn't found when separating materials: cf_m_ahoge04 3324
Warning:        Material wasn't found when separating materials: cf_m_ahoge04 3384
Error: Nothing selected

Error:          Unknown python error occurred
Traceback (most recent call last):
  File "C:\Users\Windows10\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\KK-Blender-Porter-Pack-master\importing\separatebody.py", line 610, in execute
    separate_everything(context)
  File "C:\Users\Windows10\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\KK-Blender-Porter-Pack-master\importing\separatebody.py", line 142, in separate_everything
    separate_materials(outfit, hair_mat_list)
  File "C:\Users\Windows10\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\KK-Blender-Porter-Pack-master\importing\separatebody.py", line 94, in separate_materials
    bpy.ops.mesh.separate(type='SELECTED')
  File "D:\Steam\steamapps\common\Blender\3.3\scripts\modules\bpy\ops.py", line 113, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Error: Nothing selected

Error: Traceback (most recent call last):
  File "C:\Users\Windows10\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\KK-Blender-Porter-Pack-master\importing\separatebody.py", line 610, in execute
    separate_everything(context)
  File "C:\Users\Windows10\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\KK-Blender-Porter-Pack-master\importing\separatebody.py", line 142, in separate_everything
    separate_materials(outfit, hair_mat_list)
  File "C:\Users\Windows10\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\KK-Blender-Porter-Pack-master\importing\separatebody.py", line 94, in separate_materials
    bpy.ops.mesh.separate(type='SELECTED')
  File "D:\Steam\steamapps\common\Blender\3.3\scripts\modules\bpy\ops.py", line 113, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Error: Nothing selected

Traceback (most recent call last):
  File "C:\Users\Windows10\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\KK-Blender-Porter-Pack-master\importing\importbuttons.py", line 89, in execute
    bpy.ops.kkb.separatebody('INVOKE_DEFAULT'),
  File "D:\Steam\steamapps\common\Blender\3.3\scripts\modules\bpy\ops.py", line 111, in __call__
    ret = _op_call(self.idname_py(), C_dict, kw, C_exec, C_undo)
RuntimeError: Error: Traceback (most recent call last):
  File "C:\Users\Windows10\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\KK-Blender-Porter-Pack-master\importing\separatebody.py", line 610, in execute
    separate_everything(context)
  File "C:\Users\Windows10\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\KK-Blender-Porter-Pack-master\importing\separatebody.py", line 142, in separate_everything
    separate_materials(outfit, hair_mat_list)
  File "C:\Users\Windows10\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\KK-Blender-Porter-Pack-master\importing\separatebody.py", line 94, in separate_materials
    bpy.ops.mesh.separate(type='SELECTED')
  File "D:\Steam\steamapps\common\Blender\3.3\scripts\modules\bpy\ops.py", line 113, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Error: Nothing selected

**Comment by MediaMoots** [comment]
Could you share the card please?

**Comment by Yariiko** [comment]
I've got a similar error when the card has more than the normal amount of outfit slots and I'm exporting from an extra outfit slot. Everything exports but the plugging won't load the texture files to the materials in blender (they do ge exported to the export folder tho', and can be set up manually in blender)

**Comment by Shylike** [comment]
> Could you share the card please?

Mind if I add you through discord? So that I can send you the card because it's my friend private card
