### ISSUE TITLE
Support for Face Alpha Mask

### ISSUE THREAD

**Issue by LegionInstaller** [FlailingFog/KK-Blender-Porter-Pack#288]
Some cards use an Alpha Mask for removing some parts of the Face on average they look like this
![_Export_2022-10-10-23-31-04_cf_m_face_00_AlphaMask](https://user-images.githubusercontent.com/49412050/194956234-2267b210-1c42-455b-9d3a-f1b42c5d290e.png)
Had to be manually exported

**Comment by MediaMoots** [comment]
Could you share the card?

**Comment by LegionInstaller** [comment]
https://drive.google.com/file/d/1Zh212zgMKkCyU5W7kJeX1XKsWsjj_OTM/view?usp=sharing
Best Noticable with last outfit , After Baking I have used the Black stripe on the Alpha mask to remove it on the baked face texture
because the head is otherwise clipping thru the hair
