### ISSUE TITLE
KK-Blender-Porter-Pack-V6.1.1 Error:

### ISSUE THREAD

**Issue by AkagiVoid** [FlailingFog/KK-Blender-Porter-Pack#289]
@MediaMoots 

Uh, Noice error fix but um now the materials are BROKEN AF... X3

Preview:
![image](https://user-images.githubusercontent.com/48104310/195012527-7d7626c9-acc8-4dc5-b973-20b8da8b672f.png)

Material Node preview:
![image](https://user-images.githubusercontent.com/48104310/195012706-98ac81a2-3c9f-472a-a60b-05722b6e207e.png)
Ik now I'm confused about why the plugin can't find the images LUL... ?w?

KK-Blender-Porter-Pack-V6.1.1 ErrorLog (was 2 big 2 image post it):
[KK-Blender-Porter-Pack-V6.1.1_ERRORLOG.txt](https://github.com/FlailingFog/KK-Blender-Porter-Pack/files/9751741/KK-Blender-Porter-Pack-V6.1.1_ERRORLOG.txt)

**Comment by MediaMoots** [comment]
V6 works for me
![image](https://user-images.githubusercontent.com/81146974/195018437-1da3bc96-f1d2-4617-b6cc-8fa71fff9206.png)

**Comment by AkagiVoid** [comment]
> V6 works for me ![image](https://user-images.githubusercontent.com/81146974/195018437-1da3bc96-f1d2-4617-b6cc-8fa71fff9206.png)

**>:/**
What blender version your using (And please make it the detailed version like all the way down to **V#.#.#**, because I'm using 3.3.1 btw)?

And could some mods be effecting the exporter as well?

(Also, when I export in Koikatsu I'm using the "Export Single Outfit" option and nothing else, IDK if dat could be effecting it as well.)

**Comment by MediaMoots** [comment]
Blender 3.3
KK RX 14
KKBP Exporter 3.94
KKBP 6.1.1
Windows 10

Make to export again and use the new files after updating the Exporter Plugin.

**Comment by MediaMoots** [comment]
> (Also, when I export in Koikatsu I'm using the "Export Single Outfit" option and nothing else, IDK if dat could be effecting it as well.)

yeah, I exported with those options.

**Comment by AkagiVoid** [comment]
Welp doing a hard reset atm with blender (wiping and installing 3.3.0), and I just deleted the plugin in Koikatsu 2 make sure I got the latest one installed (overwrite may have failed on it). >w<
And U said RX14 I'm in RX15, IDK if dat matters though?
BRB as I restart PC. :P

**Comment by AkagiVoid** [comment]
Nope materials still broke, even though its an improvement from the last images its still broken. >w>

And it still shows those blue pixelations on the character's MT_TC images (I believe it was baked into the PMX or JSON when it was being exported, because the png images themselves exported just fine) was made as well, and weird light shading going on with the clothing as if it got prebaked in. >:/

It's loading fine with the latest but I still see a crap ton of errors in the logs. TwT
And can't figure out which program is causing the issue. >:/

![image](https://user-images.githubusercontent.com/48104310/195068858-c17fd405-7624-4a01-9623-c358fb6d4bed.png)

ErrorLog for Blender:
[KK-Blender-Porter-Pack-V6.1.1_Errorlog2.txt](https://github.com/FlailingFog/KK-Blender-Porter-Pack/files/9754219/KK-Blender-Porter-Pack-V6.1.1_Errorlog2.txt)
This time I just straight exported everything from Koikatsu, clothes in all. >w>
Then imported it into the blender and wait for 5~8 minutes for it to do its thang. XwX
And still failed to completely get it the way UR looks without having to make any alterations. TwT

Owo I came up with a great idea. :3 Heres the extracted character MediaMoots.
If URs got the same error in Ur blender as me then its my Koikatsu dats broken. X3
https://www103.zippyshare.com/v/EVWdjD6a/file.html

**Comment by MediaMoots** [comment]
Ok, the exporter and plugin all work fine, it's just blender and the shaders that need to be configured.

First Import with these settings:
![image](https://user-images.githubusercontent.com/81146974/195105656-4afcbee0-5b39-4c3c-becf-959926de1876.png)

Then, set the blender view mode and color like so:
![image](https://user-images.githubusercontent.com/81146974/195105223-47cbc84b-a6eb-44d5-a3b6-40a5b3f83d60.png)

Finally, to fix the ears, it's a simple slider in the ear material, set it to 0:
![image](https://user-images.githubusercontent.com/81146974/195105469-98b8b005-7bac-40d9-93b6-a5e76d44cc26.png)

Result:
![image](https://user-images.githubusercontent.com/81146974/195106990-ae87d37c-9145-47bb-acb0-34fc8a5ec713.png)
![image](https://user-images.githubusercontent.com/81146974/195107050-433b53e9-fd4b-4843-9ea8-43913c8e4856.png)
![image](https://user-images.githubusercontent.com/81146974/195107108-ae751954-1a54-41c9-8fd3-44c1929d7753.png)

I suggest playing around with the shader sliders to get the look you want.

**Comment by AkagiVoid** [comment]
Ik, how to get rid of that emblem on the shirt that failed to render transparently (the white square box)?
Because by logic it should render transparently since alpha but its not. >w<

And why do the character's skin and other parts have blue pixelation on it?
I did post a [**ZIP**](https://www103.zippyshare.com/v/EVWdjD6a/file.html) of the extracted character from my own Koikatsu to see if U can test it on your end to see if U get the same results (if you do get that blue pixel effect like me, then that means its Koikatsu and a plugin is interfering with the exporting proccess).

**Comment by MediaMoots** [comment]
For your files I did the exact same as https://github.com/FlailingFog/KK-Blender-Porter-Pack/issues/289#issuecomment-1274707248

Result:
![image](https://user-images.githubusercontent.com/81146974/195231258-c528f635-fc25-4000-a07b-9ce2eee9d835.png)

For the emblem just go into edit mode and select the material verts then delete them.
https://youtu.be/JSdggnGtcmU?t=425
![image](https://user-images.githubusercontent.com/81146974/195232815-93fbe785-1fc1-4fc6-9745-3b9b0ba3bdd4.png)
![image](https://user-images.githubusercontent.com/81146974/195232834-534cd3ed-5e8c-465e-866b-6156bc91d77a.png)

**Comment by AkagiVoid** [comment]
> For your files I did the exact same as [#289 (comment)](https://github.com/FlailingFog/KK-Blender-Porter-Pack/issues/289#issuecomment-1274707248)
> For the emblem just go into edit mode and select the material verts then delete them. https://youtu.be/JSdggnGtcmU?t=425

Thank you for taking the time to check and run my character file. >w<

So got any clue as to why I'm getting those blue pixelations when I import using UR method above (i still getting the blue pixelation on the model, I can manually fix it by reimporting the texture of all the "MT_CT" images, and the images themselves exported just fine. >:/ Its the last MAJOR BUG dats still plaguing my model in Blender. TwT

**Comment by MoriMorinya** [comment]
> So got any clue as to why I'm getting those blue pixelations when I import using UR method above (i still getting the blue pixelation on the model, I can manually fix it by reimporting the texture of all the "MT_CT" images, and the images themselves exported just fine. >:/ Its the last MAJOR BUG dats still plaguing my model in Blender. TwT

You don't have to reimport the textures, just switch the texture's color space off sRGB and back again to fix it.

I have had this issue before but it stopped(?) by itself, I think Blender gets confused about the color space of the texture for some reason and causes it to convert the colors on the textures incorrectly.

**Comment by AkagiVoid** [comment]
> MoriMorinya: You don't have to reimport the textures, just switch the texture's color space off sRGB and back again to fix it.
> 
> I have had this issue before but it stopped(?) by itself, I think Blender gets confused about the color space of the texture for some reason and causes it to convert the colors on the textures incorrectly.

How do I do dat exactly? (Is still a Blender Newbie here). X3

>MediaMoots: For the emblem just go into edit mode and select the material verts then delete them. https://youtu.be/JSdggnGtcmU?t=425 ![image](https://user-images.githubusercontent.com/81146974/195232815-93fbe785-1fc1-4fc6-9745-3b9b0ba3bdd4.png) ![image](https://user-images.githubusercontent.com/81146974/195232834-534cd3ed-5e8c-465e-866b-6156bc91d77a.png)

Um dat failed... X3 I'm using Blender 3.3.0, and followed Ur instructions to the T. >w>
The result is dat nothing gets highlighted (And yes I'm in edit model mode btw) when I press select.

And when I manually hunt it down like:
![image](https://user-images.githubusercontent.com/48104310/196253087-6cf33328-1b11-4d4b-9ea1-82a1e37d74cc.png)
Dis happens:
![image](https://user-images.githubusercontent.com/48104310/196253174-1793f8e5-0123-42be-b05d-a0f6379e8a1c.png)
