### ISSUE TITLE
CATS MMD issues?

### ISSUE THREAD

**Issue by PastelMoonx** [FlailingFog/KK-Blender-Porter-Pack#290]
I’m having endless errors with every versions of everything so far. It’s really frustrating. I have Koikatsu Party with the latest HF patch and the KK Manager and all that stuff. I was able to export and set up a model 99% properly only once; the same day I installed everything. 2 days of not touching anything later, whenever I try to export any model (even the one that previously worked) it gives me errors on blender and it refuses to do anything I click. Doesn’t prepare, doesn’t rig, doesn’t bake, nothing. It loads the models in, all white and nothing more. I’ve had this issue consistently with any blender versions (2.92, 3.3, 3.0), and same with the exporter plugin and importer plugin. Have everything on the latest versions doesn’t work, have everything on earlier versions doesn’t work. I’m at a loss of what to do. 

The only time it finally “worked” today was by having the exporter in game be on the previous version, and the blender plugin on the latest version. But of course, it exports fine and then it refuses to use the Rigify option I give it. It says be sure your rigify addon is on, and once I make sure it’s on it starts giving me random fake bone errors. I say fake because click once and it says “this model doesn’t have L Eye” then click again “this model doesn’t have Hips” etc. The bones ARE there cause I do see them when I click on the armature. It’s just an utter mess of a rig. Then I can’t even click on the “prepare” button for VRM or VRCHAT because it outright refuses to by giving me errors. It only works if I click FBX but what’s the point if the armature/rig is a complete chaotic mess that I have 0 idea how to fix because if I try to use CATS then it destroys the model. If I try to export the model as is with a crappy armature but baked and prepared textures and atlases, as fbx, and then port back again into blender to try and correct anything, the model loads into blender looking even worse rig wise and textures wise or even missing the hair entirely suddenly. 

Could I get a genuine solution for this and something that will work 100% ? A good guide that also explains how to correctly set up the model to be ready for vrchat while keeping all its’ blendshapes and visemes and have no rig issue and also be able to be ported back into blender whenever as fbx and NOT have new issues arise randomly. Act like a proper model and just open up as normal. (Followed the videos linked in github but honestly they don’t help in depth. They don’t explain why the model becomes broken texture wise when imported back into blender once set up and everything as fbx)

I genuinely want to learn this and perfect it so I can export any model and make them work fully on vrchat just as any other usual fbx/pmx model does. But damn this has been an absolute headache the past few days trying to understand why the plugins just refuse to properly do the tasks and the countless blender error popups. 

Lengthy post but I really want to get this fixed up for good and learn the process properly.

**Comment by AkagiVoid** [comment]
@PastelMoonx Did u see my posts on #289 ?w?
Because dat may help you 2 sum degree. ^w^

**Comment by PastelMoonx** [comment]
> @PastelMoonx Did u see my posts on #289 ?w? Because dat may help you 2 sum degree. ^w^
> 
> O and sum of the mods in BepInEx may be interfering with export process (although dis is confirmed yet).

I did see the posts and I’ve tried every versions of the plugins and blender combined and nothing really truly fixes it, so nope. I also don’t have mods beyond the ones that came with the HF Patch / KK Manager stuff. I didn’t download anything new after the first model having worked either, so it can’t be mods related. Really sucks trying to troubleshoot this.

**Comment by KonokoMai** [comment]
1.- **To avoid the `white model` no textures.**
Try importing the .pmx using the kkbp pluggin DIRECTLY from the original exported Folder (The one inside \Export_PMX\XXXXXXXXXXX-Character Name) If I copy this folder to another location and import the model I had that same problem, so probably is a absolute/relative texture location).

2.- After you import your model DONT MODIFY the armature on anyway, DONT USE Cat's tools like FIXing model and stuff like that (the Armature generated by KKBP is not compatible with the standard MMD that Cats expects. 
But you can Use safe tools like separate by material, join meshes, decimation. Basically anything not bone related.

3.- When you are done editing your meshes, removing, adding some new, etc. 
Choose your Export Target (VRM, VRchat or General FBX)
Choose your Armature Optimization (Very Simple, Simple or Original) 
          --Very Simple provides with a pretty easy to understand Armature, Basic bones, Some dinamics, some Cloth bones, but no collisions. (You can add it later manually). This targes is around 100 bones. I recommend this one.
          --Simple is more caothic, because you have the collision bones, skin bones, etc. Is around 1000 bones.
          --Original: Is............ T_T Im dead inside.
          
Select the PREP for Target aplication (Vrm, VRchat or General FBX), and run the prep.

4.- Now you can work with your armature adding new bones, renaming it, remove things etc.

5.- Now you can generate the final textures/Atlas.
             -Select the type of Textures you want (Light, Dark, Normals)
            - Choose Bake material templates. (This is the Folder where the textures gonna be stored and you need to choose it later for Switching Atlas Type)
             -By default Light Textures is the one active
             -Go to Material Combiner, select what  things you want on the atlas and the Material you want for that.
                         For example I can choose my body parts and select material 1, and my hair with material 2. (So then I had 2 materials linked to the same atlas for use with diferent shaders). 
             -Click the Save Atlas button (With this you obtain a Light Atlas and set you meshes for a material)
                         If you want a extra Dark Atlas or Normal Atlas. 
                                   --- Then UNDO your last step with Control+Z (so your meshes return to they original materials). 
                                   --- Return to your KKBP tab, chose the Dark or Normal Textures on the Atlas Type thing and push the 
                                        SWITCH baked templates (You need to select the folder on that you bake your textures).
                                   --- Go to Material combiner and do the same of the previous step. (If you want a extra atlas repeat the same steps, Cntl+Z, switch type, material combiner, etc.
 
 6.- Now you have some Atlas and your meshes assingned to a Material.
 7.- Click Export and have fun. (On unity you need to copy the FBX and the Atlas files so you can assing it to the materials).
 
 Cats is great for not Armature related things if you try to use something that requires the armature it gonna explode in errors and mess your model.

**Comment by PastelMoonx** [comment]
> 1.- **To avoid the `white model` no textures.** Try importing the .pmx using the kkbp pluggin DIRECTLY from the original exported Folder (The one inside \Export_PMX\XXXXXXXXXXX-Character Name) If I copy this folder to another location and import the model I had that same problem, so probably is a absolute/relative texture location).
> 
> 2.- After you import your model DONT MODIFY the armature on anyway, DONT USE Cat's tools like FIXing model and stuff like that (the Armature generated by KKBP is not compatible with the standard MMD that Cats expects. But you can Use safe tools like separate by material, join meshes, decimation. Basically anything not bone related.
> 
> 3.- When you are done editing your meshes, removing, adding some new, etc. Choose your Export Target (VRM, VRchat or General FBX) Choose your Armature Optimization (Very Simple, Simple or Original) --Very Simple provides with a pretty easy to understand Armature, Basic bones, Some dinamics, some Cloth bones, but no collisions. (You can add it later manually). This targes is around 100 bones. I recommend this one. --Simple is more caothic, because you have the collision bones, skin bones, etc. Is around 1000 bones. --Original: Is............ T_T Im dead inside.
> 
> Select the PREP for Target aplication (Vrm, VRchat or General FBX), and run the prep.
> 
> 4.- Now you can work with your armature adding new bones, renaming it, remove things etc.
> 
> 5.- Now you can generate the final textures/Atlas. -Select the type of Textures you want (Light, Dark, Normals) - Choose Bake material templates. (This is the Folder where the textures gonna be stored and you need to choose it later for Switching Atlas Type) -By default Light Textures is the one active -Go to Material Combiner, select what things you want on the atlas and the Material you want for that. For example I can choose my body parts and select material 1, and my hair with material 2. (So then I had 2 materials linked to the same atlas for use with diferent shaders). -Click the Save Atlas button (With this you obtain a Light Atlas and set you meshes for a material) If you want a extra Dark Atlas or Normal Atlas. --- Then UNDO your last step with Control+Z (so your meshes return to they original materials). --- Return to your KKBP tab, chose the Dark or Normal Textures on the Atlas Type thing and push the SWITCH baked templates (You need to select the folder on that you bake your textures). --- Go to Material combiner and do the same of the previous step. (If you want a extra atlas repeat the same steps, Cntl+Z, switch type, material combiner, etc.
> 
> 6.- Now you have some Atlas and your meshes assingned to a Material. 7.- Click Export and have fun. (On unity you need to copy the FBX and the Atlas files so you can assing it to the materials).
> 
> Cats is great for not Armature related things if you try to use something that requires the armature it gonna explode in errors and mess your model.

Thanks for the lengthy guide. I want to point out I don't use CATS fix, it's just I've tried to resort to it AFTER seeing the model was still a mess armature wise because nothing else seemed to fix it, and of course CATS just makes it worse. The thing is if I export the newly made FBX (even if everything goes well), the armature is still not 100% approved by Unity/VRChat and it tells me it has pelvis issues, which is easy to fix but if I put that newly made FBX file into blender, the model now looks broken textures wise and the armature sometimes looks even worse suddenly. This is what confuses me most because if I directly put that FBX on unity I just can't correct the rig properly since reimporting it back to Blender just seems to break it non stop (even without using CATS when importing).

I just tried your suggestion of putting the plugin inside the export folder, and that finally does load the model + textures. (I reinstalled the latest blender plugin and exporter) - Next issue is that I used Rigify for my last model that DID work a few days ago; I used it because without rigify I had tons of bone issues and the fingers looked broken on vrchat and such. Once I used rigify it had corrected it although there was still a pelvis issue. Now, the rigify option completely kills the "Prep For Target Application" button no matter what I put. So I reimported the model with KKBP armature instead of Rigify and now the Prepping works. Thing is, I'm afraid it's going to give a crappy armature that won't be performing well on vrchat again. I am currently prepping the model and I will see if there's broken fingers and such once everything is done and update this thread on what the results are.

**Comment by AkagiVoid** [comment]
Well to better help with your problem U can try giving mar details like the example would be wat I did in #287 .
Which is an open blender.
Try loading in UR exported model.
And after it loads and U see sumthin not r8t is to go to:
![image](https://user-images.githubusercontent.com/48104310/195245809-eeec90dd-da99-42eb-b1ef-c7943b220160.png)

Then highlight and copy everything in the log to a txt file and either zip it up or just drop txt file r8t into dis comment 2 be uploaded for someone who how to read the errors and present a solution to the problem. ^w^
![image](https://user-images.githubusercontent.com/48104310/195246408-18fbbbfd-ed5d-4679-9951-64c31f8460f4.png)

**Note:**
U did watch the [tutorial video playlist](https://www.youtube.com/playlist?list=PLhiuav2SCuvc-wbexi2vwSnVHnZFwkYNP) r8t?
U must do exactly as he did and pay attention to what he did, for example:

> After the character exporter gets done you should drag and drop your exported character folder from "Export_PMX" to your desktop or to Ur "C:\" for path shortening. The reason is that when Blender tries to pull from somewhere like "E:\Koikatsu BetterRepack RX15\Export_PMX\(Character folder name)" the path could be to LONG and force blender to skip because it is taking to long to find the image and load it.

Dat was my first issue believe it or not. X3

**Comment by PastelMoonx** [comment]
Alright so, I prepped everything. The baking didn't want to work so I did the dragging to desktop trick and it worked, now the issue is CATS refuses to apply the blendshapes for the eye tracking and blinking. Visemes worked just fine. I merged all the meshes together and renamed it to Body but I keep getting this same error no matter what so not sure what to do now.

Error: https://imgur.com/czKzgHo.jpg

**Comment by AkagiVoid** [comment]
> Alright so, I prepped everything. The baking didn't want to work so I did the dragging to desktop trick and it worked, now the issue is CATS refuses to apply the blendshapes for the eye tracking and blinking. Visemes worked just fine. I merged all the meshes together and renamed it to Body but I keep getting this same error no matter what so not sure what to do now.

Maybe try dis:
[#issuecomment-1274707248](https://github.com/FlailingFog/KK-Blender-Porter-Pack/issues/289#issuecomment-1274707248)

**Comment by AkagiVoid** [comment]
> Importing the model into blender the way they had their settings as worked for me to be able to have a rig and have the preparation button function, but the blendshapes eyes error with CATS is unrelated pretty sure. The thing is I did join the eye meshes into the body one and yet CATS keeps giving me the error I screenshotted in my previous post. Trying to find guides on this specific blendshape error is a bit difficult but I've been trying to for the past hour now.

Well, sawry 2 say dis but dats as far as I can go for helping U because IDK on the error Ur getting since mine don't seem 2 produce it. X3
![azur-lane-gaming](https://user-images.githubusercontent.com/48104310/195261928-970c4486-08de-4417-888e-3674f8b9ad77.gif)

**Comment by PastelMoonx** [comment]
> > Importing the model into blender the way they had their settings as worked for me to be able to have a rig and have the preparation button function, but the blendshapes eyes error with CATS is unrelated pretty sure. The thing is I did join the eye meshes into the body one and yet CATS keeps giving me the error I screenshotted in my previous post. Trying to find guides on this specific blendshape error is a bit difficult but I've been trying to for the past hour now.
> 
> Well, sawry 2 say dis but dats as far as I can go for helping U because IDK on the error Ur getting since mine don't seem 2 produce it. X3 ![azur-lane-gaming](https://user-images.githubusercontent.com/48104310/195261928-970c4486-08de-4417-888e-3674f8b9ad77.gif) [ ![azur-lane-gaming](https://user-images.githubusercontent.com/48104310/195261928-970c4486-08de-4417-888e-3674f8b9ad77.gif) ](https://user-images.githubusercontent.com/48104310/195261928-970c4486-08de-4417-888e-3674f8b9ad77.gif) [ ](https://user-images.githubusercontent.com/48104310/195261928-970c4486-08de-4417-888e-3674f8b9ad77.gif)
> 
> The last thing U can try is dis [MMD tool](https://github.com/UuuNyaa/blender_mmd_tools/releases) (Disable or RECOMMENDED of removing CATS be4 installing dis plugin).

Hey it's fine! You still helped me for the baking method by reminding me that dragging the folder to desktop was a better thing for blender to process, so thank you for that. :)
Hope you get your issues sorted out too!

**Comment by AkagiVoid** [comment]
> Hey it's fine! You still helped me for the baking method by reminding me that dragging the folder to desktop was a better thing for blender to process, so thank you for that. :) Hope you get your issues sorted out too!

I my issue is almost fixed just one tiny ITY BITY problem...

Ik, its a HUGE MAJOR BUG and IDK why, but is trying to confirm which plugin for the Bepinex mod is responsible for it (if any at all) or is my PC hardware so BROKEN that it creates dis weird (BEEP) bug dat been driving me and maybe Contributor MediaMoots UP THE WALL. TwT
And the bug I'm refering to is dis one:
![image](https://user-images.githubusercontent.com/48104310/195073958-25b1e5ff-bcb8-4cd2-8795-28aaf1f3ea30.png)

**Comment by PastelMoonx** [comment]
> > Hey it's fine! You still helped me for the baking method by reminding me that dragging the folder to desktop was a better thing for blender to process, so thank you for that. :) Hope you get your issues sorted out too!
> 
> I my issue is almost fixed just one tiny ITY BITY problem...
> 
> Ik, its a HUGE MAJOR BUG and IDK why, but is trying to confirm which plugin for the Bepinex mod is responsible for it (if any at all) or is my PC hardware so BROKEN that it creates dis weird (BEEP) bug dat been driving me and maybe Contributor MediaMoots UP THE WALL. TwT And the bug I'm refering to is dis the blue pixelation one in [#issuecomment-1274508703](https://github.com/FlailingFog/KK-Blender-Porter-Pack/issues/289#issuecomment-1274508703). TwT
> 
> Anyway gonna log off now. X3 And I do suggest U look at the MMD tool link I provided above dat was taken from Tutorial Video list, credits Koikatsu Blendlet for sharing and UuuNyaa for making it. ^w^

Not sure what's causing the blue pixels on your materials, I haven't experienced that so far. But yeah I'm having issues with the blendshapes not wanting to be created and also atlasing because whenever I do it, they either duplicate themselves and turn the model entirely beige, or they will turn it entirely white. And if I look at the png of the atlas saved, it's just a black and white square. Not sure what's causing this either, but CATS is quite the annoying plugin. I will check out that MMD tool and hopefully it can help me fix these issues.
