### ISSUE TITLE
Separate Eye shape keys into Left and Right so it's easier to make the ARKit shape keys

### ISSUE THREAD

**Issue by Yariiko** [FlailingFog/KK-Blender-Porter-Pack#291]
Not super sure how feasible this is, but the idea is simple. Most of the ARKit blendshapes are "doable" tweaking the current shape keys manually and mixing them to produce the desired shape key. Problem is that currently, most eye shape keys control both eyes, so making the first 14 blendshapes (that control each eye separately) is a bit complicated unless you do a bunch of stuff manually. 

These are the arkit blendshapes (they're 52)
https://developer.apple.com/documentation/arkit/arfaceanchor/blendshapelocation

Someone else has been trying to do this in the CATS discord server, but I'm unsure if they're applying the idea to koikatsu models. I'll do more research and post my findings here. They made a script to generate the shape keys in blender, haven't tested it myself yet, here's the link to it "https://raw.githubusercontent.com/Mysteryem/Miscellaneous/master/unity/scripts/editor/VRMBlendShapeTools.cs" 

Found another plugin that supposedly helps in making these shape keys but haven't tested it yet (gotta buy it first lol, here's the link https://www.blendermarket.com/products/faceit in case you're curiuous)

This will make facetracking look way more realistic. Currently it works, but it can look a bit blocky/stiff.

**Comment by FlailingFog** [comment]
This should be pretty easy if you define left and right side vertex groups. You can set the left or right vertex group, then use the "new shape from mix" operator in the shapekeys menu to generate left and right eye shapekeys


https://user-images.githubusercontent.com/65811931/196051033-35ed6664-45b2-4a6f-84bd-e4c19e83967c.mp4

**Comment by Yariiko** [comment]
Thanks a lot! I'll check how this works and post my findings.

Tried the faceit plugin and it works pretty well, tho' it has issues with the eyes because of how the whole face is built in koikatsu.

**Comment by MediaMoots** [comment]
DId it work?
