### ISSUE TITLE
Allow for saturation to be applied when body maintex is being used

### ISSUE THREAD

**Issue by BTHP5** [FlailingFog/KK-Blender-Porter-Pack#296]
For this character, I edited the maintex of the body. While the addon allows for the maintex to be used instead, it ends up being very desaturated because of how KK uses textures.

![image](https://user-images.githubusercontent.com/54001645/195902206-5f35575a-d16f-409a-8987-a178b76b90e3.png)

I think in the future, that being able to apply the same saturation to the textures would be very helpful to someone who also did this, or needed to use the maintex instead for anything else :)

But if someone has a workaround right now, feel free to let me know!

**Comment by BTHP5** [comment]
Also yea i realised that I shoulda made an overlay instead of editing the maintex, but we learn :]

**Comment by BTHP5** [comment]
ok so i tried using a body overlay and it doesnt show up on the exported model :P

**Comment by FlailingFog** [comment]
There's a KKBP tab in the image editor that lets you saturate the currently opened image
![image](https://user-images.githubusercontent.com/65811931/196050457-6fd358aa-e5be-4073-b6b8-ef1992a5ac16.png)

**Comment by BTHP5** [comment]
Omg fr!? Thank you sm!! <3 You guys really are geniuses <3
