### ISSUE TITLE
Problem with Eyes being wider in Blender than they are in-game.

### ISSUE THREAD

**Issue by PastelMoonx** [FlailingFog/KK-Blender-Porter-Pack#297]
For some models, when imported into blender, their eyes are widened compared to how they look like in-game. How do I fix this? I tried multiple times with settings from the game but that didn't change anything so I'm assuming it's something I have to do inside blender itself.

In-game eyes:
![image](https://user-images.githubusercontent.com/115578885/196460959-ad1677c6-2ed6-4e95-8639-73f1ddd40e70.png)

Blender eyes:
![image](https://user-images.githubusercontent.com/115578885/196461191-8711854f-29ce-4426-9fd8-bc70d8aa1da1.png)

**Comment by MediaMoots** [comment]
Please see this https://github.com/FlailingFog/KK-Blender-Porter-Pack/issues/265#issuecomment-1257202956

**Comment by MediaMoots** [comment]
Maybe in the future we can make it automatic, but for now, it needs to be set manually.
Sorry about that.

**Comment by PastelMoonx** [comment]
Thank you!
