### ISSUE TITLE
Export characters with shapekeys applied

### ISSUE THREAD

**Issue by PastelMoonx** [FlailingFog/KK-Blender-Porter-Pack#298]
I've noticed one of the models I imported to blender came with weight paint on her dress already. But 2 others I've tried did not have any weight paint. Am I doing something wrong or is it something that depends on the model? (I disabled the fix body seams)

@MediaMoots also, about the shapekeys for widened eyes, could you link me a guide or something on how to do it properly? I thought I had it working but it's messing with my visemes for some reason and I'm not finding the proper way of doing it. Thanks!

**Comment by MediaMoots** [comment]
> shapekeys for widened eyes, could you link me a guide or something on how to do it properly?

Hmm, in the code (FaceBlendShape.cs):
![image](https://user-images.githubusercontent.com/81146974/208232027-cd86245c-316a-47df-b37b-1b1f3713571b.png)

These values are used here:
![image](https://user-images.githubusercontent.com/81146974/208232041-6c32b431-bd83-470a-8ace-29b2d309680f.png)

So, when the character looks to the side the eyes close by `EyeLookSideCorrect` amount.
When looking forward, the eyes are opened to about 0.9 minus the Eye Openness value
![image](https://user-images.githubusercontent.com/81146974/208232098-f0c1f161-b5fb-49f2-928d-2d63938dfd6e.png)
