### ISSUE TITLE
Error exporting to blender model

### ISSUE THREAD

**Issue by doANIYA** [FlailingFog/KK-Blender-Porter-Pack#299]
export to blender, only the human body model is exported. The hair and clothes are missing, and the material has some errors

**Comment by doANIYA** [comment]
![E(YP EN59AFRP33GE7YQ5HG](https://user-images.githubusercontent.com/116534720/197441855-bc59d5d8-bb91-4556-8aa4-27141ce3e9c7.jpg)

**Comment by MediaMoots** [comment]
Could you share the card please?

**Comment by MediaMoots** [comment]
Sorry I meant the Character Card from koikatsu.
