### ISSUE TITLE
Eyelashes deform when exported to blender, and eyes are also not the correct size.

### ISSUE THREAD

**Issue by BTHP5** [FlailingFog/KK-Blender-Porter-Pack#301]
Heyo! I'm using the latest versions of everything, and the exporter usually works just fine!
However, I'm currently exporting a model for someone, and the eyelashes deform when the eyes close, as well as the eyes are the wrong size. Either that, or the eyelids aren't closed as much as they should be.

![image](https://user-images.githubusercontent.com/54001645/197797651-1a8d8b16-e07b-454c-ac13-0d4bea85be42.png)
![image](https://user-images.githubusercontent.com/54001645/197798157-0cb20dc7-ec69-49f7-9fad-a6b3d77dbfcc.png)
![image](https://user-images.githubusercontent.com/54001645/197798236-a4ae24c1-eb3f-4d26-be37-b27517ebcd41.png)

The card:
https://drive.google.com/file/d/1Q_o7xcd9Tj8aAW1Wqr3_jW6MUBhpO7KM/view

**Comment by MoriMorinya** [comment]
looks like modified headmod is broken, I had the same issue until I switched off to another face type

**Comment by BTHP5** [comment]
Yeah..it seems to be that any face type other than the regular one causes this problem, I hope it's fixed soon
