### ISSUE TITLE
Help With Collared Shirts In Blender

### ISSUE THREAD

**Issue by PastelMoonx** [FlailingFog/KK-Blender-Porter-Pack#306]
Every single model that has a collared shirt of any kind, (inner shirts from when you choose blazers/jackets), disappear in blender and there is NO way of making them appear. I don't know if it's a major glitch or there's a trick to make it work but it's really annoying. Removing body transparency doesn't bring back the shirt and the shirt itself shows no transparency enabled in the options on blender. What do I have to do?

This is what it's supposed to look like:
![image](https://user-images.githubusercontent.com/115578885/200147716-5d0cfb52-a2e9-44a2-b618-1f69c52162ae.png)

How it looks in Blender:
![image](https://user-images.githubusercontent.com/115578885/200147721-4f01e8f4-4afa-4b97-989f-9d84b02fea4b.png)

The materials on Blender that show up:
![image](https://user-images.githubusercontent.com/115578885/200147724-58b59ec9-2fed-401b-ba42-82a00b3498a4.png)

As you can see "inner_top" does not appear anywhere in blender and that's usually how inner shirts with collars are called. No matter the model I can never seen to load them in blender. What to do?

**Comment by poisenbery** [comment]
https://github.com/FlailingFog/KK-Blender-Porter-Pack/pull/138#issuecomment-1188381193

Check this

**Comment by PastelMoonx** [comment]
> [#138 (comment)](https://github.com/FlailingFog/KK-Blender-Porter-Pack/pull/138#issuecomment-1188381193)
> 
> Check this

Thanks but can you give me steps on how to do this? I tried it out but have no idea what file I need to open specifically or how to do any of this within the program shown. I tried to look at the thread's other replies but it's pretty confusing.

**Comment by poisenbery** [comment]
I'm unable to reproduce the problem as you described it.
![Screenshot (1044)](https://user-images.githubusercontent.com/78466408/200459092-ea6dde18-6dcd-482f-be80-cc24657bcd1d.png)

**Comment by PastelMoonx** [comment]
It just happens to every model I try to export. But I haven't done the method you previously linked because I have no idea how to use the SB3 program nor do I know what files I have to upload on it to have the options of the clothes and mark them as readable. That's why I asked for a guide on how to do it/what to do so I can mark them as readable?

**Comment by MediaMoots** [comment]
Please share the card?

**Comment by poisenbery** [comment]
@PastelMoonx I actually never changed the settings on those particular files. I THOUGHT the issues were related because of how similar the described conditions were, but the fact that I can export the tops shows that they're actually not related issues.

May I ask why you chose to not share any cards that demonstrate the problem? If we can't reproduce the issue as you described, it's impossible to troubleshoot from our end.

**Comment by PastelMoonx** [comment]
I see. And well I was waiting for your response on a guide on how to do the enable thing since I thought that was the solution + I hadn't checked this in a day. Here's the card, but again, this happens on every model that has this sort of clothing. This is just one of them. Choose the outfit with the green jacket and pink shirt.

![image](https://user-images.githubusercontent.com/115578885/200857579-8fa09eac-474f-40dc-b33e-82831a1af524.png)

I have 0 issue with anything else, so not sure at all what's going on and it's always happened ever since I got koikatsu for exporting models.

**Comment by PastelMoonx** [comment]
Any update?

**Comment by MediaMoots** [comment]
Using:
KK RX14 
Blender 3.3 
Latest KKBP

Result:
![image](https://user-images.githubusercontent.com/81146974/208231891-604acc96-e5a2-4f60-9b02-03099f8173fb.png)

Also, the card you shared didn't load in KK for me, I went to bepis to find the same card.

Card (From bepis): 
![KK_166622](https://user-images.githubusercontent.com/81146974/208231885-35836c19-2894-4acc-a222-5b3b082335b9.png)

**Comment by PastelMoonx** [comment]
I might be missing that KK RX14, not sure. I found the page with all the downloads for each version, but not sure which one I even have nor where I would find mine and put the new one in. Could you let me know? Thanks!

**Comment by MediaMoots** [comment]
Umm, I'm not sure if I can share software on here...

but

Use da google:
BetterRepack RX16

the link with sukebei
