### ISSUE TITLE
Big Issues

### ISSUE THREAD

**Issue by HugglesGamerGirl** [FlailingFog/KK-Blender-Porter-Pack#312]
I feel like when i use this tool i play the lottery with the 50% chance the model will properly export i had issues where a certain accessory will mess up the entire exporting process (for example sally's nose) i even had issues where things was wrongly scaled 

this time i want to bring up an issue that happened with 2 of my recent exports (my SCP-3008-2 will be used as an example) 

here in the first image, we can see what the model looks like in-game 
![Screenshot 2022-11-22 080719](https://user-images.githubusercontent.com/118823112/203323046-f37880ff-943e-4e05-bea5-a41d3667786a.png)
and now here's what happens when the model is exported and imported into blender 
![Screenshot 2022-11-22 081743](https://user-images.githubusercontent.com/118823112/203324122-2c30c18e-9c04-47f0-b0da-8e863f9efcec.png)
![Screenshot 2022-11-22 081727](https://user-images.githubusercontent.com/118823112/203324124-64803f0a-0ca1-439d-b865-8294fa639ed0.png)
i have no idea how to fix this issue i have tried removing the clothes, accessories and even head mods to see if this would change something but no results
pls help

**Comment by MediaMoots** [comment]
Could you share the card please? Thank you!

**Comment by HugglesGamerGirl** [comment]
> 

here you go 
![Koikatu_F_20221121172935270_SCP-3008-2](https://user-images.githubusercontent.com/118823112/203337370-3aabd273-6807-4080-a83f-19897ac7d325.png)

**Comment by HugglesGamerGirl** [comment]
> Could you share the card please? Thank you!



> Could you share the card please? Thank you!

Here you go, idk how github works so i putted the card in dropbox for good measure https://www.dropbox.com/s/drwrtuy2rbr0qto/Koikatu_F_20221121172935270_SCP-3008-2.png?dl=0

**Comment by MediaMoots** [comment]
@HugglesGamerGirl 
Thank you!

Please try out PR #313 and import with these settings:
![image](https://user-images.githubusercontent.com/81146974/203354763-4fd41506-6838-48ee-b745-d2257da27eb5.png)

**Comment by MediaMoots** [comment]
result
![image](https://user-images.githubusercontent.com/81146974/203355331-ffe7e4e4-e580-4525-b5ac-ca7af9a7ab5f.png)

**Comment by HugglesGamerGirl** [comment]
> result ![image](https://user-images.githubusercontent.com/81146974/203355331-ffe7e4e4-e580-4525-b5ac-ca7af9a7ab5f.png)

THANK YOU SO MUCH !!! IT WORKED!!!
