### ISSUE TITLE
Leg IK doesn't bend properly.

### ISSUE THREAD

**Issue by VyzeTV** [FlailingFog/KK-Blender-Porter-Pack#316]
Hi, I'm starting to have an issue I never had before, whenever importing the model onto Blender, some cards seem to have a broken leg IK, where the foot seems to move just fine but the knees just don't bend at all, this seems to be caused by only some footwear models which I can just fix by changing the footwear to something else, but sometimes it seems to be linked to the body of the model itself and I have no idea what to do to fix that, really would appreciate some help!

**Comment by VyzeTV** [comment]
Ok so, after messing around with stuff in Blender I "seem" to have found a workaround for this, while I was posing the leg to see what might be broken I randomly decided to rotate the "left leg" bone while the IK was posed in a way that it would bend the leg, and to my surprise, this actually fixed the leg and it was now bending properly.

This led me to believe that maybe the knee bones needed to be moved a bit forward in order to correctly work with the IK constraints and voila, that look liked it did the trick, I will of course try it with other models I've been having issues with too.

**Comment by MediaMoots** [comment]
Yup, that was the solution.
#177
