### ISSUE TITLE
Problem exporting characters black textures

### ISSUE THREAD

**Issue by Bercraft** [FlailingFog/KK-Blender-Porter-Pack#317]
Hello i' ve a problem exporting this card 
![101620498_p0](https://user-images.githubusercontent.com/33317459/204024455-6d93739a-74fa-4cf4-8d6c-827712258f13.png)
The bug is a missing texture or black texture under the outfit
![01](https://user-images.githubusercontent.com/33317459/204024506-fe0b5c66-fe7c-4d87-b5ad-0d75d8ce9eff.PNG)
![02](https://user-images.githubusercontent.com/33317459/204024511-2ffb47d3-00c8-48ab-9bd4-56e7edc4c299.PNG)
thank you for your hard work

**Comment by LegionInstaller** [comment]
That's the Alpha Mask you can turn it off by going into the Body shader and turn off the Transparent slider

**Comment by Bercraft** [comment]
Thank you problem fixed
![Immagine 2022-12-05 095629](https://user-images.githubusercontent.com/33317459/205596449-76d12eb4-1413-47a7-b11b-68065d527e3d.png)
