### ISSUE TITLE
Corrupted Eyelashes / Headmod with default face type?

### ISSUE THREAD

**Issue by BTHP5** [FlailingFog/KK-Blender-Porter-Pack#318]
Heyo, I'm trying to export a male card with the new version of KKBP, and seeing it supported the export of more headmods, I was hoping this issue would be resolved, especially since the headmod is one of the default ones. But unfortunately, it has not.
Last time, I tried it on a female model and the same happened, but this was before V6.2, so I need to check that as well.

This card uses face type 03, which is one of the default male headmods that comes with Koikatsu.
I'm not sure if it's because I'm using the face type or if something else needs to be selected, but as you can see here, the eyelashes clip into the face when closing. 
![image](https://user-images.githubusercontent.com/54001645/204113748-0998f61c-ba72-49c5-825a-da93a8ce3519.png)

If anyone has any advice for this, please let me know.
I'm using blender 3.3.0, as well as the latest (V6.2) release of KKBP and the Exporter that came with it.
Thank you!

**Comment by BTHP5** [comment]
Upon changing the shapekey settings to "Skip Modified Shapekeys", the eyes disappear.
![image](https://user-images.githubusercontent.com/54001645/204113919-00253c35-53a0-4165-bd08-1409949ab2fe.png)

**Comment by BTHP5** [comment]
This, to me, concludes that it's only the eyes that the different headmods mess up

**Comment by BTHP5** [comment]
As well as Type 03 being broken, so is the "modified head" face type. The eyelashes are broken and the eyes don't close fully.
![image](https://user-images.githubusercontent.com/54001645/204114724-3cbeb7ce-b3e1-4779-ae55-d1b3dcebf7d9.png)

**Comment by FlailingFog** [comment]
I also came across this corruption. The "Fix body seams" option was causing some vertices to be deleted.
It should work correctly on the latest commit.

**Comment by BTHP5** [comment]
Hey Fog! Thank you for responding!! That's the Master commit, right? :]

**Comment by FlailingFog** [comment]
It's on the master branch

**Comment by BTHP5** [comment]
It works! Thank you so much for your hard work, and everyone's work toward V6.2!
