### ISSUE TITLE
Add support for Male facetypes / headmods

### ISSUE THREAD

**Issue by BTHP5** [FlailingFog/KK-Blender-Porter-Pack#319]
Guess who’s back! (I’m sorry LOL)
The new update is going great, I can export models well now. However, there’s still one issue I’m having with the new headmod support, and that the base game face types aren’t supported. Either that or they’re not supported on male characters, which really sucks D:
The facetype I'm using is **Type 03**

The issue remains the same as it was before, the eyelashes clipping through the face. Here’s an image, and I also have the card for you as well. 
![Screenshot_20221127_120600](https://user-images.githubusercontent.com/54001645/205387278-31ae41a6-e214-469b-bdba-544dce68ccc4.png)
![Screenshot_20221130_034730](https://user-images.githubusercontent.com/54001645/205387287-57cb15a8-f5d5-402e-867b-80dd35639405.png)
![Koikatu_M_20221112042018111_Kashiwagi Sousuke_Kai-Kun](https://user-images.githubusercontent.com/54001645/205387736-ee07986f-f7e3-4747-b57e-2badc377d93a.png)

Version-wise, I’m all up to date, using the latest commit on the master branch. If support could be added for this then that would be great! Thank you so much!

I put this in the enhancement section rather than the bug section because, it works, but lacks the support.

**Comment by BTHP5** [comment]
I fixed this by disabling "Fix Body Seams", but it still is something that needs added support for ^^'

**Comment by FlailingFog** [comment]
I think this was fixed (https://github.com/FlailingFog/KK-Blender-Porter-Pack/issues/318)
