### ISSUE TITLE
Remove Blue Lines, Fix Tear weighting, Improve Gageye blendshapes, Fix Iris clipping on Export

### ISSUE THREAD

**Issue by BTHP5** [FlailingFog/KK-Blender-Porter-Pack#320]
Adding this as a feature request as well, it would be great if there was a way to completely eliminate the blue pixels found on the textures of models. I was able to remove them within blender temporarily by changing the filter (?) on the textures node from sRGB to something else and then back to sRGB, but when it came to baking and applying the baked textures, the pixels reappeared again.
Here’s an image of what I mean by blue pixels.
![Screenshot_20221130_040601](https://user-images.githubusercontent.com/54001645/205388219-1b494dfa-3378-4681-b06f-2596f2bf9fc6.png)

As well as this, small and medium tears, as well as the gageyes don’t appear upon export from blender when activating the blendshapes, I'm not sure why, but I’d love to see them supported!

As well as this, the tears do not appear to be weighted properly. They tend to dip in and out of the face as the eyes move.
Looking forward:
![image](https://user-images.githubusercontent.com/54001645/205393034-66a7c3c4-669c-4451-b77b-69b63de26a20.png)
Looking downward:
![image](https://user-images.githubusercontent.com/54001645/205393328-dad38cad-ab84-4848-bbc5-d617af50fa50.png)

And lastly, when exporting my model from Blender to make into a VRM, the eyes would be clipping into the eye whites despite not messing with them. This may be because I’m using a different headmod, though. 
Here’s what I mean:
![Screenshot_20221130_023418](https://user-images.githubusercontent.com/54001645/205393816-99851bf1-5bd4-4495-89b8-cdebbaba01fc.png)
On the Left is after I moved the irises forward in unity, and the Right is the original after exporting from Blender
![Screenshot_20221130_031356](https://user-images.githubusercontent.com/54001645/205394255-bb615878-d269-4235-90e0-43656d9b18c3.png)

Thank you for reading, and I hope this was helpful!

**Comment by FlailingFog** [comment]
> , small and medium tears, as well as the gageyes don’t appear upon export from blender

These are setup in blender through drivers. You'll have to recreate these drivers in the program you want to use them in to get the same effect (or activate the gag / tear object's shapekeys manually)  
Small and medium tear shapekey setup is currently broken for all models

>the eyes would be clipping into the eye

I see what you mean now. These are the eyes with the eyewhites set to alpha blend:
![image](https://user-images.githubusercontent.com/65811931/211175678-c358fb18-1d57-45e0-880c-e88268f03f68.png)

And this is when it's set to alpha clip
![image](https://user-images.githubusercontent.com/65811931/211175687-186abdca-9d6e-4083-a356-1eb87010cec9.png)

You can see in edit mode that the eyewhite is clipping into the iris. Not sure why it looks normal when set to alpha blend (maybe [this explanation?)](https://www.youtube.com/watch?v=kwZez-eAA2w), and I also don't know why your eyes are clipping in the default position
![image](https://user-images.githubusercontent.com/65811931/211175736-4c33bfd2-15f9-4503-a83f-d74efd413d9b.png)

I have no idea how to activate the blendshapes in Unity so I can't try it with half closed eyes, but mine looks normal with the default position. Are you sure you're setting the eyewhites and eye materials to Transparent rendering in Unity? If it's set to Cutout it will probably replicate the Blender alpha clip setting shown above
![image](https://user-images.githubusercontent.com/65811931/211176229-45d5f21b-d276-4be4-a33d-630095059ce9.png)

If it's still causing an issue and you only need it to work for one or two shapekeys, you can just edit the shapekey to move the eyewhite back

> completely eliminate the blue pixels found on the textures of models.

> the tears do not appear to be weighted properly

I can't replicate these

**Comment by BTHP5** [comment]
The blue lines were / are caused both on the face and body when you use the maintex instead. E.g. if you have makeup or tattoos

**Comment by FlailingFog** [comment]
That's the slider I've been using:
![image](https://user-images.githubusercontent.com/65811931/213868807-576b77b8-5eda-44a1-94b3-71c20892ffc4.png)

Do the blue lines show up on the exported maintex png in the ####_character_name folder, or do they only show up after being imported to blender?

**Comment by BTHP5** [comment]
Heyo! I haven't been able to reply until now, the blue lines would mainly only be on the body or face when it had overlays like freckles or tattoos, which can only be seen when using the maintex slider. I believe it would be blue in the maintex folder as well, I'll do more digging though

**Comment by FlailingFog** [comment]
this should be fixed in kkbp 7.0.0
