### ISSUE TITLE
Headmods Iris Clipping when exporting to FBX or creating an atlas

### ISSUE THREAD

**Issue by BTHP5** [FlailingFog/KK-Blender-Porter-Pack#324]
Heyo! My character uses a headmod / different facetype to the default characters, and when I export them from Blender, or create a material atlas, the irises clip into the eyewhites. And when the character looks around, instead of the iris going upwards, it goes into the eye, kind of like it's going both upward and backward.

I'm not sure why it does this. I've tried weighting the iris materials to the head instead, moving the irises forward, rotating them, to no avail.
Here are screenshots of before and after atlasing!
**Before atlas / export**
![image](https://user-images.githubusercontent.com/54001645/206881216-7cb4f3b8-4e67-495e-96b5-7737f39de570.png)
**After atlas / export**
![image](https://user-images.githubusercontent.com/54001645/206881472-cc85272c-ac32-4365-8c29-aa9460d5cad3.png)
This error happens either when you create a material atlas, or Export FBX from the KKBP panel.
I do believe it's specific to the types of headmod I'm using, because the default male ones don't do this!
I believe I'm specifically using the one just labelled "Headmod", so the facetypes that modify the expressions of the original face.
_I have attached a card here that uses the headmod, so please, devs try it yourself!_
![Koikatu_F_20221106000433123_Roper Elise](https://user-images.githubusercontent.com/54001645/206881450-fdd73f57-3818-4285-b4ad-658e2affe86d.png)

**Comment by FlailingFog** [comment]
I'm going to close this since you mentioned it in (https://github.com/FlailingFog/KK-Blender-Porter-Pack/issues/320)
