### ISSUE TITLE
Im getting this texture issues when importing to unity any help ?

### ISSUE THREAD

**Issue by Retrbunny** [FlailingFog/KK-Blender-Porter-Pack#325]
Hi, I have been following the export process from blender to unity, but when I import the fbx to unity and I load the atlas textures in my model the transparent textures create some lines in the face textures, I try different methods of exporting the fbx, different baking options of the atlas but none seems to fix the issue, any help?

lastest blender version
lastest plugin version

![retrbunny - SampleScene - Windows, Mac, Linux - Unity 2021 3 14f1 Personal_ _DX11_ 11_28_2022 7_04_29 PM](https://user-images.githubusercontent.com/120332611/206924315-6750725a-d2b7-4949-84c8-500f646bf024.png)

![retrbunny - SampleScene - Windows, Mac, Linux - Unity 2021 3 14f1 Personal _DX11_ 12_11_2022 2_30_01 PM](https://user-images.githubusercontent.com/120332611/206926959-243ae8b3-a575-46cc-9b00-bfb67c90fb72.png)

**Comment by BTHP5** [comment]
When making an atlas, you need to make the body and the lines (Eyelines, nose, eyebrows) on a separate layer. Also, you need to set the exported Lines material Rendering Type to Cutout. I also suggest making the eyes a separate layer from the body as well, otherwise when you come to set the "looking around" blendshapes, your lines / body texture will move too.

**Comment by Retrbunny** [comment]
> When making an atlas, you need to make the body and the lines (Eyelines, nose, eyebrows) on a separate layer. Also, you need to set the exported Lines material Rendering Type to Cutout. I also suggest making the eyes a separate layer from the body as well, otherwise when you come to set the "looking around" blendshapes, your lines / body texture will move too.

i separate the material into a different layers before making the altlas and set the transparent material to cutout, i even try to separate each material in a different layer, but when I set it to cutout and export it the pupils and the sirome clipped each other really bad, so I do not know what else to do. I doing something wrong?

**Comment by BTHP5** [comment]
Are you using a different Facetype / Headmod to the default one? I'm experiencing that issue too because I'm not using the default face. For now, it's unfixable. You just have to use the default face to stop the clipping

**Comment by FlailingFog** [comment]
From your picture it looks like there's something wrong with one of the eyeline materials (the lines seems to match up with the sides of the eyes, not the nose)
![image](https://user-images.githubusercontent.com/65811931/208304823-9bcf7695-28b4-493f-88c7-abd9c5143715.png)

The shadowing isn't present if you open up the actual atlas png file, right? And in the Unity editor, the max png size is set to 8k like below?
![image](https://user-images.githubusercontent.com/65811931/208305236-c2efbed5-04eb-4448-b669-649fe70e8be9.png)

If there are no shadow lines on the atlas png, then I'm not sure what could be causing that. You might try deleting the "Eyeline down" mesh in Blender completely to see if it does anything.
