### ISSUE TITLE
void PmxExpoter.OnGUI()

### ISSUE THREAD

**Issue by chalilin** [FlailingFog/KK-Blender-Porter-Pack#326]
"
[Error  : Unity Log] TypeLoadException: Could not load type '<StartBuild>d__6' from assembly 'KKBP_Exporter, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
Stack trace:
void PmxExpoter.OnGUI()
"

Appear with every card. It seem has started after i've installed KPlug but uninstall Kplug hasn't solve the issue.

**Comment by BTHP5** [comment]
This doesn't really explain anything. 
Please tell exactly what you were doing when this happened. What softwares and plugins are you using and what versions?

**Comment by MediaMoots** [comment]
What version of KK are you using?
Keep in mind that you need to use the dll in the net3.5 folder for KK and the net4.0 for KKS

**Comment by chalilin** [comment]
I use the pre-modded pack "Koikatsu After School Better Repack RX15". The KK net3.5 worked until I install Kplug v2.9. 
Then, KK export menue still display, but click on "export" do nothing but print "[see the error i've quoted]" in red on the consol.

**Comment by MediaMoots** [comment]
I see, AFAIK Kplug breaks many plugins, so it is probably best to remove it when you want to use KKBP Exporter.

**Comment by chalilin** [comment]
After have delete then reinstall my whole game, it's work (without KPlugs, I won't take any risk). Long story for nothing i guess.
