### ISSUE TITLE
kk exporter removes body parts under the clothes

### ISSUE THREAD

**Issue by RayJay232** [FlailingFog/KK-Blender-Porter-Pack#328]
so when i import using kkbp from koikatsu sunshine too blender i get this....
![Screenshot 2022-12-21 154350](https://user-images.githubusercontent.com/86858825/209017114-2d842150-be99-415f-8899-07f7a7f78849.png)
which at start looks fine but when i remove the outfit from visible it turns into this.....
![Screenshot 2022-12-21 154433](https://user-images.githubusercontent.com/86858825/209017299-79ff2fb6-7104-4a8f-b63c-83245e9cdc17.png)
 and it has no body parts underneath and this is what i have checked in koikatsu exporter if it helps at all 
![KoikatsuSunshine-2022-12-21-15-54-38-UI](https://user-images.githubusercontent.com/86858825/209018754-32da923b-74d8-4c30-b549-41ee74f30586.png)

**Comment by BTHP5** [comment]
That's because of the alpha masks present within the game. It's supposed to be like that.
I don't have any advice for this other than to go out of your way to remove the alpha masks within the game and then export.

**Comment by RayJay232** [comment]
> That's because of the alpha masks present within the game. It's supposed to be like that. I don't have any advice for this other than to go out of your way to remove the alpha masks within the game and then export.

ty ill give that a shot plus i exported one outfit and it was fine so i believe that helps explain your assessment too.

**Comment by MediaMoots** [comment]
There's no need to remove the masks in KK, just go to the body shader in blender, there is a slider to turn off the mask.

**Comment by MediaMoots** [comment]
[There's no need to remove the masks in KK, just go to the body shader, there is a slider to turn off the mask.](https://github.com/FlailingFog/KK-Blender-Porter-Pack/issues/317)

**Comment by RayJay232** [comment]
> Please see #317

im un certain what body part to click on too find the correct shader slider?

**Comment by RayJay232** [comment]
> Please see #317

ty fixed it
