### ISSUE TITLE
Eyes clip into eyewhites (every model has this)

### ISSUE THREAD

**Issue by BTHP5** [FlailingFog/KK-Blender-Porter-Pack#333]
First of all, everything is up to date, I have the correct versions of everything

So, when the eyes blink, or I close the eyes even slightly, theres an odd white line that covers/clips through the top and/or bottom of the irises. I'm not sure why this is, but in earlier versions of the KKBP plugin, this wasn't a problem.

I'm not using any kind of other headmods either. 
Along with this, when importing the models into blender, the eyes are way too wide open.

I've provided images etc in previous bug reports which were not responded to, so I hope those ones and this one will be investigated

**Comment by FlailingFog** [comment]
Closing in favor of https://github.com/FlailingFog/KK-Blender-Porter-Pack/issues/320
(Check https://github.com/FlailingFog/KK-Blender-Porter-Pack/issues/297 for wide eyes)
