### ISSUE TITLE
2 Colored hair isn't exporting correctly

### ISSUE THREAD

**Issue by johnvo0918** [FlailingFog/KK-Blender-Porter-Pack#334]
![Koikatu_F_20230107220918871_Kaiz 4_K](https://user-images.githubusercontent.com/69092770/211183058-4944ca0d-28e2-40f8-9e9d-c1252d3ead07.png)

This is the character I'm trying to export.
Originally I changed the shadow color to give it colored inner hair. It didn't work when I export. I thought the shadow color is messing with the export so I changed it back to the default color and export again. (Outfit 0 In School has the default shadow color) (other outfits still has the colored shadow)

With shadow color: 
![image](https://user-images.githubusercontent.com/69092770/211183211-ce506948-5b7a-4d0a-a116-6ee6a8fde1a6.png)

Without shadow color
![image](https://user-images.githubusercontent.com/69092770/211183214-d3fd906a-12d4-4127-b72e-f9ebd7ef4fb9.png)

This is the result when export with shadow color

![image](https://user-images.githubusercontent.com/69092770/211183075-6ae7fb8d-9bf5-446c-97b0-5c7f7e9216aa.png)

Export with default shadow color

![image](https://user-images.githubusercontent.com/69092770/211183228-d69319bb-4fdc-4570-aab5-9801f1a900be.png)

As you can see, it didn't even bother changing the other parts that isn't affected by shadow color, the orange pieces is just normal hair accessory that doesn't use the main hair color anymore.
Please take a look!

Using latest KKBP Exporter, blender 3.3 plugin, HF patch 3.18,

**Comment by johnvo0918** [comment]
I can go through the grueling process of painting in the color myself but I'd like for the plugin to be able to read multiple hair color and apply it correctly. colored inner hair is kinda the new trend and the best way i found to replicate that style in KK is through editing the shadow color in material editor.
Please fix soon thank you!!!!

**Comment by johnvo0918** [comment]
Update: 
![image](https://user-images.githubusercontent.com/69092770/211186338-6ec42438-1113-4f28-b129-d9712cd2d62a.png)

So I tried to stop and categorize it myself by separating them manually (select mesh then separate selection)
It looks like it applied colors correctly but the detail and shadows are completely out of wack. dark color mode seems to not work too. 
![image](https://user-images.githubusercontent.com/69092770/211186717-e051a349-24ac-47f5-8979-a30bea6f8e2b.png)


thankfully the hair accessories can be fixed thru slider in blender.

**Comment by MediaMoots** [comment]
Well afaik shadow color is not implemented yet #39 so anything using that won't work yet...

**Comment by johnvo0918** [comment]
let's ignore the shadow hair color. but the rest of the dark color is broken even on a 1 colored hair model.

**Comment by johnvo0918** [comment]
update for 6.3.0 on blender 3.4
![image](https://user-images.githubusercontent.com/69092770/212465156-07efe2fa-cefc-44a9-9678-3706a92c3c4e.png)

Dark color works correctly! the white items can be fixed in shader. Will now try using 2 colored hair without shadow color.

**Comment by johnvo0918** [comment]
![image](https://user-images.githubusercontent.com/69092770/212795112-af4eb3a8-f37a-4d63-96d9-3f6459e2220a.png)

Going in the shaders and changing everything like this
![image](https://user-images.githubusercontent.com/69092770/212795195-90025f78-2694-4d11-8ae2-bff3e9dedef4.png)

still no way to change the shadow color of the hair in shaders.

**Comment by johnvo0918** [comment]
closed because this is more like a feature request now. 2 hair color import isn't supported as of this post. you can always load new texture in after baking.
