### ISSUE TITLE
How to use Eye Bones "Left Eye" "Right Eye" without Clipping into the Eyewhites

### ISSUE THREAD

**Issue by LegionInstaller** [FlailingFog/KK-Blender-Porter-Pack#336]
The only fix I found so far is manually Editing the Mesh deleting some vertices and Adjusting the Eyewhite Mesh to allow the Eye to Rotate
Since Blender uses the UV Warp Modifier

also a problem in VRC

Some Major Clipping Issues

**Comment by johnvo0918** [comment]
have you try https://vrm.dev/en/univrm/lookat/lookat_uv.html
i'm trying this soon (ill let you know if it works since its supposedly control UV). but the one other way to deal with this is that you can push the eye white back a little bit then when the eye rotate it wont clip too early.
