### ISSUE TITLE
Nipple mesh not being removed.

### ISSUE THREAD

**Issue by johnvo0918** [FlailingFog/KK-Blender-Porter-Pack#343]
Same card as the previous bug report.
i used the push up setting to flatten it in game but it still exports with nipple mesh attached. Exporting the model in SFW mode breaks the model.
Same problem with swimsuits despite them being on the bra section instead of top like the bunny suit.

![image](https://user-images.githubusercontent.com/69092770/212783631-cc695758-15fb-400e-85e3-7d804ae72091.png)
in game

![image](https://user-images.githubusercontent.com/69092770/212783644-d83985df-36c2-4ef6-9d2b-577df0bf0764.png)
in blender

**Comment by johnvo0918** [comment]
can be fixed by literally just select the mesh using a brush and push it in the body.

**Comment by LegionInstaller** [comment]
Body Shader , Alpha Mask turn the Slider Off

**Comment by johnvo0918** [comment]
not body shader, it's attached to the clothes.

**Comment by MoriMorinya** [comment]
The plugin can't export things like pushup or how closed the eyes are right now, you will have to go to edit mode and flatten it manually.

**Comment by johnvo0918** [comment]
> The plugin can't export things like pushup or how closed the eyes are right now, you will have to go to edit mode and flatten it manually.

I hope there will be a way to import the SFW model of the outfit. it seems like on the SFW version of the game it is flattened.

**Comment by FlailingFog** [comment]
Pushups should be supported in version 6.6.0
