### ISSUE TITLE
Stuff won't importing materials won't show up

### ISSUE THREAD

**Issue by envlightsourcegaben** [FlailingFog/KK-Blender-Porter-Pack#350]
I can't get proper import from pmx file. 

I asked friend and checked it, the pmx file is not problem, he's got everything all right, but on my side it's just dosen't work. 

What i am doing wrong? 
![изображение](https://user-images.githubusercontent.com/45875720/213968067-8188ae6f-c78b-454f-833a-b706a0886a2f.png)

**Comment by johnvo0918** [comment]
youre using V6.0.0 on blender 3.4 (only 3.0 is supported for V6.0.0). Try using the latest version V6.3.0 for blender 3.4

**Comment by envlightsourcegaben** [comment]
Tried, didn't work same result

**Comment by envlightsourcegaben** [comment]
Okay, i LITERALLY don't know what caused that, but i fully cleared blender folder in appdata, get a new clear blender, install just 3 addons (mmd_tools_unyaa, mmd_tools, kkbp) AND IT WORKED JESUS, I spend so much time on that.
