### ISSUE TITLE
Colour textures not loading in when importing pmx file

### ISSUE THREAD

**Issue by Error4-22** [FlailingFog/KK-Blender-Porter-Pack#351]
Kinda new to the whole modeling scene and I'm already lost. I can't seem to get the colours to load in with the PMX file..

![image](https://user-images.githubusercontent.com/123397897/214096377-df157f3f-01b7-4584-849e-17c0453842e9.png)

**Comment by envlightsourcegaben** [comment]
Any errors?

**Comment by Error4-22** [comment]
> Any errors?

Apparently some bone errors but I didn't seem to have a problem with them

**Comment by johnvo0918** [comment]
you didn't use the KKBP blender plugin to import ...
