### ISSUE TITLE
"Disable forced T-pose" option when exporting from KKS.

### ISSUE THREAD

**Issue by KnightDIRT** [FlailingFog/KK-Blender-Porter-Pack#352]
It would be great to have the option to disable the T-pose for other exporting purposes, such as 3D printing.

If anyone finds a workaround to the forced T-pose, please suggest.

**Comment by ilcane87** [comment]
Hi, I think there's another issue opened with basically the same request:

https://github.com/FlailingFog/KK-Blender-Porter-Pack/issues/339

**Comment by MediaMoots** [comment]
Closing in favor of #339 for tracking, thanks for the suggestion!
