### ISSUE TITLE
error when baking materials

### ISSUE THREAD

**Issue by Hive-cutie** [FlailingFog/KK-Blender-Porter-Pack#354]
I tried baking with multiple models and none of them worked. 

The files I and programs am using are:
-Blender v3.3.1
-KKBP exporter v3.98
-KKBP blender porter pack v6.3.0
-ScrewThisNoise Koikatsu better repack RX15

Screenshot of Issue:
![Screenshot (120)](https://user-images.githubusercontent.com/123508095/214402074-269dc917-b147-4b5c-b958-16dec874cd9d.png)

Card used in screenshot:
![KK_236462](https://user-images.githubusercontent.com/123508095/214402000-c182d48d-c1ac-47bc-9afa-7123f939d9f7.png)

**Comment by johnvo0918** [comment]
looks like youre using 6.3 on blender 3.3, it only support 3.4 currently

**Comment by Hive-cutie** [comment]
Ok thanks ill try updating to 3.4
