### ISSUE TITLE
no texture spawns in

### ISSUE THREAD

**Issue by Mannenhehe** [FlailingFog/KK-Blender-Porter-Pack#355]
![image](https://user-images.githubusercontent.com/123579205/214624618-de3137a1-a80c-4ef5-91fe-1dc4efcb191b.png)

So uh, yeah I put the model in blender and literally no texture comes other than the hair, I don't know how to fix this, I've tried everything
![Koikatu_F_20230109200731996_Mizuki Akida](https://user-images.githubusercontent.com/123579205/214625129-c7591078-fb09-42cc-8d25-e2052816df2b.png)

**Comment by FlailingFog** [comment]
Works for me... Try using KKBP 6.3.0 on Blender 3.4
![image](https://user-images.githubusercontent.com/65811931/214750452-93762428-f648-4e8d-97ec-6ad947a59450.png)

**Comment by johnvo0918** [comment]
looks like imported with CATS instead of KKBP
