### ISSUE TITLE
How to reduce material without using Material Combiner

### ISSUE THREAD

**Issue by higeinu3594** [FlailingFog/KK-Blender-Porter-Pack#356]
How to reduce material without using Material Combiner

Can I use KKBP to reduce the material of a loaded character?

The Material combiner is exactly what I need, but I just can't use it.
I tried the texture bake function and it didn't give me the results I wanted.

It is time consuming to create 50~100 materials each time when setting up in UE5.
Is there a better way?

I am using the textures as is for the male characters since they are originally few materials.
I need to think about resolution and UV placement, but first I am looking for a way to reduce the number of materials.

Looking forward to hearing back from you!

![blender_UHbNRHu3LY](https://user-images.githubusercontent.com/115856191/214769843-0fd61f60-691b-4da1-98c7-5a7f407276d3.jpg)
![UnrealEditor_NYdiTPVFpZ](https://user-images.githubusercontent.com/115856191/214769851-955277eb-9c65-4b71-a254-efde70d764cb.jpg)
![CharacterCreator_Acffiu9UBG](https://user-images.githubusercontent.com/115856191/214769852-3227cb72-7075-4c2f-bb99-405a344098a0.jpg)
![UnrealEditor_x1MLb6l8uX](https://user-images.githubusercontent.com/115856191/214769855-b32acb2b-f911-45d2-8634-e20c95097cf0.jpg)
![blender_6ou8rkt3VQ](https://user-images.githubusercontent.com/115856191/214769857-2e418d2e-d065-4560-9618-bd2fbd5e28f4.png)
![blender_IST9FNpb3b](https://user-images.githubusercontent.com/115856191/214769861-d8af7f4b-5bbd-4702-bf1d-04194cfd1b3c.jpg)
![blender_MiBVcONmSI](https://user-images.githubusercontent.com/115856191/214769865-7ced12d1-e049-4cae-b83a-54caf5910bd7.jpg)

**Comment by johnvo0918** [comment]
basically what material combiner does is that it combines all texture into 1 atlas thus it only use 1 material UNLESS you specify transparent material and hair material. What are the errors are you getting when you bake ? Because bake just turns all the maintex, shader, etc etc into a texture.

**Comment by FlailingFog** [comment]
> Can I use KKBP to reduce the material of a loaded character?

Sorry, Material Combiner is the only way I know how to do it, so there's no way to do it with KKBP.
You may be able to use the scripting tools in Unreal Engine to create a script that automatically sets up the materials for you based on the image filenames.

**Comment by higeinu3594** [comment]
As for the Material Combiner error.
1. Pop-up does not appear.
2. specifying the material I want to combine does not work as I want it to.
3.[Body] has never succeeded.

In part 3 of the KKBP instructional video, the Atlas image was saved and adapted.

By chance, a popup appeared and when I pressed save, the resolution of Atlas was (64x64) and I thought it was wrong somewhere, but I didn't know which was wrong.

I tried Outfit 00, which is a different character.

1. same
Check 2.Suit+gloves
3.Suit+gloves Save Atlas
4.Select Back wing then Save Atlas
5.Other selection (circle boot showd)
6.Save Atlas

I don't think it will look the same if it's the same material, but if it's a different UV or Texture, it will overwrite the selected material.
I've seen similar symptoms in the comments of the video, so I know I'm doing something wrong, but I don't know what's wrong.
![blender_1](https://user-images.githubusercontent.com/115856191/215009638-b38b506b-a7b6-4ecf-836e-17eb62efa97a.jpg)
![blender_2](https://user-images.githubusercontent.com/115856191/215009713-7724cb75-f370-4605-96ea-fde3ceef364c.jpg)
![blender_3](https://user-images.githubusercontent.com/115856191/215009715-3bd32cbc-bbef-4378-8cd7-d14602ace2b6.jpg)
![blender_4](https://user-images.githubusercontent.com/115856191/215009717-a84018d5-26c4-464a-adbc-d4c0ccc29e34.jpg)
![blender_5](https://user-images.githubusercontent.com/115856191/215009790-63ba1e39-6350-4c5c-915c-c84744e72d33.jpg)
![blender_6](https://user-images.githubusercontent.com/115856191/215009806-51754c25-169c-4349-a87e-a5f6e188057c.jpg)

The only saving grace is that if they are the same, there is no breakdown. (Wing gloves, etc.)

**Comment by higeinu3594** [comment]
Sorry for all the questions.

I would like to ask about scripting tools in UE5.
I'm using GenshinShader right now and I just got the result of UE5.
The material is created on UE5 and the image created in Koikatsu is adapted to GenshinMaterial.
(Diffse and Opashity)

I create animations with DCC tools and make videos with UE5.

I want to use UE5 as a rendering tool, so I will definitely introduce meshes.

Is it worth introducing the scripting tool in UE5 even if I have never dealt with it at all?

I know this is far from KKBP, but if you can answer, I look forward to hearing back from you.

**Comment by MediaMoots** [comment]
@higeinu3594 

You could write custom HLSL shaders in UE5 based on xukmi's shaders.

https://github.com/xukmi/KKShadersRecreated and https://github.com/xukmi/KKShadersPlus

And plug the shader code with a custom shader node:
https://docs.unrealengine.com/4.27/en-US/RenderingAndGraphics/Materials/ExpressionReference/Custom/

For rendering I suggest this article:
http://blog.theoroy.com/2017/04/27/anime-look-cel-shading-in-ue4/

All this is really advanced stuff though, monsters be here.

**Comment by MediaMoots** [comment]
@higeinu3594 

As for scripting, all the data you need is stored in the exported json files.
However once the character is processed by KKBP and blender the data may not be valid anymore.

In that case you could write a simple Editor Utility UMG BP that imports meshes, creates material instances and sets the correct textures based on file name to the material.

**Comment by higeinu3594** [comment]
Thanks for letting me know.

As for Cel Shading, I was able to create outlines in UE5 that were missing from Blender with the overwrite material.

Texture baking took a bit of work, but I was able to do it, and now I'm going to start creating animations and making videos.
