### ISSUE TITLE
Baking causes artifacts in light face & body textures

### ISSUE THREAD

**Issue by miyabi-95** [FlailingFog/KK-Blender-Porter-Pack#358]
i'm creating a base model that i can add clothing to in the meantime, but there's been an issue happening that's left me completely stumped. the face and body textures somehow end up with dark color (pink) leaking into them after i bake. i left some console text, something appears to be going wrong during the process of flattening?

few things:
1. i deleted all outlines
2. i combined all objects before baking, a la the older process (leaving them as is didn't fix anything)
3. i toyed around with the rims and raw shading nodes, didn't really get anywhere

![Screenshot (2178)](https://user-images.githubusercontent.com/63174638/215026309-0276739b-bd84-4939-88bb-b06ab551c9fe.png)
![Screenshot (2179)](https://user-images.githubusercontent.com/63174638/215026315-c57f9b54-36ea-4863-a4b0-a6fd8cb20cb8.png)
![Screenshot (2180)](https://user-images.githubusercontent.com/63174638/215026319-5fb1b6cb-90c9-42c9-b952-d1c44997c6e1.png)

i use:
blender 3.3
kkbp exporter 3.98
kkbp pack v6.0.0

idk if i need the better repack stuff bc the export process went swimmingly. now i just have blender issues. thanks in advance!

**Comment by miyabi-95** [comment]
i found a workaround by changing the dark face and body colors to light, and baking the dark textures since they don't have that issue, then relabeling them as light.

one last concern would be the eye textures looking wacky after making the atlas. is this a rendering bug that's exclusive to blender or will it carry over to unity?

![Screenshot (2245)](https://user-images.githubusercontent.com/63174638/215581082-43fec7bd-d575-455d-ad77-6aaf641b72dd.png)

**Comment by miyabi-95** [comment]
nvm, i set them to alpha blend! 
will leave this open if anyone would like to troubleshoot the original issue. i can send over the card.

**Comment by FlailingFog** [comment]
A "use old baker" option was added in one of the later versions that should prevent the artifacts from appearing
