### ISSUE TITLE
Blender complete crash when baking.

### ISSUE THREAD

**Issue by FrankVargas427** [FlailingFog/KK-Blender-Porter-Pack#359]
After shading and fixing some clipping issues, when I bake this character, not only blender but my entire GPU crashes. I have an RX5600XT, and it has given me trouble before, but when I was using KKBP V6.2.1, there was no problem with the baking procedure.

Attached are the error message, the error log itself and the character.

![Koikatu_F_20220915150434826_Key Key_key](https://user-images.githubusercontent.com/43286109/215182878-da91af75-9c57-45dd-9142-56cb97187f50.png)

[exporting.crash.txt](https://github.com/FlailingFog/KK-Blender-Porter-Pack/files/10522586/exporting.crash.txt)

![error](https://user-images.githubusercontent.com/43286109/215183483-5b8254d0-5472-4905-a3e8-09447afdb494.png)

**Comment by muyoou** [comment]
I had the same problem and only reproduced on v6.3.0.

**Comment by FlailingFog** [comment]
Sorry, I tried that card and while I did get those console errors related to the modifier, I didn't get a crash. I'm using the master branch version of the plugin on Blender 3.4.1. 

I also don't think the changes between the 6.2.1 and 6.3.0 versions of the bake script would be enough to cause a crash (they're very minimal changes), so I'm not sure why it would work on one version but not the other.

**Comment by FrankVargas427** [comment]
I am using blender 3.4, so perhaps something in the upgrade to 3.4.1 messed up the process? I will update to 3.4.1 and see if the issue persists.

**Comment by FrankVargas427** [comment]
Nope, updated to 3.4.1 and the error persists, with the same crash log reason as before. Strangely, the reason why it crashes is because of one of the tops that I'm using, which doesn't make sense because I've done the process with that same top before in previous versions of the plugin, and it has worked. Only difference is that now it has a tie.

Placing whatever png with the name of the material of the top, being **cf_top_guiche_m**, in the folder where the baked materials are going proves that the only issue is with the top, since it skips it during baking and there is no crash.

**Comment by FrankVargas427** [comment]
As a test, I deleted **every** outfit that isn't the one with the top and deleted **every** material that isn't the top so that blender would only have to bake the top itself and nothing more, and it worked! Still strange, but maybe its my fault given that the model itself has a lot of accessories and stuff.
