### ISSUE TITLE
How could I use AnotherRamp?

### ISSUE THREAD

**Issue by awaiting-death** [FlailingFog/KK-Blender-Porter-Pack#361]
![fu 10910_AR](https://user-images.githubusercontent.com/29349728/215315142-6aa3ec49-a54c-4433-90e2-077d0c055b9f.png)

Hello, I want to ask something about anotherramp. 
In Koikatsu, some clothes have metallic parts(ex: buttons, zipper) and as I know these are generated by using anotherramp.
But in Blender, when I use KKBP to import Koikatsu's model, I couldn't find any objects another ramp applied.
Doesn't KKBP support function using anotherramp? If it does, please let me know how I could use anotherramp in Blender.
Thank you.

**Comment by LetterN** [comment]
You can use the "Detail Mask" to find out the material; red is used for metal (on clothes at least)

**Comment by awaiting-death** [comment]
Thank you for your answer!
