### ISSUE TITLE
Error when prepar armature

### ISSUE THREAD

**Issue by NaughtDZ** [FlailingFog/KK-Blender-Porter-Pack#368]
[KKBP V6.3.0](https://github.com/FlailingFog/KK-Blender-Porter-Pack/releases/tag/V6.3.0),Blender 3.4
![Koikatu_F_20221021213141197_Alice](https://user-images.githubusercontent.com/37768911/216832651-2d3a0501-9769-4d86-98d8-4098aff4e966.png)
error is here(import siting "useing rigify" armature)
![image](https://user-images.githubusercontent.com/37768911/216832662-b89f6a25-05bd-4ad4-8168-9153ad4cd00a.png)
and i also cant use "generater rig" on rigify or bake texture

**Comment by ilcane87** [comment]
Hi @NaughtDZ, I tried importing that character with the Rigify armature, and besides the fact that it takes a long time to complete the process, it's working properly:
![2023-02-06 17_33_59-Blender](https://user-images.githubusercontent.com/34897042/217029816-fb6d4796-9d34-441b-b9bb-fed76897b870.png)

Are you getting that error with just this card, or with all cards in general?
If it's the latter, you may not have enabled the Rigify addon, try following the instructions here:
https://github.com/FlailingFog/KK-Blender-Porter-Pack/issues/341#issuecomment-1383101647

**Comment by NaughtDZ** [comment]
> Hi @NaughtDZ, I tried importing that character with the Rigify armature, and besides the fact that it takes a long time to complete the process, it's working properly: ![2023-02-06 17_33_59-Blender](https://user-images.githubusercontent.com/34897042/217029816-fb6d4796-9d34-441b-b9bb-fed76897b870.png)
> 
> Are you getting that error with just this card, or with all cards in general? If it's the latter, you may not have enabled the Rigify addon, try following the instructions here: [#341 (comment)](https://github.com/FlailingFog/KK-Blender-Porter-Pack/issues/341#issuecomment-1383101647)

I reinstall my Koikatu and HF Patch,now is works fine,thx.
