### ISSUE TITLE
Problem with Koikatsu Armature

### ISSUE THREAD

**Issue by eavme** [FlailingFog/KK-Blender-Porter-Pack#370]
![kk](https://user-images.githubusercontent.com/80640077/217378095-fb77ece0-3130-44ed-bffa-95779eeef8b5.png)

**Comment by FlailingFog** [comment]
That is a weird bug, were the pupil bones deleted? This version should work:
https://github.com/FlailingFog/KK-Blender-Porter-Pack/archive/refs/heads/master.zip

**Comment by Player4-AB** [comment]
Blender 3.4.1
KKBP updated on ur link.
KKBP in KK updated on last ver.
MMD updated on last ver.

Textures were not loaded when importing the model with Koikatsu Armature.
Log Import: [blender.zip](https://github.com/FlailingFog/KK-Blender-Porter-Pack/files/10701335/blender.zip)
After "Prep for target application": ![as](https://user-images.githubusercontent.com/80640077/217935465-07abe177-f98a-445c-9857-1bfd87384312.png)

UPD: textures generally not loading at any settings. The old version of the Blender didn't have this problem.

**Comment by FlailingFog** [comment]
If this is happening with a specific card, could you upload it?
I'm unable to replicate the error or the textures issue...

**Comment by eavme** [comment]
> 

It's not about the cards. Perhaps the problem is in the assembly of Koikatsu, which has some kind of plug-in with bone modifications. Although I'm not sure... So, I reinstalled Koikatsu to BR PX16, loaded the model into Blender 3.4, the problem with the eyes disappeared, but a new one appeared. The error log is below. This error occurs with all cards, even with the default Chika.

`Traceback (most recent call last):
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\KK-Blender-Porter-Pack-master\exporting\exportprep.py", line 246, in execute
    main(prep_type, simp_type)
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\KK-Blender-Porter-Pack-master\exporting\exportprep.py", line 109, in main
    armature.data.edit_bones['Pelvis'].parent = None
KeyError: 'bpy_prop_collection[key]: key "Pelvis" not found'`
![1](https://user-images.githubusercontent.com/80640077/221715694-7d1fab48-060f-49da-98cb-c666786b375b.png)

**Comment by eavme** [comment]
Oh, I forgot that in 3.4 there was the same error. The problem with the eyes was in 3.3. Either way, we get an error...

**Comment by eavme** [comment]
Oh, I forgot that in 3.4 there was the same error. The problem with the eyes was in 3.3. Either way, we get an error...

**Comment by eavme** [comment]
123
