### ISSUE TITLE
ears and horns have no colors

### ISSUE THREAD

**Issue by firemonkey2** [FlailingFog/KK-Blender-Porter-Pack#371]
![ears and horns](https://user-images.githubusercontent.com/124755013/217423963-71d67b87-4094-4147-b637-71a05a06bf0e.PNG)
when i import this character her ears and horns have no colors any help are welcome

**Comment by FlailingFog** [comment]
You might want to take a look through this. It should give you pretty good hints for adjusting the colors  of everything: https://www.youtube.com/watch?v=gCLKAYrykso

**Comment by MediaMoots** [comment]
Could you share the card please?
