### ISSUE TITLE
Trying to import any model results in errors

### ISSUE THREAD

**Issue by aaSensei** [FlailingFog/KK-Blender-Porter-Pack#375]
![blender_RAEgPLTRWb](https://user-images.githubusercontent.com/107249995/218371708-cc9d4892-83f2-4a20-8d81-5acce4de332e.png)

**Comment by Di-Bao** [comment]
I got the same issue

**Comment by FlailingFog** [comment]
Sorry, I can't replicate this. Even the default model exported with KKBP Exporter 4.21 and imported with KKBP 6.4.0 / 6.4.1 will fail there?

**Comment by MediaMoots** [comment]
@aaSensei @Di-Bao 

What Koikatsu version are you using?
Try using BetterRepack RX15 and up. (You could use google to find it :)
