### ISSUE TITLE
FurRimColorShader

### ISSUE THREAD

**Issue by VP1989** [FlailingFog/KK-Blender-Porter-Pack#376]
Is it possible to make the KKBP Exporter compatible with shaders that aren't ShaderForge? I have a card with curly hair that uses the FurRimColorShader for that effect, but it gets exported as a mesh of straight hair in Blender.
I included a card along with the screenshots in Koikatsu Studio and Blender.
![Koikatu_M_20210507102558258](https://user-images.githubusercontent.com/8047059/218888530-d4db5d05-8282-4621-9ebb-88301408c158.png)
![image](https://user-images.githubusercontent.com/8047059/218888542-05b05dcb-b861-4145-b9dc-20a09a1b0981.png)
![image](https://user-images.githubusercontent.com/8047059/218888553-ce1c7208-8896-4e1c-8f1e-873943af2f41.png)

**Comment by FlailingFog** [comment]
I'm going to guess this is more to do with blender than the exporter. Here's the same hair mesh when set back to the default hair shader in koikatsu:
![image](https://user-images.githubusercontent.com/65811931/219539528-735e2664-3ab0-4836-92fc-0941c4d3d699.png)

The fur shader is probably just using the straight hair mesh as a base for that effect, so you would have to figure out how to replicate the fur shader behavior in blender.
