### ISSUE TITLE
Unable to pack file - 6.4.0 Create animation library

### ISSUE THREAD

**Issue by RotcivOcnarb** [FlailingFog/KK-Blender-Porter-Pack#377]
After following [this tutorial](https://www.youtube.com/watch?v=Ezsy6kwgBE0) on importing Koikatsu animations, I cant get past the part where you create the animation library.

It gives me this error:
![image](https://user-images.githubusercontent.com/17129106/218920686-bff25186-547a-4d90-ac4e-fdc4b33be507.png)

After searching for the specified path, it realy does not exist, there isn't even an "textures" folder. Whats going on?
![image](https://user-images.githubusercontent.com/17129106/218920982-50e0e94d-a36d-42ed-bf48-1e46d452c401.png)

I'm using Unity 3.4.1 and KKBP 6.4.0

**Comment by FlailingFog** [comment]
Shoot, I thought I fixed that before I made the 6.4.0 release. I'll update the release to 6.4.1
