### ISSUE TITLE
Blend shapes are not configured correctly (Problems importing into Unity)

### ISSUE THREAD

**Issue by RotcivOcnarb** [FlailingFog/KK-Blender-Porter-Pack#379]
When importing a character into blender, the shape keys are working properly by changing the values while selecting the Body object, however, when i export the .fbx and import it into unity, the Body model doesn't seem to import the blendshapes properly, as there isn't any showing in the inspector:

![image](https://user-images.githubusercontent.com/17129106/219540789-3744ac10-2950-473c-b74f-b6931da0ce03.png)

They are correctly showing into the Gag Eyes and Tears objects though, but they do not work, as changing the slider does not affect the face:

![image](https://user-images.githubusercontent.com/17129106/219541248-9ebb53c0-3fcf-467d-9aee-1061cc6a4b09.png)

By messing around with the blendshapes into blender itself, i noticed that the blend shapes that are shown when the body is selected, are not purple, meaning that there are no Drivers created for them:

![image](https://user-images.githubusercontent.com/17129106/219541447-1291e3f7-3fcc-4823-b13a-eae383feb565.png)

But they do show purple while selecting the Gag Eyes or the Tears, I assume this has something to do with the issue

![image](https://user-images.githubusercontent.com/17129106/219541526-6651435f-0447-4448-95af-74e69f093fe0.png)

Maybe i'm missing something, and if i do, please forgive me, as i don't have much experience in blender, and i don't really know how those Shape Keys and Drivers fully work, i just haven't got the shape keys working in Unity and i don't know exactly what is the issue.

Thanks!

**Comment by BlueScreenofDeath201** [comment]
Be sure that "Apply Modifiers" is unchecked upon export.

**Comment by FlailingFog** [comment]
That sounds right. If you re-export using the export button in the KKBP panel, it will uncheck that option for you automatically.
