### ISSUE TITLE
Cannot prep a model that was automatically categorized

### ISSUE THREAD

**Issue by FrankVargas427** [FlailingFog/KK-Blender-Porter-Pack#381]
As the title says, I selected 'Automatically Categorize' in the import options because it makes it easier for me in the shading stage to put each piece of clothing in a collection of tops, bottoms, accessories, etc. However, now that I'm ready to prep the character for the next step, this is what happens after clicking the button:

```
Prepping for export...
Moving unused objects to their own collection...
Removing object outline modifier...

Error:          Unknown python error occurred
Traceback (most recent call last):
  File "C:\Users\Frank\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\KK-Blender-Porter-Pack-641\exporting\exportprep.py", line 251, in execute
    main(prep_type, simp_type)
  File "C:\Users\Frank\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\KK-Blender-Porter-Pack-641\exporting\exportprep.py", line 47, in main
    if ob.type == 'MESH' and ob in bpy.context.view_layer.objects:
TypeError: bpy_prop_collection.__contains__: expected a string or a tuple of strings
```

I loaded the character again in a new project from scratch, and the issue appears right after importing, meaning that, somehow, setting 'Automatically Categorize' is the source of the issue.

![Koikatu_F_20220915150434826_Key Key_key](https://user-images.githubusercontent.com/43286109/219991342-b6a9f02a-efdc-440b-9528-2a86b1bcfd2d.png)

Thanks for the help!

**Comment by BlueScreenofDeath201** [comment]
I get the same thing trying to prep with the default "dont pause" option as well. Simply cannot prep for target application at all without getting this error.

**Comment by firemonkey2** [comment]
i also got the same error

**Comment by BlueScreenofDeath201** [comment]
Temporary Fix: Utilize Blender 3.3.3 with KKBP 6.2.1(With appropriate exporter of course) and prep target there. Then open the file in Blender 3.4+ with the new KKBP and you can still use all the new features of baking and finalizing.

**Comment by nizhuan-jjr** [comment]
Here are my two edits to the exportprep.py; the **prep** works for me now.
![0](https://user-images.githubusercontent.com/3255986/220403112-a3fe0756-9983-4f44-9627-6c1793a2fc60.png)
![1](https://user-images.githubusercontent.com/3255986/220403130-8e6841eb-ce9f-414b-99c6-6396cb18b478.png)
The code could still be improved though, especially the second part, I'm not sure my edit is an optimized one.

**Comment by FrankVargas427** [comment]
> Temporary Fix: Utilize Blender 3.3.3 with KKBP 6.2.1(With appropriate exporter of course) and prep target there. Then open the file in Blender 3.4+ with the new KKBP and you can still use all the new features of baking and finalizing.

@BlueScreenofDeath201 I've already done a bunch of mesh editing and texture fixing on my current save in blender 3.4, and I don't want to do aaaaall that again 😭
Still, thank you for the temp fix!

**Comment by FrankVargas427** [comment]
@nizhuan-jjr it took forever, but it worked! Thanks a lot for your edit!

**Comment by nizhuan-jjr** [comment]
> @nizhuan-jjr it took forever, but it worked! Thanks a lot for your edit!

You don't need to close this issue too soon. The main contributors of KKBP should be informed.
@FlailingFog @MediaMoots @castbohea

**Comment by FlailingFog** [comment]
Oops, I changed this line but didn't test it because I did not want to wait for it to process. It should work in the master branch now.
