### ISSUE TITLE
Problem with the colors of the textures

### ISSUE THREAD

**Issue by rusharkxp** [FlailingFog/KK-Blender-Porter-Pack#382]
The koikatsu card that I am using.
![33707__23068](https://user-images.githubusercontent.com/37933820/220378046-f31d6c2d-6459-4167-ab50-6e9827bb3090.png)

There is a slight problem with the colors of the texture when I import the model.
![image](https://user-images.githubusercontent.com/37933820/220390931-0e1d7f9a-9245-40a2-81a9-d22cc8d07026.png)

Moreover, the textures inside the output folder have the same wrong coloring.
![image](https://user-images.githubusercontent.com/37933820/220391395-e587f8f4-ae58-49d2-b3f8-a10db08b7f0f.png)

Additionally, when I am setting the strength in Viewport Shading to 0. This is what happens to the textures:
![image](https://user-images.githubusercontent.com/37933820/220393208-7c0a3909-c365-42ed-8b0c-24eaaf0bf3e5.png)

KKBP V6.4.1 Blender 3.4.1 (Export options in the game: Single outfit).

**Comment by FlailingFog** [comment]
Thank you! Now I finally know why these weren't loading in for some people.
The shadow color for these materials were missing, so the plugin wouldn't load an image. I made it use a default shadow color when it doesn't find one. It should work in the master branch version.

![image](https://user-images.githubusercontent.com/65811931/220793141-67480d89-fd1c-4b6f-9e9a-566992a71aff.png)

**Comment by rusharkxp** [comment]
@FlailingFog Artefacts on the texture are only fixable manually, aren't they?

**Comment by FlailingFog** [comment]
I guess so. The dark texture generation works best with flat colors. You can put the light color texture and darken it manually instead if you want to reduce the artifacting.
