### ISSUE TITLE
Missing Textures when rendering (Cycles)

### ISSUE THREAD

**Issue by DedProtectr** [FlailingFog/KK-Blender-Porter-Pack#386]
This is the card I'm using:
![Koikatu_F_20230219031845014_Kasane Teto](https://user-images.githubusercontent.com/13284262/221127174-c4c6179e-6c1d-482e-a80c-9434c0cfa789.png)

When importing, the only option I change is "Use Cycles" rather than "Use Eevee".

![image](https://user-images.githubusercontent.com/13284262/221127744-1f561aea-ce4a-4f47-9d75-9b74a07bfaa7.png)

Material view shows proper textures

![image](https://user-images.githubusercontent.com/13284262/221128153-52654372-a128-4a3e-bbe5-0c09878970cd.png)

Rendered view shows proper textures for the shirt, but is missing textures for all other clothing

I'm using the latest release.

**Comment by FlailingFog** [comment]
I am not sure what I changed, but this model shows up in Cycles correctly now:
![image](https://github.com/FlailingFog/KK-Blender-Porter-Pack/assets/65811931/7a53923c-c83e-4658-b6b5-9c1f055c665d)
