### ISSUE TITLE
Materials are getting mangled

### ISSUE THREAD

**Issue by StuartVW** [FlailingFog/KK-Blender-Porter-Pack#387]
I'm trying to get Koitatsu characters into Unity.  I'm new to the koitatsu ->KKBP -> Unity workflow.  I followed the video turorials, dowloaded and installed everything, then went to get some test models out.  The models seemed to import fine, but materials were getting lost / corrupted after creating the atlas.  Looking at the logs all kinds of errors were popping up.  Do I have a mismatch somewhere between versions some software versions?  Did something get overwritten?

![model as imported](https://user-images.githubusercontent.com/126360948/221382599-ae82cb5b-6774-4aa2-adcd-54abb9ae9927.png)

![model after atlas created](https://user-images.githubusercontent.com/126360948/221382612-37cb6bb6-53ca-446d-9fa4-1e037587683a.png)

[blenderlog123.txt](https://github.com/FlailingFog/KK-Blender-Porter-Pack/files/10832457/blenderlog123.txt)

**Comment by FlailingFog** [comment]
It looks like you're only using one atlas layer on the body. Try using two instead: https://www.youtube.com/watch?v=4Z02sY6Y8GI&t=181
