### ISSUE TITLE
Hello I need your help

### ISSUE THREAD

**Issue by ziyiacc00** [FlailingFog/KK-Blender-Porter-Pack#389]
Hello, I have some problems extracting models in the studio. I hope you can help me. Thank you
Hint:
mesh export attempt falled wish exception:fbx exporter dll unable to load!
the fbx exporter dll was localed at unityfbxExporter_86_64_v16 dll but failed to load.

**Comment by MediaMoots** [comment]
KKBP only works with the KKBP exporter, any other exporters are not really supported.

**Comment by eavme** [comment]
> Sorry to bother you, but the games I'm talking about are hs2(grey mesh exporter) can't extract the models anymore at the studio. What's the problem? Extract model panel prompt :unityfxbexporter 86 64 16 dll cannot load

You don't write there. This plugin only works with Koikatsu and Koikatsu Sunshine

**Comment by FlailingFog** [comment]
I would suggest looking into the [sklx-creator ](https://sklx.gumroad.com/l/sklx-creator) plugin instead of this one if you want to export hs2 models
