### ISSUE TITLE
When applying VMD to a character, there is a bug where the arms are fixed and do not move properly.

### ISSUE THREAD

**Issue by DOODED** [FlailingFog/KK-Blender-Porter-Pack#390]
When using the KKBP armature or Rigify armature, there is a bug where the hands are fixed and do not move properly.
When using Koikatsu or PMX, there is a bug where the legs are fixed and move strangely.
I used mmd_uuunyaa_tools to apply VMD.
Is there any other way to apply VMD in blender?
Thank you for reading my message.

**Comment by FlailingFog** [comment]
The KKBP and Rigify armature have IKs enabled by default. For the KKBP armature you may need to disable the IK modifiers on the hand bones. For the Rigify armature you may need to enable the IK-FK switch for the hand bones in the rigify settings. Koikatsu and PMX armatures do not have leg IKs, so if they appear fixed the motion you're applying probably requires leg IKs.

**Comment by ddcddc1541** [comment]
Could you teach me how to disable IK modifiers? I'm new to this and have been trying for several days to solve the problem with my character not moving properly due to the IK modifiers. I've been attempting to fix it, but it keeps getting stuck in place

**Comment by ddcddc1541** [comment]
> The KKBP and Rigify armature have IKs enabled by default. For the KKBP armature you may need to disable the IK modifiers on the hand bones. For the Rigify armature you may need to enable the IK-FK switch for the hand bones in the rigify settings. Koikatsu and PMX armatures do not have leg IKs, so if they appear fixed the motion you're applying probably requires leg IKs.

Could you teach me how to disable IK modifiers? I'm new to this and have been trying for several days to solve the problem with my character not moving properly due to the IK modifiers. I've been attempting to fix it, but it keeps getting stuck in place

**Comment by ddcddc1541** [comment]
ah I have solved it. Thank you for your helpful answer.
