### ISSUE TITLE
KK flashes back after installation

### ISSUE THREAD

**Issue by Policturn** [FlailingFog/KK-Blender-Porter-Pack#391]
I found the unmodified integration package to boot (other users can boot normally), and it still crashes after loading. When the ontology is started, the program process appears for a period of time, and then disappears directly. At present, we can rule out the plugin conflict, and suspect the hardware problem for the time being. At present, the hardware environment I use is 13900k and 4090, on the win11 platform.

**Comment by MediaMoots** [comment]
Try using BetterRepack RX15+ and install the plugin in that install.
