### ISSUE TITLE
Emission?

### ISSUE THREAD

**Issue by VP1989** [FlailingFog/KK-Blender-Porter-Pack#395]
Does the KK Shader have an option to turn down Emission?

**Comment by FlailingFog** [comment]
Not really. You can at least soften the effect by going into the raw shading group
![image](https://user-images.githubusercontent.com/65811931/223571937-1e9e9ca4-b49d-4471-a697-c2c014755511.png)

Then attaching the multiply node in the blue frame like this
![image](https://user-images.githubusercontent.com/65811931/223572907-596fdb27-ac1f-4ca6-9793-4731e8c7f2e8.png)

**Comment by VP1989** [comment]
What if it is already there?
![image](https://user-images.githubusercontent.com/8047059/224779559-953ed2c0-1f86-4fda-bbd0-be24821e3d1c.png)
