### ISSUE TITLE
Moving any mesh under the Body group will move the entire body instead of selected mesh (and eye white clipping)

### ISSUE THREAD

**Issue by johnvo0918** [FlailingFog/KK-Blender-Porter-Pack#396]
I noticed that on the 6.4.2 version of the pack I cannot move the eye white or any part of the body without moving the ENTIRE body. I usually fix the eye clipping by just moving the eye white back and it didnt have influence on the entire body
check video:
https://youtu.be/w42RceSM-jY
---------
from my findings the eye white needs to be moved Y: 0.0007 m to have proper clipping 
![image](https://user-images.githubusercontent.com/69092770/224000473-fe291a7d-1816-47e4-b6c5-6cb7b396415a.png)

This needs to be documented for people who aren't savvy in 3d modeling i guess ? I'm at the stage of combining the materials and still have no idea if this model will import to unity correctly. will update.

**Comment by FlailingFog** [comment]
It looks like you have proportional editing on when trying to move back the eyewhites (the dot icon next to the hump on the top bar)

And I am getting clipping after creating the atlas
![image](https://user-images.githubusercontent.com/65811931/224029579-e63007fd-48c1-4348-a479-8f38c8052b86.png)

But this clipping becomes minimal when I change the transparent layer's blending mode to Alpha Blend (this might just be the bottom of the eye socket creating the white line, and it's not really noticeable unless you're super close)
![image](https://user-images.githubusercontent.com/65811931/224029730-8396dd5d-8e26-48a6-bbc6-ace53b4a8b94.png)

Same thing in Unity, when the material containing the eyewhites is set to cutout, the eyewhites will clip
![image](https://user-images.githubusercontent.com/65811931/224032343-5005bf6f-d24d-4ab6-afa7-39a324b63766.png)

But when they're set to transparent, the clipping returns to being minimal
![image](https://user-images.githubusercontent.com/65811931/224032369-56767503-0b52-4e4c-a4c7-971568ae3f4f.png)

**Comment by johnvo0918** [comment]
Huh, I never thought about putting the eyewhite on transparent since it's a solid color thanks for the update!
