### ISSUE TITLE
V6.4.2 incorrect bone hierarchy (not sure if it's my card or universal)

### ISSUE THREAD

**Issue by johnvo0918** [FlailingFog/KK-Blender-Porter-Pack#397]
real bug this time i promise i'm really invested in this project and documenting my problems with it.
When choosing Use KKBP Armature + Very Simple + Unity - VRM compatible.
Your Upper legs (named Left Leg and Right Leg) are placed under the wrong bones

![image](https://user-images.githubusercontent.com/69092770/224285957-f9313c65-f3f4-47ab-ab68-d4e615780374.png)

This will cause a problem the upper left and right leg to not be child of Hip, the model will not work and the fingers apparently is affecting the t pose.

![image](https://user-images.githubusercontent.com/69092770/224287570-9c2dc279-73b6-422c-b21a-21da0f849f5d.png)

(also unused bones are still not being deleted)

**Comment by johnvo0918** [comment]
update: Pelvis is completely in the wrong position in the hierarchy, the skirt bones are under it and if you choose Hips instead of Pelvis your skirts wont follow you at all. (im too balls deep into making this model the only way to fix this bs is to restart the project) (maybe i shouldve chosen use VRC armature instead

**Comment by FlailingFog** [comment]
I'm not sure what's going on, but this is what I get after using KKBP Armature + Very Simple + Unity - VRM compatible.
![image](https://user-images.githubusercontent.com/65811931/230803852-f9002beb-a585-43a8-94b9-dd04cb903e3a.png)

I also don't have a Pelvis bone or cf_j_waist02 bone after running the script. The [prep script](https://github.com/FlailingFog/KK-Blender-Porter-Pack/blob/master/exporting/exportprep.py#L114-L124) should delete the original HIps bone and rename the Pelvis bone to act as a new "Hips" bone

**Comment by johnvo0918** [comment]
https://github.com/FlailingFog/KK-Blender-Porter-Pack/issues/394
The card is from here if you want to take a look.

**Comment by johnvo0918** [comment]
![Koikatu_F_20230302002219610_Kaiz 5_K](https://user-images.githubusercontent.com/69092770/232255408-796d1bb9-dc90-4224-965b-0d8f7697b4c7.png)
actually here is the most updated card. nothing much changed. but the previous card was a little old.

**Comment by FlailingFog** [comment]
Okay yeah, I think the accessory in slot 19 is causing the issue. Right after import it has bone names that are Spine and Chest that cause the real Spine and Chest to get a .001 at the end of them:
![image](https://user-images.githubusercontent.com/65811931/235372954-9d4a6061-b7c7-452e-95ae-d8c6d5e38776.png)

After using KKBP Armature + Very Simple + Unity - VRM compatible on your card (Gives an error about not finding a bone named "Spine", so this is probably why you're getting weird results):
![image](https://user-images.githubusercontent.com/65811931/235373344-b3231189-7ea7-4a74-a581-b390031feb1a.png)

It's fixable though, renaming the accessory slot 19 bones to something random, and then naming the real "Spine", 'Chest', 'Head' and 'Neck' to their correct names before running Very Simple + Unity - VRM compatible gives the correct Unity compatible bone hierarchy:
![image](https://user-images.githubusercontent.com/65811931/235373613-6607f4f2-d946-41bb-ac4e-135c62dd5f86.png)

**Comment by johnvo0918** [comment]
@FlailingFog Hey! sorry for the super late response. Since you said that accessory 19 was the problem, I went ahead and changed it to another item. So far so good It's working on 6.5. But I have a few questions

`
Info: Applied modifier was not first, result may not be as expected (repeated infinite time for 4-5 hours...)
Light None
Camera None
Armature POSE
Body None
Outfit 00 None
Outfit 01 None
Outfit 02 None
Outfit 03 None
Outfit 04 None
Outfit 05 None
Outfit 06 None
Tears None
Gag Eyes None
Hair Outfit 00 None
Hair Outfit 01 None
Hair Outfit 04 None
Hair Outfit 05 None
Info: cats merge weights success
Editing armature for VRM...

Error:          Unknown python error occurred
Traceback (most recent call last):
  File "C:\Users\KaizPC\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\KK-Blender-Porter-Pack-650\exporting\exportprep.py", line 251, in execute
    main(prep_type, simp_type)
  File "C:\Users\KaizPC\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\KK-Blender-Porter-Pack-650\exporting\exportprep.py", line 115, in main
    armature.data.edit_bones['Spine'].parent = armature.data.edit_bones['Pelvis']
KeyError: 'bpy_prop_collection[key]: key "Spine" not found'`

after running the prep script (immediately after importing and enabling only the outfit/hair pieces i want to keep), this error showed up. I will continue export to unity to see if the bone hierarchy is correct, I will assume it is correct since i can't find another Spine bone in the list despite it being named Spine.001

Most recent card if you want to take a look

![Koikatu_F_20230507170323634_Kaiz 5_K](https://user-images.githubusercontent.com/69092770/236799666-4598b554-1614-43ac-8d1e-1a5ca963832d.png)

**Comment by johnvo0918** [comment]
just found out that is the error. will try looking through again.
