### ISSUE TITLE
mouth and tongue rig where?

### ISSUE THREAD

**Issue by Warbandit100** [FlailingFog/KK-Blender-Porter-Pack#399]
I don't know if it's supposed to be hidden, i was told the tongue rig would be, but i can't seem to open the mouth with the face rig, i can only find the eyes handle, and the body parts sliders, but can't find mouth and tongue controllers anywhere, did I do something wrong?
![c](https://user-images.githubusercontent.com/127598354/224481092-9cb0d0e0-3115-45e0-b42a-e4288b033df7.png)

**Comment by ilcane87** [comment]
Hi @Warbandit100, these models aren't really weighted to be able to alter the face with that degree of control, most standard humanoid face deformations wouldn't suit an anime face either way.
Instead there are shape keys in the Body object with several pre-defined expressions for the mouth, tongue, eyes, eyebrows, etc... that you can enable manually, then you can use the rig controls to tweak them if needed.

**Comment by Warbandit100** [comment]
Hello @ilcane87 , thank you very much for the quick answer, It was clear and easy to understand, I will use the shape keys then, after I update the addon.

P.S. Good to see you again after MUGEN, still have to thank you for the support and advices you gave me those days.

**Comment by ilcane87** [comment]
> P.S. Good to see you again after MUGEN, still have to thank you for the support and advices you gave me those days.

Wow, can't believe someone from back then would come up here of all places, and good job remembering my name after 20 years or something! 
The world is crazy small.

**Comment by Warbandit100** [comment]
> good job remembering my name after 20 years or something! The world is crazy small.

Of course I remember a compatriot who also taught me pixelart, not to mention, I still use EvilDan as of today!

> Wow, can't believe someone from back then would come up here of all places

I'm a professional 3D modeler now, so I don't have time to do pixelart, so I'll use koikatsu models and repurpose them as fighters, after i pixelify them.
