### ISSUE TITLE
Missing Materials/textures

### ISSUE THREAD

**Issue by HaiseSaeye** [FlailingFog/KK-Blender-Porter-Pack#401]
i did the export process before updating mods with KK manager, if that's the cause of the textures and materials not loading on blender

![imagen](https://user-images.githubusercontent.com/99570315/226126060-98db9fd4-73b9-4b08-b63f-2421826ff7b2.png)
![imagen](https://user-images.githubusercontent.com/99570315/226126139-5fe843b9-0696-4f80-b4be-8f322194c276.png)
here's the card since it's bigger than 10 mb
https://www.pixiv.net/en/artworks/102661253

**Comment by HaiseSaeye** [comment]
![100763135_p19](https://user-images.githubusercontent.com/99570315/226126781-5dadc5a3-5c03-4492-b778-a4b815c6caa2.png)
also happens with this card

**Comment by WeeblyMon** [comment]
have you found a solution yet?

**Comment by HaiseSaeye** [comment]
nope as for now

**Comment by FlailingFog** [comment]
Those warnings are nothing to worry about. It looks like you just need to adjust a few sliders in the material node groups. 
Please check the faq here: https://github.com/FlailingFog/KK-Blender-Porter-Pack/blob/master/wiki/Wiki%20faq.md#im-getting-fully-white-textures-but-only-in-certain-places-after-importing-my-character

![image](https://github.com/FlailingFog/KK-Blender-Porter-Pack/assets/65811931/514cd88b-30cf-4acb-a075-e456833d082f)
