### ISSUE TITLE
Blue pixels appears on my model

### ISSUE THREAD

**Issue by ice987** [FlailingFog/KK-Blender-Porter-Pack#402]
After imported my KKSunshine model to blender,i found that blue pixels appears on my model
Just like this,they also appears on clothes:
![image](https://user-images.githubusercontent.com/58386875/226135025-fe2061a4-9b63-44f1-b712-fcf4ed82985f.png)
and this one,even in eyes:
![image](https://user-images.githubusercontent.com/58386875/226135064-bdbf6803-c99c-4988-9b16-0a33eec1c2f0.png)
But i found that in former version V5.1.0 blue pixels won't exist,using latest KKBPExporter and blender3.3,which caused serious quality issues.
Please help

**Comment by FlailingFog** [comment]
Just wondering, do the blue lines show up on the pngs inside of the export folder as well? Or do they only appear in blender?

**Comment by ice987** [comment]
> Just wondering, do the blue lines show up on the pngs inside of the export folder as well? Or do they only appear in blender?

I checked the pngs,the blue lines only appears in blender

**Comment by FlailingFog** [comment]
Thanks, so it's something in the blender materials that's causing it then. I don't recall a lot being added between the V5.1 and V6.0 materials, so I'll see if I can compare the two.

Also, does it fix anything if the material's "Blend mode" is set to Opaque, alpha blend or alpha clip in the material settings?
![image](https://user-images.githubusercontent.com/65811931/227778171-bb845fa5-a666-4138-a572-7cc53dc5a3f3.png)

**Comment by MoriMorinya** [comment]
had this issue happening before and fixed it by changing the textures color space off and on to srgb again, it could be something with blender or an addon that is doing this since these blue pixels were a short lived issue for me.

**Comment by FlailingFog** [comment]
this should be fixed in kkbp 7.0.0
