### ISSUE TITLE
KeyError: 'bpy_prop_collection[key]: key "cf_j_leg03_R" not found'

### ISSUE THREAD

**Issue by WeeblyMon** [FlailingFog/KK-Blender-Porter-Pack#404]
Won't load in with materials, textures, eyes at all, no matter how many times I redownload, change versions- nothing. 

KeyError: 'bpy_prop_collection[key]: key "cf_j_leg03_R" not found'

my last attempt was with Blender 3.3 and KKBP 6.2.1

I looked at this forum and the youtube comments and found no solution and it looks like this issue is widespread. You guys don't have a discord, nor reply to anything so I'm having trouble finding a way to make this work.

**Comment by FlailingFog** [comment]
Sorry, I don’t like giving useless replies so I don't normally respond if I don't have an idea of what could be causing an error. I remember seeing instances of this error a few times, but haven't encountered it myself so I have no idea what could be causing it. Every single model should have that bone.

In this case the only advice I can offer is to make absolutely sure you’re installing the right prerequisites, following the process shown in the readme, and to make sure the default character exports correctly before trying any other cards: https://github.com/FlailingFog/KK-Blender-Porter-Pack#usage-instructions-for-v6
That will narrow it down to the software versions, the process, or the card you're trying to export at least.

**Comment by WeeblyMon** [comment]
I get ya, it’s still frustrating to try making the tool work for days and
end up with nothing to show for it. I attempted with multiple blender, kkbp
and exporter versions and all of them had the missing bone errors, even on
default cards.

I’m grateful for the tool as it saves me modelling time and I usually don’t
mind texturing, but anime eyes has always been annoying for me to make so I
really wanted it to work so It could save me the hassle.

I gave up on getting the textures to show up as I’ve had no luck and no one
else found a fix to it. Thanks for your reply anyway, I wasn’t really
expecting one.

**Comment by MediaMoots** [comment]
@WeeblyMon 

What Koikatsu version are you using?
Try using BetterRepack RX15 and up. (You could use google to find it :)

**Comment by WeeblyMon** [comment]
I managed to get it working, I installed Blender 3.4 and the required KKBP files. I can only export if nothing is ticked in the export options which is better than nothing. When I import, I can only select the model.pmx thats outside the outfit files.

**Comment by MediaMoots** [comment]
@WeeblyMon 
Well yes, you shouldn't use the model.pmx inside the folders, those are exclusively used by the addon.
Only use the model.pmx in the root folder.

**Comment by MediaMoots** [comment]
@WeeblyMon The model.pmx files in the Outfit folders lack very important information that only the file in the root folder has, the addon merges all the pmx files together starting with the root file, so that why you can only import the pmx in the root folder.
