### ISSUE TITLE
Retargeting of animations

### ISSUE THREAD

**Issue by BlueScreenofDeath201** [FlailingFog/KK-Blender-Porter-Pack#411]
Please include the Koikatsu character card that causes the issue!  
You can copy paste it directly into this text box.  
(it can
![Screenshot 2023-03-31 003808](https://user-images.githubusercontent.com/125942857/229024219-e34830ac-734b-4450-93d6-f294b93d95b9.png)
 really help with the debug process)
![Koikatu_F_20221209135748771_Narita Reina](https://user-images.githubusercontent.com/125942857/229024325-3e5fe6ee-e5b8-47e5-a95b-3042d8b68fdb.png)
This is happening with all cards that I use. I usually try to debug these things myself, but my limited python knowledge leaves me at a loss sometimes.

**Comment by BlueScreenofDeath201** [comment]
Using Current Master commit, btw...if that helps at all

**Comment by FlailingFog** [comment]
This is something with the Rokoko plugin that I couldn't fix. You can do the reinstall like you did, or you can import an animation and click the X button next to the "Custom Naming Schemes" section that appears in the Rokoko retargeting panel and it should also work.
