### ISSUE TITLE
Not all the textures are imported. 

### ISSUE THREAD

**Issue by Lyeco** [FlailingFog/KK-Blender-Porter-Pack#415]
Some textures are white when I exported my character. Here is the card I am using. 
https://drive.google.com/file/d/10_aOmlwMME7bp2qN-iKllG8nn9xNjv3O/view?usp=share_link
(File exceeds 10mb) 
Here what it looks like in-game
![Screenshot_159](https://user-images.githubusercontent.com/15318314/231220807-72cf7ded-ac00-4545-aa3d-80ef0244f06b.png)
![Screenshot_160](https://user-images.githubusercontent.com/15318314/231220832-9340d107-c957-443b-a5c3-52a1b3353ba8.png)

Now, heres what it looks like in blender
![Screenshot_157](https://user-images.githubusercontent.com/15318314/231220951-a3de09f7-3ce2-4638-8287-bb33e3465359.png)
![Screenshot_158](https://user-images.githubusercontent.com/15318314/231220989-10851c77-2cc6-45b4-8b08-bb31b7690ebd.png)

Is there like something wrong on the way I exported the model???

**Comment by tomcatmew** [comment]
I have a similar problem when importing my character. Currently, I'm trying to modify the shader to see if there is any texture/transparency problem but so far no luck at all.
Please vote this issue up and I think 
this is a common issue that many people encounter. 
![Capture11](https://user-images.githubusercontent.com/20173396/235619538-a3845593-8cc3-49ed-ab68-93d6895cf885.PNG)
![Capture12](https://user-images.githubusercontent.com/20173396/235619549-8c2df125-fd32-4b98-bfa2-94e762cd9f96.PNG)

**Comment by 4ng4rp3** [comment]
The same thing happens to me, I have tried all possible version combinations and nothing

**Comment by FlailingFog** [comment]
Please see https://github.com/FlailingFog/KK-Blender-Porter-Pack/issues/401
I think you just need to adjust a few sliders.
![image](https://github.com/FlailingFog/KK-Blender-Porter-Pack/assets/65811931/4d6552f2-95a8-4df7-a2a3-e119c5557a92)
