### ISSUE TITLE
Textures not appearing.

### ISSUE THREAD

**Issue by NozoMooMoo** [FlailingFog/KK-Blender-Porter-Pack#416]
https://www.pixiv.net/en/artworks/98574171
Yes, it uses a modified head. But this wasn't an issue until now.

I've been using this exporter since last year now, haven't had issues with it until now.
Textures won't appear for what ever reason. I tried other models such as the vanilla koi model, still no textures.

![image](https://user-images.githubusercontent.com/130847474/232247333-63e4291c-7694-4dc7-ae83-b7e81f8989c4.png)
this might be useful, i hope so.

**Comment by FlailingFog** [comment]
It looks like you're importing the wrong .pmx in Iroha \ outfit 00 \ model.pmx
Try importing the Iroha \ model.pmx instead

**Comment by NozoMooMoo** [comment]
> It looks like you're importing the wrong .pmx in Iroha \ outfit 00 \ model.pmx Try importing the Iroha \ model.pmx instead

Oh, it worked. It became a habit for me to import the .pmx in the folder 0X. Thank you.
