### ISSUE TITLE
ERROR: Image "" not available. Keeping packed image

### ISSUE THREAD

**Issue by awaiting-death** [FlailingFog/KK-Blender-Porter-Pack#419]
![error](https://user-images.githubusercontent.com/29349728/234188388-b473518a-3c58-4f2e-86be-f951725d1c3e.png)

Hi, I got an issue related to importing character. These error messages continue endlessly. Is there anyting I can try to solve this problem? Thank you.

**Comment by awaiting-death** [comment]
I've updated KKBP exporter and it works well. Sorry for disturbing.

**Comment by dravpin** [comment]
This is now an issue again using blender 3.6 latest koikatsu sunshine plugin and mmd tools 2.9.2 as stated in the readme although is does eventually finish but a bunch of textures are missing
