### ISSUE TITLE
Can't import model blender 3.5

### ISSUE THREAD

**Issue by HaiseSaeye** [FlailingFog/KK-Blender-Porter-Pack#420]
![imagen](https://user-images.githubusercontent.com/99570315/234394976-30c7403b-553c-4d17-aeba-5c806e40d436.png)

**Comment by FlailingFog** [comment]
It looks like mmd_tools or CATS is not installed. Check the table in the readme for required software:
https://github.com/FlailingFog/KK-Blender-Porter-Pack#required-software
