### ISSUE TITLE
Error when importing the model, model just plain white or doesn't have texture (Blender 3.4, KKBP 6.4.2 and HF 3.16)

### ISSUE THREAD

**Issue by nyxriella** [FlailingFog/KK-Blender-Porter-Pack#422]
Excuse me, I don't understand how to read the log or anything about this so please help me.
I watched the videos and try step by step but blender won't import the model correctly. I also tried using default chika but it still gave me the same result. 

![image](https://user-images.githubusercontent.com/29898864/237001045-20065928-268d-46b5-a330-c7d1d734b323.png)
![image](https://user-images.githubusercontent.com/29898864/237000039-edf92825-2d53-414f-b385-d7cce1a2bfc1.png)

[blender info log.txt](https://github.com/FlailingFog/KK-Blender-Porter-Pack/files/11427447/blender.info.log.txt)
[blender log.txt](https://github.com/FlailingFog/KK-Blender-Porter-Pack/files/11427448/blender.log.txt)
[output_log.txt](https://github.com/FlailingFog/KK-Blender-Porter-Pack/files/11427497/output_log.txt)

**Comment by FlailingFog** [comment]
Can you try exporting with just the "Export single outfit" option selected? It looks like using Export variations + Export hit meshes is broken at the moment.

**Comment by nyxriella** [comment]
sorry for late reply, had been busy with my works recently. Already done do that part and still have the same result. Both with default chika card or even with my card.

**Comment by FenghuaJ** [comment]
> 您可以嘗試僅選擇「匯出單身服裝」選項即可匯出嗎？目前看來使用導出變體 + 匯出命中網格已損壞。

Hi, I've the same question of this. By using Blender 3.5, lastest KKBP and HF.

**Comment by FrankVargas427** [comment]
I have tried with 4 different models, 2 male and 2 female, and I too have this issue.  They're all wearing mostly the same outfits, accessories and other details, but they all crash when importing. Using Blender 3.5.1, KKBP 6.5.0 with the latest HF patch.

**Comment by FrankVargas427** [comment]
@FlailingFog it seems like this issue could happen if there is an outfit with no hair inside the card. One of the outfits in my cards is purely dedicated to accessories, and it has no hair. I added both back and front hair to that outfit and the model imports correctly into Blender.

**Comment by 777Leinad77** [comment]
@nyxriella  what is the dependency do you use with KK-Blender-Porter-Pack ,  cat blender plugin or mmd_tools ?
Because i get a similar issue while using mmd_tools with the same script seperate_body , but when i used cat blender plugin it worked.
If you use mmd_tools , try cat blender plugin.

**Comment by nyxriella** [comment]
> @nyxriella If you use mmd_tools , try cat blender plugin.
I did use both of this and the screenshot in this post was use the cat plugin.

**Comment by nyxriella** [comment]
> @nyxriella what is the dependency do you use with KK-Blender-Porter-Pack , cat blender plugin or mmd_tools ? Because i get a similar issue while using mmd_tools with the same script seperate_body , but when i used cat blender plugin it worked. If you use mmd_tools , try cat blender plugin.
