### ISSUE TITLE
Imported into blender, parts of body missing

### ISSUE THREAD

**Issue by LuoiZQ** [FlailingFog/KK-Blender-Porter-Pack#423]
The kkbp used is the net3.5 exported model in V4.21. blender uses KK-Blender-Porter-Pack-V6.5.0.zip and mmd_tools-v2.8.1.zip plugins to import pmx from kkbp in N menu. After automatic repair, the middle part of the body is missing, I don't know how to solve this.
The missing body parts after import are as follows
![issue](https://github.com/FlailingFog/KK-Blender-Porter-Pack/assets/78594251/e53063ef-9115-4dfd-87df-66cc1eba9cee)

**Comment by Frosti88** [comment]
Hi, i encountered the same issue as @LuoiZQ  and was able to fix it in Blenders shading workspace by removing the connection of the Alpha node in Body Shader and the Alpha node in Rim: Skin (see attached image)
![Untitled](https://github.com/FlailingFog/KK-Blender-Porter-Pack/assets/59071339/df01c95d-ad8b-40ad-a320-408360abf9ac)

**Comment by FlailingFog** [comment]
This is intentional to prevent the body clipping through the clothes, please check the pinned issue here: https://github.com/FlailingFog/KK-Blender-Porter-Pack/issues/378
