### ISSUE TITLE
Is there a way to speed up the prep process? 

### ISSUE THREAD

**Issue by johnvo0918** [FlailingFog/KK-Blender-Porter-Pack#424]
Okay, I get that VERY SIMPLE (slow) is slow but my prep of (7outfits 4 hair) has been going on for 4 hours and i dont see any changes. even the console log is still moving...

**Comment by FlailingFog** [comment]
I don't think so. The simple and very simple options use the [CATS merge weights function](https://github.com/absolute-quantum/cats-blender-plugin/blob/master/tools/armature_manual.py) so any speedups would come from that project. There's also nothing preventing you from keeping all the bones, or just deleting the bones you don't want (but I don't know what would happen to the bone weights in that case).
