### ISSUE TITLE
VRC:MMD Face Won't Work.

### ISSUE THREAD

**Issue by KaraEdword** [FlailingFog/KK-Blender-Porter-Pack#425]
I'm not a 3d Modeler or an programmer so if I'm wrong feel free to correct me.

My Koikatsu avatar that exports with KKBP can't use any face animation in vrc mmd world

I'm pretty sure I got everything right in the Unity section. WriteDefult on, parameter or else is correct. so I assume that it won't work bcuz of the KKBP. Or maybe I'm wrong.

Here is the video
https://youtu.be/WZOS_xG3c6g

anyway, thank you for your time.

**Comment by FlailingFog** [comment]
If I had to guess the shapekeys need to be renamed to match an mmd model's face shapekeys.
