### ISSUE TITLE
LUT function does not work

### ISSUE THREAD

**Issue by KotoriKoi** [FlailingFog/KK-Blender-Porter-Pack#428]
The LUT function of kkbp6.5 does not work in blender3.5 import model, this may be the cause of issue #427.
In the Image Editor works fine, but it doesn't solve #427.
Can anyone verify it?
The console displays the following warning：
![image](https://github.com/FlailingFog/KK-Blender-Porter-Pack/assets/91445888/1c25bd17-4196-44b6-a157-b1e08eeae3f1)

**Comment by FlailingFog** [comment]
this should be fixed in kkbp 7.0.0
