### ISSUE TITLE
Exporter forces wrong animation, breaking the resulting rig

### ISSUE THREAD

**Issue by Fantazilite** [FlailingFog/KK-Blender-Porter-Pack#441]
Whenever I export any character from Koikatsu Sunshine EX (BetterRepack R10), even the default ones, they are forced into a hand-behind-head pose, which then results in the end result in blender being completely displaced and broken. In videos I see they're supposed to stay in a default pose, but they don't do this for me. What's going wrong?

**Comment by ghosting3175** [comment]
Can confirm.

Maybe something changed with BetterRepack but T-Pose is missing in the character creator and the plugin exports using the final pose in the list.
