### ISSUE TITLE
textures not importing KKBP 6.5 Blender 3.5.0  

### ISSUE THREAD

**Issue by HaiseSaeye** [FlailingFog/KK-Blender-Porter-Pack#448]
Importing pmx files with mmdtools...
Info: Imported MMD model from "E:\KK\Koikatsu.Party\Koikatsu.Party\Koikatsu Party After Party\Export_PMX\20230713225223_マリン宝鐘\model.pmx"
Info: Imported MMD model from "E:\KK\Koikatsu.Party\Koikatsu.Party\Koikatsu Party After Party\Export_PMX\20230713225223_マリン宝鐘\Outfit 00\model.pmx"
Info: Imported MMD model from "E:\KK\Koikatsu.Party\Koikatsu.Party\Koikatsu Party After Party\Export_PMX\20230713225223_マリン宝鐘\Outfit 01\model.pmx"
Info: Imported MMD model from "E:\KK\Koikatsu.Party\Koikatsu.Party\Koikatsu Party After Party\Export_PMX\20230713225223_マリン宝鐘\Outfit 02\model.pmx"
Info: Imported MMD model from "E:\KK\Koikatsu.Party\Koikatsu.Party\Koikatsu Party After Party\Export_PMX\20230713225223_マリン宝鐘\Outfit 03\model.pmx"
Info: Imported MMD model from "E:\KK\Koikatsu.Party\Koikatsu.Party\Koikatsu Party After Party\Export_PMX\20230713225223_マリン宝鐘\Outfit 04\model.pmx"
Info: Imported MMD model from "E:\KK\Koikatsu.Party\Koikatsu.Party\Koikatsu Party After Party\Export_PMX\20230713225223_マリン宝鐘\Outfit 05\model.pmx"
Info: Imported MMD model from "E:\KK\Koikatsu.Party\Koikatsu.Party\Koikatsu Party After Party\Export_PMX\20230713225223_マリン宝鐘\Outfit 06\model.pmx"

Finalizing PMX file...
Modifying armature...
Finished in 10.3s

Translating and combining shapekeys...
Warning: 1 x Draw window and swap: 167.3247 ms, average: 167.32470000 ms
Warning: 1 x Draw window and swap: 57.5083 ms, average: 57.50830000 ms
Warning: 1 x Draw window and swap: 47.3783 ms, average: 47.37830001 ms
Warning: 1 x Draw window and swap: 47.9209 ms, average: 47.92090000 ms
Warning: 1 x Draw window and swap: 46.4864 ms, average: 46.48640000 ms
Warning: 1 x Draw window and swap: 47.2519 ms, average: 47.25190000 ms
Warning: 1 x Draw window and swap: 46.8837 ms, average: 46.88370000 ms
Warning: 1 x Draw window and swap: 47.9870 ms, average: 47.98700000 ms
Warning: 1 x Draw window and swap: 46.6712 ms, average: 46.67120000 ms
Warning: 1 x Draw window and swap: 46.0796 ms, average: 46.07960000 ms
Warning: 1 x Draw window and swap: 44.9570 ms, average: 44.95700001 ms
Warning: 1 x Draw window and swap: 45.0386 ms, average: 45.03859999 ms
Warning: 1 x Draw window and swap: 45.0200 ms, average: 45.02000000 ms
Warning: 1 x Draw window and swap: 44.2815 ms, average: 44.28150000 ms
Warning: 1 x Draw window and swap: 44.5511 ms, average: 44.55110000 ms
Warning: 1 x Draw window and swap: 45.7595 ms, average: 45.75950000 ms
Warning: 1 x Draw window and swap: 45.5030 ms, average: 45.50300000 ms
Warning: 1 x Draw window and swap: 44.0159 ms, average: 44.01590000 ms
Warning: 1 x Draw window and swap: 46.3664 ms, average: 46.36640000 ms
Warning: 1 x Draw window and swap: 45.2527 ms, average: 45.25270000 ms
Warning: 1 x Draw window and swap: 44.9743 ms, average: 44.97430000 ms
Warning: 1 x Draw window and swap: 47.5229 ms, average: 47.52290000 ms
Warning: 1 x Draw window and swap: 46.0580 ms, average: 46.05800000 ms
Warning: 1 x Draw window and swap: 45.4247 ms, average: 45.42470000 ms
Warning: 1 x Draw window and swap: 55.9059 ms, average: 55.90590000 ms
Warning: 1 x Draw window and swap: 58.5259 ms, average: 58.52590000 ms
Warning: 1 x Draw window and swap: 61.8808 ms, average: 61.88080000 ms
Warning: 1 x Draw window and swap: 56.5424 ms, average: 56.54240000 ms
Warning: 1 x Draw window and swap: 47.5861 ms, average: 47.58610000 ms
Warning: 1 x Draw window and swap: 47.4978 ms, average: 47.49780001 ms
Warning: 1 x Draw window and swap: 47.8674 ms, average: 47.86740000 ms
Warning: 1 x Draw window and swap: 52.8575 ms, average: 52.85750000 ms
Warning: 1 x Draw window and swap: 52.3857 ms, average: 52.38569999 ms
Warning: 1 x Draw window and swap: 47.6727 ms, average: 47.67270000 ms
Warning: 1 x Draw window and swap: 50.7008 ms, average: 50.70080000 ms
Warning: 1 x Draw window and swap: 45.3253 ms, average: 45.32530000 ms
Warning: 1 x Draw window and swap: 47.1347 ms, average: 47.13470000 ms
Warning: 1 x Draw window and swap: 46.9480 ms, average: 46.94800000 ms
Warning: 1 x Draw window and swap: 45.8514 ms, average: 45.85140000 ms
Warning: 1 x Draw window and swap: 46.8663 ms, average: 46.86630000 ms
Warning: 1 x Draw window and swap: 44.6828 ms, average: 44.68280000 ms
Warning: 1 x Draw window and swap: 45.3150 ms, average: 45.31500000 ms
Warning: 1 x Draw window and swap: 48.1553 ms, average: 48.15530000 ms
Warning: 1 x Draw window and swap: 46.5525 ms, average: 46.55250000 ms
Warning: 1 x Draw window and swap: 47.6595 ms, average: 47.65950000 ms
Warning: 1 x Draw window and swap: 48.0441 ms, average: 48.04410000 ms
Finished in 3.27s

Separating body, clothes, hair, hitboxes and shadowcast, then removing duplicate materials...
Info: Removed 21 slots
Info: Removed 21 slots
Info: Removed 19 slots
Info: Removed 7 slots
Moving duplicate material Bonelyfans in slot 14 to the original slot 1
Moving duplicate material cf_m_sirome_00 in slot 9 to the original slot 8
Info: Removed 2 slots
Moving duplicate material H_marinn_b1 8150 in slot 7 to the original slot 6
Moving duplicate material H_marinn_b1 11720 in slot 9 to the original slot 8
Moving duplicate material H_marinn_b1 11720 in slot 10 to the original slot 8
Moving duplicate material H_marinn_b1 16890 in slot 12 to the original slot 11
Moving duplicate material H_marinn_b1 16890 in slot 13 to the original slot 11
Info: Removed 5 slots
Moving duplicate material H_marinn_b1 6911 in slot 5 to the original slot 4
Moving duplicate material H_marinn_b1 10481 in slot 7 to the original slot 6
Moving duplicate material H_marinn_b1 10481 in slot 8 to the original slot 6
Moving duplicate material H_marinn_b1 15651 in slot 10 to the original slot 9
Moving duplicate material H_marinn_b1 15651 in slot 11 to the original slot 9
Info: Removed 5 slots
Moving duplicate material Skirt 16972 in slot 9 to the original slot 8
Moving duplicate material Skirt 16972 in slot 10 to the original slot 8
Moving duplicate material Skirt 16972 in slot 14 to the original slot 8
Moving duplicate material Skirt 16972 in slot 15 to the original slot 8
Moving duplicate material Acc1 16972 in slot 12 to the original slot 11
Moving duplicate material Acc1 16972 in slot 13 to the original slot 11
Moving duplicate material Fuku_A 17012 in slot 20 to the original slot 16
Moving duplicate material Fuku_A 17012 in slot 21 to the original slot 16
Moving duplicate material Fuku_B 17012 in slot 18 to the original slot 17
Moving duplicate material Fuku_B 17012 in slot 19 to the original slot 17
Moving duplicate material Fuku_B 17012 in slot 22 to the original slot 17
Moving duplicate material pants 17182 in slot 25 to the original slot 24
Moving duplicate material pants 17182 in slot 26 to the original slot 24
Moving duplicate material glove 17302 in slot 31 to the original slot 30
Moving duplicate material shoes 17492 in slot 34 to the original slot 33
Info: Removed 15 slots
Moving duplicate material EAR 13113 in slot 2 to the original slot 1
Moving duplicate material EAR 13113 in slot 3 to the original slot 1
Moving duplicate material EAR 13113 in slot 4 to the original slot 1
Info: Removed 3 slots
Moving duplicate material cf_m_sweater01 10294 in slot 6 to the original slot 5
Info: Removed 1 slots
Moving duplicate material cf_m_hair_b_19_01 4185 in slot 3 to the original slot 2
Moving duplicate material cf_m_hair_b_19_01 4185 in slot 4 to the original slot 2
Moving duplicate material Mai Material Main2 10405 in slot 8 to the original slot 7
Moving duplicate material Mai Material Main1 10465 in slot 11 to the original slot 9
Moving duplicate material Mai Material Main1 10465 in slot 12 to the original slot 9
Moving duplicate material Mai Material Main1 10465 in slot 14 to the original slot 9
Moving duplicate material Mai Material Main1 10465 in slot 15 to the original slot 9
Info: Removed 7 slots
Moving duplicate material YukiLBMat 10766 in slot 5 to the original slot 4
Moving duplicate material YukiLBMat 10766 in slot 6 to the original slot 4
Moving duplicate material YukiLBMat 10766 in slot 7 to the original slot 4
Moving duplicate material YukiLBMat 10766 in slot 8 to the original slot 4
Moving duplicate material YukiLBMat 10766 in slot 9 to the original slot 4
Moving duplicate material YukiLBMat 10766 in slot 10 to the original slot 4
Info: Removed 6 slots
Warning:        Material wasn't found when separating materials: cf_m_hair_b_06_00 3985
Warning:        Material wasn't found when separating materials: cf_m_hair_b_19_01 4185
Error: Nothing selected

Error:          Unknown python error occurred
Traceback (most recent call last):
  File "C:\Users\haise\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\KK-Blender-Porter-Pack-650\importing\separatebody.py", line 700, in execute
    separate_everything(context)
  File "C:\Users\haise\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\KK-Blender-Porter-Pack-650\importing\separatebody.py", line 204, in separate_everything
    separate_materials(outfit, hair_mat_list)
  File "C:\Users\haise\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\KK-Blender-Porter-Pack-650\importing\separatebody.py", line 145, in separate_materials
    bpy.ops.mesh.separate(type='SELECTED')
  File "C:\Program Files\Blender Foundation\Blender 3.5\3.5\scripts\modules\bpy\ops.py", line 113, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Error: Nothing selected

Error: Traceback (most recent call last):
  File "C:\Users\haise\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\KK-Blender-Porter-Pack-650\importing\separatebody.py", line 700, in execute
    separate_everything(context)
  File "C:\Users\haise\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\KK-Blender-Porter-Pack-650\importing\separatebody.py", line 204, in separate_everything
    separate_materials(outfit, hair_mat_list)
  File "C:\Users\haise\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\KK-Blender-Porter-Pack-650\importing\separatebody.py", line 145, in separate_materials
    bpy.ops.mesh.separate(type='SELECTED')
  File "C:\Program Files\Blender Foundation\Blender 3.5\3.5\scripts\modules\bpy\ops.py", line 113, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Error: Nothing selected

Traceback (most recent call last):
  File "C:\Users\haise\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\KK-Blender-Porter-Pack-650\importing\importbuttons.py", line 93, in execute
    bpy.ops.kkb.separatebody('INVOKE_DEFAULT'),
  File "C:\Program Files\Blender Foundation\Blender 3.5\3.5\scripts\modules\bpy\ops.py", line 111, in __call__
    ret = _op_call(self.idname_py(), C_dict, kw, C_exec, C_undo)
RuntimeError: Error: Traceback (most recent call last):
  File "C:\Users\haise\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\KK-Blender-Porter-Pack-650\importing\separatebody.py", line 700, in execute
    separate_everything(context)
  File "C:\Users\haise\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\KK-Blender-Porter-Pack-650\importing\separatebody.py", line 204, in separate_everything
    separate_materials(outfit, hair_mat_list)
  File "C:\Users\haise\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\KK-Blender-Porter-Pack-650\importing\separatebody.py", line 145, in separate_materials
    bpy.ops.mesh.separate(type='SELECTED')
  File "C:\Program Files\Blender Foundation\Blender 3.5\3.5\scripts\modules\bpy\ops.py", line 113, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Error: Nothing selected

![imagen](https://github.com/FlailingFog/KK-Blender-Porter-Pack/assets/99570315/43b94bde-d2bb-49ae-838b-3417002c4ac7)

**Comment by Weetile** [comment]
Same issue.
