### ISSUE TITLE
Textures not importing and Blender crash

### ISSUE THREAD

**Issue by CrystalGoddess** [FlailingFog/KK-Blender-Porter-Pack#449]
Multiple textures are not importing when importing the model and whenever I click the button "Prep for target application" (always with the option "Unity - VRM compatible" as that is what I need it for) Blender just crashes, no error dialogue box, it just closes. I have tried this with both versions 3.5.0 and 3.6.0 of Blender with version 6.5.0 of KKBP and version 2.8.1 of MMD Tools.

**Comment by FlailingFog** [comment]
this should be fixed in kkbp 7.0.0
