### ISSUE TITLE
How to import multiple models

### ISSUE THREAD

**Issue by mh8859** [FlailingFog/KK-Blender-Porter-Pack#451]
After importing one model, I want to import another model, but the import button of the plugin has turned gray. What should I do?

**Comment by FrankVargas427** [comment]
I have tried to do so as well, and [this ](https://github.com/FlailingFog/KK-Blender-Porter-Pack/issues/430#issuecomment-1599751644) is the most official answer to this concept. In short, do multiple saves for each character and then join them using the Append save function.

**Comment by FlailingFog** [comment]
This is currently not supported atm. Closing in favor of https://github.com/FlailingFog/KK-Blender-Porter-Pack/issues/430
