### ISSUE TITLE
Screen goes black/gpu problem

### ISSUE THREAD

**Issue by PauloKami** [FlailingFog/KK-Blender-Porter-Pack#454]
I'm using blender 3.6 (I tested other versions and the same error happens); KKBP 6.5.0; CATS (I believe it is 0.19)

Every time I try to import the model, after a few seconds my computer stops and my screen goes black and goes into "Energy Management" mode (I don't know if it's translated correctly), sometimes it comes back alone with the bug report window from amd, but most times I have to restart my computer to get it back. I tested with Koikatsu Sunshine and Party models, both don't work. I sent the plugins to a friend and it worked fine for him.
Something that I find strange is that my computer and that of KoikatsuBlendlet (the guy who made the plugin tutorials) are very similar, my GPU is an RX550 4GB, I don't think my computer is the problem, but anything is possible :/

**Comment by FlailingFog** [comment]
That sounds more like a driver issue than a plugin issue to be honest...
I didn't have any problems like that when I was using the RX470 card.
