### ISSUE TITLE
Imported characters show with a complete white body, textureless when using kkbp exporter when importing them to blender using a single outfit option in kk/kks

### ISSUE THREAD

**Issue by NWZ1** [FlailingFog/KK-Blender-Porter-Pack#457]
So, for some unknown reason, every single character card that has just one single outfit when exported to Blender is completely unable to load the character textures with the textures for the clothing giving out a completely white textureless character. Strangely, however, it appears that this does not happen at all with any given character with all outfits and alternate clothing enabled though.

**Comment by FlailingFog** [comment]
This is working correctly in 6.6.0 now
