### ISSUE TITLE
Cannot convert to Rigify if Face Type is not 1

### ISSUE THREAD

**Issue by higeinu3594** [FlailingFog/KK-Blender-Porter-Pack#458]
Cannot convert to Rigify if Face Type is not 1

When I convert a face type other than 1 to Rigify in Blender 3.5 3.6, it is not converted properly.

KKBP V6.5.0
KKBP_Exporter_V4.21

I tried with many characters and the solution was to change Face Type.
If it is Face Type 1, it succeeds.
![230822118](https://github.com/FlailingFog/KK-Blender-Porter-Pack/assets/115856191/88683349-a822-493c-b410-0731494f9932)
![230822119](https://github.com/FlailingFog/KK-Blender-Porter-Pack/assets/115856191/ebf6a0c7-c0f8-4e17-b230-24da684a656b)

Otherwise, Rigify will be as shown in the image.

How can I convert a character with a different Face Type to Rigify?
Only the conversion does not work.
Other than that, I am able to import without any problems.

**Comment by higeinu3594** [comment]
The images are Face Type 2 and 3.

**Comment by ilcane87** [comment]
Hi @higeinu3594, you are right, it seems that when picking those face types the 'Left Eye' and 'Right Eye' vertex groups aren't populated, even with the standard armature where the eyes consequently don't work, which in turn causes the Rigify conversion error.

Fortunately it's very easy to solve manually, just follow these steps:

1. Import the character with the 'KKBP Armature' option;
2. Select the 'Body' object and go into Edit mode, then in the Object Data Properties section of the inspector, look for the Left Eye vertex group;
3. Make sure nothing is selected, then hover the mouse over the left pupil and press L to select all linked vertices and add them to the Left Eye vertex group with the weight of 1, like in the picture below:
![2023-08-25 13_26_14-Blender_  C__Users_ilcane87_Desktop_untitled_001 blend](https://github.com/FlailingFog/KK-Blender-Porter-Pack/assets/34897042/445b739a-1408-48bd-bf25-5979d6b2867d)
4. Repeat the same process for the Right Eye vertex group;
5. Now the eyes movement should work with the default armature, but you need to convert it to the Rigify one, so go back to Object mode, select the armature object and nothing else, then in the KKBP addon panel look for the 'Convert for Rigify' star shaped button in the Extras and click it, as shown in the image below:
![2023-08-25 13_27_37-Blender_  C__Users_ilcane87_Desktop_untitled_001 blend](https://github.com/FlailingFog/KK-Blender-Porter-Pack/assets/34897042/941974f7-b49d-4694-a700-a7df1d0c46fe)

At that point you should have the Rigify armature with fully working eyes and everything else.

**Comment by higeinu3594** [comment]
Thank you very much!
Tried Face2 3 with default character and succeeded!
Other character (Face3) was also successful.
