### ISSUE TITLE
All of the sudden, Eyes do not import.

### ISSUE THREAD

**Issue by TheMaskedMan00** [FlailingFog/KK-Blender-Porter-Pack#460]
This happens with every card now, even ones that worked with previous versions of the plugin, that I had exported back then. 
![image](https://github.com/FlailingFog/KK-Blender-Porter-Pack/assets/46354545/eb17b5f9-a99a-42b9-b65f-5b7a67d2c8c2)
The eyes just refuse to import. The files are in fact there, And i did re install the plugin and even updated to blender 3.5 but still the same result. Here is the log file 
[KKBP Log.txt](https://github.com/FlailingFog/KK-Blender-Porter-Pack/files/12492145/KKBP.Log.txt)

**Comment by TheMaskedMan00** [comment]
I managed to fix it myself, I will post a pull request

**Comment by FlailingFog** [comment]
See https://github.com/FlailingFog/KK-Blender-Porter-Pack/pull/461
