### ISSUE TITLE
Error while importing

### ISSUE THREAD

**Issue by Sharaj00** [FlailingFog/KK-Blender-Porter-Pack#467]
[Card](https://db.bepis.moe/card/download/KK_233923.png)
![image](https://github.com/FlailingFog/KK-Blender-Porter-Pack/assets/16534883/e477ab7f-1ef2-4e7e-8e89-9e47072479ed)

**Comment by LegionInstaller** [comment]
Same

**Comment by FlailingFog** [comment]
The "modified headmod" head should import without errors now
