### ISSUE TITLE
Requesting increased compatibility for MMD motion files?

### ISSUE THREAD

**Issue by BugMonkey42335** [FlailingFog/KK-Blender-Porter-Pack#47]
Would it be possible to add a button that toggles the bones back to MMD naming convention so that we can use MMD motion files? They partially work but I think that the bones being renamed is preventing the motion files from working. It might also be useful to have a button to toggle bone constraints, since I think that might also be preventing the animations from working correctly.

**Comment by FlailingFog** [comment]
Sure, most of the code for this is already written so it should be easy to add

**Comment by miyabi-95** [comment]
On a similar note, I was having issues with my character's elbow twist bones while testing out MMD motions in VRMLiveViewer, and I ended up fixing them by selecting "Freeze T-Pose" under the UniVRM menu before you export from Unity!

**Comment by FlailingFog** [comment]
Here's what I've come across regarding this:
* The MMD bone names are actually separate from the ones displayed in Blender, so mmd bone names can be applied to every model, even if the user isn't going to be importing vmds (added this in the [V5-merger branch](https://github.com/FlailingFog/KK-Blender-Shader-Pack/tree/V5-merger))
* Hand and arm IKs need to be disabled after importing the motion (added a toggle in V5-merger under the Extras panel to do this)
* Even with those changes, the legs refuse to work. I'll see if the mmd-focused constraints used by the original pmx exporter in V4 can be used to fix it

**Comment by XyangHuang** [comment]
I found a way to fix the leg IK when importing vmd files.
First. Clear target.
![image](https://user-images.githubusercontent.com/11631364/153880377-dd5c3df1-432d-471e-9e0c-b7ca65f5eaae.png)
Second.  Set IK constraints.
![image](https://user-images.githubusercontent.com/11631364/153880467-334e7dc6-6b52-4447-803e-76b0aafbbdd3.png)

But still don't know how to fix fk hand and waist.
![image](https://user-images.githubusercontent.com/11631364/153880830-f9848dc9-6c95-4a83-8835-4f87e6792978.png)
![image](https://user-images.githubusercontent.com/11631364/153880915-4b811042-0877-4281-b731-45525d8161fa.png)
