### ISSUE TITLE
About skirt weights

### ISSUE THREAD

**Issue by higeinu3594** [FlailingFog/KK-Blender-Porter-Pack#474]
I have never animated skirts before and this was the first time I read about them, but most of them were unweighted.

I was able to move clothes like pants without any problem, but how should I move skirts?

There are many ways to do this, such as weight transfers, impro

ving the bones, or introducing physics into the bones, etc. Is there a better way?
I want the skirt to follow when the legs are lifted.

![231001177](https://github.com/FlailingFog/KK-Blender-Porter-Pack/assets/115856191/e0686f89-117a-4879-beec-f6c9b69b873e)

**Comment by higeinu3594** [comment]
Blender version is 3.6
KKBP is 6.5

KKBP 6.6 has been pre-released but I have not tried it.
If I install it, will it solve this problem?

**Comment by FlailingFog** [comment]
The skirt bones have weights, but they aren't connected to the leg weights. You can move the skirt bones by rotating the red spatula looking bones in the Skirt layer or rotating the green circular bones in the Skirt (detail) layer of the armature. 
![image](https://github.com/FlailingFog/KK-Blender-Porter-Pack/assets/65811931/6e665009-c436-4ad5-b10c-3c944a1b3999)

**Comment by higeinu3594** [comment]
Thank you very much.
I will try to animate it this way!
