### ISSUE TITLE
Minor color bug with skin darker regions turning light blue?

### ISSUE THREAD

**Issue by EvgeneKuklin** [FlailingFog/KK-Blender-Porter-Pack#481]
All skin darker regions went to 00FFFF for some reason. 
Manual fix in KK Body material's shader settings (Body overlays)

(Sunshine, KK-Blender-Porter-Pack: V6.6.2, [HF Patch v1.12 for Koikatsu Sunshine](https://github.com/ManlyMarco/KKS-HF_Patch/releases/tag/v1.12))
[blender_import_logs.txt](https://github.com/FlailingFog/KK-Blender-Porter-Pack/files/12908130/blender_import_logs.txt)

![Example](https://github.com/FlailingFog/KK-Blender-Porter-Pack/assets/52193937/8b0701e7-4237-4a0f-bee7-97eba6b85f9d)
![KoikatsuSun_F_20230729151118112](https://github.com/FlailingFog/KK-Blender-Porter-Pack/assets/52193937/f4d0b31b-d451-4322-8964-9f21412f8186)

P.S. Thanks for your work!

**Comment by FlailingFog** [comment]
The color 00FFFF is the placeholder color used when the import scripts can't find a color value.
I guess the exporter couldn't find the colors for this body type in the KK_MaterialData.json file, so it left the values blank.
![image](https://github.com/FlailingFog/KK-Blender-Porter-Pack/assets/65811931/ad9ba024-1f2c-4590-81d4-52c2969fa315)

**Comment by evshiron** [comment]
I just upgraded from Blender 3.5 and KKBP V6.5.0 to Blender 3.6 and KKBP V6.6.2 and encountered this issue. The body colors are all `00FFFF` including the nail color.

There are some other issues:

* Importing Chika or other vanilla models is not working
  * `UnboundLocalError: local variable 'shadow_color' referenced before assignment` at [modifymaterial.py](https://github.com/FlailingFog/KK-Blender-Porter-Pack/blob/master/importing/modifymaterial.py#L1604)
  * The assignment routine might not be called
* If Blender System Console is showing before importing in KKBP, Blender will become unresponsive and the importing will never finish

I am using KKS BR R9, and KKBP V6.5.0 was working pretty well.

**Comment by FieryLionite** [comment]
looks like this issue is still there for KKSunshine, I use latest KKS BR10 and KKBP V6.6.2
