### ISSUE TITLE
Option/workaround for importing underwear/other clothing with empty faces?

### ISSUE THREAD

**Issue by VP1989** [FlailingFog/KK-Blender-Porter-Pack#482]
Hello.

![image](https://github.com/FlailingFog/KK-Blender-Porter-Pack/assets/8047059/4590313f-0653-4de5-921b-c3cf7f924168)

If I import some types of clothing from Koikatsu, like thongs, to Blender, they end up being these types of meshes for shorts with a lot of empty/clear faces (Please correct me if there is a different term) like in the image above. I am mostly using Koikatsu models for animation in Blender and this can cause issues with the clothing simulation.

I noticed there are MMD Clothes on DeviantArt that are also pmx files and they do not have those empty faces. Other than manually cutting out the thong without affecting the textures, is there a workaround for this to save time or is it at all possible for the plugin to import clothes without those empty faces?

**Comment by FlailingFog** [comment]
Some clothing uses the same base mesh with different textures, so that's just how it comes from the game. I'm not aware of any way to automatically delete the transparent faces.
