### ISSUE TITLE
Mixamo animation

### ISSUE THREAD

**Issue by shadow189** [FlailingFog/KK-Blender-Porter-Pack#484]
Hi, I would like a mixamo animation importer option, is posible?

**Comment by FlailingFog** [comment]
I think you can just edit this file and enter the Mixamo bone names:
https://github.com/FlailingFog/KK-Blender-Porter-Pack/blob/master/extras/animationlibrary/Rokoko%20retargeting%20list%20(koikatsu%20fbx%20to%20KKBP%20Rigify).json

It should be in this format:
```
"custom_bone_Mixamo_Hips_bone_name": [
            "Mixamo_Hips_bone_name",
            "KKBP_armature_bone_name" 
        ],
```

Then you can load this file in and retarget using the Rokoko addon: https://www.youtube.com/watch?v=Nyxeb48mUfs&t=713s

**Comment by shadow189** [comment]
Thanks, it helps a lot
