### ISSUE TITLE
Baking, Emmisions, and general texture stuff

### ISSUE THREAD

**Issue by HarryBols** [FlailingFog/KK-Blender-Porter-Pack#486]
Please include the Koikatsu character card that causes the issue!  
You can copy paste it directly into this text box.  
(it can really help with the debug process)
![Koikatu_F_20231019150710067_Kurta Kurapika](https://github.com/FlailingFog/KK-Blender-Porter-Pack/assets/77550756/43cd260e-8f28-4a04-b5d9-2ee612c98413)
Every single character still bakes white
All characters emit light 
Why is the recalculate texture button gone

**Comment by FlailingFog** [comment]
I can't replicate the first two. Are you using the default settings for everything?
I removed the recalculate colors button because I think the default "Experimental" option gives the best head start for dark colors in most scenarios. If you want to use a different color option, you'll have to choose the option before clicking the import button now

**Comment by HarryBols** [comment]
Yes i use the default settings
I used the recalculate colors button so when i append a character it regains the color instead of being washed out, the dark colors thing never meant or did anything for me. The dark colors option only served to make more nodes that i would have to fiddle with until i finally got the light colors to work.

**Comment by FlailingFog** [comment]
Okay, I see. It should be easy to add a button to let you saturate all the images again, so I'll do that.  
I also used the default settings (with single outfit enabled) and didn't see any baking or emission issues, so I'm not sure what could be causing that...

**Comment by HarryBols** [comment]
Outlines also never worked

**Comment by FlailingFog** [comment]
this should be fixed in kkbp 7.0.0
