### ISSUE TITLE
animation library from mixamo?....

### ISSUE THREAD

**Issue by hsxfunc** [FlailingFog/KK-Blender-Porter-Pack#488]
I like this plugin very much. When using the function of creating action library, I tried to write a json file of animation redirection of fbx file downloaded from mixamo. Because I am not good at writing code, and the version of rokoko I actually use is 1.0, so I am not sure whether this can be used by everyone. But I think it might be useful for people who want to do animation. I'm not sure if I did something illegal (because I don't know the github rules), and if the question is bad, it can be deleted（I am not good at English, I hope you can understand）
Finally, I hope this plugin gets better and better

![55779567)JH~9_}3~AQYT$G](https://github.com/FlailingFog/KK-Blender-Porter-Pack/assets/129939853/bfb970ce-be17-4069-a802-b75fb1eb0f2b)
[rokoko1.0.json](https://github.com/FlailingFog/KK-Blender-Porter-Pack/files/13054052/rokoko1.0.json)
[rokoko1.4.json](https://github.com/FlailingFog/KK-Blender-Porter-Pack/files/13054101/rokoko1.4.json)

**Comment by FlailingFog** [comment]
Hey, thank you! I will integrate this into the plugin.
