### ISSUE TITLE
Broken colormasks on accessories when using cycles

### ISSUE THREAD

**Issue by savorytuna777** [FlailingFog/KK-Blender-Porter-Pack#513]
Card: 
![Cirno](https://github.com/FlailingFog/KK-Blender-Porter-Pack/assets/156110312/9145e6bd-487f-4201-83d0-3809f193d06d)
Using: Blender 3.6.2, KKBP V6.6.2,  KKBP Exporter V4.30, and mmd_tools v2.9.2

Colormasks on accessories seem to be broken for me when using the importer with the Cycles setting. No matter what options I change, the colormask will always output the same orange color on light and dark.
![scr2](https://github.com/FlailingFog/KK-Blender-Porter-Pack/assets/156110312/cbecdabc-aec5-4965-96c6-1da72a9c3d0c)
![scr3](https://github.com/FlailingFog/KK-Blender-Porter-Pack/assets/156110312/e878d78e-713b-4aa4-9d7e-b362b0b9cc85)
No issues with the same card on Eevee
![scr1](https://github.com/FlailingFog/KK-Blender-Porter-Pack/assets/156110312/8905df40-7cd1-4ab3-a502-6fc7af6f8a92)
Luckily I can work around it by uploading a colored texture into the material in Koikatsu, but its a pain. Any ideas?

**Comment by FlailingFog** [comment]
I don't know why, but this now works in blender 4.2 / kkbp 7.0.0 despite not changing anything...
