### ISSUE TITLE
White textures on Hair and Clothes. Changing Maintex sliders doesnt fix

### ISSUE THREAD

**Issue by JAzerad** [FlailingFog/KK-Blender-Porter-Pack#520]
Importing this card breaks a few materials. Finding the materials and messing with the sliders doesn't get them to the proper colours and attempting to change the Maintex setting doesn't help either **(1)**. Attempting to change the colour mask settings can fix the model **(2)** but when trying to bake and export the model as a FBX it seems to cause parts of the model to be completely transparent. **(3)**

**1**
![Hakari Issue 1](https://github.com/FlailingFog/KK-Blender-Porter-Pack/assets/62903133/d31201d7-fe63-4181-8fec-026e1d60c4ca)

**2**
![Hakari Issue 2](https://github.com/FlailingFog/KK-Blender-Porter-Pack/assets/62903133/2c0ff6c5-117c-4357-b9d0-334c2e57fe11)

**3**
![Hakari Issue 3](https://github.com/FlailingFog/KK-Blender-Porter-Pack/assets/62903133/fb0fc70b-10ae-4af8-8b69-650adf62cd93)

card
![KK_321217](https://github.com/FlailingFog/KK-Blender-Porter-Pack/assets/62903133/ad48b55d-40f1-4714-83f7-67e0c5227355)

**Comment by z4m1** [comment]
I am the same way. Fortunately, it looks like he will fix it in the next release! Thanks!

**Comment by FlailingFog** [comment]
Not sure what I changed, but when I tested it on aug 2nd it looked like it worked correctly in kkbp 7.0.0
