### ISSUE TITLE
Trying to Import model from "Koikatsu" using KKBP, but I keep getting Python Traceback Errors

### ISSUE THREAD

**Issue by xxSuicidium** [FlailingFog/KK-Blender-Porter-Pack#522]
Title explains itself, i'm using Blender 3.6, CATS 0.19.0, KKBP v6.6.2, material-combiner-addon.

![Screenshot_1](https://github.com/FlailingFog/KK-Blender-Porter-Pack/assets/159596369/7c6e1d71-e498-4dcb-9fdb-e3b89cec4e58)

How do I fix this?
Any help would be greatly appreciated, thank you in advance. : )

**Comment by Pippers02** [comment]
Also getting the same issue.
Everything is installed to be the correct versions, but every time I try to import a model I get this error.
![Screenshot 2024-02-21 155707](https://github.com/FlailingFog/KK-Blender-Porter-Pack/assets/160755985/118c5059-b8d6-46b2-829c-5d4efbdc1274)

**Comment by FlailingFog** [comment]
Do you have a "KK_KKBPExporterConfig.json" file in the same directory as the pmx file? If not, check you're using the latest version of the KKBP_exporter.dll and not an older version.
