### ISSUE TITLE
import model

### ISSUE THREAD

**Issue by MadeEvil** [FlailingFog/KK-Blender-Porter-Pack#538]
Traceback:
```
Python: Traceback (most recent call last):
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\KK-Blender-Porter-Pack-663\importing\importbuttons.py", line 53, in execute
    force_current_pose = c.get_json_file('KK_KKBPExporterConfig.json')['exportCurrentPose']
TypeError: 'NoneType' object is not subscriptable
```

Card used:
![Koikatu_F_20230713165022153_Chika Haruno_MrMadesPc](https://github.com/FlailingFog/KK-Blender-Porter-Pack/assets/165521662/75420d54-dc4f-4704-b94f-acb147803b89)

game created and exported in: koikatsu party
Blender version:3.6.9
kkbp addon version; latest (6.6.3)
pmx converter used: mmd tools version 2.10.2
Material combiner version:2.1.2.4

video proof of error:
https://github.com/FlailingFog/KK-Blender-Porter-Pack/assets/165521662/acfd1c4f-6509-4841-80f9-022b97561ebd

**Comment by Yharim2** [comment]
I probably should have zipped the card, here is the card in a zipped format
[charCard.zip](https://github.com/FlailingFog/KK-Blender-Porter-Pack/files/14813489/charCard.zip)

**Comment by Yharim2** [comment]
whats strange is it works in bklender version 3.5, but textures wont show up and in the console it states that its because blender 4.0 dropped support for them. and bare in mind im not using blender 4.0, im using blender 3.5 for that run.

**Comment by Yharim2** [comment]
I believe i have found the root cause of my problems, I was using the wrong version of kkbp exporter on the koi katsu side of things. im gonna try using kks this time.

**Comment by Yharim2** [comment]
ok so i dont have that problem anymore, but now i have a new problem, blender **ALWAYS** freezes at this point 
![image](https://github.com/FlailingFog/KK-Blender-Porter-Pack/assets/165521662/08a1cc0f-870a-4329-ac81-46bc7e7f077f)

**Comment by Yharim2** [comment]
actually wait, the import button error strikes again, but at a different time now, and at various different lines of code
![image](https://github.com/FlailingFog/KK-Blender-Porter-Pack/assets/165521662/31effcae-012a-47d2-9c96-5feec4e55b3d)
