### ISSUE TITLE
Prep Option always causes crash

### ISSUE THREAD

**Issue by ZombieKillerGaming** [FlailingFog/KK-Blender-Porter-Pack#543]
Literally every time I try to prep the card for target application it always crashes blender. This issue has been mentioned before but never fixed. I would appreciate any help I can get because this is really bugging me.
![117747938_p9](https://github.com/FlailingFog/KK-Blender-Porter-Pack/assets/106704341/7168856a-05c1-48bf-b8b7-b0936a574500)
This is the card in case it helps. (Although I'm sure the issue occurs with literally ANY card.)

**Comment by InkFlowerz** [comment]
I have the same issue, heres a screen shot of my blender console moments before it crashes, if anyone knows how to fix this, itd be much appreciated. 
![Screenshot 2024-05-16 113633](https://github.com/FlailingFog/KK-Blender-Porter-Pack/assets/170030521/fa19ca48-6f01-4970-bb8a-988c9b7d215c)

**Comment by FlailingFog** [comment]
this should be fixed in kkbp 7.0.0
