### ISSUE TITLE
Blender crashes after clicking "prep for target application"

### ISSUE THREAD

**Issue by HT4XSora** [FlailingFog/KK-Blender-Porter-Pack#545]
Is there a way to fix this problem?
I'm afraid I may not be able to explain it thoroughly, so I just provide a screen rec
If I missed a step, I'm sorry. I'm not using Bender normally
 - regard

vid.
https://github.com/FlailingFog/KK-Blender-Porter-Pack/assets/167107022/73b839d4-9863-49b7-875e-5e5e9f6dfb7b

img.
![image](https://github.com/FlailingFog/KK-Blender-Porter-Pack/assets/167107022/fd78c21b-bed2-4a65-93aa-9ba19768f4c5)

**Comment by InkFlowerz** [comment]
Have this same issue, no clue what makes it happen and its really annoying
![Screenshot 2024-05-16 113633](https://github.com/FlailingFog/KK-Blender-Porter-Pack/assets/170030521/5d52e5d3-75ef-4d88-ae73-11bdab6e5236)

**Comment by FlailingFog** [comment]
this should be fixed in kkbp 7.0.0
