### ISSUE TITLE
All White Textures - Yes, I read the FAQ

### ISSUE THREAD

**Issue by dragonash2019** [FlailingFog/KK-Blender-Porter-Pack#546]
And as you know, all the FAQ says is that a scripting error occurred.
The script can never seem to find the materials. I've attached for reference.

I'm only testing this out on the basic models that came with the game, nothing custom yet.

[KKBP Log.txt](https://github.com/FlailingFog/KK-Blender-Porter-Pack/files/15055962/KKBP.Log.txt)

**Comment by FlailingFog** [comment]
this error should be fixed in kkbp 7.0.0
