### ISSUE TITLE
How does the Pushup function work?

### ISSUE THREAD

**Issue by Erodeed** [FlailingFog/KK-Blender-Porter-Pack#547]
I've enabled the pushup function when exporting the character but upon importing it I have no idea where to find  this function. I found nothing on the wiki and the update that mentioned this feature didn't explain how it works. Is it a shapekey that gets added, because if so, it does not appear? Or how does it work? I want make use of multiple outfits but the alpha masks don't work with every outfit and most are made for the pushup function. Is there something I'm missing?

**Comment by MoriMorinya** [comment]
There is no "pushup function" for the exported model.
Every modification in-game to the body, like the boob size, position ect is done via bones, Pushup in-game just makes it use a second "set" of bone positions to the boobs according to the character's clothing state

Selecting export Pushups just exports the model with the same bone positions as the pushup settings  (not including flattened nipples), it doesn't have a shape key or anything cus its all in the armature. 

It's pretty useless if you plan to have the character naked or have multiple outfits, if you need the boobs to pushup or anything like that sadly you would need to pose the boob bones manually to mimic the same effect.

**Comment by Erodeed** [comment]
Ah ok I understand now, thanks for the answer. A Shapekey feature would be really cool of course but I understand that'd probably be a lot of work for a small feature like that. And you're right, it's probably better to do one outfit and then manually import another one if you need it. How do you go about merging a model with one outfit with one that has another outfit? Do you join the new clothing bones of the second rig to the first one and then parent the new outfit to that rig? So that all the weights match up with the bones?

**Comment by MoriMorinya** [comment]
Merging Armatures in Blender is pretty messy, especially if with rigify/custom scripts and might take a lot of time, by exporting separate outfits I meant exporting the character again with the new outfit and just using that model, not merging the outfit/armatures.
