### ISSUE TITLE
So when trying to export my blender save the console appears and when I close it, Blender crashes

### ISSUE THREAD

**Issue by TimyIsCool** [FlailingFog/KK-Blender-Porter-Pack#549]
I don't know how to properly describe it but here are some screenshots

![Screenshot 2024-04-30 233208](https://github.com/FlailingFog/KK-Blender-Porter-Pack/assets/74112751/64905689-8df8-4c31-b437-2d45946892d3)
![Screenshot 2024-04-30 233257](https://github.com/FlailingFog/KK-Blender-Porter-Pack/assets/74112751/98dc5054-e130-4c87-8306-71bfb26617b3)

**Comment by InkFlowerz** [comment]
Similar thing happens to me, only the console automatically closes itself and force quits blender without any reason. Idk what to do about it. 
![Screenshot 2024-05-16 113633](https://github.com/FlailingFog/KK-Blender-Porter-Pack/assets/170030521/ca6cd63f-0714-45e8-bc3e-79a52de3b52d)
