### ISSUE TITLE
KKBP Armature has incorrect/different finger axis orientation for both hands

### ISSUE THREAD

**Issue by MoriMorinya** [FlailingFog/KK-Blender-Porter-Pack#551]
Self explanatory; Both hands have different XYZ orientations making mirroring broken

![image](https://github.com/FlailingFog/KK-Blender-Porter-Pack/assets/101014618/5e0d5793-7832-4335-8d7a-31c5b2f206fe)
![image](https://github.com/FlailingFog/KK-Blender-Porter-Pack/assets/101014618/8591d49f-f388-4843-a426-aba8eb4f0a05)
![image](https://github.com/FlailingFog/KK-Blender-Porter-Pack/assets/101014618/cd0c9d90-0723-4c40-9c87-0d11c7f0e8ac)

**Comment by FlailingFog** [comment]
This is kinda just how the armature from the game comes. The Rigify armature is better if you plan to actually use the model in Blender (mirroring works as expected with that armature)

**Comment by MoriMorinya** [comment]
ah, I expected it was something like that. I use rigify anyway I just found this when trying out the kkbp armture to see if theres a difference thats better or worse than rigify and thought to report it :P
