### ISSUE TITLE
KKBP refuses to import PMX models after closing Blender and opening it back.

### ISSUE THREAD

**Issue by TSPEnforcer** [FlailingFog/KK-Blender-Porter-Pack#552]
Once KKBP and CATS plugins are installed onto Blender, everything works fine, the importing and Fix Model of CATS work as intended. 

However, once Blender is closed and opened again, an error occurs. (See attachements 1 and 2) 

Fixes applied that DID NOT negate the issue:
-Updating Blender to 3.6.11 (Latest 3.6 LTS)
-Restarting the System/Reinstalling Blender.
-Trying different Koikatsu Cards.

Fix applied that DID negate the issue:
Using MMD Tools along side the CATS.

In use are:
KKBP Exporter V6.6.3
Blender 3.6.9/3.6.11 
CATS Blender Plugin (UNOFFICIAL) - https://github.com/Yusarina/Cats-Blender-Plugin-Unofficial-/releases/tag/3.6.7.1
blender_mmd_tool - https://github.com/UuuNyaa/blender_mmd_tools/releases/tag/v2.10.2
![Attachement1](https://github.com/FlailingFog/KK-Blender-Porter-Pack/assets/168968700/e44fc2d9-7ae0-4ca8-9d85-c388e0a704dc)
![Attachement2](https://github.com/FlailingFog/KK-Blender-Porter-Pack/assets/168968700/f23adfc0-7cd2-4da9-afcb-a2780ab40f1e)

**Comment by FlailingFog** [comment]
this should be fixed in kkbp 7.0.0
