### ISSUE TITLE
Pressing Prep for target application crashes blender

### ISSUE THREAD

**Issue by InkFlowerz** [FlailingFog/KK-Blender-Porter-Pack#554]
I use blender 3.6 and had no problems getting up to the point where i needed to export it to a Unity file to use for VR Chat but as soon as i press prep for target application it brings up the console for 10 seconds and then crashes blender. I have no clue why this is happening, i followed a tutorial and they never had this issue. 

Heres all that it said before crashing
![Screenshot 2024-05-16 113633](https://github.com/FlailingFog/KK-Blender-Porter-Pack/assets/170030521/2caa9843-48ed-4e05-a8e3-f8896bde4b79)

**Comment by FlailingFog** [comment]
this should be fixed in kkbp 7.0.0
