### ISSUE TITLE
KK Party Compatibility

### ISSUE THREAD

**Issue by Zibokwe** [FlailingFog/KK-Blender-Porter-Pack#56]
Export_PMX folder for the character has all textures but no .PMX model. Have not been able to get it to output the .PMX no matter what I do.
(Using the V5.0 plugin in Koikatsu Party([Steam + After Party DLC] w/ HF Patch.)

**Comment by MediaMoots** [comment]
I'm afraid the plugin won't work on KK Party, I only tested it to work on KK
Maybe I'll support it in the future, but for now I am unable to get/run KK Party.

Sorry about this.

**Comment by gitburned** [comment]
> Maybe I'll support it in the future, but for now I am unable to get/run KK Party.

What exactly is the holdup there? I want to know so I can think further...

**Comment by Zibokwe** [comment]
It only exports some of the textures, not all and does not export the PMX
file. so it seems to hang somewhere and then stop working.

**Comment by gitburned** [comment]
I know, I'm trying to inqure MediaMoots as to the difficulty on their end for getting Koikatsu _Party_ to run on their machine.

**Comment by MediaMoots** [comment]
@gitburned @Zibokwe 
Does this work?
[KKBP_Exporter.zip](https://github.com/FlailingFog/KK-Blender-Shader-Pack/files/7517713/KKBP_Exporter.zip)

**Comment by gitburned** [comment]
Where'd you get that from?

It produced me a pmx so it works (I also use Koikatsu Party with HF patch).

**Comment by MediaMoots** [comment]
PR #67

**Comment by MediaMoots** [comment]
> It produced me a pmx so it works (I also use Koikatsu Party with HF patch).

Thanks for testing it! : )
Glad it works.

**Comment by gitburned** [comment]
but it's always out the frying pan and into the fire cause now when i tried using CATS (downloaded right from https://github.com/e63uozicmujivxmyshivi9ao/cats-blender-plugin) on a model I exported with the exporter it couldn't find the arm and elbow bones and failed. Is it a CATS side problem? How do I work around it?

**Comment by gitburned** [comment]
While it works, I noticed after importing pmx then finalizing it, then using CATS' "Fix Model", it seems to error out at "chest" bone not being found, what gives?

**Comment by MediaMoots** [comment]
could you upload the pmx file here please?
Thanks

**Comment by MediaMoots** [comment]
~~could you upload the pmx  file please?~~~

Edit: nvm, you do not need to fix the model with cats, as this plugin is works with KKBP V5
Please see this for more info: https://github.com/FlailingFog/KK-Blender-Shader-Pack/blob/V5-merger/README.md#usage-instructions-for-v5

**Comment by MediaMoots** [comment]
I made some changes to the plugin, please try this version with KK Party and see if it works
[KKBP_Exporter.zip](https://github.com/FlailingFog/KK-Blender-Shader-Pack/files/7519072/KKBP_Exporter.zip)

**Comment by gitburned** [comment]
Unfortunately that dll didn't work again anymore for some reason.

For context I use HF patch with KKAPI 1.28

**Comment by MediaMoots** [comment]
Alright then, for now you can use the dll from PR #67 that should work fine

**Comment by MediaMoots** [comment]
[KKBP_Exporter.zip](https://github.com/FlailingFog/KK-Blender-Shader-Pack/files/7524822/KKBP_Exporter.zip)
Please try this version

**Comment by MediaMoots** [comment]
PR #67 
@gitburned 
Please try out v1.12 from this PR, thanks!

**Comment by Zibokwe** [comment]
> @gitburned @Zibokwe Does this work? [KKBP_Exporter.zip](https://github.com/FlailingFog/KK-Blender-Shader-Pack/files/7517713/KKBP_Exporter.zip)

Seems to work fine, models utilizing Head Mod don't seem to export the PMX though. Thanks for the assistance.

**Comment by MediaMoots** [comment]
Did models with head mod export correctly in the original KK game?

**Comment by Zibokwe** [comment]
Not sure, I only had Steam version of KKP. KKS I have in JP but there's no exporter for it afaik.

**Comment by MediaMoots** [comment]
Could you share a card that uses head mod so that i can test it on the original KK? thanks!
