### ISSUE TITLE
Different Normal Smoothing Method

### ISSUE THREAD

**Issue by MoriMorinya** [FlailingFog/KK-Blender-Porter-Pack#563]
aVersionOfReality recently showed a shader he made in Malt on Twitter, which included a Normal Smoothing setup; by using GeoNodes and smoothing normals, then making the smoothed out normals into an attribute to plug into the shader's normals.

This could be a good alterative to the current "Face Shading" method (which, looking at Blender's Terminal fails to setup for some reason) as it doesn't require adjusting an empty and you only deal with changing the iterations/weight on the GeoNodes and can be applied to multiple parts of the model.

![image](https://github.com/FlailingFog/KK-Blender-Porter-Pack/assets/101014618/5768814e-4991-4b65-a780-5ec6b75ae338)

![image](https://github.com/FlailingFog/KK-Blender-Porter-Pack/assets/101014618/b5c851b7-5a15-4e5d-ba55-c433bda55f3c)
![image](https://github.com/FlailingFog/KK-Blender-Porter-Pack/assets/101014618/f9a18284-4143-48ee-95cd-f74033927938)

I separated it into 2 Geo Groups, one for the Face/Body to fix a seam between the head material and body, and also so you can adjust the smoothing separately. The other one is just the original node setup

https://drive.google.com/file/d/1HUsmt4v3KmHihCTluGyDmJsRhUcN4Uvr/view?usp=sharing

You would need to create new raw shading groups in the shader (like you did for the Face one) because disabling the geonodes with the normals plugged in messes up the normals, I am not sure how it will work/how to combine it with the normal textures that are extracted from the game, but I am sure its possible without them "ruining"  one another.

**Comment by FlailingFog** [comment]
Hey, thanks a lot for this! GFN definitely did not seem to work on the latest blender version. I'll try to put this into the plugin.

**Comment by FlailingFog** [comment]
added in 7.0.0!
