### ISSUE TITLE
Calling Operator Error

### ISSUE THREAD

**Issue by LieoLieo** [FlailingFog/KK-Blender-Porter-Pack#564]
![image](https://github.com/FlailingFog/KK-Blender-Porter-Pack/assets/114969086/e394d551-45f7-46cd-a08f-a45102c445f8)

![KK_111304](https://github.com/FlailingFog/KK-Blender-Porter-Pack/assets/114969086/5429b2c8-02e5-4a49-a72a-db9184c40e92)

**Comment by LieoLieo** [comment]
I don't know much about this all so I'm sorry if I've made any mistakes.

**Comment by 777Leinad77** [comment]
You are using blender 4.1 ,   i recommend you to use blender 3.6 like the "read me" say.
it happen also to me me and it worked with the 3.6

**Comment by FlailingFog** [comment]
It looks like you don't have mmd tools installed. Please check the [readme](https://github.com/FlailingFog/KK-Blender-Porter-Pack) for more info
