### ISSUE TITLE
Makeup not working

### ISSUE THREAD

**Issue by esfe3323** [FlailingFog/KK-Blender-Porter-Pack#565]
As i said in title when i import the character into blender it doesnt have the makeup also the lens dont have transparency.
Koikatsu betterrepack last version.
last version here and all the plugins.
Blender 3.6.
Also is there is a way that when you import into blender to erase the blush in cheeks i will be thankfull for answers.
i attach card file
![55f60e08a1ec56e199d9281911259c1a7d9c5b52](https://github.com/FlailingFog/KK-Blender-Porter-Pack/assets/68568051/48ec7748-5462-41f1-b914-1ce63eadf61b)

**Comment by MoriMorinya** [comment]
All of those things should be changeable inside of the Node Group for the face material 
![image](https://github.com/FlailingFog/KK-Blender-Porter-Pack/assets/101014618/f8c1c491-d746-4e48-96f4-e5efa4fa9bdd)
![image](https://github.com/FlailingFog/KK-Blender-Porter-Pack/assets/101014618/e7980bd9-0cf5-4bac-b4e0-6873ffcaae04)
Check if the lens material has the blend mode set to Alpha Blend (you can select the exact material by going into edit mode with face selection and selecting one of the faces on the lens)
![image](https://github.com/FlailingFog/KK-Blender-Porter-Pack/assets/101014618/e9d66436-4d33-414b-881f-4366aa1b8112)

**Comment by esfe3323** [comment]
a ok thanks, this is only for the blush and the lens, it dont fix the makeup right?
