### ISSUE TITLE
Can it support export the shape keys  from the third party mods?

### ISSUE THREAD

**Issue by NaughtDZ** [FlailingFog/KK-Blender-Porter-Pack#569]
For ex：An uncensored body model called “SAC",Usually, it has a “vaginal_kupa” shape key.But when I exprot the character which use it.
In blender ,even I chose skipp modifie shape key,It still missing.
How do i keep it?
PS: I try use MMD tool inport pmx file directly,shape key still missing.So,must something need to do when export pmx in game.

**Comment by NaughtDZ** [comment]
But,I try [Grey's mesh exporter for Koikatsu](https://www.google.com/search?q=koikatsu+discord).It can keep all the shape keys...but we all know GME out put fbx is suck.
So , can KKBP keep all shape keys even from mod?

**Comment by FlailingFog** [comment]
Sorry, it does not look like the exporter supports this.
