### ISSUE TITLE
What exactly does Enable Shapekey do ?

### ISSUE THREAD

**Issue by johnvo0918** [FlailingFog/KK-Blender-Porter-Pack#570]
Title, I couldn't find anything on the repo that explains what it does.

**Comment by multitrack-collector** [comment]
I thinks it allows you to modify the character's properties like you could in the Koikatsu Characcter Maker. SO give her larger bust for example.

**Comment by johnvo0918** [comment]
so far what i can notice is that the eyes are correctly applied. theyre not wide open like the previous versions.

**Comment by MoriMorinya** [comment]
It exports the model keeping whatever expression is currently on and how open the eyes so you could import the model with more accurate eyes into Blender.


> I thinks it allows you to modify the character's properties like you could in the Koikatsu Characcter Maker. SO give her larger bust for example.

that is done using bones in both in Koikatsu Character Maker and in Blender, not with shape keys.
