### ISSUE TITLE
Skip dark version texture creation.

### ISSUE THREAD

**Issue by johnvo0918** [FlailingFog/KK-Blender-Porter-Pack#581]
Most shaders nowadays does the shading for you if you plan to use the exported model in Unity (which i do).
Having an option to skip the creation of dark textures would speed up my import time a bit !
Also what is Error: Image "" not available. Keeping packed Image. this shows up A LOT.

**Comment by FlailingFog** [comment]
Sure! I've added a dropdown in KKBP 7.0.0 that you can select to not use dark colors at all.
I don't know why that error pops up, but everything still saves correctly so I don't worry about it.
