### ISSUE TITLE
7.0.0 doesnt create shaders on import.

### ISSUE THREAD

**Issue by LarsDuJour** [FlailingFog/KK-Blender-Porter-Pack#583]
Blender 4.2 LTS.
Using the KKBP 7.0.0 nightly.
Exporting from Sunshine with the correct HF patch.
Problem is with all characters.
Yes, I've read the Wiki several times.

Hi, I've been trying to get this to work for a few days. The model meshes seems to export and import correctly, and the exporter gets all the texture files seemingly correctly.

The problem comes on textures. All textures come out white using MMDtools, BUT the suggested method of turning off alpha simply can't be done. The game only creates materials of the MMDShaderDev kind, and there are no nodes in the shaders tab for anything.
If I try with CATS and without MMDtools, everything is black instead and hair+clothes dont import.

I've tried with multiple export and import settings, I've tried multiple cards (official and otherwise) and I've even tried with both CATS and MMDtools installed.

At this point, my best gueses its something inside 7.0.0 that needs to be tweaked.

Thanks in advance for any help.

**Comment by FlailingFog** [comment]
Hey I tried it out with KKS yesterday and I was able to import correctly with the default card

Can you try with the testing set I currently have for sunshine?
* Koikatsu Sunshine
* HF patch for Koikatsu Sunshine 1.17
* [mmd_tools 4.2.2](https://extensions.blender.org/add-ons/mmd-tools/) (CATS will not work anymore)
* KKBP exporter V4.21 for sunshine
* KKBP importer V7.0.0 (this branch)
* Blender 4.2.0

I also just updated the beta release here: https://github.com/FlailingFog/KK-Blender-Porter-Pack/releases/tag/V7.0.0_beta

**Comment by FlailingFog** [comment]
Going to close because this was for the beta, but if it's still happening feel free to reopen the issue
