### ISSUE TITLE
I cant get it to work

### ISSUE THREAD

**Issue by Tobias0404** [FlailingFog/KK-Blender-Porter-Pack#584]
I am trying to get it to work. Any charcter I import into blender is completely white. Also while exporting from sunshine my character suddenly changes pose and is also exported in that pose.

I am using 6.2.1 for blender 3.3(.21) and I am running the sunshine repack. I used this tutorial till 3:34 https://www.youtube.com/watch?v=JSdggnGtcmU&t=207s

The result I get:
![blender](https://github.com/user-attachments/assets/97a4d8ef-77f1-40af-b1ee-801014506115)

**Comment by FlailingFog** [comment]
Hey, can you try please try the things detailed in these issues? There's some extra stuff you have to do if you're using KKS and the repack version
https://github.com/FlailingFog/KK-Blender-Porter-Pack/issues/523 https://github.com/FlailingFog/KK-Blender-Porter-Pack/issues/535

**Comment by Tobias0404** [comment]
I fixed the pose thing. 

But still cant get any colour to appear. 
I tried "The V4.21 exporter works correctly on KKS, but you will have to use KKBP V6.5.0, KKBP exporter V4.21, and Blender 3.5" by installing the correct blender and the correct versions of each of the other things. But it still doesnt work.

While importing i am now also getting the error "KeyError: 'bpy_prop_collection[key]: key "Outfit 00" not found'" in the console.

**Comment by Tobias0404** [comment]
Did some more expirementing today.

It appears it was because I was exporting it with a single outfit and this outfit was not the first outfit (outfit 00). Not exporting a single outfit also fixed the body colouring. Now it does have colours. It appears the files used for the colouring in the export are named with "01" instead of "00" if the first outfit is not also exported.

Examples of said files:
cf_m_body_AM_00
cf_m_body_MT_00

Maybe there is a stting I was supposed to change in the importer, sorry for the trouble if that was the case. I just haven't looked into the settings yet.

Sadly though a new issue has appeard. The boobs area of the chest is not exported, clothes are but just not the skin.
![k](https://github.com/user-attachments/assets/c503fa61-310b-4075-9760-1fcbebc6831e)

**Comment by Tobias0404** [comment]
I did some more expirementing. The last new issue i now avoid by ecporting only 1 outfit again. To avoid the isseu where no colour appears, I rename some of the export files by either removing the _01 or changing it to _00 and then it works.

Now I have no more unavoidable issues anymore. But i do hope the hole through the body and the seemingly wrong naming of files while exporting get fixed.

**Comment by MoriMorinya** [comment]
the hole through the body is suppose to be a texture that makes parts invisible to avoid clipping and isnt an issue with the exporter #378

**Comment by Tobias0404** [comment]
Oh, ok, thx. 

Do you know what was up with the other thing? Where no colour appearing on the model (and the outfit 00 not found error) when only exporting a single outfit, which I solved by renaming some files in the exported folder. Is that supposed to happen? Or am I supposed to change a setting somewhere?

**Comment by MoriMorinya** [comment]
I have no idea what is going on with Sunshine both in general and with this exporter, but its no setting or anything, just the sunshine exporter being consistently broken

**Comment by Tobias0404** [comment]
Ok. I will point out the files I renamed for any person running into the same issue.

Outfit ## -> Outfit 00 (folder)
cf_m_body_AM_##.png -> cf_m_body_AM.png
cf_m_body_MT_##.png -> cf_m_body_MT_00.png

## depends on which outfit is exported.

**Comment by Tobias0404** [comment]
Close
