### ISSUE TITLE
I can't use the newer versions of the PorterPack

### ISSUE THREAD

**Issue by UKPMAN** [FlailingFog/KK-Blender-Porter-Pack#586]
@FlailingFog I had a problem with the T-pose and I solved it by installing a mod. :)

But I have to use the porterPack 6.5.0, if I use the 6.6.3 I get a error about "ShadowColor". :(
With the older addon and exporter this works fine but sometimes some materials on hair or accessories are just white.
![Screenshot 2024-07-31 010419](https://github.com/user-attachments/assets/31bde92c-b2ea-4e9d-a7e6-8750ec23c003)

Even in the older exporter I have to untick "Export Hit meshes" or I'll get this when importing to blender:
![image](https://github.com/user-attachments/assets/7d5d406c-954e-4daa-b928-bd57d7408249)

This is what happens if I use the newest(6.6.3) version of PorterPack:
![image](https://github.com/user-attachments/assets/50373139-81c7-47b5-bcac-0f1e1eca6f98)

I hope someone can help me fix this （。＾▽＾）

**Comment by Jonah-multi** [comment]
#508 #579 the a quick fix solution was to just define 'shadowcolor' a bit earlier. It also looks like you don't have an "outfit 00", something which is repaired in later updates, but another quick fix is to just rename the outfit folder (Outfit 01, Outfit 02, etc), and make sure at least *one* of them is Outfit 00.

**Comment by UKPMAN** [comment]
@Jonah-multi I tried that fix and it imported but the materials are messed up. 
In the older version I get that "key : Outfit 00 not found" error is because I only import one outfit and it get named by the corresponding outfit number on the character creator, so if I export outfit variations then it works.
![image](https://github.com/user-attachments/assets/34dd1701-94c9-46c6-bfb7-25133b3b687b)
I think the script looks for "outfit 00" even if you export single outfit.
I got that figured out but now the white material issue still remains. I'm trying to find a way to fix this :)

**Comment by Jonah-multi** [comment]
You're using KKS correct? Because, if so, KKS is facked beyond belief. It's being repaired slowly in 7.0.0, but my suggestion, which I've used, is to just... Use KK or KKP, because for the time being, KKS is not functioning with 6.6.3.

**Comment by Jonah-multi** [comment]
It's very annoying, but for the time being at least, it's the only reliable way to get KKBP to work at all, and it does come out really good, even if it means that any cards made on KKS can't be used. An example of a KK card working in Blender 3.6.9 is here.
![Himeko in Imaginary2](https://github.com/user-attachments/assets/f0be2afd-3b12-4113-944e-b4188342bf1c)

**Comment by Jonah-multi** [comment]
#535 has some solutions, use KKBP V6.5.0, KKBP exporter V4.21, and Blender 3.5 for KKS and supposedly that should work.

**Comment by UKPMAN** [comment]
@Jonah-multi yeah, I use Blender 3.6.9 with KKBP 6.5.0 and this kinda works, sometimes get white textures but some fixable. I tried KKP with this and soon as the loading screen ends it crashes :( that's why I moved to KKS and got it tot work at least like this

https://github.com/user-attachments/assets/6fe56c32-9a8b-47d9-9d8c-f98131fbf3ea

**Comment by UKPMAN** [comment]
By the way do you know how I can use the map importing thing?
![Screenshot 2024-07-31 213840](https://github.com/user-attachments/assets/484156a9-b17d-4e15-a639-e46ab5209e51)

**Comment by Jonah-multi** [comment]
Sorry mate, no I don't. I've never messed with that before.
