### ISSUE TITLE
Help!load failed

### ISSUE THREAD

**Issue by DataOod** [FlailingFog/KK-Blender-Porter-Pack#587]
Please include the Koikatsu character card that causes the issue!  
You can copy paste it directly into this text box.  
(it can really help with the debug process)
![15](https://github.com/user-attachments/assets/ebafddff-bc66-4cb4-abbc-cc1325d8854a)
I been try with doc but sitll be like this like image only don't have dress and hair.
![12](https://github.com/user-attachments/assets/72d82916-6c01-4be0-a393-618fe00fc142)
![14](https://github.com/user-attachments/assets/62bc7c69-a2d0-4c14-8f09-48a1a4b850b8)
![13](https://github.com/user-attachments/assets/f91e4e69-c00f-49cc-ac1c-ac987c8a9a0f)

![11](https://github.com/user-attachments/assets/6c3c85cc-c415-460a-968f-83d409237657)

**Comment by DataOod** [comment]
blender 4.2 kkbp7.0

**Comment by FlailingFog** [comment]
Hi, I updated the 7.0 release earlier today. It should fix this error.
If the new update doesn't work, please set your Blender language to English and try again.

**Comment by DataOod** [comment]
thanks!

**Comment by DataOod** [comment]
> Hi, I updated the 7.0 release earlier today. It should fix this error. If the new update doesn't work, please set your Blender language to English and try again.


emmmm， seems you update a 6.3 version on release

**Comment by clockworkphysicist** [comment]
As a bit more context, I also ran into this exact same issue, with a fresh install a few minutes ago. Here is the exact code I recieve:
![Screenshot 2024-08-11 100853](https://github.com/user-attachments/assets/39642e07-4453-4b99-88b8-8e84d40be163)

I do have HF patch, as well as the most recent versions mentioned here, and am running into the same issue as this user.

**Comment by TimyIsCool** [comment]
Also have this error
![Screenshot 2024-08-11 234414](https://github.com/user-attachments/assets/d963c320-2344-4d65-a60c-6afd9b881880)
I am on the latest pre-release

**Comment by FlailingFog** [comment]
> > Hi, I updated the 7.0 release earlier today. It should fix this error. If the new update doesn't work, please set your Blender language to English and try again.
> 
> emmmm， seems you update a 6.3 version on release

I apologize, I have updated it again with the correct 7.0 version

**Comment by FlailingFog** [comment]
I think this was fixed before 7.0 released, so closing
