### ISSUE TITLE
Rigify eye controller does not work.

### ISSUE THREAD

**Issue by higeinu3594** [FlailingFog/KK-Blender-Porter-Pack#588]
If you select a bone and it does not move, the controller will work correctly if you re-set either the “Left Eye or Right Eye” weight to 1, but there is one problem.
If I save the project and reopen it, the eyes do not move.
If I reweight the project in the same way, the eyes move, but it is a pain to reweight them each time.

Please let me know if there is any additional information you would like. I will try to answer as much as possible.

The result is the same whether I use the default character or the original.

**Blender 4.2
KKBP 7.0.0
Koikatsu HF Patch v3.30gx**

**Comment by higeinu3594** [comment]
Postscript.
I have a problem with the eyes not moving when I close or save Blender.
After saving the file, it did not move when I moved my eyes.
I can resolve this by reinserting the weight to 1.

I don't know if this will be helpful, but I made a video of the whole process.
I really like the creator's add-on and the additional features of Rigify, please let me know how to solve this.

Google Drive
https://drive.google.com/file/d/1gNbPEvxphNGzlDP0kv5AAVf4-VrnOfsy/view?usp=sharing

**Comment by higeinu3594** [comment]
The eye only moved once, not save or restart.
The cause is unknown and when I installed KKBP 7.0, when I ran Blender 3.6.9 I got the following error and Blender 2.90 was the only option.
I hope this helps.

Error text when running 3.6.9
![blender24081x](https://github.com/user-attachments/assets/fbf37d5e-1336-425e-aaf6-1f957c9216c9)

Python: Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 4.2\4.2\python\Lib\zipfile.py", line 1735, in _extract_member
    open(targetpath, "wb") as target:
    ^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\tekki\\AppData\\Roaming\\Blender Foundation\\Blender\\4.2\\extensions\\user_default\\kkbp\\importing\\dependencies\\blender-3.6.9-windows-x64\\3.6\\scripts\\addons\\io_scene_gltf2\\blender\\exp\\animation\\sampled\\armature\\gltf2_blender_gather_armature_action_sampled.py'

https://github.com/user-attachments/assets/2c102a73-69e1-486c-9aec-2862173e251c

**Comment by FlailingFog** [comment]
Hey, I'm sorry but I can't replicate this issue... I can still move the eyes after I save. I also tried closing blender and opening again, but it still worked.
Are you using these settings in KKBP 7.0 to import the model, or something different?
![image](https://github.com/user-attachments/assets/a8ae6e0e-d3f1-4727-9ec4-c00e3de7cc16)

**Comment by higeinu3594** [comment]
Hello.
What I found out is that I'm a little mistaken.
It doesn't work in pause mode and when I switch back to object mode, it reflects the values that I moved in pause mode.
I can move the other bones without any problem, but only the eye controllers are like in the video.

I have tried re-installing the add-on, but with the same result.
I don't know if there is a problem with Koikatsu or with the way Blender is installed.
The procedure for KKBP 7.0 is
1. impot model
2. Convert for Rigify
3. Check eye movement

![blender240824](https://github.com/user-attachments/assets/c2ce1ee0-bfab-4af8-a53d-45c8c957562e)

https://github.com/user-attachments/assets/dcc8943a-70fa-4b1b-b3e2-c8cccdb5ec14

**Comment by higeinu3594** [comment]
Resolved! I had left the add-on “Sakura Auto Simplify” Simplify turned on.
It is hard to see in the video, but you can think of it as turning the modifier on and off.
I had just recently purchased the add-on and was not aware of its functionality.
It was just another add-on that was causing the problem. Sorry for taking your time.

https://github.com/user-attachments/assets/747ef6be-c696-45d8-a92b-1be6a52445ca
