### ISSUE TITLE
[KKS BR10 / KKBP 7.0.0] Portion of hair is classified as a part of the outfit, rendered white as a result

### ISSUE THREAD

**Issue by HiLordReilo** [FlailingFog/KK-Blender-Porter-Pack#590]
Basically everything is in the title.
![image](https://github.com/user-attachments/assets/6777dc54-0cce-4258-9810-d7059555f370)

The card I'm trying to import
![KoikatsuSun_F_20240812094418758_Reune Kayla_HiLord Reilo](https://github.com/user-attachments/assets/af209098-87c5-4f0c-a681-62ca254939b0)

**Comment by FlailingFog** [comment]
I think it classifies something as hair if the shader is set to a hair shader, or if there's _HGLS files present. There are _HGLS files present so I'm not sure why it didn't work for you...

![image](https://github.com/user-attachments/assets/834524a7-f0e0-4fda-b18a-38ac0dc0e2e1)

It looks like this card has the shader set to "main clothes item", so maybe try changing that?

![image](https://github.com/user-attachments/assets/a774d9f8-2a18-4dbb-a3ac-9bb157110051)

**Comment by HiLordReilo** [comment]
Unfortunately, this only resulted in ribbons looking wrong as well (which is kinda not surprising, considering this is ribbons' material section)
![image](https://github.com/user-attachments/assets/3989d136-6768-405e-928c-2a2d2b5a02ac)

I wonder if this has something to do with the exporter. My export window looks different from what can be seen in documentation, despite using exporter from the same release with the importer
![image](https://github.com/user-attachments/assets/8d4b74a3-99cb-4faf-a5ab-aef56f884643)

Maybe I installed the thing incorrectly?

**Comment by HiLordReilo** [comment]
Okay, yeah, it seems I had a wrong version of exporter for some reason. Installing the newest package (3 hrs ago from now) helped and now everything is imported correctly, minus some accessories (which is okay, I've read the FAQ)

Sorry for the confusion this might've caused!
