### ISSUE TITLE
[KKBP 7.0.0 / Help Wanted] Importing KKS model into Unity generates untextured model

### ISSUE THREAD

**Issue by HiLordReilo** [FlailingFog/KK-Blender-Porter-Pack#591]
I'm trying to import the model to Unity for VRC, but upon drag'n'dropping files generated by KKBP FBX export into Unity project assets folder, I just get an untextured model
![image](https://github.com/user-attachments/assets/ace74e75-de49-447d-b3ce-2aa4c51a18f2)

I followed the "How to use" section on the wiki and both initial and baked models shows up fine in Blender.
Am I missing something? Do I need to do some extra configuration in Unity?

**Comment by HiLordReilo** [comment]
A small correction: it seems that resulting FBX file is not linked with the textures in general, as the model won't be textured even if you import it into empty Blender project

**Comment by FlailingFog** [comment]
I could never get texture linking to work, so the exported fbx file won't have a texture. You have to make a material in unity and load in the textures / atlas files. It's not for VRC, but I have an example of doing something similar here: https://youtu.be/4Z02sY6Y8GI&t=399. Just note that KKBP 7.0.0 has more material slots than what's shown in this video, so you have to make a Body material and drag it into several body material slots, make a Clothes material and drag it into several clothes material slots, etc

**Comment by HiLordReilo** [comment]
Yeah, I really should've took at older examples first 😅
Is it fine to use material combiner with new approach to reduce the slot count though?

**Comment by FlailingFog** [comment]
I don't think material combiner will work, but you can just use the minus button where the material slots are to reduce the slot count. 
![image](https://github.com/user-attachments/assets/3efe7840-7d58-4009-a622-4ee4dd4a2765)

**Comment by FlailingFog** [comment]
New example here: https://www.youtube.com/watch?v=pUusXi_Np8s
