### ISSUE TITLE
Do imported models have jiggle physics, or do we need to add those ourselves?

### ISSUE THREAD

**Issue by Namelessdegenerate** [FlailingFog/KK-Blender-Porter-Pack#599]
Just wanted clarification on this. I couldn't find any answers to this in the FAQs. I think there are no physics for imported models, at least I couldn't find a way to turn them on, but I might just be dense. I been looking at tutorials on how to add jiggle physics to models, but I wanted to make sure I actually need to do this before going ahead and putting in all that work. 

Also, if we do add our own physics, can we use the pre-existing chest/glute bones, or would we need to add those ourselves too?

**Comment by BlueScreenofDeath201** [comment]
I use dynamic bone in Unity to add jiggle physics, and in that case I can use the existing bones. Ive never took the time to learn weight painting in blender, or anything like that so not sure if that helps

**Comment by FlailingFog** [comment]
No, there's no built in physics for any bones. I'm not really familiar with adding physics in blender, but the last time I did it I used the wiggle bones addon on an existing hair bone on the armature.
