### ISSUE TITLE
启动blender4.2.1lts，打开插件，点击开始导入模型，启动3.6.9后，blender4.2.1没反应

### ISSUE THREAD

**Issue by zhaixly** [FlailingFog/KK-Blender-Porter-Pack#605]
启动blender4.2.1lts，打开插件，点击开始导入模型，启动3.6.9后，blender4.2.1没反应

Uploading 2024-09-26 14-56-32_1.mp4…

<img width="1233" alt="Snipaste_2024-09-26_15-08-52" src="https://github.com/user-attachments/assets/d10395ee-8688-485e-a967-51883b4b28f8">
![Uploading Snipaste_2024-09-26_15-08-38.png…]()
![Uploading Snipaste_2024-09-26_15-08-24.png…]()

**Comment by FlailingFog** [comment]
Yes, please wait some more time. You can see the progress if you check this folder while it's importing: \Koikatsu\Export_PMX\20241004154450_Character\saturated_files\
