### ISSUE TITLE
[KKBP 7.0.0] Stretched eyes, missing kage

### ISSUE THREAD

**Issue by Matoyamah** [FlailingFog/KK-Blender-Porter-Pack#607]
Latest everything, fresh install of repack RX21. When importing any of Evaan's Pokemon girls, the eye texture appears vertically stretched, and the kage eyelash texture doesn't import. It does this on KKBP 6.6.3 as well. Also slaps on an extra eye highlight and wrong eyebrow color, but those are easy fixes.

![Screenshot 2024-09-27 201444](https://github.com/user-attachments/assets/7ec0a441-22e9-410f-87c4-25f7606efe9c)

It's always something with the Evaan cards, I swear. Is there something obvious I missed, or an easy way to add in the eyelash kage texture after import?

Card and zipmod:
https://files.catbox.moe/819wge.zipmod
![Koikatu_F_20220519031604350_May_Evaan](https://github.com/user-attachments/assets/4a54ae35-9503-4b3c-ac07-1329481c71e6)

**Comment by FlailingFog** [comment]
Check https://github.com/FlailingFog/KK-Blender-Porter-Pack/issues/606 for the stretched eyes

I'm not sure why the kage isn't loading in, but it might have to do with the fact they're using this override slot
![image](https://github.com/user-attachments/assets/0ec9a3dd-8b5f-4851-ab39-649c5cb13443)

You can load it in by going to the eyeline up material on the body material, go into the green texture group and and load in the eyeline textures there
![image](https://github.com/user-attachments/assets/0a67b8c8-2601-4adf-8668-4cf48c2ecb5c)

**Comment by Matoyamah** [comment]
Good info, thank you.
