### ISSUE TITLE
New Saturation has weird Posterize-like artificing   

### ISSUE THREAD

**Issue by MoriMorinya** [FlailingFog/KK-Blender-Porter-Pack#608]
# Result after Saturation applied:
![image](https://github.com/user-attachments/assets/bd0345e0-b340-4486-8547-0250d4716cab)

# The original texture:
![image](https://github.com/user-attachments/assets/3e83e05c-1ecb-4cd6-a9c4-414b35179f86)

**Comment by FlailingFog** [comment]
fixed in 7.0.1
