### ISSUE TITLE
Multiple Characters

### ISSUE THREAD

**Issue by Jonah-multi** [FlailingFog/KK-Blender-Porter-Pack#610]
I'd like to have a scene with Multiple Characters in it, if it's at all possible to have Multiple Characters imported, then that'd be great, if not, feel free to swear at me and delete the post, I'll just take the long route of Exporting to PMX and importing to another file.

**Comment by FlailingFog** [comment]
Importing multiple characters isn't supported, but you can import each character to an individual file then append all of the character collections into one file afterwards (see https://github.com/FlailingFog/KK-Blender-Porter-Pack/issues/430). I'm also going to close this in favor of that issue to avoid duplicates
