### ISSUE TITLE
Can transparent parts be imported into blender?

### ISSUE THREAD

**Issue by dddder4** [FlailingFog/KK-Blender-Porter-Pack#612]
![image](https://github.com/user-attachments/assets/068bd0bf-a1b2-41f3-9bd8-74f69b553ab6)
![image](https://github.com/user-attachments/assets/e1555baf-17e6-4f9d-b56a-6972a94b4df9)

Some characters use alpha shader, but i can't find any configuration in blender.

**Comment by johnvo0918** [comment]
you'll need to setup shader render queue for it to render over the hair. I have no idea how to setup in blender but in Unity every shaders will include a tutorial to do this.

**Comment by dddder4** [comment]
> you'll need to setup shader render queue for it to render over the hair. I have no idea how to setup in blender but in Unity every shaders will include a tutorial to do this.

Before setup render queue, I'd like to know if the transparent material is exported or not. Please have a look, Halloween hair uses a material named "_hair1.MECopy1", it should be different from "_hair1", but I can't find it in blender.
![QQ20241009-192921](https://github.com/user-attachments/assets/bb04fdfb-baa2-4481-881f-6e8673caaa26)
![QQ20241009-193126](https://github.com/user-attachments/assets/ad5a6509-d328-45e0-97ff-080b40e75584)
![QQ20241009-193215](https://github.com/user-attachments/assets/641a93c2-c9fb-4c23-9d74-82b457e007cb)

**Comment by FlailingFog** [comment]
Transparent parts are automatically imported.

Do you want the eyes to show through the hair? I don't think that's done with transparent materials in the game. I think they use the render queue like johnvo said.

If you want to do this in blender, try the cryptomatte features. This is how I setup the transparent eyes for [this animation](https://www.youtube.com/watch?v=7BWrZkdzkQQ) using cryptomatte:


![1](https://github.com/user-attachments/assets/82146c31-38ee-4b08-abde-9f44ac065d8e)
![2](https://github.com/user-attachments/assets/5ea4d543-a4e5-42f7-9f97-affcc559a8d4)
![4](https://github.com/user-attachments/assets/f4f0c721-5187-4300-87f9-5b65bcc66890)
![3](https://github.com/user-attachments/assets/6d7f0a0b-2583-4e5e-abf6-c7cadea76f4c)
![image](https://github.com/user-attachments/assets/77238fac-c138-45a3-abc1-58a78a8e02bb)

**Comment by dddder4** [comment]
> Transparent parts are automatically imported.
> 
> Do you want the eyes to show through the hair? I don't think that's done with transparent materials in the game. I think they use the render queue like johnvo said.
> 
> If you want to do this in blender, try the cryptomatte features. This is how I setup the transparent eyes for [this animation](https://www.youtube.com/watch?v=7BWrZkdzkQQ) using cryptomatte:
> 
> ![1](https://private-user-images.githubusercontent.com/65811931/376044499-82146c31-38ee-4b08-abde-9f44ac065d8e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAxNjQyNzcsIm5iZiI6MTczMDE2Mzk3NywicGF0aCI6Ii82NTgxMTkzMS8zNzYwNDQ0OTktODIxNDZjMzEtMzhlZS00YjA4LWFiZGUtOWY0NGFjMDY1ZDhlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI5VDAxMDYxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE1NjBhOTc2NDlhNjhiMGEyYTZlNWQ0NTcyNmI4MzRmMzFhZDU5MzliNzc2MGY2ZjVhNDYxMjM3ZGYwYWNmODAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.AZ5QjZ-8tEccdCLlGyEUyoDgaG2z9RDfuTrlCUIDAyA) ![2](https://private-user-images.githubusercontent.com/65811931/376044505-5ea4d543-a4e5-42f7-9f97-affcc559a8d4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAxNjQyNzcsIm5iZiI6MTczMDE2Mzk3NywicGF0aCI6Ii82NTgxMTkzMS8zNzYwNDQ1MDUtNWVhNGQ1NDMtYTRlNS00MmY3LTlmOTctYWZmY2M1NTlhOGQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI5VDAxMDYxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk0ODhjYmM4NmZmMzQ4MzkzMmY5MjVjY2U3MDYyNTc4ZGFjOWQyZWRiOWQ1OWJhMzdlZGU1NjVmNTg4NmUyZTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.wxX_VyVH0Js3gyd2IbICgwnyEEGdc7gMkyJRs9oP8tE) ![4](https://private-user-images.githubusercontent.com/65811931/376045037-f4f0c721-5187-4300-87f9-5b65bcc66890.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAxNjQyNzcsIm5iZiI6MTczMDE2Mzk3NywicGF0aCI6Ii82NTgxMTkzMS8zNzYwNDUwMzctZjRmMGM3MjEtNTE4Ny00MzAwLTg3ZjktNWI2NWJjYzY2ODkwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI5VDAxMDYxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlkOGEzZTQyNDg0ZTUwY2EzM2VmNjFjM2EzMzMyNjQyMGU2NzY0MjFlMWVkZDI1M2E3ZDU0YzEzODRiZjc4NzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.u94i1QDQ4jud18WOllct29Y9BQSzJSgarRRAu0I2RMU) ![3](https://private-user-images.githubusercontent.com/65811931/376044509-6d7f0a0b-2583-4e5e-abf6-c7cadea76f4c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAxNjQyNzcsIm5iZiI6MTczMDE2Mzk3NywicGF0aCI6Ii82NTgxMTkzMS8zNzYwNDQ1MDktNmQ3ZjBhMGItMjU4My00ZTVlLWFiZjYtYzdjYWRlYTc2ZjRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI5VDAxMDYxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRkNDRhMGFmM2MwNDdjMDQwMGJhZmQyM2Q1NjRlNjdkNTc0NmMyYWZjMTE5MTEzMTEwMzFjZmMxMzA4NzliMTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.-XaYWWJLIohgnFRHc05jX3JKz_epUk_IhojdkiEPILc) ![image](https://private-user-images.githubusercontent.com/65811931/376044485-77238fac-c138-45a3-abc1-58a78a8e02bb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAxNjQyNzcsIm5iZiI6MTczMDE2Mzk3NywicGF0aCI6Ii82NTgxMTkzMS8zNzYwNDQ0ODUtNzcyMzhmYWMtYzEzOC00NWEzLWFiYzEtNThhNzhhOGUwMmJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI5VDAxMDYxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE4ZjYzNTE0YTJmOGE0NmYyNTM5OWU0NTBiMmNjOWM4ZTk1YzJmZGI1ODExNDk5MmZlNWRmYzEwMzQxYTMzMTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.kn8AfDems9_gHHKB7_uU0edntmCp1yUaBIqIDK-h4TM)

I'll have a try, thank you!
