### ISSUE TITLE
Knee doesn't bend when moving the legs IK

### ISSUE THREAD

**Issue by Shidokami** [FlailingFog/KK-Blender-Porter-Pack#621]
So I'm using the V5 version on Blender 3.0 and when I tried to move the legs bone the knee won't bend how do I fix this? tried to find someone with same issue but I can't find anyone with the same issue.

![Capture](https://github.com/user-attachments/assets/e035babe-b599-4af3-a2fb-3f5f8b83de40)

**Comment by JJJHH4466** [comment]
try changing the "body scale" to 100 in koikatsu.
![Screenshot 2024-11-02 115106](https://github.com/user-attachments/assets/0ab3d1f2-3c80-40e9-837d-7fa87e0277ed)

**Comment by JJJHH4466** [comment]
my solution is : 
In the koikatsu, Adjust the Y-axis scaling related to the feet, Or reset "身長", Keep the character's feet close to the ground.

![Screenshot 2024-11-02 130223](https://github.com/user-attachments/assets/5bbb88af-a7a7-4a71-b65f-7ade89251284)
![Screenshot 2024-11-02 131449](https://github.com/user-attachments/assets/e4e26100-d260-4605-b68c-1eb9d15dca77)
![Screenshot 2024-11-02 130257](https://github.com/user-attachments/assets/70823373-7d41-46ce-8dcd-37ac860396ae)
![Screenshot 2024-11-02 130302](https://github.com/user-attachments/assets/1711c640-3bc5-4da1-8294-56f78d3f33b7)
![Screenshot 2024-11-02 131117](https://github.com/user-attachments/assets/33eb4fb4-87ff-4aca-942b-6824ddb81d06)

**Comment by JJJHH4466** [comment]
I also encountered the same problem.
![Screenshot 2024-11-02 140658](https://github.com/user-attachments/assets/d86e006d-5ab4-4235-b061-f05f3b3b4be7)

My solution is:
Open "1"  in the box "bone collections".
![Screenshot 2024-11-02 140830](https://github.com/user-attachments/assets/9592d5df-dbf3-4771-8613-34016081a803)

Select the bones of the thigh. Move a little bit in front of your knees.
![Screenshot 2024-11-02 140854](https://github.com/user-attachments/assets/cc08d427-ec9a-4142-861e-00d9bc783cf6)

Now the controller can work normally.
![Screenshot 2024-11-02 140727](https://github.com/user-attachments/assets/be52f7c2-36fe-4d22-aaea-9f8461f84967)

**Comment by Shidokami** [comment]
> I also encountered the same problem. ![Screenshot 2024-11-02 140658](https://private-user-images.githubusercontent.com/179292096/382452413-d86e006d-5ab4-4235-b061-f05f3b3b4be7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA1Mjk5MTgsIm5iZiI6MTczMDUyOTYxOCwicGF0aCI6Ii8xNzkyOTIwOTYvMzgyNDUyNDEzLWQ4NmUwMDZkLTVhYjQtNDIzNS1iMDYxLWYwNWYzYjNiNGJlNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwMlQwNjQwMThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMGIwZWQ0NDljOThjZTdiZmI5M2U5ZTU4ZDJiNGViNzlmMjlkYzM2OGM2MjZiZDQ5ZDNjNjhiNTQ4NGNiNDVlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.cx99DREwgHkCzAPXFzqlXslcZObYIEtgJZA61x7cKDg)
> 
> My solution is: Open "1" in the box "bone collections". ![Screenshot 2024-11-02 140830](https://private-user-images.githubusercontent.com/179292096/382452231-9592d5df-dbf3-4771-8613-34016081a803.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA1Mjk5MTgsIm5iZiI6MTczMDUyOTYxOCwicGF0aCI6Ii8xNzkyOTIwOTYvMzgyNDUyMjMxLTk1OTJkNWRmLWRiZjMtNDc3MS04NjEzLTM0MDE2MDgxYTgwMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwMlQwNjQwMThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNjIzYjhkNTgwYjcyM2U2MTA5ZDFmMWViNjJlY2FkMDZhMWVjNTE2MWY5NWUxZmM5MmJmNWMwZDI0N2MzZmVkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.UrxjlC4RxwQ_vqrJsqyMHeBCLPWqVhWG47xJimX09GE)
> 
> Select the bones of the thigh. Move a little bit in front of your knees. ![Screenshot 2024-11-02 140854](https://private-user-images.githubusercontent.com/179292096/382452369-cc08d427-ec9a-4142-861e-00d9bc783cf6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA1Mjk5MTgsIm5iZiI6MTczMDUyOTYxOCwicGF0aCI6Ii8xNzkyOTIwOTYvMzgyNDUyMzY5LWNjMDhkNDI3LWVjOWEtNDE0Mi04NjFlLTAwZDliYzc4M2NmNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwMlQwNjQwMThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMWFmMTdkOGYwMDBkN2QwYzlmZDljYzYzYmUxNTQ1ZTY2NzljYzE5MTZmZTAwNzEyMmM2NjMwNmFjNjhhMjRhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.9KxWyMQmulgouG8247YZt3OT7ErDLrjJKfjmMBI5WWY)
> 
> Now the controller can work normally. ![Screenshot 2024-11-02 140727](https://private-user-images.githubusercontent.com/179292096/382452402-be52f7c2-36fe-4d22-aaea-9f8461f84967.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA1Mjk5MTgsIm5iZiI6MTczMDUyOTYxOCwicGF0aCI6Ii8xNzkyOTIwOTYvMzgyNDUyNDAyLWJlNTJmN2MyLTM2ZmUtNGQyMi1hYWVhLTlmODQ2MWY4NDk2Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwMlQwNjQwMThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMjg5YjEzZjk5ZjcyNmQwYTVjOGNjNzRiOTBkMjBhYjg0YTE4OGYwZTliODNlMjUxZDZmODhkNTU5YjY1YTI5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.aw_fdsoHs0cwUL8cdp83NNbvE-j4dyLTa1OYbcPMlAI)

Thank you very much it worked, 1 more question, now some of my character model cannot bend their elbow like in the picture below, should I use the same method to fix the elbow one?
![image](https://github.com/user-attachments/assets/208b4133-1b26-4d81-94fc-7299dd618643)
