### ISSUE TITLE
Modules installed but KKBP add on doesn't show up

### ISSUE THREAD

**Issue by Paperrandom** [FlailingFog/KK-Blender-Porter-Pack#624]
Hi there! I downloaded the KKBP_importer_7.0.1 and tried to install it for my blender but every time I installed it through the addons it came up as modules installed but never showed up in my sidebar. So I went around and followed different tutorials on youtube on how to fix it but none worked for me so I tried to download the dependencies for a different version of blender I had but an error came up saying it couldn't find the right file. I didn't know where else to ask so I'm sorry if this is an incorrect place or off topic question to ask. Thank you all for your time for reading.

**Comment by FlailingFog** [comment]
Maybe you're on the wrong blender version? KKBP 7 is only supported on blender 4.2. I've also noticed if the inside of the zip file doesn't look exactly like this it will say "modules were installed ()" but do nothing, so make sure you haven't edited the zip

![image](https://github.com/user-attachments/assets/97c15a3f-f397-4b0e-a0ea-a6e6d525c70a)

**Comment by Paperrandom** [comment]
I have it installed in blender 4.2.3 now. But when I do it speaks about dependencies which is where the issue of the last message comes up again. I've seen for others it pops up with the proper menu but for me it comes up with a different menu about needing different versions of blender. 
![Screenshot 2024-11-13 122630](https://github.com/user-attachments/assets/4a9c4055-b4c8-4459-b59f-1047223991d2)

**Comment by AnalogKnight** [comment]
Do you actually have Blender 2.9 or 3.6 installed?

**Comment by Paperrandom** [comment]
I have 3.6 installed

**Comment by AnalogKnight** [comment]
Try removing the plugin, download and install Blender 3.6 from here: https://www.blender.org/download/release/Blender3.6/blender-3.6.17-windows-x64.msi
Then add the plugin in Blender 4.2, which worked for me.

**Comment by Paperrandom** [comment]
I tried what you reccomended, thank you for that by the way, but it still gave me the same message I screenshotted from before.

**Comment by FlailingFog** [comment]
> I have it installed in blender 4.2.3 now. But when I do it speaks about dependencies which is where the issue of the last message comes up again. I've seen for others it pops up with the proper menu but for me it comes up with a different menu about needing different versions of blender.

If you update to KKBP 7.1.0 it won't ask you to download anything and will show you the expected addon panel right when you install it. 

That message was needed for an extra dependency in KKBP 7.0.0 and 7.0.1. If you don't want to update to KKBP 7.1.0, you can do two things:
* Click on either of the buttons it'll automatically download the dependency from blender.org and give you the normal addon panel after that
* Download the dependency yourself using the link from AnalogKnight, install it, open the KKBP addon preferences in Blender 4.2 (located in Edit > Preferences > add-ons) and put the direct path to your blender 3.6 exe into the box
![image](https://github.com/user-attachments/assets/35c09cfd-89f4-4ac7-a423-fb70ba2b7ad1)

**Comment by Paperrandom** [comment]
Thanks so much. I tried that and I got it to work. I was able to get that menu and start loading models now. I don't think my set up is strong enough though as it freezes during the loading process but thank you for the help!
