### ISSUE TITLE
The error message below occurs when exporting after selecting "Create Atlas" during the finalize materials stage.

### ISSUE THREAD

**Issue by baishi820** [FlailingFog/KK-Blender-Porter-Pack#645]
Error:          Unknown python error occurred
Traceback (most recent call last):
  File "C:\Users\bai'shi\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\user_default\kkbp\exporting\bakematerials.py", line 1068, in execute
    create_material_atlas(folderpath)
  File "C:\Users\bai'shi\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\user_default\kkbp\exporting\bakematerials.py", line 542, in create_material_atlas
    bpy.context.view_layer.active_layer_collection = layerColl
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: bpy_struct: item.attr = val: ViewLayer.active_layer_collection does not support a 'None' assignment LayerCollection type

This error also occurs even when I don't select "Create Atlas."
![无标题](https://github.com/user-attachments/assets/19ddaea2-c19c-4a24-baee-12a50d2e7590)

**Comment by HiLordReilo** [comment]
bump, getting the same error
![image](https://github.com/user-attachments/assets/2909a9c1-e317-4f39-b8e8-3204bbea9061)

**Comment by FlailingFog** [comment]
Did you all delete the default "Collection" collection?

![image](https://github.com/user-attachments/assets/8dffaf03-0bc9-48bf-9334-d529ac0a4ea1)

If so, try creating the collection again and putting the character back inside of the collection

**Comment by HiLordReilo** [comment]
> If so, try creating the collection again and putting the character back inside of the collection

I just didn't delete anything from the general template this time instead, but yes, this helped

**Comment by FlailingFog** [comment]
Great!
