### ISSUE TITLE
Add option to export from CharaStudio

### ISSUE THREAD

**Issue by vanilla-shirt** [FlailingFog/KK-Blender-Porter-Pack#649]
I am trying to use this porter pack to make 3D printable figures. While it technically works, there are a limited amount of poses and objects etc. in character maker as opposed to studio where you can customize everything. 

It would be really helpful if you could export the same way in studio as you already can in character maker, or if you could export poses from studio to character maker, and then export the normal way. Thanks for reading and making the plugin <3

**Comment by FlailingFog** [comment]
If you just want a mesh of the character to print, you might want to check out Grey's mesh exporter instead. It takes a character in studio and exports it as an fbx file that you can import into blender. 

You can search for "Grey.MeshExporter" on the koikatsu discord to get it, or if you don't have discord you can get it [through this link](https://github.com/FlailingFog/KK-Blender-Porter-Pack/tree/9fcef4127ba56b4e8e8718fb546945fc00eaaad9/GME)

**Comment by vanilla-shirt** [comment]
First off, thank you for the reply and for your work on the plugin. Grey's mesh exporter isn't exactly perfect since it separates all of the hair accessories and body parts making it time consuming to work with BUT it is essentially what i was looking for. It didn't work with sunshine but worked after a fresh install of the original game. Thanks again <3
