### ISSUE TITLE
Cycles not shaded properly

### ISSUE THREAD

**Issue by coolboi85** [FlailingFog/KK-Blender-Porter-Pack#651]
Please include the Koikatsu character card that causes the issue!  
You can copy paste it directly into this text box.  
(it can really help with the debug process)

When using cycles in the blender option it does not change the lighting at all
![Screenshot 2024-12-16 031240](https://github.com/user-attachments/assets/5d7fb2c3-f213-4d18-884b-53e467f6ebe4)

**Comment by FlailingFog** [comment]
You need to add a light object to the scene or the model will be completely dark
![image](https://github.com/user-attachments/assets/fe0b5546-2f29-42e3-a66b-335c013f3d59)

If you're talking about the toon shading, then it's intended to be like that. If you want more realistic lighting then try replacing the "Toon BSDF" inside of the Cycles node group with a regular diffuse BSDF
![image](https://github.com/user-attachments/assets/6c2b4e11-ebea-489d-b64c-c040e4ae597c)
