### ISSUE TITLE
Certain accessories causing the plugin to not import outfits in Blender

### ISSUE THREAD

**Issue by HugglesGamerGirl** [FlailingFog/KK-Blender-Porter-Pack#652]
This is an issue that's been persisting since the older versions of KKBP and I thought it would get patched but sadly it's still persisting
this is not just a card issue this is a universal issue that affects many cards where certain accessories cause the plugin not to import any outfits (and I would assume not export either)
there has to be a workaround for this right? 
(the only answer this wiki gives to this is to check if the clothes are hidden in blender but in my case, they are simply gone)
![clothes gone](https://github.com/user-attachments/assets/dfce9d25-3204-4135-a3ab-01a6a93549c4)
I will now provide the most recent card where this issue happened a cute Koikatsu model of the Irasutoya clipart girl 
![KK_350242](https://github.com/user-attachments/assets/18619f49-e966-4593-9e80-37e2c8b5a62a)
I ported the model carefully removing each accessory until I found the one causing the issue it was the Hemicardios accessory something that I can't remove due to the fact it's a key part of the character's hair
for additional context I am using a fresh install of the latest Koikatsu Better Repack and the accessory mod is part of this repack

For further aid I will also provide a log of when the import is attempted with the accessory that causes the clothes to not be imported
this crash log is what happens if the model with the accessory is attempted
for the sake of this test those were my export options, Export Single Outfit, Enable Shapekeys and Export Without Physics

// LOG SECTION//

====    KKBP Log    ====
Importing pmx files with mmdtools...
Import PMX operation took 0.0 seconds
get_body_material_names operation took 0.007 seconds
separate_rigged_tongue operation took 1.17 seconds
separate_hair operation took 0.001 seconds
Warning:        Material wasn't found when separating materials: c_m_shadowcast
Warning:        Material wasn't found when separating materials: Standard
Warning:        Nothing was selected when separating materials from: Body
separate_shad_bone operation took 1.631 seconds
separate_hitboxes operation took 0.001 seconds
delete_mask_quad operation took 0.0 seconds
remove_unused_shapekeys operation took 0.009 seconds
rename_uv_maps operation took 0.0 seconds
translate_shapekeys operation took 0.291 seconds
combine_shapekeys operation took 0.882 seconds
create_tear_shapekeys operation took 1.863 seconds
create_gag_eye_shapekeys operation took 0.877 seconds
add_body_datatransfer operation took 0.001 seconds
mark_body_freestyle_faces operation took 0.106 seconds
tag_all_objects_for_next_operation operation took 0.0 seconds
reparent_all_objects operation took 0.021 seconds
remove_bone_locks_and_modifiers operation took 0.037 seconds
scale_armature_bones_down operation took 0.023 seconds
reparent_leg_and_body_bone operation took 0.0 seconds
delete_non_height_bones operation took 0.142 seconds
modify_finger_bone_orientations operation took 0.054 seconds
set_bone_roll_data operation took 0.042 seconds
bend_bones_for_iks operation took 0.043 seconds
remove_empty_vertex_groups operation took 1.028 seconds
reorganize_armature_layers operation took 3.798 seconds
move_accessory_bones_to_layer10 operation took 0.001 seconds
create_eye_reference_bone operation took 0.005 seconds
create_eye_controller_bone operation took 0.096 seconds
shorten_kokan_bone operation took 0.032 seconds
scale_skirt_and_face_bones operation took 2.904 seconds
prepare_ik_bones operation took 0.149 seconds
rename_mmd_bones operation took 0.766 seconds
retreive_stored_tags operation took 0.123 seconds
remove_unused_material_slots operation took 0.018 seconds
Moving duplicate material cf_m_sirome_00 in slot 7 to the original slot 6
remap_duplcate_material_slots operation took 0.142 seconds
Warning:        material or template wasn't found when replacing body materials: cf_m_eyeline_kage / KK Eyeline Kage
Warning:        material or template wasn't found when replacing body materials: Eyeline_Over / KK Eyeline Kage
Warning:        material or template wasn't found when replacing body materials: cf_m_sirome_00 / KK EyewhitesR (sirome)
replace_materials_for_body operation took 0.188 seconds
replace_materials_for_hair operation took 0.0 seconds
replace_materials_for_outfits operation took 0.0 seconds
replace_materials_for_shadowcast operation took 0.0 seconds
replace_materials_for_tears_tongue_gageye operation took 0.001 seconds
remove_duplicate_node_groups operation took 0.008 seconds
Saturated cf_m_body_MT.png in 5.0 sec
Saturated cf_m_body_MT_CT.png in 5.3 sec
Saturated cf_m_eyeline_kage_MT_CT.png in 0.3 sec
Saturated cf_m_face_00_MT.png in 1.1 sec
Saturated cf_m_face_00_MT_CT.png in 1.2 sec
Saturated cf_m_gageye_00_cf_t_gageye_00_MT_CT.png in 0.3 sec
Saturated cf_m_gageye_00_cf_t_gageye_02_MT_CT.png in 0.3 sec
Saturated cf_m_gageye_00_cf_t_gageye_04_MT_CT.png in 0.3 sec
Saturated cf_m_gageye_00_cf_t_gageye_05_MT_CT.png in 0.4 sec
Saturated cf_m_gageye_00_cf_t_gageye_06_MT_CT.png in 0.3 sec
Saturated cf_m_gageye_00_MT_CT.png in 0.5 sec
Saturated cf_m_gageye_01_cf_t_gageye_01_MT_CT.png in 0.3 sec
Saturated cf_m_gageye_01_cf_t_gageye_03_MT_CT.png in 0.3 sec
Saturated cf_m_gageye_01_MT_CT.png in 0.3 sec
Saturated cf_m_gageye_02_cf_t_gageye_07_MT_CT.png in 0.2 sec
Saturated cf_m_gageye_02_cf_t_gageye_08_MT_CT.png in 1.4 sec
Saturated cf_m_gageye_02_cf_t_gageye_09_MT_CT.png in 1.3 sec
Saturated cf_m_gageye_02_MT_CT.png in 1.2 sec
Saturated cf_m_hitomi_00_cf_Ohitomi_L02_MT_CT.png in 0.3 sec
Saturated cf_m_hitomi_00_cf_Ohitomi_R02_MT_CT.png in 0.3 sec
Saturated cf_m_namida_00_MT_CT.png in 0.3 sec
Saturated cf_m_sirome_00_MT_CT.png in 0.4 sec
Saturated cf_m_bot_skirt06 9020_MT_CT.png in 0.7 sec
Saturated cf_m_bra_01 9130_MT_CT.png in 0.7 sec
Saturated cf_m_shoes_maid_01 9410_MT_CT.png in 0.2 sec
Saturated cf_m_shorts_02 9230_MT_CT.png in 0.6 sec
Saturated cf_m_top_sailor01_tent 8880_MT_CT.png in 4.8 sec
Saturated cf_m_top_tsyatu_cm 8290_MT_CT.png in 1.0 sec
Saturated MAT_OrgnaicShape01 3290_MT_CT.png in 1.1 sec
Created dark version of cf_m_body_ST_DT.png in 4.791865348815918 seconds
Created dark version of cf_m_bot_skirt06 9020_ST_DT.png in 0.5760817527770996 seconds
Created dark version of cf_m_bra_01 9130_ST_DT.png in 0.5423533916473389 seconds
Created dark version of cf_m_face_00_ST_DT.png in 1.0749061107635498 seconds
Created dark version of cf_m_shoes_maid_01 9410_ST_DT.png in 0.15063166618347168 seconds
Created dark version of cf_m_shorts_02 9230_ST_DT.png in 0.5266027450561523 seconds
Created dark version of cf_m_top_sailor01_tent 8880_ST_DT.png in 4.902709245681763 seconds
Created dark version of cf_m_top_tsyatu_cm 8290_ST_DT.png in 1.043079137802124 seconds
Created dark version of MAT_OrgnaicShape01 3290_ST_DT.png in 0.9999196529388428 seconds
load_images_and_shadow_colors operation took 45.75 seconds
File wasnt found, skipping: cm_m_body_DM.png
File wasnt found, skipping: cm_m_body_LM.png
File wasnt found, skipping: cf_m_body_ot2.png
File wasnt found, skipping: cm_m_body_ot1.png
File wasnt found, skipping: cm_m_body_ot1.png
File wasnt found, skipping: cf_m_body_T4.png
File wasnt found, skipping: cf_m_face_00_LM.png
File wasnt found, skipping: cf_m_face_00_T5.png
File wasnt found, skipping: cf_m_face_00_T8.png
File wasnt found, skipping: cf_m_face_00_ot3.png
File wasnt found, skipping: cf_m_noseline_00_MT_CT.png
File wasnt found, skipping: cf_m_eyeline_kage_ST.png
File wasnt found, skipping: Eyeline_Over_ST_CT.png
link_textures_for_body operation took 0.044 seconds
link_textures_for_hair operation took 0.0 seconds
link_textures_for_clothes operation took 0.0 seconds
File wasnt found, skipping: cf_m_tang_NMPD_CNV.png
link_textures_for_tongue_tear_gag operation took 0.013 seconds
import_and_setup_smooth_normals operation took 0.064 seconds
setup_gag_eye_material_drivers operation took 0.0 seconds
add_outlines_to_body operation took 0.057 seconds
add_outlines_to_hair operation took 0.0 seconds
add_outlines_to_clothes operation took 0.033 seconds
load_json_colors operation took 0.195 seconds
set_color_management operation took 0.001 seconds
KKBP import finished in 1.04 minutes

// LOG SECTION //

I hope this post can really help finally solve this issue while it is quite rare it is very annoying when it happens 
I also want to add this was all done on KKBP 7.1.0 (sep 14 release) on Blender 4.2.4 LTS

Thank You.
![ok_woman](https://github.com/user-attachments/assets/427a7b4e-f40c-4944-81d0-bf7b756a04cc)

**Comment by FlailingFog** [comment]
Confirmed, but this looks more like an exporter issue to me. There should be a .pmx file in the / Export_PMX / イラクーヤいらすとや / Outfit 00 / folder, but there's not so the exporter must not like something about the accessory. Here's the error in the Koikatsu console:
```[Info   :   Console] Exporting: cf_hair_maf_05_2_f
[Info   :   Console] Exporting: CTA_cf_hair_b_21_00_
[Info   :   Console] Exporting: CTA_cf_hair_b_21_01_
[Info   :   Console] Exporting: CTA_o_top_tsyats_cm_a_
[Info   :   Console] Exporting: o_top_sailor01_tent_a
[Info   :   Console] Exporting: o_bot_skirt06_a
[Info   :   Console] Exporting: o_bra_a
[Info   :   Console] Exporting: o_shorts_a
[Info   :   Console] Exporting: o_shoes_maid_01
[Info   :   Console] Exporting Acc: OrganicShape17
[Info   :   Console] System.IndexOutOfRangeException: Array index is out of range.
  at PmxBuilder.AddAccessory () [0x00000] in <filename unknown>:0
  at PmxBuilder+<BuildStart_OG>d__42.MoveNext () [0x00000] in <filename unknown>:0
```

I am looking to eventually start updating the exporter to fix small bugs like this, but right now I cannot tell you what's wrong with it

As a workaround you can export the accessory as an obj file and import it separately into blender, then parent the object to the head bone on the armature
![image](https://github.com/user-attachments/assets/fe914971-63c3-435f-97c5-b1f7302c4a1c)

**Comment by HugglesGamerGirl** [comment]
Thank you I'm glad the issue is finally being noticed!

**Comment by FlailingFog** [comment]
The issue was that the accessory didn't have a UV map. This version of the exporter should catch that and allow the accessory to export:
[KKBP_Exporter 4.31.zip](https://github.com/user-attachments/files/18211402/KKBP_Exporter.4.31.zip)

**Comment by HugglesGamerGirl** [comment]
OMG it worked! I'm surprised how fast you fixed it I expected this to take a few weeks, thank you so much!
![image](https://github.com/user-attachments/assets/8f9400b3-f938-436d-88ae-f4a94d3ed177)
