### ISSUE TITLE
Strange asymmetrical weights for "cf_s_head" bone

### ISSUE THREAD

**Issue by ilcane87** [FlailingFog/KK-Blender-Porter-Pack#69]
Here's the freshly imported character in weight paint mode, front view:

![image](https://user-images.githubusercontent.com/34897042/141519037-3914727f-9468-404d-81c9-3919ac6de84c.png)

You can see those small abrupt changes of the weights on the neck, which is strange to boot, but they're also different from the left to the right side of the character, so I'm assuming something is wrong.
The bone is on layer 2 (starting from 0).

Here's the reference character, I used the default outfit:

https://db.bepis.io/koikatsu/view/17005

**Comment by FlailingFog** [comment]
The merge by distance line in finalizepmx is causing this, but if it isn't run you get seams on the neck later on... I'll see if this or the seams can be fixed a different way.

**Comment by FlailingFog** [comment]
Not a fix, but I added a toggle to prevent the remove doubles operation from running during the finalize pmx script a while back, which will prevent the weights from being corrupted like that

**Comment by MediaMoots** [comment]
Is this fixed?

**Comment by ilcane87** [comment]
Hi, the workaround is more than enough for me, though it's up to FlailingFog whether to consider it fixed.
Feel free to close the issue accordingly.

**Comment by FlailingFog** [comment]
the thing causing this is now off by default
