### ISSUE TITLE
Arm bone weight problem

### ISSUE THREAD

**Issue by DOODKAHEIMU** [FlailingFog/KK-Blender-Porter-Pack#71]
The plug-in is very easy to use, but there are still some defects, as shown in the figure. I feel whether there is a problem with the weight of the arm bones when exporting all models. The arm will undergo strange deformation when rotating the bones. I queried these weights in the arm bones. Maybe "cf_s_elback" is the key to the wrong weight of these bones? Later, I came up with the method of weight replication to solve this difficult problem, but obviously this is not the best method, and it is very troublesome. I hope to get the fastest solution in my lifetime (Google translation language is not clea
![~$17NFK_Q8L@C088M KHK60](https://user-images.githubusercontent.com/83935958/142009729-dbf3946c-445e-4b08-b68a-a9a525cd7c96.png)
![0M)RX3$OM(`2 Q1NZH ZDD6](https://user-images.githubusercontent.com/83935958/142009735-b330e489-fa3c-42b0-a1e5-80fdbd6470ee.png)
![V D1UZ1KSEC4{C`~H5U8M$Q](https://user-images.githubusercontent.com/83935958/142009747-c0331d70-78ae-4084-a58e-7ca7f6512a9a.png)
r)

**Comment by DOODKAHEIMU** [comment]
There is a problem with the export     But it's right in the game
![0M)RX3$OM(`2 Q1NZH ZDD6](https://user-images.githubusercontent.com/83935958/142010474-02ebad2c-2668-4502-916b-4c24ed7d35c5.png)

**Comment by MediaMoots** [comment]
Try adjusting the twist bones to fix this (cf_s, cf_d)

**Comment by DOODKAHEIMU** [comment]
> Try adjusting the twist bones to fix this (cf_s, cf_d)

Try to twist the bone, but it doesn't work. Can you speak in detail

**Comment by ilcane87** [comment]
> twist bones (cf_s, cf_d)

On that note, can you explain what the other bone prefixes mean?
Like cf_j, k_f, cf_hit... I've been working on adding Rigify controls on top of the armature but for some parts I have a hard time understanding which bones are supposed to be moved by the user and which are just there to provide better deformation mechanics.

**Comment by FlailingFog** [comment]
>On that note, can you explain what the bone prefixes stand for?

Might be better to ask on the koikatsu discord, but this is the info I have on the armature:

>currently layer 1 has all the main joint bones, layer 2 has the cf_j joint bones not used when IKs are active, layer 3 has the cf_s bones used in the character creator and in some joint corrections, layer 4 has the cf_d bones used for joint corrections, layer 5 contains bones used by the better penetration armature so if you had that body type selected in koikatsu this is where the bones for the toes and stuff will be, layer 17 has the upper face bones, layer 18 has the lower face bones, layer 9 has the skirt bones, layer 10 has the accessory bones that have weight to them, layer 11 has all the intermediate bones that don't have weight to them (I find these completely useless), layer 12 has the cf_hit bones for physics and layer 13 has the k_f_ bones that you can use for IK applications.

Also, if you search for the user johnbbob_la_petite on the discord they've made a rigify armature on top of the existing armature you might be interested in looking at. It also has joint corrections on it, so you may find that useful too (though if you've already looked at the KKBP joint corrections you won't find anything new because I copied these directly from their armature).

**Comment by FlailingFog** [comment]
> There is a problem with the export But it's right in the game

The export is okay but the in-game joint correction bones are not being accurately replicated in Blender. Also, some cf_s and cf_d bones on layer 3 and 4 have "drivers" enabled. You need to disable the driver in the drivers window before you can move it around (or right click on the pink location values and delete the driver).

**Comment by MediaMoots** [comment]
cf_j: j -> Joint Bone
cf_d: d -> Dynamic Bone
cf_s: s -> Scale Bone

cf_hit: mouse hitbox bones
kf: I Don't know, haha

**Comment by ilcane87** [comment]
> Might be better to ask on the koikatsu discord, but this is the info I have on the armature:
Thanka a lot, that's what I was looking for.

> the user johnbbob_la_petite on the discord they've made a rigify armature on top of the existing armature
Nice, I found his blend file and instructions which can be used for reference, but his process was unnecessarily complicated, it seems like he thought that in order to use Rigify you must start from the default metarig, which is really just a standard skeleton with a few Rigify properties set on some bones.
The way I'm doing it is just adding the properties to the existing armature and generating the control rig from it, it's not going to be a long script by the end, I just have to be careful not to disrupt the existing KKBP bone mechanisms.

**Comment by FlailingFog** [comment]
> cf_hit: mouse hitbox bones

Darn I must have confused this with something else

> a list of all the bones involved in those joint corrections

There's a list in bonedrivers.py from [lines 332-378](https://github.com/FlailingFog/KK-Blender-Shader-Pack/blob/V5-merger/importing/bonedrivers.py#L332-L378) and [lines 439-498](https://github.com/FlailingFog/KK-Blender-Shader-Pack/blob/V5-merger/importing/bonedrivers.py#L439-L498).  
Ignore the cf_j_ bones for the first set of lines

**Comment by MediaMoots** [comment]
> Darn I must have confused this with something else

I'm not 100% sure that it's the mouse hitboxes, but from what I've seen in the source code it appears to be the case.
