### ISSUE TITLE
Error on the 2b step

### ISSUE THREAD

**Issue by cccbbaa** [FlailingFog/KK-Blender-Porter-Pack#73]
when i execute the 2b step in blender 2.93.6
blender tell me have a python error
![1](https://user-images.githubusercontent.com/95020703/143409446-98b8612c-b0a6-428b-808b-b38a479ca08e.png)
this is about the error

**Comment by MediaMoots** [comment]
Hi! Does this error appear on other cards?
If not, please upload the card that has this error, thanks!

**Comment by cccbbaa** [comment]
> Hi! Does this error appear on other cards? If not, please upload the card that has this error, thanks!

I think it just appear on the cards that I used , I try the 春野千佳 and the error don't appear 
![Koikatu_F](https://user-images.githubusercontent.com/95020703/143691941-76f18094-c270-487f-bfd8-3b21b037f55a.png)
and this is the card i used that appeared error in the blender

**Comment by MediaMoots** [comment]
Perfect, ill test this card when i have the time, thanks!
