### ISSUE TITLE
Eye doesn't appear properly after importing with v5-merger

### ISSUE THREAD

**Issue by lurkingaround** [FlailingFog/KK-Blender-Porter-Pack#75]
![95e51e2](https://user-images.githubusercontent.com/88926467/143862467-332142ac-aca9-401d-a186-3d70cefda8a4.png)
95e51e2

![f848408](https://user-images.githubusercontent.com/88926467/143862519-4e6f1251-4eb5-4df6-af26-e59f8a701b62.png)
f848408

**Comment by lurkingaround** [comment]
![9901a03](https://user-images.githubusercontent.com/88926467/144836696-055ab92f-06d4-4ad1-bfc4-ebaeea39600b.png)


9901a03

**Comment by FlailingFog** [comment]
Do you have the outline on? When you're exporting the "prep things for export" button should disable it

**Comment by lurkingaround** [comment]
Sorry I should've been clearer, this is when I exported from Koikatsu with the latest commit. I'll rename the issue.

**Comment by lurkingaround** [comment]
![ed9a90e](https://user-images.githubusercontent.com/88926467/145182437-23cb852e-86df-492e-b8c7-d58ee3e21662.png)

ed9a90e

**Comment by FlailingFog** [comment]
Got it! The face outline material had to be set to the "alpha clip" blend mode

**Comment by lurkingaround** [comment]
![5fb281e](https://user-images.githubusercontent.com/88926467/145337258-5ab967f8-cdaa-47e9-ac7c-c89a913768df.png)
5fb281e

I think it is set to that, I just followed the guide in the readme and the eye (hitomi) seems to still exhibit this issue. I don't know if it's the exporter from koikatsu that's at fault or the importer into blender.
