### ISSUE TITLE
Vertex on upper/bottom lip merged together

### ISSUE THREAD

**Issue by poisenbery** [FlailingFog/KK-Blender-Porter-Pack#82]
![Screenshot (366)](https://user-images.githubusercontent.com/78466408/146496348-ea4b2f47-fe6a-4262-8e20-48b885a46f8e.png)

Center vertex on lips seems to be merged together. Relatively consistent error. I'm pretty sure it's happening on all of my models but I need to test further to see.
EDIT: It's on all of my models. I tried importing with a larger scale size to see if it was a merge by distance thing, but no luck.

**Comment by naminode** [comment]
Just noticed this. Not sure how the exporter works. I guess the only solution for now is to un-assign the mix vertices from the vertex group. 

Mouth_Up
![image](https://user-images.githubusercontent.com/88361811/146584601-78bf5ae1-fa35-4159-a50f-2d33ed1385df.png)

Mouth_Low
![image](https://user-images.githubusercontent.com/88361811/146584758-f31105b5-077f-497e-ac69-c63cbed6cf01.png)

Mouth_R
![image](https://user-images.githubusercontent.com/88361811/146585248-620065b9-545f-403c-9de1-086f309b0421.png)

**Comment by MediaMoots** [comment]
What blender version?

**Comment by FlailingFog** [comment]
I see what you mean for mouthup and mouthlow. Happens for 2.93 and 3.0.0 on a CATS import or mmd tools file menu import.
For Mouth_R though, the weight for the stray vertices are zero, so it should be okay. They're just assigned to the group for some reason

**Comment by poisenbery** [comment]
> What blender version?

I tested on 3.0 and I believe the prior LTR to make sure it wasn't a 3.0 issue, so the same as @FlailingFog

**Comment by MediaMoots** [comment]
Is this fixed?

**Comment by poisenbery** [comment]
@MediaMoots

**Comment by poisenbery** [comment]
Somehow it's not. 
![Screenshot (904)](https://user-images.githubusercontent.com/78466408/190914316-f5d31e5e-8f49-4de5-8e83-7a93ee293674.png)
![KK_109194](https://user-images.githubusercontent.com/78466408/190914345-c6852f4e-7c0b-401f-be7d-abff4c41efb1.png)

**Comment by poisenbery** [comment]
@FlailingFog @MediaMoots It might be a better idea to "Select all by trait - Non Manifold" and merge with those vertices, instead of performing the operation on the entire mesh.

**Comment by MediaMoots** [comment]
@poisenbery Just checking, is this fixed?

**Comment by poisenbery** [comment]
AFAIR, yes

**Comment by MediaMoots** [comment]
Cool! Thanks for your help!
