### ISSUE TITLE
Textures set to "sRBG" instead of "Raw"

### ISSUE THREAD

**Issue by poisenbery** [FlailingFog/KK-Blender-Porter-Pack#83]
I was exploring the body textures node group and noticed that some of the groups had a thing that said "Raw colorspace"

All of the textures were in sRGB. I know that Blender likes to change the image texture nodes to sRBG after you open a file. I've always had to change it to the correct color space after I open the texture.

**Comment by MediaMoots** [comment]
KKBP's color part,aims to perfectly replicate KK's in game colors, does this issue affect the look of the character?

**Comment by poisenbery** [comment]
I should have checked that before I posted this. My mistake.
I saw these nodes and that they had a label for "Raw Color Space"
![Screenshot (393)](https://user-images.githubusercontent.com/78466408/146852611-e5200f29-efd2-47cb-9655-10a3d7d659d2.png)
But after import, they're in sRBG
![Screenshot (394)](https://user-images.githubusercontent.com/78466408/146852614-31b7b2d9-4173-44e7-a325-68dd91bcfde9.png)
It DOES have an effect, but when I compare to in-game, the sRBG scheme results in a more similar look. When set to raw, it appears to have a blotchy appearance.
![Screenshot (395)](https://user-images.githubusercontent.com/78466408/146852617-7de2a83b-6eda-44a2-9c9c-383e4f53b24c.png)

My understanding of how the Image texture node works had me convinced that the textures were supposed to be in Raw color space. 

Just out of curiosity, why does their label have "Raw Color Space?"

**Comment by FlailingFog** [comment]
> Just out of curiosity, why does their label have "Raw Color Space?"

The color space label is something carried over from an older version of the plugin, where you had to manually load in each texture then set certain textures to raw. You should be able to stick to whatever the defaults are

**Comment by FlailingFog** [comment]
I removed the color space labels
