### ISSUE TITLE
Feature Request: Export with all outfit sets

### ISSUE THREAD

**Issue by poisenbery** [FlailingFog/KK-Blender-Porter-Pack#84]
Currently, the plugin exports only the outfit the character is currently wearing. It would be cool if the plugin had an option to export the character with all outfits. 

Im using the plugin to export models for use in blender. Currently, I have to export the models 1 at a time with each outfit, and then combine in a later step. It is very time consuming this way.

**Comment by MediaMoots** [comment]
The best we could do KK Plugin-wise, is to export all the outfits as separate .pmx files/folders in one go.

**Comment by poisenbery** [comment]
> The best we could do KK Plugin-wise, is to export all the outfits as separate .pmx files/folders in one go.

That would be insanely useful. The "1 at a time" method sometimes requires exiting out of character maker because the export will only be 500kb and have a couple of accessories. If there was a way to do it all in 1 click without having to manually check the file size every time, I would be so grateful.

**Comment by MediaMoots** [comment]
Y'know, I was just testing the export, when I switch outfits on Chika, I can export them all one by one quite quickly without needing to exit the Char maker, is there a specific card that has this issue?

**Comment by poisenbery** [comment]
@MediaMoots It wasn't any specific cards, just a random issue.
Unfortunately, I posted this before I knew about Pushup settings.
The pushup settings are probably the nail in the coffin for this. Sometimes, they're different per outfit and it changes the shape of the....chest area, which means I have to make custom shape keys per outfit in blender.

It's probably more work than it's worth.
