### ISSUE TITLE
Blender 3.0, Cats 0.19.0, KKBP V5 Error on hitting Finalize PMX for Male model / Loss of Shape keys on export

### ISSUE THREAD

**Issue by WillabyNeko** [FlailingFog/KK-Blender-Porter-Pack#87]
First issue as stated in title and has the log on what occurs when trying to finalize the PMX below.

location: <unknown location>:-1
Error: Python: Traceback (most recent call last):
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\KK-Blender-Porter-Pack-5-merger\importing\finalizepmx.py", line 904, in execute
    bpy.ops.kkb.separatebody('INVOKE_DEFAULT')
  File "C:\Users\User\Desktop\Steam\steamapps\common\Blender\3.0\scripts\modules\bpy\ops.py", line 130, in __call__
    ret = _op_call(self.idname_py(), C_dict, kw, C_exec, C_undo)
RuntimeError: Error: Python: Traceback (most recent call last):
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\KK-Blender-Porter-Pack-5-merger\importing\separatebody.py", line 169, in execute
    base_name, dupe_number = mat.name.split('.',2)
ValueError: too many values to unpack (expected 2)

location: C:\Users\User\Desktop\Steam\steamapps\common\Blender\3.0\scripts\modules\bpy\ops.py:130

Second issue:

After following the written guide with a female model that had no issues prior, none of the shape keys export into the FBX, and I have tested exporting with pmx/mmd models without any issues in theirs' exporting.

**Comment by FlailingFog** [comment]
The first one is probably a result of lazy coding on my part, but I don't know about the second one. I tried to export the model as an fbx file then re-import into blender and the shapekeys were still there.
Do you have the male card you were using?

**Comment by WillabyNeko** [comment]
I found it was due to the "Small Beard" face accessory, as I removed it from the character and importing him into Blender worked. The issue with lack of shape keys I'll try to record and post on a dropbox or something when I get a chance today.

**Comment by WillabyNeko** [comment]
Small update; been busy with life stuff so I haven't recorded it, but the one time I did record it today the shapekeys were there in the fbx when I reimported it.
