### ISSUE TITLE
Colormask for white flared clothing has no detail color?

### ISSUE THREAD

**Issue by miyabi-95** [FlailingFog/KK-Blender-Porter-Pack#88]
I was wondering if there was a way to color this accessory on my character. She's wearing a scrunchy (meant to go on wrists, but because she's a clown it's around her neck) that comes with a pattern, tho I don't want a pattern, just the detail mask. My problem is that if I give it a manual color, the detail mask disappears. Any help is appreciated, I'm really happy with how v5 is performing!
![Screenshot (1209)](https://user-images.githubusercontent.com/63174638/147907365-5d43690f-a5ee-48b5-a56c-7ebc71efdd00.png)

**Comment by MediaMoots** [comment]
Did you manage to solve this?
