### ISSUE TITLE
finalizepmx.py error in bpy.ops.kkb.separatebody

### ISSUE THREAD

**Issue by ManeiDomini** [FlailingFog/KK-Blender-Porter-Pack#90]
Upon running Finalize PMX, Blender spits out this error block. This then prevents the bones from being added, importation of textures, etc.

![image](https://user-images.githubusercontent.com/95846636/148017442-a9dcdc35-b5fd-4eff-9172-ca745e8966ef.png)

**Comment by FlailingFog** [comment]
See #105
