### ISSUE TITLE
Trouble with imported map colors

### ISSUE THREAD

**Issue by BugMonkey42335** [FlailingFog/KK-Blender-Porter-Pack#91]
When attempting to import a map the colors are faded, despite my attempts to adjust the settings.

Koikatsu
![KK in-game map](https://user-images.githubusercontent.com/64150986/148295173-f76ee2cf-67dc-4d5f-bbdb-8b472e3bf748.png)

Blender
![Blender imported map](https://user-images.githubusercontent.com/64150986/148295203-48c8e371-ca10-4963-81b1-23924c4e8cd1.png)

Also attempting to use the convert textures option results in this error.

Python: Traceback (most recent call last):
  File "C:\Users\Standard\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\KK-Blender-Porter-Pack-5-merger\extras\importstudio.py", line 375, in execute
    runIt()
  File "C:\Users\Standard\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\KK-Blender-Porter-Pack-5-merger\extras\importstudio.py", line 352, in runIt
    load_luts()
TypeError: load_luts() missing 2 required positional arguments: 'lut_light' and 'lut_dark'

location: <unknown location>:-1

**Comment by MediaMoots** [comment]
I'm afraid that the color import system is made only for importing (especially female) characters, so unfortunately the system can't do this now.

**Comment by FlailingFog** [comment]
Not sure why that's happening... This is what I'm getting for everything:

![image](https://user-images.githubusercontent.com/65811931/155851407-beec1271-626e-421a-aacf-662a524a6ef2.png)

Even if you don't use the convert textures option, it shouldn't be that light. And even if you do convert the textures, I think koikatsu uses a different shader for maps, so using the options on the panel won't get you completely accurate results (stuff like the lights are completely absent)

**Comment by BugMonkey42335** [comment]
I have been using the KK Shader option and Scene World for lighting which results in the faded colors.

Also testing out the new fix results in the following error, as well as the map defaulting to the Principled BSDF shader.

> Python: Traceback (most recent call last):
  File "C:\Users\Standard\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\KK-Blender-Porter-Pack-master\extras\importstudio.py", line 380, in execute
    runIt()
  File "C:\Users\Standard\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\KK-Blender-Porter-Pack-master\extras\importstudio.py", line 140, in runIt
    nodes['Principled BSDF'].inputs[19].default_value = (0, 0, 0, 1)
TypeError: bpy_struct: item.attr = val: NodeSocketFloatFactor.default_value expected a float type, not tuple
>
>location: <unknown location>:-1

**Comment by FlailingFog** [comment]
It looks like the images from my export and your export are different. I set the view transform to standard and set the images to sRGB, but they're still not the same. I guess check if there's a setting in SB3U that could make make it export slightly faded images
![image](https://user-images.githubusercontent.com/65811931/155884069-178321b5-6283-4b8e-a32b-4da307661fc6.png)

**Comment by BugMonkey42335** [comment]
Could you upload some of your textures so I can compare and contrast?

**Comment by FlailingFog** [comment]
This is what I got from using SB3UGS_v20.6.6: https://files.catbox.moe/t5ptoa.7z
