### ISSUE TITLE
V5 - Import KK Shader and Textures Error

### ISSUE THREAD

**Issue by dragonash2019** [FlailingFog/KK-Blender-Porter-Pack#93]
When clicking on the import KK shader button, I browse to my folder location with all of the textures and get the error below.

I'm on Blender 3.0 using your V5 script.
Any ideas?

![image](https://user-images.githubusercontent.com/47508016/149345313-faf07758-36fa-4a4a-a602-2178f8b792e7.png)

**Comment by FlailingFog** [comment]
It looks like you saved the blend file to the same directory the pmx file is in. If a blend file is in that directory, it'll error out because it's expecting the KK Shader.blend from the repository to be there.

**Comment by dragonash2019** [comment]
thank you

**Comment by MediaMoots** [comment]
Umm... Is this solved?
