### ISSUE TITLE
IK won't work on legs with certain card

### ISSUE THREAD

**Issue by hdddestroyer** [FlailingFog/KK-Blender-Porter-Pack#98]
Hi! I'm trying to convert a certain card (linked [here](https://www.patreon.com/file?h=59607966&i=9535476); it's Nessa card, these cards require a zipmod which is also included), after setting everything like I wanted to I realize that the IK on legs won't work. The knees just don't bend and her feet seem a little like a mess. Switching to FK gives me this error: 
```
Python: Traceback (most recent call last):
  File "C:\Users\<my name>\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\KK-Blender-Porter-Pack-master\extras\switcharmature.py", line 43, in execute
    reparent('cf_pv_elbo_R', 'cf_pv_root')
  File "C:\Users\<my name>\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\KK-Blender-Porter-Pack-master\extras\switcharmature.py", line 41, in reparent
    armature.data.edit_bones[bone].parent = armature.data.edit_bones[newparent]
KeyError: 'bpy_prop_collection[key]: key "cf_pv_root" not found'

location: <unknown location>:-1
```
So is there a bone missing or something?

**Comment by FlailingFog** [comment]
The plugin doesn't seem to move the bone forward enough, making the IK malfunction. Just go into edit mode for the armature, and move the top of the knee bone outward a bit. 
![image](https://user-images.githubusercontent.com/65811931/155855641-317ccfeb-c4ad-444e-aae5-19243fcadcba.png)
