### ISSUE TITLE
Export to PMX for a certain card broken

### ISSUE THREAD

**Issue by hdddestroyer** [FlailingFog/KK-Blender-Porter-Pack#99]
Hello I found a card that for some reason stops exporting at some point. Card available [here](https://drive.google.com/file/d/1jJ6niOvTc9tbLdHya5hZm5EFFDdXMilW/view).
Does the Koikatsu plugin create any log files somewhere?

**Comment by MediaMoots** [comment]
What Koikatsu game are you using?

**Comment by hdddestroyer** [comment]
I'm using Koikatsu Party with HF patch of course.
